In [1]:
import pandas as pd
import os
import random
from collections import Counter
import numpy as np
import json

In [24]:
df = pd.read_csv("F:\\LCE\\predicate\\predicates_cardinality_all.csv")

In [25]:
def get_table_name(x):
    data = json.loads(x)
    return data["table"]

In [26]:
df['table'] = df['cardinality'].apply(get_table_name)

In [27]:
condition = df['table'] == 'problem'

In [28]:
df_1 = df[condition]

In [29]:
df_1  =  df_1.drop('table', axis=1)

In [30]:
df_1  =  df_1.drop('index', axis=1)

In [31]:
df_1

,expression,cardinality,target
11,problem.(language = 'English' and ((score!='5....,"{""cardinality"": 73, ""table"": ""problem"", ""tree""...",73
16,problem.(language = 'Chinese' and ((score='10....,"{""cardinality"": 84790, ""table"": ""problem"", ""tr...",84790
27,problem.((language = 'English' and score!='2.5...,"{""cardinality"": 4407, ""table"": ""problem"", ""tre...",4407
67,problem.((language = 'Chinese' and score!='0.5...,"{""cardinality"": 111964, ""table"": ""problem"", ""t...",111964
95,problem.((language = 'English' and score!='2.5...,"{""cardinality"": 2570, ""table"": ""problem"", ""tre...",2570
...,...,...,...
102674,problem.(language = 'Chinese' and (score!='8.0...,"{""cardinality"": 112088, ""table"": ""problem"", ""t...",112088
102681,problem.(language = 'English' and ((score!='10...,"{""cardinality"": 11178, ""table"": ""problem"", ""tr...",11178
102683,problem.(language = 'Chinese' and ((score='12....,"{""cardinality"": 108645, ""table"": ""problem"", ""t...",108645
102686,problem.(language = 'Chinese' and ((score!='9....,"{""cardinality"": 90559, ""table"": ""problem"", ""tr...",90559
102699,problem.((language = 'Chinese' and score='20.0...,"{""cardinality"": 107, ""table"": ""problem"", ""tree...",107

In [32]:
df_1 = df_1.head(5000)

In [33]:
df_2 = pd.read_csv('F:\\LCE\\dataset\\problem.csv')

In [34]:
df_2 = df_2.head(5000)

In [35]:
df_2

,id,language,content,score,type,typetext,feature
0,13816,Chinese,中国共产党从成立之日起，就确立了（ ）的远大理想，始终团结带领中国人民朝着这个伟大目标前进。,1.0,1,单选题,"[0.3620103895664215, 0.4917919635772705, 0.001..."
1,13817,Chinese,走好新时代的长征路，大学生要不断增强中国特色社会主义（ ），自觉做共产主义远大理想和中国特色...,1.0,1,单选题,"[0.307481974363327, 0.13994258642196655, 0.536..."
2,13829,Chinese,国家安全问题事关国家安危和民族存亡，大学生要增强国家安全意识，以下做法错误的是（ ）,1.0,1,单选题,"[-0.15822555124759674, -0.12112200260162354, -..."
3,13832,Chinese,对于社会主义核心价值观的自信，来自于（ ）,2.0,2,多选题,"[0.06346714496612549, -0.10366339236497879, 0...."
4,13835,Chinese,党的十八大提出，要倡导（ ），倡导（ ），倡导（ ），积极培育和践行社会主义核心价值观。,1.0,1,单选题,"[0.07375973463058472, 0.32700297236442566, -0...."
...,...,...,...,...,...,...,...
4995,800289,Chinese,单轨悬挂式吊车一般由悬挂在屋架下弦的型钢轨道和吊车组成，型钢轨道可以布置为( )和( )。,2.0,2,多选题,"[0.07139145582914352, 0.19061002135276794, -0...."
4996,800290,Chinese,梁式吊车有( )和( )两种形式。,2.0,2,多选题,"[0.18365173041820526, 0.2732599377632141, -0.1..."
4997,800291,Chinese,桥式吊车主要由( )和( )两部分组成。,2.0,2,多选题,"[0.197997584939003, 0.19874148070812225, -0.01..."
4998,800292,Chinese,单层工业厂房从材料及结构特点上分为砖混结构厂房、( )和( )。,2.0,2,多选题,"[0.12680557370185852, 0.0645834356546402, 0.23..."
4999,800293,Chinese,厂房运输设备一般有（ ）三类。,2.0,2,多选题,"[0.20549215376377106, -0.1319410651922226, 0.1..."

In [36]:
feature = df_2["feature"]

In [37]:
feature.dropna()

0       [0.3620103895664215, 0.4917919635772705, 0.001...
1       [0.307481974363327, 0.13994258642196655, 0.536...
2       [-0.15822555124759674, -0.12112200260162354, -...
3       [0.06346714496612549, -0.10366339236497879, 0....
4       [0.07375973463058472, 0.32700297236442566, -0....
                              ...
4995    [0.07139145582914352, 0.19061002135276794, -0....
4996    [0.18365173041820526, 0.2732599377632141, -0.1...
4997    [0.197997584939003, 0.19874148070812225, -0.01...
4998    [0.12680557370185852, 0.0645834356546402, 0.23...
4999    [0.20549215376377106, -0.1319410651922226, 0.1...
Name: feature, Length: 5000, dtype: object

In [38]:
type(feature)

pandas.core.series.Series

In [39]:
df_1 = df_1.reset_index(drop=True)

In [40]:
df_1["feature"] = feature

In [44]:
df_1

,expression,feature
0,problem.(language = 'English' and ((score!='5....,"[0.3620103895664215, 0.4917919635772705, 0.001..."
1,problem.(language = 'Chinese' and ((score='10....,"[0.307481974363327, 0.13994258642196655, 0.536..."
2,problem.((language = 'English' and score!='2.5...,"[-0.15822555124759674, -0.12112200260162354, -..."
3,problem.((language = 'Chinese' and score!='0.5...,"[0.06346714496612549, -0.10366339236497879, 0...."
4,problem.((language = 'English' and score!='2.5...,"[0.07375973463058472, 0.32700297236442566, -0...."
...,...,...
4995,problem.((language = 'Chinese' and score!='33....,"[0.07139145582914352, 0.19061002135276794, -0...."
4996,problem.(language = 'Chinese' and ((score!='40...,"[0.18365173041820526, 0.2732599377632141, -0.1..."
4997,problem.(language = 'English' and ((score!='30...,"[0.197997584939003, 0.19874148070812225, -0.01..."
4998,problem.((language = 'English' and score!='12....,"[0.12680557370185852, 0.0645834356546402, 0.23..."
4999,problem.(language = 'English' and ((score='2.0...,"[0.20549215376377106, -0.1319410651922226, 0.1..."

In [42]:
df_1  =  df_1.drop('target', axis=1)

In [43]:
df_1 = df_1.drop('cardinality', axis=1)

In [46]:
df_1.to_csv("F:\\LCE\\dataset\\bench_problem_query_file_5000.csv", index=False)

### 谓词长度分类

In [67]:
def count_and_or(expr):
    and_count = expr.count(" and ")
    or_count = expr.count(" or ")
    return and_count + or_count

In [68]:
def computer_predicate(x):
    return count_and_or(x)+1

In [70]:
df_1['predicates'] = df_1['expression'].apply(computer_predicate)

In [71]:
df_1

,expression,cardinality,target,feature,predicates
0,problem.(language = 'English' and ((score!='5....,"{""cardinality"": 73, ""table"": ""problem"", ""tree""...",73,"[0.3620103895664215, 0.4917919635772705, 0.001...",5
1,problem.(language = 'Chinese' and ((score='10....,"{""cardinality"": 84790, ""table"": ""problem"", ""tr...",84790,"[0.307481974363327, 0.13994258642196655, 0.536...",5
2,problem.((language = 'English' and score!='2.5...,"{""cardinality"": 4407, ""table"": ""problem"", ""tre...",4407,"[-0.15822555124759674, -0.12112200260162354, -...",6
3,problem.((language = 'Chinese' and score!='0.5...,"{""cardinality"": 111964, ""table"": ""problem"", ""t...",111964,"[0.06346714496612549, -0.10366339236497879, 0....",6
4,problem.((language = 'English' and score!='2.5...,"{""cardinality"": 2570, ""table"": ""problem"", ""tre...",2570,"[0.07375973463058472, 0.32700297236442566, -0....",6
...,...,...,...,...,...
9038,problem.(language = 'Chinese' and (score!='8.0...,"{""cardinality"": 112088, ""table"": ""problem"", ""t...",112088,"[0.01358968485146761, 0.10460367798805237, 0.1...",3
9039,problem.(language = 'English' and ((score!='10...,"{""cardinality"": 11178, ""table"": ""problem"", ""tr...",11178,"[0.04117879271507263, 0.2561227083206177, 0.54...",4
9040,problem.(language = 'Chinese' and ((score='12....,"{""cardinality"": 108645, ""table"": ""problem"", ""t...",108645,"[-0.03014330565929413, 0.014116000384092331, 0...",5
9041,problem.(language = 'Chinese' and ((score!='9....,"{""cardinality"": 90559, ""table"": ""problem"", ""tr...",90559,"[0.03244158998131752, 0.020678682252764702, 0....",4
9042,problem.((language = 'Chinese' and score='20.0...,"{""cardinality"": 107, ""table"": ""problem"", ""tree...",107,"[0.05161565542221069, -0.030359286814928055, 0...",6

In [72]:
df_1["predicates"].max()

6

In [73]:
df_1["predicates"].min()

1

In [ ]:
short_df = df_1[df_1["predicates"]]