In [1]:
import pandas as pd
import os
import random
from collections import Counter
import numpy as np
import json

In [2]:
df = pd.read_csv("F:\\LCE\\predicate\\predicates_cardinality_all.csv")

In [3]:
def get_table_name(x):
    data = json.loads(x)
    return data["table"]

In [4]:
df['table'] = df['cardinality'].apply(get_table_name)

In [5]:
condition = df['table'] == 'business'

In [6]:
df_1 = df[condition]

In [8]:
df_1 = df_1.head(5000)

In [9]:
df_1

,index,expression,cardinality,target,table
6,7,business.(favorites>=47 and (avgspend>82 or po...,"{""cardinality"": 94354, ""table"": ""business"", ""t...",94354,business
7,8,business.review<=117 and popular = FALSE,"{""cardinality"": 46734, ""table"": ""business"", ""t...",46734,business
9,10,business.((city='Broomall' and state!='AZ') an...,"{""cardinality"": 84, ""table"": ""business"", ""tree...",84,business
17,18,business.(city!='Upper Darby' and ((state='DE'...,"{""cardinality"": 910, ""table"": ""business"", ""tre...",910,business
20,21,business.((city!='Reno' and state='IL') and ((...,"{""cardinality"": 1876, ""table"": ""business"", ""tr...",1876,business
...,...,...,...,...,...
13461,13462,business.((city='Seminole' and state!='ID') an...,"{""cardinality"": 163, ""table"": ""business"", ""tre...",163,business
13463,13464,business.((city!='Fairless Hills' and state='M...,"{""cardinality"": 7337, ""table"": ""business"", ""tr...",7337,business
13468,13469,business.(city='Feasterville Trevose' and ((st...,"{""cardinality"": 62, ""table"": ""business"", ""tree...",62,business
13470,13471,business.((city='King Of Prussia' and state!='...,"{""cardinality"": 134, ""table"": ""business"", ""tre...",134,business
13475,13476,business.(city!='Zionsville' and (state='CA' o...,"{""cardinality"": 149381, ""table"": ""business"", ""...",149381,business

In [8]:
def count_and_or(expr):
    and_count = expr.count(" and ")
    or_count = expr.count(" or ")
    return and_count + or_count

In [9]:
def computer_predicate(x):
    return count_and_or(x)+1

In [10]:
df_1['predicates'] = df_1['expression'].apply(computer_predicate)

/tmp/ipykernel_1907/1187415099.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['predicates'] = df_1['expression'].apply(computer_predicate)

In [11]:
df_1

,index,expression,cardinality,target,table,predicates
6,7,business.(favorites>=47 and (avgspend>82 or po...,"{""cardinality"": 94354, ""table"": ""business"", ""t...",94354,business,3
7,8,business.review<=117 and popular = FALSE,"{""cardinality"": 46734, ""table"": ""business"", ""t...",46734,business,2
9,10,business.((city='Broomall' and state!='AZ') an...,"{""cardinality"": 84, ""table"": ""business"", ""tree...",84,business,6
17,18,business.(city!='Upper Darby' and ((state='DE'...,"{""cardinality"": 910, ""table"": ""business"", ""tre...",910,business,6
20,21,business.((city!='Reno' and state='IL') and ((...,"{""cardinality"": 1876, ""table"": ""business"", ""tr...",1876,business,7
...,...,...,...,...,...,...
102706,102707,business.((city='Elkins Park' and state!='AZ')...,"{""cardinality"": 83, ""table"": ""business"", ""tree...",83,business,7
102710,102711,business.favorites<=155 or stars=4.5,"{""cardinality"": 132129, ""table"": ""business"", ""...",132129,business,2
102714,102715,business.(city='Newark' and ((state!='AZ' and ...,"{""cardinality"": 213, ""table"": ""business"", ""tre...",213,business,7
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472,business,4
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585,business,8

In [27]:
df_1  =  df_1.drop('index', axis=1)

In [28]:
df_1 = df_1.reset_index(drop=True)

In [29]:
short_df = df_1[(df_1['predicates'] >= 1) & (df_1['predicates'] <= 3)]

In [30]:
middle_df = df_1[(df_1['predicates'] >= 4) & (df_1['predicates'] <= 6)]

In [31]:
long_df = df_1[(df_1['predicates'] >= 7)]

In [33]:
short_df = short_df.reset_index(drop=True)

In [35]:
middle_df = middle_df.reset_index(drop=True)

In [36]:
long_df = long_df.reset_index(drop=True)

### 拼接 vector

In [20]:
df_2 = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business_mf.csv')

In [38]:
feature = df_2["feature"]

In [39]:
feature

0         [0.5149855613708496, -0.2046436369419098, -0.3...
1         [0.2881472706794739, -0.04402739554643631, -0....
2         [0.49464067816734314, 0.022908760234713554, -0...
3         [0.47613540291786194, 0.04090013727545738, -0....
4         [0.6412854790687561, 0.15557944774627686, -0.2...
                                ...
150238    [0.4360079765319824, 0.15860453248023987, -0.6...
150239    [0.43686267733573914, 0.10853110998868942, -0....
150240    [0.34829986095428467, 0.06677868217229843, -0....
150241    [0.45862674713134766, 0.17515017092227936, -0....
150242    [0.19764001667499542, 0.24613741040229797, -0....
Name: feature, Length: 150243, dtype: object

In [41]:
short_df["feature"] = pd.Series(np.random.choice(feature,len(short_df) , replace=False))

In [43]:
middle_df["feature"] = pd.Series(np.random.choice(feature,len(middle_df) , replace=False))

In [44]:
long_df["feature"] = pd.Series(np.random.choice(feature,len(long_df) , replace=False))

In [46]:
short_df = short_df.drop(columns=["cardinality","target","table","predicates"])

In [ ]:
middle_df = middle_df.drop(columns=["cardinality","target","table","predicates"])

In [48]:
long_df = long_df.drop(columns=["cardinality","target","table","predicates"])

In [ ]:
df_1.to_csv("/remote-home/cs_acmis_wsf/ai4dingo/predicate/business_table_short_predicates.csv", index=False)

### 生成bench_query_file

In [10]:
df_2 = pd.read_csv('F:\\LCE\\dataset\\business_mf.csv')

In [11]:
df_2 = df_2.head(5000)

In [12]:
df_2

,business_id,name,address,city,state,code,stars,review,favorites,avgspend,popular,categories,feature
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,5.0,7,220,160,True,"Doctors, Traditional Chinese Medicine, Naturop...","[0.5149855613708496, -0.2046436369419098, -0.3..."
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,3.0,15,36,27,False,"Shipping Centers, Local Services, Notaries, Ma...","[0.2881472706794739, -0.04402739554643631, -0...."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,3.5,22,134,56,True,"Department Stores, Shopping, Fashion, Home & G...","[0.49464067816734314, 0.022908760234713554, -0..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,4.0,80,98,49,True,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","[0.47613540291786194, 0.04090013727545738, -0...."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,4.5,13,215,116,True,"Brewpubs, Breweries, Food","[0.6412854790687561, 0.15557944774627686, -0.2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,qWTzwt7IyrElM2g9nVHm2Q,Super Acucare Inc,46 N 10th St,Philadelphia,PA,19107,4.5,47,213,131,True,"Beauty & Spas, Massage, Acupuncture, Health & ...","[0.47891372442245483, 0.1718011200428009, -0.6..."
4996,o6hWaMjS7-CdXq3WzW9d8w,Best Mattress,4002 N Stone Ave,Tucson,AZ,85705,5.0,37,179,93,True,"Home & Garden, Mattresses, Shopping, Furniture...","[0.4217585027217865, 0.07948575168848038, -0.4..."
4997,g79jYJz3FEvgvglXqOUWxw,IHOP,3400 South I-10 Service Rd W,Metairie,LA,70001,3.0,75,61,31,True,"Breakfast & Brunch, Burgers, Restaurants, Amer...","[0.4487774968147278, 0.049153365194797516, -0...."
4998,QK1OLsTL-WORwk9acRVV8g,CVS Pharmacy,7240 E 82nd St,Indianapolis,IN,46256,2.0,15,20,15,False,"Food, Convenience Stores, Shopping, Drugstores...","[0.39141765236854553, -0.05717073753476143, -0..."
4999,QCSLVCAx7nl_0B2PNVSnyg,A Little Taste of Heaven Bakery,2709 N Center St,Maryville,IL,62062,4.5,37,182,94,True,"Food, Cupcakes, Bakeries, Patisserie/Cake Shop...","[0.35307934880256653, 0.11712891608476639, -0...."

In [13]:
feature = df_2["feature"]

In [14]:
feature.dropna()

0       [0.5149855613708496, -0.2046436369419098, -0.3...
1       [0.2881472706794739, -0.04402739554643631, -0....
2       [0.49464067816734314, 0.022908760234713554, -0...
3       [0.47613540291786194, 0.04090013727545738, -0....
4       [0.6412854790687561, 0.15557944774627686, -0.2...
                              ...
4995    [0.47891372442245483, 0.1718011200428009, -0.6...
4996    [0.4217585027217865, 0.07948575168848038, -0.4...
4997    [0.4487774968147278, 0.049153365194797516, -0....
4998    [0.39141765236854553, -0.05717073753476143, -0...
4999    [0.35307934880256653, 0.11712891608476639, -0....
Name: feature, Length: 5000, dtype: object

In [15]:
df_1 = df_1.reset_index(drop=True)

In [16]:
df_1["feature"] = feature

In [20]:
df_1

,index,expression,table,feature
0,7,business.(favorites>=47 and (avgspend>82 or po...,business,"[0.5149855613708496, -0.2046436369419098, -0.3..."
1,8,business.review<=117 and popular = FALSE,business,"[0.2881472706794739, -0.04402739554643631, -0...."
2,10,business.((city='Broomall' and state!='AZ') an...,business,"[0.49464067816734314, 0.022908760234713554, -0..."
3,18,business.(city!='Upper Darby' and ((state='DE'...,business,"[0.47613540291786194, 0.04090013727545738, -0...."
4,21,business.((city!='Reno' and state='IL') and ((...,business,"[0.6412854790687561, 0.15557944774627686, -0.2..."
...,...,...,...,...
4995,13462,business.((city='Seminole' and state!='ID') an...,business,"[0.47891372442245483, 0.1718011200428009, -0.6..."
4996,13464,business.((city!='Fairless Hills' and state='M...,business,"[0.4217585027217865, 0.07948575168848038, -0.4..."
4997,13469,business.(city='Feasterville Trevose' and ((st...,business,"[0.4487774968147278, 0.049153365194797516, -0...."
4998,13471,business.((city='King Of Prussia' and state!='...,business,"[0.39141765236854553, -0.05717073753476143, -0..."
4999,13476,business.(city!='Zionsville' and (state='CA' o...,business,"[0.35307934880256653, 0.11712891608476639, -0...."

In [18]:
df_1  =  df_1.drop('target', axis=1)

In [19]:
df_1 = df_1.drop('cardinality', axis=1)

In [21]:
df_1 = df_1.drop('table', axis=1)

In [22]:
df_1.to_csv("F:\\LCE\\dataset\\bench_business_query_file_5000.csv", index=False)