In [1]:
import pandas as pd
import os
import random
from collections import Counter
import numpy as np
import json

In [2]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/LCEModels/attention-tree-lstm/data/predicates_cardinality_all.csv')

In [3]:
df

,index,expression,cardinality,target
0,1,review.(read = FALSE and ((stars>=4.0 and funn...,"{""cardinality"": 552, ""table"": ""review"", ""tree""...",552
1,2,tip.num>=50 and amount<=13.9,"{""cardinality"": 618, ""table"": ""tip"", ""tree"": {...",618
2,3,tip.((compliment=2 and num<68) and ((amount<13...,"{""cardinality"": 539, ""table"": ""tip"", ""tree"": {...",539
3,4,review.((stars!=1.0 and useful<7.0) and (funny...,"{""cardinality"": 3473476, ""table"": ""review"", ""t...",3473476
4,5,review.read = TRUE and likes>=73,"{""cardinality"": 2401730, ""table"": ""review"", ""t...",2401730
...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289

In [10]:
def complex_expression(x):
    data = x.split(".",1)
    return data[1]

In [11]:
df["sql"] = df['expression'].apply(complex_expression)

In [12]:
df

,index,expression,cardinality,target,sql
0,1,review.(read = FALSE and ((stars>=4.0 and funn...,"{""cardinality"": 552, ""table"": ""review"", ""tree""...",552,(read = FALSE and ((stars>=4.0 and funny=5.0) ...
1,2,tip.num>=50 and amount<=13.9,"{""cardinality"": 618, ""table"": ""tip"", ""tree"": {...",618,num>=50 and amount<=13.9
2,3,tip.((compliment=2 and num<68) and ((amount<13...,"{""cardinality"": 539, ""table"": ""tip"", ""tree"": {...",539,((compliment=2 and num<68) and ((amount<13.1 a...
3,4,review.((stars!=1.0 and useful<7.0) and (funny...,"{""cardinality"": 3473476, ""table"": ""review"", ""t...",3473476,((stars!=1.0 and useful<7.0) and (funny!=12.0 ...
4,5,review.read = TRUE and likes>=73,"{""cardinality"": 2401730, ""table"": ""review"", ""t...",2401730,read = TRUE and likes>=73
...,...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356,useful>5.0 and dislikes<=33
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470,(stars!=3.0 and ((funny>=21.0 and cool<=22.0) ...
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472,((state='AB' and popular = TRUE) and (review<9...
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585,((city!='Collegeville' and state!='IL') and ((...
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289,(compliment>=2 and (num>=48 or amount<=10.0))