In [2]:
import pandas as pd
import numpy as np

In [4]:
user_df = pd.read_csv('/media/wsf/Disk/mooccubex/csv/user.csv')

In [5]:
user_df = user_df.dropna(subset=["name"])

In [6]:
user_df = user_df.dropna(subset=["gender"])

In [7]:
user_df

,id,name,gender,school,year_of_birth,course_order,enroll_time
0,U_22,我,0.0,NaN,2015.0,"[682129,2294668]","['2019-10-1210:28:02','2020-11-2114:03:28']"
1,U_24,王帅国,1.0,清华大学,6558.0,"[597214,605512,597211,597314,597208,629501,597...","['2019-05-2016:06:48','2019-05-2419:34:43','20..."
2,U_25,王帅国,0.0,清华大学,NaN,[1903985],['2020-08-0718:59:13']
3,U_53,于歆杰,1.0,清华大学,1973.0,"[696679,1704639,943255,1729417,682164,1771179,...","['2020-03-0121:24:30','2020-03-1216:17:02','20..."
4,U_54,马昱春,2.0,清华大学,NaN,"[682442,682164,1748240,1778890,1829031,1794464...","['2019-10-0902:17:49','2019-11-0800:49:03','20..."
...,...,...,...,...,...,...,...
3330170,U_34711822,杨文操,1.0,NaN,NaN,[1822804],['2020-10-1200:09:21']
3330193,U_34711862,超,1.0,陕西师范大学,NaN,[936971],['2020-12-0317:59:07']
3330194,U_34711863,娅伦格日勒,2.0,NaN,NaN,"[948124,936971]","['2020-10-1208:13:11','2020-11-3012:21:23']"
3330236,U_34711954,Deloray,2.0,NaN,NaN,"[696807,697360,696889,1765604,1761462,735197,6...","['2020-10-1200:48:01','2020-10-1200:48:40','20..."
3330257,U_34712015,Santana,0.0,NaN,NaN,"[1755939,1764844,1782008]","['2020-10-1201:40:27','2020-10-1904:53:30','20..."

In [8]:
def handle_gender(x):
    return int(x)

In [9]:
user_df["gender"] = user_df["gender"].apply(handle_gender)

In [10]:
def hanlde_course_order(x):
    x = str(x)
    x =  x.replace("[","")
    x= x.replace("]","")
    return x

In [11]:
user_df["course_order"] = user_df["course_order"].apply( hanlde_course_order)

In [64]:
def hanlde_enroll_time(x):
    x = str(x)
    x =  x.replace("[","")
    x= x.replace("]","")
    x = x.replace("'","")
    return x

In [13]:
user_df

,id,name,gender,school,year_of_birth,course_order,enroll_time
0,U_22,我,0,NaN,2015.0,"682129,2294668","['2019-10-1210:28:02','2020-11-2114:03:28']"
1,U_24,王帅国,1,清华大学,6558.0,"597214,605512,597211,597314,597208,629501,5971...","['2019-05-2016:06:48','2019-05-2419:34:43','20..."
2,U_25,王帅国,0,清华大学,NaN,1903985,['2020-08-0718:59:13']
3,U_53,于歆杰,1,清华大学,1973.0,"696679,1704639,943255,1729417,682164,1771179,1...","['2020-03-0121:24:30','2020-03-1216:17:02','20..."
4,U_54,马昱春,2,清华大学,NaN,"682442,682164,1748240,1778890,1829031,1794464,...","['2019-10-0902:17:49','2019-11-0800:49:03','20..."
...,...,...,...,...,...,...,...
3330170,U_34711822,杨文操,1,NaN,NaN,1822804,['2020-10-1200:09:21']
3330193,U_34711862,超,1,陕西师范大学,NaN,936971,['2020-12-0317:59:07']
3330194,U_34711863,娅伦格日勒,2,NaN,NaN,"948124,936971","['2020-10-1208:13:11','2020-11-3012:21:23']"
3330236,U_34711954,Deloray,2,NaN,NaN,"696807,697360,696889,1765604,1761462,735197,69...","['2020-10-1200:48:01','2020-10-1200:48:40','20..."
3330257,U_34712015,Santana,0,NaN,NaN,"1755939,1764844,1782008","['2020-10-1201:40:27','2020-10-1904:53:30','20..."

In [14]:
def handle_year(x):
    if not pd.isna(x):
        x = str(x)
        x = x.split(".")[0]
        return x;
    else:
        return x;

In [15]:
user_df["year_of_birth"]  = user_df["year_of_birth"].apply(handle_year)

In [17]:
user_df

,id,name,gender,school,year_of_birth,course_order,enroll_time
0,U_22,我,0,NaN,2015,"682129,2294668","['2019-10-1210:28:02','2020-11-2114:03:28']"
1,U_24,王帅国,1,清华大学,6558,"597214,605512,597211,597314,597208,629501,5971...","['2019-05-2016:06:48','2019-05-2419:34:43','20..."
2,U_25,王帅国,0,清华大学,NaN,1903985,['2020-08-0718:59:13']
3,U_53,于歆杰,1,清华大学,1973,"696679,1704639,943255,1729417,682164,1771179,1...","['2020-03-0121:24:30','2020-03-1216:17:02','20..."
4,U_54,马昱春,2,清华大学,NaN,"682442,682164,1748240,1778890,1829031,1794464,...","['2019-10-0902:17:49','2019-11-0800:49:03','20..."
...,...,...,...,...,...,...,...
3330170,U_34711822,杨文操,1,NaN,NaN,1822804,['2020-10-1200:09:21']
3330193,U_34711862,超,1,陕西师范大学,NaN,936971,['2020-12-0317:59:07']
3330194,U_34711863,娅伦格日勒,2,NaN,NaN,"948124,936971","['2020-10-1208:13:11','2020-11-3012:21:23']"
3330236,U_34711954,Deloray,2,NaN,NaN,"696807,697360,696889,1765604,1761462,735197,69...","['2020-10-1200:48:01','2020-10-1200:48:40','20..."
3330257,U_34712015,Santana,0,NaN,NaN,"1755939,1764844,1782008","['2020-10-1201:40:27','2020-10-1904:53:30','20..."

### 清洗NaN

In [91]:
user_df_clean = user_df.dropna(subset=['school'])

In [92]:
user_df_clean = user_df_clean.drop("course_order",axis=1)

In [93]:
user_df_clean = user_df_clean.dropna(subset=['enroll_time'])

In [94]:
def handle_enroll_time_1(x):
    enroll_time_list = x.split(',')
#     print(enroll_time_list[0])
    return enroll_time_list[0]

In [95]:
user_df_clean["first_enroll_time"]  = user_df_clean["enroll_time"].apply(hanlde_enroll_time)

In [96]:
user_df_clean = user_df_clean.drop("enroll_time",axis=1)

In [97]:
user_df_clean["first_enroll_time"]  = user_df_clean["first_enroll_time"].apply(handle_enroll_time_1)

In [98]:
user_df_clean

,id,name,gender,school,year_of_birth,first_enroll_time
1,U_24,王帅国,1,清华大学,6558,2019-05-2016:06:48
2,U_25,王帅国,0,清华大学,NaN,2020-08-0718:59:13
3,U_53,于歆杰,1,清华大学,1973,2020-03-0121:24:30
4,U_54,马昱春,2,清华大学,NaN,2019-10-0902:17:49
5,U_67,李小马,1,学堂在线,6798,2019-12-2012:06:00
...,...,...,...,...,...,...
3329921,U_34711247,李晓楠,1,内蒙古科技大学,NaN,2020-11-0614:58:11
3329965,U_34711344,钱智美子,0,安徽新华学院,NaN,2020-12-0418:17:37
3329999,U_34711409,邹晓梅,2,安徽师范大学,NaN,2020-11-3012:40:26
3330132,U_34711719,敖进东,1,中国人民解放军国防科技大学,NaN,2020-10-2214:25:03
3330193,U_34711862,超,1,陕西师范大学,NaN,2020-12-0317:59:07

In [99]:
user_df_clean.to_csv('/media/wsf/Disk/mooccubex/csv/user_clear.csv', index=False)

### 分成多份来存储

In [43]:
# 将数据分成多份，每份 20w 条
df = user_df
num_chunks = 12
chunk_size = 200000
chunks = [df.iloc[i*chunk_size:(i+1)*chunk_size] for i in range(num_chunks)]

# 将每份数据存成 CSV 文件
for i, chunk in enumerate(chunks):
    chunk.to_csv(f'chunk_{i+1}.csv', index=False)

### 再处理User数据

In [3]:
user_df = pd.read_csv('/media/wsf/Disk/mooccubex/csv/user_clear.csv')

In [7]:
user_df

,id,name,gender,school,year_of_birth,first_enroll_time
0,U_24,王帅国,1,清华大学,6558.0,2019-05-20 16:06:48
1,U_25,王帅国,0,清华大学,NaN,2020-08-07 18:59:13
2,U_53,于歆杰,1,清华大学,1973.0,2020-03-01 21:24:30
3,U_54,马昱春,2,清华大学,NaN,2019-10-09 02:17:49
4,U_67,李小马,1,学堂在线,6798.0,2019-12-20 12:06:00
...,...,...,...,...,...,...
1127683,U_34711247,李晓楠,1,内蒙古科技大学,NaN,2020-11-06 14:58:11
1127684,U_34711344,钱智美子,0,安徽新华学院,NaN,2020-12-04 18:17:37
1127685,U_34711409,邹晓梅,2,安徽师范大学,NaN,2020-11-30 12:40:26
1127686,U_34711719,敖进东,1,中国人民解放军国防科技大学,NaN,2020-10-22 14:25:03
1127687,U_34711862,超,1,陕西师范大学,NaN,2020-12-03 17:59:07

In [5]:
def handle_first_enroll_time(original_string):
    formatted_string = original_string[:10] + " " + original_string[10:]
    return formatted_string

In [6]:
user_df["first_enroll_time"]  = user_df["first_enroll_time"].apply(handle_first_enroll_time)

In [9]:
duplicates = user_df['id'].duplicated()

In [10]:
duplicates

0          False
1          False
2          False
3          False
4          False
           ...
1127683    False
1127684    False
1127685    False
1127686    False
1127687    False
Name: id, Length: 1127688, dtype: bool

In [8]:
user_df.to_csv('/media/wsf/Disk/mooccubex/csv/user_clear.csv', index=False)