In [62]:
import pandas as pd
import os
import random
from collections import Counter
import numpy as np
import json

In [3]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/predicate/predicates_cardinality_new_1.csv')

In [8]:
df

,serial,expression,cardinality
0,1,business.((city='Valrico' and state!='FL') and...,"{""cardinality"": 0, ""table"": ""business"", ""tree""..."
1,2,business.((city!='Norristown' and state='CA') ...,"{""cardinality"": 1291, ""table"": ""business"", ""tr..."
2,3,business.review!=147 or stars=3.5,"{""cardinality"": 150192, ""table"": ""business"", ""..."
3,4,business.((city='Ruskin' and state!='LA') and ...,"{""cardinality"": 2, ""table"": ""business"", ""tree""..."
4,5,business.(city='Madison' and (favorites>=115 o...,"{""cardinality"": 272, ""table"": ""business"", ""tre..."
...,...,...,...
120334,120335,tip.((compliment>=3 and num<=9) and (amount!=8...,"{""cardinality"": 98, ""table"": ""tip"", ""tree"": {""..."
120335,120336,tip.((compliment<6 and num!=47) and ((amount>=...,"{""cardinality"": 87758, ""table"": ""tip"", ""tree"":..."
120336,120337,tip.((compliment!=5 and num<86) and ((amount<8...,"{""cardinality"": 845934, ""table"": ""tip"", ""tree""..."
120337,120338,tip.compliment<=2 or amount!=19.3,"{""cardinality"": 851032, ""table"": ""tip"", ""tree""..."
120338,120339,tip.((compliment!=5 and num>3) and ((amount<5....,"{""cardinality"": 10813, ""table"": ""tip"", ""tree"":..."

In [82]:
df_1 = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/predicate/predicates_cardinality_1.csv')

In [5]:
df = df.dropna()

In [ ]:
df_1 = df_1.dropna()

In [87]:
df_2 = pd.concat([df, df_1], axis=0)

In [7]:
df_2 = df

In [9]:
df_3  =  df_2.drop('serial', axis=1)

In [38]:
df_4 = df_3.drop_duplicates(subset='expression')

In [39]:
def complex_function(x):
    data = json.loads(x)
    return data["cardinality"]

In [40]:
df_4['count'] = df_4['cardinality'].apply(complex_function)

In [41]:
condition = df_4['count'] > 20

In [42]:
df_4 = df_4[condition]

In [43]:
df_4 = df_4.drop_duplicates(subset='expression')

In [44]:
df_4

,expression,cardinality,count
1,business.((city!='Norristown' and state='CA') ...,"{""cardinality"": 1291, ""table"": ""business"", ""tr...",1291
2,business.review!=147 or stars=3.5,"{""cardinality"": 150192, ""table"": ""business"", ""...",150192
4,business.(city='Madison' and (favorites>=115 o...,"{""cardinality"": 272, ""table"": ""business"", ""tre...",272
5,business.(city!='University City' and (review>...,"{""cardinality"": 149689, ""table"": ""business"", ""...",149689
6,business.(city='Ambler' and (state='DE' or avg...,"{""cardinality"": 203, ""table"": ""business"", ""tre...",203
...,...,...,...
120334,tip.((compliment>=3 and num<=9) and (amount!=8...,"{""cardinality"": 98, ""table"": ""tip"", ""tree"": {""...",98
120335,tip.((compliment<6 and num!=47) and ((amount>=...,"{""cardinality"": 87758, ""table"": ""tip"", ""tree"":...",87758
120336,tip.((compliment!=5 and num<86) and ((amount<8...,"{""cardinality"": 845934, ""table"": ""tip"", ""tree""...",845934
120337,tip.compliment<=2 or amount!=19.3,"{""cardinality"": 851032, ""table"": ""tip"", ""tree""...",851032
120338,tip.((compliment!=5 and num>3) and ((amount<5....,"{""cardinality"": 10813, ""table"": ""tip"", ""tree"":...",10813

In [45]:
df_4['index'] = df_4.index + 1

In [46]:
df_4

,expression,cardinality,count,index
1,business.((city!='Norristown' and state='CA') ...,"{""cardinality"": 1291, ""table"": ""business"", ""tr...",1291,2
2,business.review!=147 or stars=3.5,"{""cardinality"": 150192, ""table"": ""business"", ""...",150192,3
4,business.(city='Madison' and (favorites>=115 o...,"{""cardinality"": 272, ""table"": ""business"", ""tre...",272,5
5,business.(city!='University City' and (review>...,"{""cardinality"": 149689, ""table"": ""business"", ""...",149689,6
6,business.(city='Ambler' and (state='DE' or avg...,"{""cardinality"": 203, ""table"": ""business"", ""tre...",203,7
...,...,...,...,...
120334,tip.((compliment>=3 and num<=9) and (amount!=8...,"{""cardinality"": 98, ""table"": ""tip"", ""tree"": {""...",98,120335
120335,tip.((compliment<6 and num!=47) and ((amount>=...,"{""cardinality"": 87758, ""table"": ""tip"", ""tree"":...",87758,120336
120336,tip.((compliment!=5 and num<86) and ((amount<8...,"{""cardinality"": 845934, ""table"": ""tip"", ""tree""...",845934,120337
120337,tip.compliment<=2 or amount!=19.3,"{""cardinality"": 851032, ""table"": ""tip"", ""tree""...",851032,120338
120338,tip.((compliment!=5 and num>3) and ((amount<5....,"{""cardinality"": 10813, ""table"": ""tip"", ""tree"":...",10813,120339

In [47]:
df_4 = df_4.reset_index(drop=False)

In [48]:
df_4  =  df_4.drop('level_0', axis=1)

In [141]:
df_4.rename(columns={'Expression': 'expression'}, inplace=True)

In [142]:
df_4.rename(columns={'Cardinality': 'cardinality'}, inplace=True)

In [49]:
df_4.rename(columns={'count': 'target'}, inplace=True)

In [50]:
df_4

,expression,cardinality,target,index
0,business.((city!='Norristown' and state='CA') ...,"{""cardinality"": 1291, ""table"": ""business"", ""tr...",1291,2
1,business.review!=147 or stars=3.5,"{""cardinality"": 150192, ""table"": ""business"", ""...",150192,3
2,business.(city='Madison' and (favorites>=115 o...,"{""cardinality"": 272, ""table"": ""business"", ""tre...",272,5
3,business.(city!='University City' and (review>...,"{""cardinality"": 149689, ""table"": ""business"", ""...",149689,6
4,business.(city='Ambler' and (state='DE' or avg...,"{""cardinality"": 203, ""table"": ""business"", ""tre...",203,7
...,...,...,...,...
102715,tip.((compliment>=3 and num<=9) and (amount!=8...,"{""cardinality"": 98, ""table"": ""tip"", ""tree"": {""...",98,120335
102716,tip.((compliment<6 and num!=47) and ((amount>=...,"{""cardinality"": 87758, ""table"": ""tip"", ""tree"":...",87758,120336
102717,tip.((compliment!=5 and num<86) and ((amount<8...,"{""cardinality"": 845934, ""table"": ""tip"", ""tree""...",845934,120337
102718,tip.compliment<=2 or amount!=19.3,"{""cardinality"": 851032, ""table"": ""tip"", ""tree""...",851032,120338
102719,tip.((compliment!=5 and num>3) and ((amount<5....,"{""cardinality"": 10813, ""table"": ""tip"", ""tree"":...",10813,120339

In [51]:
df_4 = df_4.sample(frac=1, random_state=1)

In [52]:
df_4 = df_4.sample(frac=1, random_state=3)

In [53]:
df_4 = df_4.reset_index(drop=False)

In [54]:
df_4['index'] = df_4.index + 1

In [55]:
df_4  =  df_4.drop('level_0', axis=1)

In [59]:
df_4

,index,expression,cardinality,target
0,1,review.(read = FALSE and ((stars>=4.0 and funn...,"{""cardinality"": 552, ""table"": ""review"", ""tree""...",552
1,2,tip.num>=50 and amount<=13.9,"{""cardinality"": 618, ""table"": ""tip"", ""tree"": {...",618
2,3,tip.((compliment=2 and num<68) and ((amount<13...,"{""cardinality"": 539, ""table"": ""tip"", ""tree"": {...",539
3,4,review.((stars!=1.0 and useful<7.0) and (funny...,"{""cardinality"": 3473476, ""table"": ""review"", ""t...",3473476
4,5,review.read = TRUE and likes>=73,"{""cardinality"": 2401730, ""table"": ""review"", ""t...",2401730
...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289

In [58]:
df_4 = df_4[['index','expression','cardinality','target']]

In [60]:
df_4.to_csv("/remote-home/cs_acmis_wsf/ai4dingo/predicate/predicates_cardinality_all.csv", index=False)

In [61]:
df_4.to_csv("/remote-home/cs_acmis_wsf/LCEModels/attention-tree-lstm/data/predicates_cardinality_all.csv", index=False)

### 分割数据集

In [63]:
df_5 = pd.read_csv('/remote-home/cs_acmis_wsf/LCEModels/attention-tree-lstm/data/predicates_cardinality_all.csv')

In [64]:
df_5

,index,expression,cardinality,target
0,1,review.(read = FALSE and ((stars>=4.0 and funn...,"{""cardinality"": 552, ""table"": ""review"", ""tree""...",552
1,2,tip.num>=50 and amount<=13.9,"{""cardinality"": 618, ""table"": ""tip"", ""tree"": {...",618
2,3,tip.((compliment=2 and num<68) and ((amount<13...,"{""cardinality"": 539, ""table"": ""tip"", ""tree"": {...",539
3,4,review.((stars!=1.0 and useful<7.0) and (funny...,"{""cardinality"": 3473476, ""table"": ""review"", ""t...",3473476
4,5,review.read = TRUE and likes>=73,"{""cardinality"": 2401730, ""table"": ""review"", ""t...",2401730
...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289

In [65]:
def split_dataframe(df, train_ratio=0.8):
    train_size = int(train_ratio * len(df))
    train_df = df[:train_size]
    test_df = df[train_size:]
    return train_df, test_df

In [66]:
train_df, test_df = split_dataframe(df_5,0.8)

In [67]:
train_df

,index,expression,cardinality,target
0,1,review.(read = FALSE and ((stars>=4.0 and funn...,"{""cardinality"": 552, ""table"": ""review"", ""tree""...",552
1,2,tip.num>=50 and amount<=13.9,"{""cardinality"": 618, ""table"": ""tip"", ""tree"": {...",618
2,3,tip.((compliment=2 and num<68) and ((amount<13...,"{""cardinality"": 539, ""table"": ""tip"", ""tree"": {...",539
3,4,review.((stars!=1.0 and useful<7.0) and (funny...,"{""cardinality"": 3473476, ""table"": ""review"", ""t...",3473476
4,5,review.read = TRUE and likes>=73,"{""cardinality"": 2401730, ""table"": ""review"", ""t...",2401730
...,...,...,...,...
82171,82172,business.avgspend>=113 and city!='Maryland Hei...,"{""cardinality"": 25864, ""table"": ""business"", ""t...",25864
82172,82173,problem.(language = 'Chinese' and ((score='0.8...,"{""cardinality"": 112122, ""table"": ""problem"", ""t...",112122
82173,82174,review.(read = FALSE and ((funny=18.0 and cool...,"{""cardinality"": 17783, ""table"": ""review"", ""tre...",17783
82174,82175,tip.((compliment=3 and num!=20) and ((amount<1...,"{""cardinality"": 80, ""table"": ""tip"", ""tree"": {""...",80
82175,82176,business.(city='Clementon' and ((state!='IL' a...,"{""cardinality"": 92, ""table"": ""business"", ""tree...",92

In [68]:
test_df

,index,expression,cardinality,target
82176,82177,review.(read = TRUE and ((stars!=5.0 and cool!...,"{""cardinality"": 1633444, ""table"": ""review"", ""t...",1633444
82177,82178,business.stars>2.5 or state='NV',"{""cardinality"": 120917, ""table"": ""business"", ""...",120917
82178,82179,business.review<=188 and stars=4.5,"{""cardinality"": 25572, ""table"": ""business"", ""t...",25572
82179,82180,business.((city!='Newtown Square' and state!='...,"{""cardinality"": 44705, ""table"": ""business"", ""t...",44705
82180,82181,review.(read = FALSE and ((useful>28.0 and fun...,"{""cardinality"": 782310, ""table"": ""review"", ""tr...",782310
...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289

In [69]:
def get_table_name(x):
    data = json.loads(x)
    return data["table"]

In [70]:
test_df['table'] = test_df['cardinality'].apply(get_table_name)

/tmp/ipykernel_190963/725234405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['table'] = test_df['cardinality'].apply(get_table_name)

In [71]:
test_df

,index,expression,cardinality,target,table
82176,82177,review.(read = TRUE and ((stars!=5.0 and cool!...,"{""cardinality"": 1633444, ""table"": ""review"", ""t...",1633444,review
82177,82178,business.stars>2.5 or state='NV',"{""cardinality"": 120917, ""table"": ""business"", ""...",120917,business
82178,82179,business.review<=188 and stars=4.5,"{""cardinality"": 25572, ""table"": ""business"", ""t...",25572,business
82179,82180,business.((city!='Newtown Square' and state!='...,"{""cardinality"": 44705, ""table"": ""business"", ""t...",44705,business
82180,82181,review.(read = FALSE and ((useful>28.0 and fun...,"{""cardinality"": 782310, ""table"": ""review"", ""tr...",782310,review
...,...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356,review
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470,review
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472,business
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585,business
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289,tip

In [72]:
def split_dataframe_by_column(df, column_name, target_value):
    target_df = df[df[column_name] == target_value]
    other_df = df[df[column_name] != target_value]
    return target_df, other_df

In [73]:
mooccubex_test_df, yelp_test_df = split_dataframe_by_column(test_df,'table','problem')

In [76]:
mooccubex_test_df  =  mooccubex_test_df.drop('table', axis=1)

In [77]:
mooccubex_test_df

,index,expression,cardinality,target
82186,82187,problem.(language = 'Chinese' and ((score='0.8...,"{""cardinality"": 572, ""table"": ""problem"", ""tree...",572
82197,82198,problem.((language = 'Chinese' and score!='30....,"{""cardinality"": 111571, ""table"": ""problem"", ""t...",111571
82205,82206,problem.(language = 'Chinese' and ((score='10....,"{""cardinality"": 570, ""table"": ""problem"", ""tree...",570
82210,82211,problem.(language = 'Chinese' and ((score='3.5...,"{""cardinality"": 589, ""table"": ""problem"", ""tree...",589
82212,82213,problem.(language = 'English' and ((score!='30...,"{""cardinality"": 11441, ""table"": ""problem"", ""tr...",11441
...,...,...,...,...
102674,102675,problem.(language = 'Chinese' and (score!='8.0...,"{""cardinality"": 112088, ""table"": ""problem"", ""t...",112088
102681,102682,problem.(language = 'English' and ((score!='10...,"{""cardinality"": 11178, ""table"": ""problem"", ""tr...",11178
102683,102684,problem.(language = 'Chinese' and ((score='12....,"{""cardinality"": 108645, ""table"": ""problem"", ""t...",108645
102686,102687,problem.(language = 'Chinese' and ((score!='9....,"{""cardinality"": 90559, ""table"": ""problem"", ""tr...",90559
102699,102700,problem.((language = 'Chinese' and score='20.0...,"{""cardinality"": 107, ""table"": ""problem"", ""tree...",107

In [78]:
yelp_test_df  =  yelp_test_df.drop('table', axis=1)

In [79]:
yelp_test_df

,index,expression,cardinality,target
82176,82177,review.(read = TRUE and ((stars!=5.0 and cool!...,"{""cardinality"": 1633444, ""table"": ""review"", ""t...",1633444
82177,82178,business.stars>2.5 or state='NV',"{""cardinality"": 120917, ""table"": ""business"", ""...",120917
82178,82179,business.review<=188 and stars=4.5,"{""cardinality"": 25572, ""table"": ""business"", ""t...",25572
82179,82180,business.((city!='Newtown Square' and state!='...,"{""cardinality"": 44705, ""table"": ""business"", ""t...",44705
82180,82181,review.(read = FALSE and ((useful>28.0 and fun...,"{""cardinality"": 782310, ""table"": ""review"", ""tr...",782310
...,...,...,...,...
102715,102716,review.useful>5.0 and dislikes<=33,"{""cardinality"": 39356, ""table"": ""review"", ""tre...",39356
102716,102717,review.(stars!=3.0 and ((funny>=21.0 and cool<...,"{""cardinality"": 2265470, ""table"": ""review"", ""t...",2265470
102717,102718,business.((state='AB' and popular = TRUE) and ...,"{""cardinality"": 3472, ""table"": ""business"", ""tr...",3472
102718,102719,business.((city!='Collegeville' and state!='IL...,"{""cardinality"": 83585, ""table"": ""business"", ""t...",83585
102719,102720,tip.(compliment>=2 and (num>=48 or amount<=10.0)),"{""cardinality"": 289, ""table"": ""tip"", ""tree"": {...",289

In [80]:
train_df.to_csv("/remote-home/cs_acmis_wsf/LCEModels/attention-tree-lstm/data/train.csv", index=False)

In [81]:
mooccubex_test_df.to_csv("/remote-home/cs_acmis_wsf/LCEModels/attention-tree-lstm/data/mooccubex_test.csv", index=False)

In [82]:
yelp_test_df.to_csv("/remote-home/cs_acmis_wsf/LCEModels/attention-tree-lstm/data/yelp_test.csv", index=False)