In [1]:
import json
import pandas as pd
import requests
import time
import re
import multiprocessing
import math
from transformers import BertModel, BertConfig, BertTokenizer
import torch,gc
from collections import Counter
import os

### Common Function

In [2]:
def bert_define(path="/remote-home/cs_acmis_wsf/ai4dingo/model/bert_english_pretrained"):
    # 加载bert的tokenizer分词
    tokenizer = BertTokenizer.from_pretrained(path)
    # 加载预训练模型
    model_config = BertConfig.from_pretrained(path)
    model = BertModel.from_pretrained(path, config=model_config)
    model = model.cuda()
    return tokenizer, model

In [3]:
def closest_batch_size(vector_count, min_n=6, max_n=12):
    best_n = min_n
    best_batch_size = 2**best_n
    best_batch = vector_count // best_batch_size
    min_difference = abs(vector_count - best_batch * best_batch_size)

    for n in range(min_n + 1, max_n + 1):
        batch_size = 2**n
        batch = vector_count // batch_size
        difference = abs(vector_count - batch * batch_size)

        # 检查当前batch_size是否比之前的更接近vector_count
        if difference < min_difference:
            best_n = n
            best_batch_size = batch_size
            best_batch = batch
            min_difference = difference

    return best_n, best_batch_size, best_batch

In [4]:
def split_dataframe(df, n_parts, rows_per_part):
    # 计算总行数
    total_rows = len(df)
    # 计算前n-1份的总行数
    rows_for_first_n_minus_one_parts = (n_parts - 1) * rows_per_part
    # 确定是否需要额外的部分来存储剩余的数据
    extra_part_needed = total_rows > rows_for_first_n_minus_one_parts

    # 创建一个包含所有分片的列表
    dfs = []

    # 分配前n-1份
    for i in range(n_parts - 1):
        start = i * rows_per_part
        end = start + rows_per_part
        dfs.append(df.iloc[start:end])

    # 如果需要，分配最后一部分
    if extra_part_needed:
        start = (n_parts - 1) * rows_per_part
        dfs.append(df.iloc[start:])

    return dfs

In [5]:
def handle_text(text):
    text = text.replace('\n','').replace('\t','')
    return text

### handle user

In [7]:
user_data = []

# 打开JSON文件
with open('/remote-home/cs_acmis_wsf/ai4dingo/yelp/yelp_academic_dataset_user.json', 'r', encoding='utf-8') as file:
    # 逐行读取
    for line in file:
        # 解析每一行为JSON对象
        user = json.loads(line)
        user_id = user["user_id"]
        name = user["name"]
        review_count = user["review_count"]
        yelping_since = user["yelping_since"]
        useful = user["useful"]
        funny = user["funny"]
        cool = user["cool"]
        elite = user["elite"]
        fans = user["fans"]
        average_stars = user["average_stars"]
        compliment_hot = user["compliment_hot"]
        compliment_more = user["compliment_more"]
        compliment_profile = user["compliment_profile"]
        compliment_cute = user["compliment_cute"]
        compliment_list = user["compliment_list"]
        compliment_note = user["compliment_note"]
        compliment_plain = user["compliment_plain"]
        compliment_cool = user["compliment_cool"]
        compliment_funny = user["compliment_funny"]
        compliment_writer = user["compliment_writer"]
        compliment_photos = user["compliment_photos"]
        user_data.append([user_id,name,review_count,yelping_since,useful,funny,cool,elite,fans,average_stars,compliment_hot,compliment_more,compliment_profile
                         ,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos])

In [8]:
len(user_data)

1987897

In [9]:
user_df = pd.DataFrame(user_data,columns=["user_id","name","review_count","yelping_since","useful","funny","cool","elite","fans","average_stars","compliment_hot","compliment_more","compliment_profile"
                         ,"compliment_cute","compliment_list","compliment_note","compliment_plain","compliment_cool","compliment_funny","compliment_writer","compliment_photos"])

### handle business

In [16]:
business_data = []

# 打开JSON文件
with open('/remote-home/cs_acmis_wsf/ai4dingo/yelp/yelp_academic_dataset_business.json', 'r', encoding='utf-8') as file:
    # 逐行读取
    for line in file:
        # 解析每一行为JSON对象
        business = json.loads(line)
        business_id = business["business_id"]
        name = business["name"]
        address = business["address"]
        city = business["city"]
        state = business["state"]
        postal_code = business["postal_code"]
        stars = business["stars"]
        review_count = business["review_count"]
        categories = business["categories"]
        business_data.append([business_id,name,address,city,state,postal_code,stars,review_count,categories])

In [64]:
business_df = pd.DataFrame(business_data,columns=["business_id","name","address","city","state","postal_code","stars","review_count","categories"])

In [65]:
business_df['length'] = business_df['categories'].str.len()

In [67]:
business_df = business_df.dropna(subset=['categories'])

In [68]:
business_df

,business_id,name,address,city,state,postal_code,stars,review_count,categories,length
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,5.0,7,"Doctors, Traditional Chinese Medicine, Naturop...",106.0
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,3.0,15,"Shipping Centers, Local Services, Notaries, Ma...",78.0
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,3.5,22,"Department Stores, Shopping, Fashion, Home & G...",82.0
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",53.0
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,4.5,13,"Brewpubs, Breweries, Food",25.0
...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,3.0,13,"Nail Salons, Beauty & Spas",26.0
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,4.0,5,"Pets, Nurseries & Gardening, Pet Stores, Hobby...",89.0
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,3.5,8,"Shopping, Jewelry, Piercing, Toy Stores, Beaut...",76.0
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,4.0,24,"Fitness/Exercise Equipment, Eyewear & Optician...",80.0
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,4.5,9,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo",49.0

In [32]:
tokenizer,model = bert_define()

Some weights of the model checkpoint at /remote-home/cs_acmis_wsf/ai4dingo/model/bert_english_pretrained were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [33]:
# 构成一个小batch
batch_token, batch_segment, batch_mask = list(), list(), list()

In [74]:
text = business_df["categories"].tolist()

In [75]:
max_len = int(business_df["length"].max())

In [76]:
for t in text:
    # text 作 tokenizer 分词
    token = tokenizer.tokenize(t)
    token = ['[CLS]'] + token + ['[SEP]']
    token_id = tokenizer.convert_tokens_to_ids(token)  # 字转换vocab中的index 
    # 加padding补齐及segment、mask
    padding = [0] * (max_len - len(token_id))
    mask = [1] * len(token_id) + padding
    segment = [0] * len(token_id) + padding
    token_id = token_id + padding

    batch_token.append(token_id)
    batch_segment.append(segment)
    batch_mask.append(mask)

In [79]:
vector_count = min([len(business_df),len(batch_mask),len(batch_segment),len(batch_token)])

In [80]:
vector_count

150243

In [82]:
n, batch_size, batch = closest_batch_size(vector_count)
print(f"vector_count: {vector_count}, n: {n}, batch_size: {batch_size}, batch: {batch}")

vector_count: 150243, n: 6, batch_size: 64, batch: 2347

In [97]:
rows_per_part = 5120
n =  math.ceil(vector_count / rows_per_part)

In [98]:
split_dfs_business = split_dataframe(business_df, n,rows_per_part)

##### 循环处理

In [100]:
batch_size_num = 64

for i in range(len(split_dfs_business)):
    df = split_dfs_business[i]
    print(f'正在读取第 {i+1} 个DF')
    text = df["categories"].tolist()
    
    print(f'初始化batch数据： {i+1}')
    batch_token, batch_segment, batch_mask = list(), list(), list()
    for t in text:
        # text 作 tokenizer 分词
        token = tokenizer.tokenize(t)
        token = ['[CLS]'] + token + ['[SEP]']
        token_id = tokenizer.convert_tokens_to_ids(token)  # 字转换vocab中的index

        # 加padding补齐及segment、mask
        padding = [0] * (max_len - len(token_id))
        mask = [1] * len(token_id) + padding
        segment = [0] * len(token_id) + padding
        token_id = token_id + padding

        batch_token.append(token_id)
        batch_segment.append(segment)
        batch_mask.append(mask)
        
    print(f'batch数据 组装完毕 ：{i+1}')
   
    batch_tensor_token = torch.tensor(batch_token)
    batch_tensor_segment = torch.tensor(batch_segment)
    batch_tensor_mask = torch.tensor(batch_mask)

    batch_len = len(batch_tensor_token)
    
    if torch.cuda.is_available():
        batch_tensor_token = batch_tensor_token.to('cuda:0')
        batch_tensor_segment = batch_tensor_segment.to('cuda:0')
        batch_tensor_mask = batch_tensor_mask.to('cuda:0')
    
    print(f'batch_tensor数据 组装完毕 ：{i+1},开始分块处理')
    
    batch_tensor_token_chunked = [batch_tensor_token[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    batch_tensor_segment_chunked = [batch_tensor_segment[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    batch_tensor_mask_chunked = [batch_tensor_mask[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    print(f'分块处理完毕数据完毕，每块的长度为:{batch_size_num},一共有 {len(batch_tensor_token_chunked)} 块， 开始调用模型')
    
    gc.collect()
    torch.cuda.empty_cache()
    text_vector = []
    
    try:
        for k in range(len(batch_tensor_token_chunked)):
            with torch.no_grad():
                print(f'正在处理 {i+1} ----- {k+1}')
                outputs = model(batch_tensor_token_chunked[k], token_type_ids=batch_tensor_segment_chunked[k], attention_mask=batch_tensor_mask_chunked[k])
                outputs = outputs[0][:, 0, :]  # 取cls向量
                for o in range(outputs.shape[0]):
                    text_vector.append(outputs[o])
        df["feature"] = [ tv.tolist() for tv in  text_vector] 
        df.to_csv(f'/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business_{i+1}.csv', index=False)
        print(f"文件写入完毕 {i+1}")
                    
    except Exception as e:
        print(f"出现异常 {i+1}: {e}")
        continue
            
    
    print('============================')
    print()

正在读取第 1 个DF
初始化batch数据： 1
batch数据 组装完毕 ：1
batch_tensor数据 组装完毕 ：1,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 1 ----- 1
正在处理 1 ----- 2
正在处理 1 ----- 3
正在处理 1 ----- 4
正在处理 1 ----- 5
正在处理 1 ----- 6
正在处理 1 ----- 7
正在处理 1 ----- 8
正在处理 1 ----- 9
正在处理 1 ----- 10
正在处理 1 ----- 11
正在处理 1 ----- 12
正在处理 1 ----- 13
正在处理 1 ----- 14
正在处理 1 ----- 15
正在处理 1 ----- 16
正在处理 1 ----- 17
正在处理 1 ----- 18
正在处理 1 ----- 19
正在处理 1 ----- 20
正在处理 1 ----- 21
正在处理 1 ----- 22
正在处理 1 ----- 23
正在处理 1 ----- 24
正在处理 1 ----- 25
正在处理 1 ----- 26
正在处理 1 ----- 27
正在处理 1 ----- 28
正在处理 1 ----- 29
正在处理 1 ----- 30
正在处理 1 ----- 31
正在处理 1 ----- 32
正在处理 1 ----- 33
正在处理 1 ----- 34
正在处理 1 ----- 35
正在处理 1 ----- 36
正在处理 1 ----- 37
正在处理 1 ----- 38
正在处理 1 ----- 39
正在处理 1 ----- 40
正在处理 1 ----- 41
正在处理 1 ----- 42
正在处理 1 ----- 43
正在处理 1 ----- 44
正在处理 1 ----- 45
正在处理 1 ----- 46
正在处理 1 ----- 47
正在处理 1 ----- 48
正在处理 1 ----- 49
正在处理 1 ----- 50
正在处理 1 ----- 51
正在处理 1 ----- 52
正在处理 1 ----- 53
正在处理 1 ----- 54
正在处理 1 ----- 55
正在处理 1 ----- 56
正在处理 1 ----- 57
正在处理 1 ----- 58
正在处理 1 ----- 59
正在处理 1 ----- 60
正在处理 1 ----- 61
正在处理 1 ----- 62
正在处理 1 ----- 63
正在处理 1 ----- 64
正在处理 1 ----- 65
正在处理 1 ----- 66
正在处理 1 ----- 67
正在处理 1 ----- 68
正在处理 1 ----- 69
正在处理 1 ----- 70
正在处理 1 ----- 71
正在处理 1 ----- 72
正在处理 1 ----- 73
正在处理 1 ----- 74
正在处理 1 ----- 75
正在处理 1 ----- 76
正在处理 1 ----- 77
正在处理 1 ----- 78
正在处理 1 ----- 79
正在处理 1 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1
============================

正在读取第 2 个DF
初始化batch数据： 2
batch数据 组装完毕 ：2
batch_tensor数据 组装完毕 ：2,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 2 ----- 1
正在处理 2 ----- 2
正在处理 2 ----- 3
正在处理 2 ----- 4
正在处理 2 ----- 5
正在处理 2 ----- 6
正在处理 2 ----- 7
正在处理 2 ----- 8
正在处理 2 ----- 9
正在处理 2 ----- 10
正在处理 2 ----- 11
正在处理 2 ----- 12
正在处理 2 ----- 13
正在处理 2 ----- 14
正在处理 2 ----- 15
正在处理 2 ----- 16
正在处理 2 ----- 17
正在处理 2 ----- 18
正在处理 2 ----- 19
正在处理 2 ----- 20
正在处理 2 ----- 21
正在处理 2 ----- 22
正在处理 2 ----- 23
正在处理 2 ----- 24
正在处理 2 ----- 25
正在处理 2 ----- 26
正在处理 2 ----- 27
正在处理 2 ----- 28
正在处理 2 ----- 29
正在处理 2 ----- 30
正在处理 2 ----- 31
正在处理 2 ----- 32
正在处理 2 ----- 33
正在处理 2 ----- 34
正在处理 2 ----- 35
正在处理 2 ----- 36
正在处理 2 ----- 37
正在处理 2 ----- 38
正在处理 2 ----- 39
正在处理 2 ----- 40
正在处理 2 ----- 41
正在处理 2 ----- 42
正在处理 2 ----- 43
正在处理 2 ----- 44
正在处理 2 ----- 45
正在处理 2 ----- 46
正在处理 2 ----- 47
正在处理 2 ----- 48
正在处理 2 ----- 49
正在处理 2 ----- 50
正在处理 2 ----- 51
正在处理 2 ----- 52
正在处理 2 ----- 53
正在处理 2 ----- 54
正在处理 2 ----- 55
正在处理 2 ----- 56
正在处理 2 ----- 57
正在处理 2 ----- 58
正在处理 2 ----- 59
正在处理 2 ----- 60
正在处理 2 ----- 61
正在处理 2 ----- 62
正在处理 2 ----- 63
正在处理 2 ----- 64
正在处理 2 ----- 65
正在处理 2 ----- 66
正在处理 2 ----- 67
正在处理 2 ----- 68
正在处理 2 ----- 69
正在处理 2 ----- 70
正在处理 2 ----- 71
正在处理 2 ----- 72
正在处理 2 ----- 73
正在处理 2 ----- 74
正在处理 2 ----- 75
正在处理 2 ----- 76
正在处理 2 ----- 77
正在处理 2 ----- 78
正在处理 2 ----- 79
正在处理 2 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 2
============================

正在读取第 3 个DF
初始化batch数据： 3
batch数据 组装完毕 ：3
batch_tensor数据 组装完毕 ：3,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 3 ----- 1
正在处理 3 ----- 2
正在处理 3 ----- 3
正在处理 3 ----- 4
正在处理 3 ----- 5
正在处理 3 ----- 6
正在处理 3 ----- 7
正在处理 3 ----- 8
正在处理 3 ----- 9
正在处理 3 ----- 10
正在处理 3 ----- 11
正在处理 3 ----- 12
正在处理 3 ----- 13
正在处理 3 ----- 14
正在处理 3 ----- 15
正在处理 3 ----- 16
正在处理 3 ----- 17
正在处理 3 ----- 18
正在处理 3 ----- 19
正在处理 3 ----- 20
正在处理 3 ----- 21
正在处理 3 ----- 22
正在处理 3 ----- 23
正在处理 3 ----- 24
正在处理 3 ----- 25
正在处理 3 ----- 26
正在处理 3 ----- 27
正在处理 3 ----- 28
正在处理 3 ----- 29
正在处理 3 ----- 30
正在处理 3 ----- 31
正在处理 3 ----- 32
正在处理 3 ----- 33
正在处理 3 ----- 34
正在处理 3 ----- 35
正在处理 3 ----- 36
正在处理 3 ----- 37
正在处理 3 ----- 38
正在处理 3 ----- 39
正在处理 3 ----- 40
正在处理 3 ----- 41
正在处理 3 ----- 42
正在处理 3 ----- 43
正在处理 3 ----- 44
正在处理 3 ----- 45
正在处理 3 ----- 46
正在处理 3 ----- 47
正在处理 3 ----- 48
正在处理 3 ----- 49
正在处理 3 ----- 50
正在处理 3 ----- 51
正在处理 3 ----- 52
正在处理 3 ----- 53
正在处理 3 ----- 54
正在处理 3 ----- 55
正在处理 3 ----- 56
正在处理 3 ----- 57
正在处理 3 ----- 58
正在处理 3 ----- 59
正在处理 3 ----- 60
正在处理 3 ----- 61
正在处理 3 ----- 62
正在处理 3 ----- 63
正在处理 3 ----- 64
正在处理 3 ----- 65
正在处理 3 ----- 66
正在处理 3 ----- 67
正在处理 3 ----- 68
正在处理 3 ----- 69
正在处理 3 ----- 70
正在处理 3 ----- 71
正在处理 3 ----- 72
正在处理 3 ----- 73
正在处理 3 ----- 74
正在处理 3 ----- 75
正在处理 3 ----- 76
正在处理 3 ----- 77
正在处理 3 ----- 78
正在处理 3 ----- 79
正在处理 3 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 3
============================

正在读取第 4 个DF
初始化batch数据： 4
batch数据 组装完毕 ：4
batch_tensor数据 组装完毕 ：4,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 4 ----- 1
正在处理 4 ----- 2
正在处理 4 ----- 3
正在处理 4 ----- 4
正在处理 4 ----- 5
正在处理 4 ----- 6
正在处理 4 ----- 7
正在处理 4 ----- 8
正在处理 4 ----- 9
正在处理 4 ----- 10
正在处理 4 ----- 11
正在处理 4 ----- 12
正在处理 4 ----- 13
正在处理 4 ----- 14
正在处理 4 ----- 15
正在处理 4 ----- 16
正在处理 4 ----- 17
正在处理 4 ----- 18
正在处理 4 ----- 19
正在处理 4 ----- 20
正在处理 4 ----- 21
正在处理 4 ----- 22
正在处理 4 ----- 23
正在处理 4 ----- 24
正在处理 4 ----- 25
正在处理 4 ----- 26
正在处理 4 ----- 27
正在处理 4 ----- 28
正在处理 4 ----- 29
正在处理 4 ----- 30
正在处理 4 ----- 31
正在处理 4 ----- 32
正在处理 4 ----- 33
正在处理 4 ----- 34
正在处理 4 ----- 35
正在处理 4 ----- 36
正在处理 4 ----- 37
正在处理 4 ----- 38
正在处理 4 ----- 39
正在处理 4 ----- 40
正在处理 4 ----- 41
正在处理 4 ----- 42
正在处理 4 ----- 43
正在处理 4 ----- 44
正在处理 4 ----- 45
正在处理 4 ----- 46
正在处理 4 ----- 47
正在处理 4 ----- 48
正在处理 4 ----- 49
正在处理 4 ----- 50
正在处理 4 ----- 51
正在处理 4 ----- 52
正在处理 4 ----- 53
正在处理 4 ----- 54
正在处理 4 ----- 55
正在处理 4 ----- 56
正在处理 4 ----- 57
正在处理 4 ----- 58
正在处理 4 ----- 59
正在处理 4 ----- 60
正在处理 4 ----- 61
正在处理 4 ----- 62
正在处理 4 ----- 63
正在处理 4 ----- 64
正在处理 4 ----- 65
正在处理 4 ----- 66
正在处理 4 ----- 67
正在处理 4 ----- 68
正在处理 4 ----- 69
正在处理 4 ----- 70
正在处理 4 ----- 71
正在处理 4 ----- 72
正在处理 4 ----- 73
正在处理 4 ----- 74
正在处理 4 ----- 75
正在处理 4 ----- 76
正在处理 4 ----- 77
正在处理 4 ----- 78
正在处理 4 ----- 79
正在处理 4 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 4
============================

正在读取第 5 个DF
初始化batch数据： 5
batch数据 组装完毕 ：5
batch_tensor数据 组装完毕 ：5,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 5 ----- 1
正在处理 5 ----- 2
正在处理 5 ----- 3
正在处理 5 ----- 4
正在处理 5 ----- 5
正在处理 5 ----- 6
正在处理 5 ----- 7
正在处理 5 ----- 8
正在处理 5 ----- 9
正在处理 5 ----- 10
正在处理 5 ----- 11
正在处理 5 ----- 12
正在处理 5 ----- 13
正在处理 5 ----- 14
正在处理 5 ----- 15
正在处理 5 ----- 16
正在处理 5 ----- 17
正在处理 5 ----- 18
正在处理 5 ----- 19
正在处理 5 ----- 20
正在处理 5 ----- 21
正在处理 5 ----- 22
正在处理 5 ----- 23
正在处理 5 ----- 24
正在处理 5 ----- 25
正在处理 5 ----- 26
正在处理 5 ----- 27
正在处理 5 ----- 28
正在处理 5 ----- 29
正在处理 5 ----- 30
正在处理 5 ----- 31
正在处理 5 ----- 32
正在处理 5 ----- 33
正在处理 5 ----- 34
正在处理 5 ----- 35
正在处理 5 ----- 36
正在处理 5 ----- 37
正在处理 5 ----- 38
正在处理 5 ----- 39
正在处理 5 ----- 40
正在处理 5 ----- 41
正在处理 5 ----- 42
正在处理 5 ----- 43
正在处理 5 ----- 44
正在处理 5 ----- 45
正在处理 5 ----- 46
正在处理 5 ----- 47
正在处理 5 ----- 48
正在处理 5 ----- 49
正在处理 5 ----- 50
正在处理 5 ----- 51
正在处理 5 ----- 52
正在处理 5 ----- 53
正在处理 5 ----- 54
正在处理 5 ----- 55
正在处理 5 ----- 56
正在处理 5 ----- 57
正在处理 5 ----- 58
正在处理 5 ----- 59
正在处理 5 ----- 60
正在处理 5 ----- 61
正在处理 5 ----- 62
正在处理 5 ----- 63
正在处理 5 ----- 64
正在处理 5 ----- 65
正在处理 5 ----- 66
正在处理 5 ----- 67
正在处理 5 ----- 68
正在处理 5 ----- 69
正在处理 5 ----- 70
正在处理 5 ----- 71
正在处理 5 ----- 72
正在处理 5 ----- 73
正在处理 5 ----- 74
正在处理 5 ----- 75
正在处理 5 ----- 76
正在处理 5 ----- 77
正在处理 5 ----- 78
正在处理 5 ----- 79
正在处理 5 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 5
============================

正在读取第 6 个DF
初始化batch数据： 6
batch数据 组装完毕 ：6
batch_tensor数据 组装完毕 ：6,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 6 ----- 1
正在处理 6 ----- 2
正在处理 6 ----- 3
正在处理 6 ----- 4
正在处理 6 ----- 5
正在处理 6 ----- 6
正在处理 6 ----- 7
正在处理 6 ----- 8
正在处理 6 ----- 9
正在处理 6 ----- 10
正在处理 6 ----- 11
正在处理 6 ----- 12
正在处理 6 ----- 13
正在处理 6 ----- 14
正在处理 6 ----- 15
正在处理 6 ----- 16
正在处理 6 ----- 17
正在处理 6 ----- 18
正在处理 6 ----- 19
正在处理 6 ----- 20
正在处理 6 ----- 21
正在处理 6 ----- 22
正在处理 6 ----- 23
正在处理 6 ----- 24
正在处理 6 ----- 25
正在处理 6 ----- 26
正在处理 6 ----- 27
正在处理 6 ----- 28
正在处理 6 ----- 29
正在处理 6 ----- 30
正在处理 6 ----- 31
正在处理 6 ----- 32
正在处理 6 ----- 33
正在处理 6 ----- 34
正在处理 6 ----- 35
正在处理 6 ----- 36
正在处理 6 ----- 37
正在处理 6 ----- 38
正在处理 6 ----- 39
正在处理 6 ----- 40
正在处理 6 ----- 41
正在处理 6 ----- 42
正在处理 6 ----- 43
正在处理 6 ----- 44
正在处理 6 ----- 45
正在处理 6 ----- 46
正在处理 6 ----- 47
正在处理 6 ----- 48
正在处理 6 ----- 49
正在处理 6 ----- 50
正在处理 6 ----- 51
正在处理 6 ----- 52
正在处理 6 ----- 53
正在处理 6 ----- 54
正在处理 6 ----- 55
正在处理 6 ----- 56
正在处理 6 ----- 57
正在处理 6 ----- 58
正在处理 6 ----- 59
正在处理 6 ----- 60
正在处理 6 ----- 61
正在处理 6 ----- 62
正在处理 6 ----- 63
正在处理 6 ----- 64
正在处理 6 ----- 65
正在处理 6 ----- 66
正在处理 6 ----- 67
正在处理 6 ----- 68
正在处理 6 ----- 69
正在处理 6 ----- 70
正在处理 6 ----- 71
正在处理 6 ----- 72
正在处理 6 ----- 73
正在处理 6 ----- 74
正在处理 6 ----- 75
正在处理 6 ----- 76
正在处理 6 ----- 77
正在处理 6 ----- 78
正在处理 6 ----- 79
正在处理 6 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 6
============================

正在读取第 7 个DF
初始化batch数据： 7
batch数据 组装完毕 ：7
batch_tensor数据 组装完毕 ：7,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 7 ----- 1
正在处理 7 ----- 2
正在处理 7 ----- 3
正在处理 7 ----- 4
正在处理 7 ----- 5
正在处理 7 ----- 6
正在处理 7 ----- 7
正在处理 7 ----- 8
正在处理 7 ----- 9
正在处理 7 ----- 10
正在处理 7 ----- 11
正在处理 7 ----- 12
正在处理 7 ----- 13
正在处理 7 ----- 14
正在处理 7 ----- 15
正在处理 7 ----- 16
正在处理 7 ----- 17
正在处理 7 ----- 18
正在处理 7 ----- 19
正在处理 7 ----- 20
正在处理 7 ----- 21
正在处理 7 ----- 22
正在处理 7 ----- 23
正在处理 7 ----- 24
正在处理 7 ----- 25
正在处理 7 ----- 26
正在处理 7 ----- 27
正在处理 7 ----- 28
正在处理 7 ----- 29
正在处理 7 ----- 30
正在处理 7 ----- 31
正在处理 7 ----- 32
正在处理 7 ----- 33
正在处理 7 ----- 34
正在处理 7 ----- 35
正在处理 7 ----- 36
正在处理 7 ----- 37
正在处理 7 ----- 38
正在处理 7 ----- 39
正在处理 7 ----- 40
正在处理 7 ----- 41
正在处理 7 ----- 42
正在处理 7 ----- 43
正在处理 7 ----- 44
正在处理 7 ----- 45
正在处理 7 ----- 46
正在处理 7 ----- 47
正在处理 7 ----- 48
正在处理 7 ----- 49
正在处理 7 ----- 50
正在处理 7 ----- 51
正在处理 7 ----- 52
正在处理 7 ----- 53
正在处理 7 ----- 54
正在处理 7 ----- 55
正在处理 7 ----- 56
正在处理 7 ----- 57
正在处理 7 ----- 58
正在处理 7 ----- 59
正在处理 7 ----- 60
正在处理 7 ----- 61
正在处理 7 ----- 62
正在处理 7 ----- 63
正在处理 7 ----- 64
正在处理 7 ----- 65
正在处理 7 ----- 66
正在处理 7 ----- 67
正在处理 7 ----- 68
正在处理 7 ----- 69
正在处理 7 ----- 70
正在处理 7 ----- 71
正在处理 7 ----- 72
正在处理 7 ----- 73
正在处理 7 ----- 74
正在处理 7 ----- 75
正在处理 7 ----- 76
正在处理 7 ----- 77
正在处理 7 ----- 78
正在处理 7 ----- 79
正在处理 7 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 7
============================

正在读取第 8 个DF
初始化batch数据： 8
batch数据 组装完毕 ：8
batch_tensor数据 组装完毕 ：8,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 8 ----- 1
正在处理 8 ----- 2
正在处理 8 ----- 3
正在处理 8 ----- 4
正在处理 8 ----- 5
正在处理 8 ----- 6
正在处理 8 ----- 7
正在处理 8 ----- 8
正在处理 8 ----- 9
正在处理 8 ----- 10
正在处理 8 ----- 11
正在处理 8 ----- 12
正在处理 8 ----- 13
正在处理 8 ----- 14
正在处理 8 ----- 15
正在处理 8 ----- 16
正在处理 8 ----- 17
正在处理 8 ----- 18
正在处理 8 ----- 19
正在处理 8 ----- 20
正在处理 8 ----- 21
正在处理 8 ----- 22
正在处理 8 ----- 23
正在处理 8 ----- 24
正在处理 8 ----- 25
正在处理 8 ----- 26
正在处理 8 ----- 27
正在处理 8 ----- 28
正在处理 8 ----- 29
正在处理 8 ----- 30
正在处理 8 ----- 31
正在处理 8 ----- 32
正在处理 8 ----- 33
正在处理 8 ----- 34
正在处理 8 ----- 35
正在处理 8 ----- 36
正在处理 8 ----- 37
正在处理 8 ----- 38
正在处理 8 ----- 39
正在处理 8 ----- 40
正在处理 8 ----- 41
正在处理 8 ----- 42
正在处理 8 ----- 43
正在处理 8 ----- 44
正在处理 8 ----- 45
正在处理 8 ----- 46
正在处理 8 ----- 47
正在处理 8 ----- 48
正在处理 8 ----- 49
正在处理 8 ----- 50
正在处理 8 ----- 51
正在处理 8 ----- 52
正在处理 8 ----- 53
正在处理 8 ----- 54
正在处理 8 ----- 55
正在处理 8 ----- 56
正在处理 8 ----- 57
正在处理 8 ----- 58
正在处理 8 ----- 59
正在处理 8 ----- 60
正在处理 8 ----- 61
正在处理 8 ----- 62
正在处理 8 ----- 63
正在处理 8 ----- 64
正在处理 8 ----- 65
正在处理 8 ----- 66
正在处理 8 ----- 67
正在处理 8 ----- 68
正在处理 8 ----- 69
正在处理 8 ----- 70
正在处理 8 ----- 71
正在处理 8 ----- 72
正在处理 8 ----- 73
正在处理 8 ----- 74
正在处理 8 ----- 75
正在处理 8 ----- 76
正在处理 8 ----- 77
正在处理 8 ----- 78
正在处理 8 ----- 79
正在处理 8 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 8
============================

正在读取第 9 个DF
初始化batch数据： 9
batch数据 组装完毕 ：9
batch_tensor数据 组装完毕 ：9,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 9 ----- 1
正在处理 9 ----- 2
正在处理 9 ----- 3
正在处理 9 ----- 4
正在处理 9 ----- 5
正在处理 9 ----- 6
正在处理 9 ----- 7
正在处理 9 ----- 8
正在处理 9 ----- 9
正在处理 9 ----- 10
正在处理 9 ----- 11
正在处理 9 ----- 12
正在处理 9 ----- 13
正在处理 9 ----- 14
正在处理 9 ----- 15
正在处理 9 ----- 16
正在处理 9 ----- 17
正在处理 9 ----- 18
正在处理 9 ----- 19
正在处理 9 ----- 20
正在处理 9 ----- 21
正在处理 9 ----- 22
正在处理 9 ----- 23
正在处理 9 ----- 24
正在处理 9 ----- 25
正在处理 9 ----- 26
正在处理 9 ----- 27
正在处理 9 ----- 28
正在处理 9 ----- 29
正在处理 9 ----- 30
正在处理 9 ----- 31
正在处理 9 ----- 32
正在处理 9 ----- 33
正在处理 9 ----- 34
正在处理 9 ----- 35
正在处理 9 ----- 36
正在处理 9 ----- 37
正在处理 9 ----- 38
正在处理 9 ----- 39
正在处理 9 ----- 40
正在处理 9 ----- 41
正在处理 9 ----- 42
正在处理 9 ----- 43
正在处理 9 ----- 44
正在处理 9 ----- 45
正在处理 9 ----- 46
正在处理 9 ----- 47
正在处理 9 ----- 48
正在处理 9 ----- 49
正在处理 9 ----- 50
正在处理 9 ----- 51
正在处理 9 ----- 52
正在处理 9 ----- 53
正在处理 9 ----- 54
正在处理 9 ----- 55
正在处理 9 ----- 56
正在处理 9 ----- 57
正在处理 9 ----- 58
正在处理 9 ----- 59
正在处理 9 ----- 60
正在处理 9 ----- 61
正在处理 9 ----- 62
正在处理 9 ----- 63
正在处理 9 ----- 64
正在处理 9 ----- 65
正在处理 9 ----- 66
正在处理 9 ----- 67
正在处理 9 ----- 68
正在处理 9 ----- 69
正在处理 9 ----- 70
正在处理 9 ----- 71
正在处理 9 ----- 72
正在处理 9 ----- 73
正在处理 9 ----- 74
正在处理 9 ----- 75
正在处理 9 ----- 76
正在处理 9 ----- 77
正在处理 9 ----- 78
正在处理 9 ----- 79
正在处理 9 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 9
============================

正在读取第 10 个DF
初始化batch数据： 10
batch数据 组装完毕 ：10
batch_tensor数据 组装完毕 ：10,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 10 ----- 1
正在处理 10 ----- 2
正在处理 10 ----- 3
正在处理 10 ----- 4
正在处理 10 ----- 5
正在处理 10 ----- 6
正在处理 10 ----- 7
正在处理 10 ----- 8
正在处理 10 ----- 9
正在处理 10 ----- 10
正在处理 10 ----- 11
正在处理 10 ----- 12
正在处理 10 ----- 13
正在处理 10 ----- 14
正在处理 10 ----- 15
正在处理 10 ----- 16
正在处理 10 ----- 17
正在处理 10 ----- 18
正在处理 10 ----- 19
正在处理 10 ----- 20
正在处理 10 ----- 21
正在处理 10 ----- 22
正在处理 10 ----- 23
正在处理 10 ----- 24
正在处理 10 ----- 25
正在处理 10 ----- 26
正在处理 10 ----- 27
正在处理 10 ----- 28
正在处理 10 ----- 29
正在处理 10 ----- 30
正在处理 10 ----- 31
正在处理 10 ----- 32
正在处理 10 ----- 33
正在处理 10 ----- 34
正在处理 10 ----- 35
正在处理 10 ----- 36
正在处理 10 ----- 37
正在处理 10 ----- 38
正在处理 10 ----- 39
正在处理 10 ----- 40
正在处理 10 ----- 41
正在处理 10 ----- 42
正在处理 10 ----- 43
正在处理 10 ----- 44
正在处理 10 ----- 45
正在处理 10 ----- 46
正在处理 10 ----- 47
正在处理 10 ----- 48
正在处理 10 ----- 49
正在处理 10 ----- 50
正在处理 10 ----- 51
正在处理 10 ----- 52
正在处理 10 ----- 53
正在处理 10 ----- 54
正在处理 10 ----- 55
正在处理 10 ----- 56
正在处理 10 ----- 57
正在处理 10 ----- 58
正在处理 10 ----- 59
正在处理 10 ----- 60
正在处理 10 ----- 61
正在处理 10 ----- 62
正在处理 10 ----- 63
正在处理 10 ----- 64
正在处理 10 ----- 65
正在处理 10 ----- 66
正在处理 10 ----- 67
正在处理 10 ----- 68
正在处理 10 ----- 69
正在处理 10 ----- 70
正在处理 10 ----- 71
正在处理 10 ----- 72
正在处理 10 ----- 73
正在处理 10 ----- 74
正在处理 10 ----- 75
正在处理 10 ----- 76
正在处理 10 ----- 77
正在处理 10 ----- 78
正在处理 10 ----- 79
正在处理 10 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 10
============================

正在读取第 11 个DF
初始化batch数据： 11
batch数据 组装完毕 ：11
batch_tensor数据 组装完毕 ：11,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 11 ----- 1
正在处理 11 ----- 2
正在处理 11 ----- 3
正在处理 11 ----- 4
正在处理 11 ----- 5
正在处理 11 ----- 6
正在处理 11 ----- 7
正在处理 11 ----- 8
正在处理 11 ----- 9
正在处理 11 ----- 10
正在处理 11 ----- 11
正在处理 11 ----- 12
正在处理 11 ----- 13
正在处理 11 ----- 14
正在处理 11 ----- 15
正在处理 11 ----- 16
正在处理 11 ----- 17
正在处理 11 ----- 18
正在处理 11 ----- 19
正在处理 11 ----- 20
正在处理 11 ----- 21
正在处理 11 ----- 22
正在处理 11 ----- 23
正在处理 11 ----- 24
正在处理 11 ----- 25
正在处理 11 ----- 26
正在处理 11 ----- 27
正在处理 11 ----- 28
正在处理 11 ----- 29
正在处理 11 ----- 30
正在处理 11 ----- 31
正在处理 11 ----- 32
正在处理 11 ----- 33
正在处理 11 ----- 34
正在处理 11 ----- 35
正在处理 11 ----- 36
正在处理 11 ----- 37
正在处理 11 ----- 38
正在处理 11 ----- 39
正在处理 11 ----- 40
正在处理 11 ----- 41
正在处理 11 ----- 42
正在处理 11 ----- 43
正在处理 11 ----- 44
正在处理 11 ----- 45
正在处理 11 ----- 46
正在处理 11 ----- 47
正在处理 11 ----- 48
正在处理 11 ----- 49
正在处理 11 ----- 50
正在处理 11 ----- 51
正在处理 11 ----- 52
正在处理 11 ----- 53
正在处理 11 ----- 54
正在处理 11 ----- 55
正在处理 11 ----- 56
正在处理 11 ----- 57
正在处理 11 ----- 58
正在处理 11 ----- 59
正在处理 11 ----- 60
正在处理 11 ----- 61
正在处理 11 ----- 62
正在处理 11 ----- 63
正在处理 11 ----- 64
正在处理 11 ----- 65
正在处理 11 ----- 66
正在处理 11 ----- 67
正在处理 11 ----- 68
正在处理 11 ----- 69
正在处理 11 ----- 70
正在处理 11 ----- 71
正在处理 11 ----- 72
正在处理 11 ----- 73
正在处理 11 ----- 74
正在处理 11 ----- 75
正在处理 11 ----- 76
正在处理 11 ----- 77
正在处理 11 ----- 78
正在处理 11 ----- 79
正在处理 11 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 11
============================

正在读取第 12 个DF
初始化batch数据： 12
batch数据 组装完毕 ：12
batch_tensor数据 组装完毕 ：12,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 12 ----- 1
正在处理 12 ----- 2
正在处理 12 ----- 3
正在处理 12 ----- 4
正在处理 12 ----- 5
正在处理 12 ----- 6
正在处理 12 ----- 7
正在处理 12 ----- 8
正在处理 12 ----- 9
正在处理 12 ----- 10
正在处理 12 ----- 11
正在处理 12 ----- 12
正在处理 12 ----- 13
正在处理 12 ----- 14
正在处理 12 ----- 15
正在处理 12 ----- 16
正在处理 12 ----- 17
正在处理 12 ----- 18
正在处理 12 ----- 19
正在处理 12 ----- 20
正在处理 12 ----- 21
正在处理 12 ----- 22
正在处理 12 ----- 23
正在处理 12 ----- 24
正在处理 12 ----- 25
正在处理 12 ----- 26
正在处理 12 ----- 27
正在处理 12 ----- 28
正在处理 12 ----- 29
正在处理 12 ----- 30
正在处理 12 ----- 31
正在处理 12 ----- 32
正在处理 12 ----- 33
正在处理 12 ----- 34
正在处理 12 ----- 35
正在处理 12 ----- 36
正在处理 12 ----- 37
正在处理 12 ----- 38
正在处理 12 ----- 39
正在处理 12 ----- 40
正在处理 12 ----- 41
正在处理 12 ----- 42
正在处理 12 ----- 43
正在处理 12 ----- 44
正在处理 12 ----- 45
正在处理 12 ----- 46
正在处理 12 ----- 47
正在处理 12 ----- 48
正在处理 12 ----- 49
正在处理 12 ----- 50
正在处理 12 ----- 51
正在处理 12 ----- 52
正在处理 12 ----- 53
正在处理 12 ----- 54
正在处理 12 ----- 55
正在处理 12 ----- 56
正在处理 12 ----- 57
正在处理 12 ----- 58
正在处理 12 ----- 59
正在处理 12 ----- 60
正在处理 12 ----- 61
正在处理 12 ----- 62
正在处理 12 ----- 63
正在处理 12 ----- 64
正在处理 12 ----- 65
正在处理 12 ----- 66
正在处理 12 ----- 67
正在处理 12 ----- 68
正在处理 12 ----- 69
正在处理 12 ----- 70
正在处理 12 ----- 71
正在处理 12 ----- 72
正在处理 12 ----- 73
正在处理 12 ----- 74
正在处理 12 ----- 75
正在处理 12 ----- 76
正在处理 12 ----- 77
正在处理 12 ----- 78
正在处理 12 ----- 79
正在处理 12 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 12
============================

正在读取第 13 个DF
初始化batch数据： 13
batch数据 组装完毕 ：13
batch_tensor数据 组装完毕 ：13,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 13 ----- 1
正在处理 13 ----- 2
正在处理 13 ----- 3
正在处理 13 ----- 4
正在处理 13 ----- 5
正在处理 13 ----- 6
正在处理 13 ----- 7
正在处理 13 ----- 8
正在处理 13 ----- 9
正在处理 13 ----- 10
正在处理 13 ----- 11
正在处理 13 ----- 12
正在处理 13 ----- 13
正在处理 13 ----- 14
正在处理 13 ----- 15
正在处理 13 ----- 16
正在处理 13 ----- 17
正在处理 13 ----- 18
正在处理 13 ----- 19
正在处理 13 ----- 20
正在处理 13 ----- 21
正在处理 13 ----- 22
正在处理 13 ----- 23
正在处理 13 ----- 24
正在处理 13 ----- 25
正在处理 13 ----- 26
正在处理 13 ----- 27
正在处理 13 ----- 28
正在处理 13 ----- 29
正在处理 13 ----- 30
正在处理 13 ----- 31
正在处理 13 ----- 32
正在处理 13 ----- 33
正在处理 13 ----- 34
正在处理 13 ----- 35
正在处理 13 ----- 36
正在处理 13 ----- 37
正在处理 13 ----- 38
正在处理 13 ----- 39
正在处理 13 ----- 40
正在处理 13 ----- 41
正在处理 13 ----- 42
正在处理 13 ----- 43
正在处理 13 ----- 44
正在处理 13 ----- 45
正在处理 13 ----- 46
正在处理 13 ----- 47
正在处理 13 ----- 48
正在处理 13 ----- 49
正在处理 13 ----- 50
正在处理 13 ----- 51
正在处理 13 ----- 52
正在处理 13 ----- 53
正在处理 13 ----- 54
正在处理 13 ----- 55
正在处理 13 ----- 56
正在处理 13 ----- 57
正在处理 13 ----- 58
正在处理 13 ----- 59
正在处理 13 ----- 60
正在处理 13 ----- 61
正在处理 13 ----- 62
正在处理 13 ----- 63
正在处理 13 ----- 64
正在处理 13 ----- 65
正在处理 13 ----- 66
正在处理 13 ----- 67
正在处理 13 ----- 68
正在处理 13 ----- 69
正在处理 13 ----- 70
正在处理 13 ----- 71
正在处理 13 ----- 72
正在处理 13 ----- 73
正在处理 13 ----- 74
正在处理 13 ----- 75
正在处理 13 ----- 76
正在处理 13 ----- 77
正在处理 13 ----- 78
正在处理 13 ----- 79
正在处理 13 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 13
============================

正在读取第 14 个DF
初始化batch数据： 14
batch数据 组装完毕 ：14
batch_tensor数据 组装完毕 ：14,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 14 ----- 1
正在处理 14 ----- 2
正在处理 14 ----- 3
正在处理 14 ----- 4
正在处理 14 ----- 5
正在处理 14 ----- 6
正在处理 14 ----- 7
正在处理 14 ----- 8
正在处理 14 ----- 9
正在处理 14 ----- 10
正在处理 14 ----- 11
正在处理 14 ----- 12
正在处理 14 ----- 13
正在处理 14 ----- 14
正在处理 14 ----- 15
正在处理 14 ----- 16
正在处理 14 ----- 17
正在处理 14 ----- 18
正在处理 14 ----- 19
正在处理 14 ----- 20
正在处理 14 ----- 21
正在处理 14 ----- 22
正在处理 14 ----- 23
正在处理 14 ----- 24
正在处理 14 ----- 25
正在处理 14 ----- 26
正在处理 14 ----- 27
正在处理 14 ----- 28
正在处理 14 ----- 29
正在处理 14 ----- 30
正在处理 14 ----- 31
正在处理 14 ----- 32
正在处理 14 ----- 33
正在处理 14 ----- 34
正在处理 14 ----- 35
正在处理 14 ----- 36
正在处理 14 ----- 37
正在处理 14 ----- 38
正在处理 14 ----- 39
正在处理 14 ----- 40
正在处理 14 ----- 41
正在处理 14 ----- 42
正在处理 14 ----- 43
正在处理 14 ----- 44
正在处理 14 ----- 45
正在处理 14 ----- 46
正在处理 14 ----- 47
正在处理 14 ----- 48
正在处理 14 ----- 49
正在处理 14 ----- 50
正在处理 14 ----- 51
正在处理 14 ----- 52
正在处理 14 ----- 53
正在处理 14 ----- 54
正在处理 14 ----- 55
正在处理 14 ----- 56
正在处理 14 ----- 57
正在处理 14 ----- 58
正在处理 14 ----- 59
正在处理 14 ----- 60
正在处理 14 ----- 61
正在处理 14 ----- 62
正在处理 14 ----- 63
正在处理 14 ----- 64
正在处理 14 ----- 65
正在处理 14 ----- 66
正在处理 14 ----- 67
正在处理 14 ----- 68
正在处理 14 ----- 69
正在处理 14 ----- 70
正在处理 14 ----- 71
正在处理 14 ----- 72
正在处理 14 ----- 73
正在处理 14 ----- 74
正在处理 14 ----- 75
正在处理 14 ----- 76
正在处理 14 ----- 77
正在处理 14 ----- 78
正在处理 14 ----- 79
正在处理 14 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 14
============================

正在读取第 15 个DF
初始化batch数据： 15
batch数据 组装完毕 ：15
batch_tensor数据 组装完毕 ：15,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 15 ----- 1
正在处理 15 ----- 2
正在处理 15 ----- 3
正在处理 15 ----- 4
正在处理 15 ----- 5
正在处理 15 ----- 6
正在处理 15 ----- 7
正在处理 15 ----- 8
正在处理 15 ----- 9
正在处理 15 ----- 10
正在处理 15 ----- 11
正在处理 15 ----- 12
正在处理 15 ----- 13
正在处理 15 ----- 14
正在处理 15 ----- 15
正在处理 15 ----- 16
正在处理 15 ----- 17
正在处理 15 ----- 18
正在处理 15 ----- 19
正在处理 15 ----- 20
正在处理 15 ----- 21
正在处理 15 ----- 22
正在处理 15 ----- 23
正在处理 15 ----- 24
正在处理 15 ----- 25
正在处理 15 ----- 26
正在处理 15 ----- 27
正在处理 15 ----- 28
正在处理 15 ----- 29
正在处理 15 ----- 30
正在处理 15 ----- 31
正在处理 15 ----- 32
正在处理 15 ----- 33
正在处理 15 ----- 34
正在处理 15 ----- 35
正在处理 15 ----- 36
正在处理 15 ----- 37
正在处理 15 ----- 38
正在处理 15 ----- 39
正在处理 15 ----- 40
正在处理 15 ----- 41
正在处理 15 ----- 42
正在处理 15 ----- 43
正在处理 15 ----- 44
正在处理 15 ----- 45
正在处理 15 ----- 46
正在处理 15 ----- 47
正在处理 15 ----- 48
正在处理 15 ----- 49
正在处理 15 ----- 50
正在处理 15 ----- 51
正在处理 15 ----- 52
正在处理 15 ----- 53
正在处理 15 ----- 54
正在处理 15 ----- 55
正在处理 15 ----- 56
正在处理 15 ----- 57
正在处理 15 ----- 58
正在处理 15 ----- 59
正在处理 15 ----- 60
正在处理 15 ----- 61
正在处理 15 ----- 62
正在处理 15 ----- 63
正在处理 15 ----- 64
正在处理 15 ----- 65
正在处理 15 ----- 66
正在处理 15 ----- 67
正在处理 15 ----- 68
正在处理 15 ----- 69
正在处理 15 ----- 70
正在处理 15 ----- 71
正在处理 15 ----- 72
正在处理 15 ----- 73
正在处理 15 ----- 74
正在处理 15 ----- 75
正在处理 15 ----- 76
正在处理 15 ----- 77
正在处理 15 ----- 78
正在处理 15 ----- 79
正在处理 15 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 15
============================

正在读取第 16 个DF
初始化batch数据： 16
batch数据 组装完毕 ：16
batch_tensor数据 组装完毕 ：16,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 16 ----- 1
正在处理 16 ----- 2
正在处理 16 ----- 3
正在处理 16 ----- 4
正在处理 16 ----- 5
正在处理 16 ----- 6
正在处理 16 ----- 7
正在处理 16 ----- 8
正在处理 16 ----- 9
正在处理 16 ----- 10
正在处理 16 ----- 11
正在处理 16 ----- 12
正在处理 16 ----- 13
正在处理 16 ----- 14
正在处理 16 ----- 15
正在处理 16 ----- 16
正在处理 16 ----- 17
正在处理 16 ----- 18
正在处理 16 ----- 19
正在处理 16 ----- 20
正在处理 16 ----- 21
正在处理 16 ----- 22
正在处理 16 ----- 23
正在处理 16 ----- 24
正在处理 16 ----- 25
正在处理 16 ----- 26
正在处理 16 ----- 27
正在处理 16 ----- 28
正在处理 16 ----- 29
正在处理 16 ----- 30
正在处理 16 ----- 31
正在处理 16 ----- 32
正在处理 16 ----- 33
正在处理 16 ----- 34
正在处理 16 ----- 35
正在处理 16 ----- 36
正在处理 16 ----- 37
正在处理 16 ----- 38
正在处理 16 ----- 39
正在处理 16 ----- 40
正在处理 16 ----- 41
正在处理 16 ----- 42
正在处理 16 ----- 43
正在处理 16 ----- 44
正在处理 16 ----- 45
正在处理 16 ----- 46
正在处理 16 ----- 47
正在处理 16 ----- 48
正在处理 16 ----- 49
正在处理 16 ----- 50
正在处理 16 ----- 51
正在处理 16 ----- 52
正在处理 16 ----- 53
正在处理 16 ----- 54
正在处理 16 ----- 55
正在处理 16 ----- 56
正在处理 16 ----- 57
正在处理 16 ----- 58
正在处理 16 ----- 59
正在处理 16 ----- 60
正在处理 16 ----- 61
正在处理 16 ----- 62
正在处理 16 ----- 63
正在处理 16 ----- 64
正在处理 16 ----- 65
正在处理 16 ----- 66
正在处理 16 ----- 67
正在处理 16 ----- 68
正在处理 16 ----- 69
正在处理 16 ----- 70
正在处理 16 ----- 71
正在处理 16 ----- 72
正在处理 16 ----- 73
正在处理 16 ----- 74
正在处理 16 ----- 75
正在处理 16 ----- 76
正在处理 16 ----- 77
正在处理 16 ----- 78
正在处理 16 ----- 79
正在处理 16 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 16
============================

正在读取第 17 个DF
初始化batch数据： 17
batch数据 组装完毕 ：17
batch_tensor数据 组装完毕 ：17,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 17 ----- 1
正在处理 17 ----- 2
正在处理 17 ----- 3
正在处理 17 ----- 4
正在处理 17 ----- 5
正在处理 17 ----- 6
正在处理 17 ----- 7
正在处理 17 ----- 8
正在处理 17 ----- 9
正在处理 17 ----- 10
正在处理 17 ----- 11
正在处理 17 ----- 12
正在处理 17 ----- 13
正在处理 17 ----- 14
正在处理 17 ----- 15
正在处理 17 ----- 16
正在处理 17 ----- 17
正在处理 17 ----- 18
正在处理 17 ----- 19
正在处理 17 ----- 20
正在处理 17 ----- 21
正在处理 17 ----- 22
正在处理 17 ----- 23
正在处理 17 ----- 24
正在处理 17 ----- 25
正在处理 17 ----- 26
正在处理 17 ----- 27
正在处理 17 ----- 28
正在处理 17 ----- 29
正在处理 17 ----- 30
正在处理 17 ----- 31
正在处理 17 ----- 32
正在处理 17 ----- 33
正在处理 17 ----- 34
正在处理 17 ----- 35
正在处理 17 ----- 36
正在处理 17 ----- 37
正在处理 17 ----- 38
正在处理 17 ----- 39
正在处理 17 ----- 40
正在处理 17 ----- 41
正在处理 17 ----- 42
正在处理 17 ----- 43
正在处理 17 ----- 44
正在处理 17 ----- 45
正在处理 17 ----- 46
正在处理 17 ----- 47
正在处理 17 ----- 48
正在处理 17 ----- 49
正在处理 17 ----- 50
正在处理 17 ----- 51
正在处理 17 ----- 52
正在处理 17 ----- 53
正在处理 17 ----- 54
正在处理 17 ----- 55
正在处理 17 ----- 56
正在处理 17 ----- 57
正在处理 17 ----- 58
正在处理 17 ----- 59
正在处理 17 ----- 60
正在处理 17 ----- 61
正在处理 17 ----- 62
正在处理 17 ----- 63
正在处理 17 ----- 64
正在处理 17 ----- 65
正在处理 17 ----- 66
正在处理 17 ----- 67
正在处理 17 ----- 68
正在处理 17 ----- 69
正在处理 17 ----- 70
正在处理 17 ----- 71
正在处理 17 ----- 72
正在处理 17 ----- 73
正在处理 17 ----- 74
正在处理 17 ----- 75
正在处理 17 ----- 76
正在处理 17 ----- 77
正在处理 17 ----- 78
正在处理 17 ----- 79
正在处理 17 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 17
============================

正在读取第 18 个DF
初始化batch数据： 18
batch数据 组装完毕 ：18
batch_tensor数据 组装完毕 ：18,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 18 ----- 1
正在处理 18 ----- 2
正在处理 18 ----- 3
正在处理 18 ----- 4
正在处理 18 ----- 5
正在处理 18 ----- 6
正在处理 18 ----- 7
正在处理 18 ----- 8
正在处理 18 ----- 9
正在处理 18 ----- 10
正在处理 18 ----- 11
正在处理 18 ----- 12
正在处理 18 ----- 13
正在处理 18 ----- 14
正在处理 18 ----- 15
正在处理 18 ----- 16
正在处理 18 ----- 17
正在处理 18 ----- 18
正在处理 18 ----- 19
正在处理 18 ----- 20
正在处理 18 ----- 21
正在处理 18 ----- 22
正在处理 18 ----- 23
正在处理 18 ----- 24
正在处理 18 ----- 25
正在处理 18 ----- 26
正在处理 18 ----- 27
正在处理 18 ----- 28
正在处理 18 ----- 29
正在处理 18 ----- 30
正在处理 18 ----- 31
正在处理 18 ----- 32
正在处理 18 ----- 33
正在处理 18 ----- 34
正在处理 18 ----- 35
正在处理 18 ----- 36
正在处理 18 ----- 37
正在处理 18 ----- 38
正在处理 18 ----- 39
正在处理 18 ----- 40
正在处理 18 ----- 41
正在处理 18 ----- 42
正在处理 18 ----- 43
正在处理 18 ----- 44
正在处理 18 ----- 45
正在处理 18 ----- 46
正在处理 18 ----- 47
正在处理 18 ----- 48
正在处理 18 ----- 49
正在处理 18 ----- 50
正在处理 18 ----- 51
正在处理 18 ----- 52
正在处理 18 ----- 53
正在处理 18 ----- 54
正在处理 18 ----- 55
正在处理 18 ----- 56
正在处理 18 ----- 57
正在处理 18 ----- 58
正在处理 18 ----- 59
正在处理 18 ----- 60
正在处理 18 ----- 61
正在处理 18 ----- 62
正在处理 18 ----- 63
正在处理 18 ----- 64
正在处理 18 ----- 65
正在处理 18 ----- 66
正在处理 18 ----- 67
正在处理 18 ----- 68
正在处理 18 ----- 69
正在处理 18 ----- 70
正在处理 18 ----- 71
正在处理 18 ----- 72
正在处理 18 ----- 73
正在处理 18 ----- 74
正在处理 18 ----- 75
正在处理 18 ----- 76
正在处理 18 ----- 77
正在处理 18 ----- 78
正在处理 18 ----- 79
正在处理 18 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 18
============================

正在读取第 19 个DF
初始化batch数据： 19
batch数据 组装完毕 ：19
batch_tensor数据 组装完毕 ：19,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 19 ----- 1
正在处理 19 ----- 2
正在处理 19 ----- 3
正在处理 19 ----- 4
正在处理 19 ----- 5
正在处理 19 ----- 6
正在处理 19 ----- 7
正在处理 19 ----- 8
正在处理 19 ----- 9
正在处理 19 ----- 10
正在处理 19 ----- 11
正在处理 19 ----- 12
正在处理 19 ----- 13
正在处理 19 ----- 14
正在处理 19 ----- 15
正在处理 19 ----- 16
正在处理 19 ----- 17
正在处理 19 ----- 18
正在处理 19 ----- 19
正在处理 19 ----- 20
正在处理 19 ----- 21
正在处理 19 ----- 22
正在处理 19 ----- 23
正在处理 19 ----- 24
正在处理 19 ----- 25
正在处理 19 ----- 26
正在处理 19 ----- 27
正在处理 19 ----- 28
正在处理 19 ----- 29
正在处理 19 ----- 30
正在处理 19 ----- 31
正在处理 19 ----- 32
正在处理 19 ----- 33
正在处理 19 ----- 34
正在处理 19 ----- 35
正在处理 19 ----- 36
正在处理 19 ----- 37
正在处理 19 ----- 38
正在处理 19 ----- 39
正在处理 19 ----- 40
正在处理 19 ----- 41
正在处理 19 ----- 42
正在处理 19 ----- 43
正在处理 19 ----- 44
正在处理 19 ----- 45
正在处理 19 ----- 46
正在处理 19 ----- 47
正在处理 19 ----- 48
正在处理 19 ----- 49
正在处理 19 ----- 50
正在处理 19 ----- 51
正在处理 19 ----- 52
正在处理 19 ----- 53
正在处理 19 ----- 54
正在处理 19 ----- 55
正在处理 19 ----- 56
正在处理 19 ----- 57
正在处理 19 ----- 58
正在处理 19 ----- 59
正在处理 19 ----- 60
正在处理 19 ----- 61
正在处理 19 ----- 62
正在处理 19 ----- 63
正在处理 19 ----- 64
正在处理 19 ----- 65
正在处理 19 ----- 66
正在处理 19 ----- 67
正在处理 19 ----- 68
正在处理 19 ----- 69
正在处理 19 ----- 70
正在处理 19 ----- 71
正在处理 19 ----- 72
正在处理 19 ----- 73
正在处理 19 ----- 74
正在处理 19 ----- 75
正在处理 19 ----- 76
正在处理 19 ----- 77
正在处理 19 ----- 78
正在处理 19 ----- 79
正在处理 19 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 19
============================

正在读取第 20 个DF
初始化batch数据： 20
batch数据 组装完毕 ：20
batch_tensor数据 组装完毕 ：20,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 20 ----- 1
正在处理 20 ----- 2
正在处理 20 ----- 3
正在处理 20 ----- 4
正在处理 20 ----- 5
正在处理 20 ----- 6
正在处理 20 ----- 7
正在处理 20 ----- 8
正在处理 20 ----- 9
正在处理 20 ----- 10
正在处理 20 ----- 11
正在处理 20 ----- 12
正在处理 20 ----- 13
正在处理 20 ----- 14
正在处理 20 ----- 15
正在处理 20 ----- 16
正在处理 20 ----- 17
正在处理 20 ----- 18
正在处理 20 ----- 19
正在处理 20 ----- 20
正在处理 20 ----- 21
正在处理 20 ----- 22
正在处理 20 ----- 23
正在处理 20 ----- 24
正在处理 20 ----- 25
正在处理 20 ----- 26
正在处理 20 ----- 27
正在处理 20 ----- 28
正在处理 20 ----- 29
正在处理 20 ----- 30
正在处理 20 ----- 31
正在处理 20 ----- 32
正在处理 20 ----- 33
正在处理 20 ----- 34
正在处理 20 ----- 35
正在处理 20 ----- 36
正在处理 20 ----- 37
正在处理 20 ----- 38
正在处理 20 ----- 39
正在处理 20 ----- 40
正在处理 20 ----- 41
正在处理 20 ----- 42
正在处理 20 ----- 43
正在处理 20 ----- 44
正在处理 20 ----- 45
正在处理 20 ----- 46
正在处理 20 ----- 47
正在处理 20 ----- 48
正在处理 20 ----- 49
正在处理 20 ----- 50
正在处理 20 ----- 51
正在处理 20 ----- 52
正在处理 20 ----- 53
正在处理 20 ----- 54
正在处理 20 ----- 55
正在处理 20 ----- 56
正在处理 20 ----- 57
正在处理 20 ----- 58
正在处理 20 ----- 59
正在处理 20 ----- 60
正在处理 20 ----- 61
正在处理 20 ----- 62
正在处理 20 ----- 63
正在处理 20 ----- 64
正在处理 20 ----- 65
正在处理 20 ----- 66
正在处理 20 ----- 67
正在处理 20 ----- 68
正在处理 20 ----- 69
正在处理 20 ----- 70
正在处理 20 ----- 71
正在处理 20 ----- 72
正在处理 20 ----- 73
正在处理 20 ----- 74
正在处理 20 ----- 75
正在处理 20 ----- 76
正在处理 20 ----- 77
正在处理 20 ----- 78
正在处理 20 ----- 79
正在处理 20 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 20
============================

正在读取第 21 个DF
初始化batch数据： 21
batch数据 组装完毕 ：21
batch_tensor数据 组装完毕 ：21,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 21 ----- 1
正在处理 21 ----- 2
正在处理 21 ----- 3
正在处理 21 ----- 4
正在处理 21 ----- 5
正在处理 21 ----- 6
正在处理 21 ----- 7
正在处理 21 ----- 8
正在处理 21 ----- 9
正在处理 21 ----- 10
正在处理 21 ----- 11
正在处理 21 ----- 12
正在处理 21 ----- 13
正在处理 21 ----- 14
正在处理 21 ----- 15
正在处理 21 ----- 16
正在处理 21 ----- 17
正在处理 21 ----- 18
正在处理 21 ----- 19
正在处理 21 ----- 20
正在处理 21 ----- 21
正在处理 21 ----- 22
正在处理 21 ----- 23
正在处理 21 ----- 24
正在处理 21 ----- 25
正在处理 21 ----- 26
正在处理 21 ----- 27
正在处理 21 ----- 28
正在处理 21 ----- 29
正在处理 21 ----- 30
正在处理 21 ----- 31
正在处理 21 ----- 32
正在处理 21 ----- 33
正在处理 21 ----- 34
正在处理 21 ----- 35
正在处理 21 ----- 36
正在处理 21 ----- 37
正在处理 21 ----- 38
正在处理 21 ----- 39
正在处理 21 ----- 40
正在处理 21 ----- 41
正在处理 21 ----- 42
正在处理 21 ----- 43
正在处理 21 ----- 44
正在处理 21 ----- 45
正在处理 21 ----- 46
正在处理 21 ----- 47
正在处理 21 ----- 48
正在处理 21 ----- 49
正在处理 21 ----- 50
正在处理 21 ----- 51
正在处理 21 ----- 52
正在处理 21 ----- 53
正在处理 21 ----- 54
正在处理 21 ----- 55
正在处理 21 ----- 56
正在处理 21 ----- 57
正在处理 21 ----- 58
正在处理 21 ----- 59
正在处理 21 ----- 60
正在处理 21 ----- 61
正在处理 21 ----- 62
正在处理 21 ----- 63
正在处理 21 ----- 64
正在处理 21 ----- 65
正在处理 21 ----- 66
正在处理 21 ----- 67
正在处理 21 ----- 68
正在处理 21 ----- 69
正在处理 21 ----- 70
正在处理 21 ----- 71
正在处理 21 ----- 72
正在处理 21 ----- 73
正在处理 21 ----- 74
正在处理 21 ----- 75
正在处理 21 ----- 76
正在处理 21 ----- 77
正在处理 21 ----- 78
正在处理 21 ----- 79
正在处理 21 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 21
============================

正在读取第 22 个DF
初始化batch数据： 22
batch数据 组装完毕 ：22
batch_tensor数据 组装完毕 ：22,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 22 ----- 1
正在处理 22 ----- 2
正在处理 22 ----- 3
正在处理 22 ----- 4
正在处理 22 ----- 5
正在处理 22 ----- 6
正在处理 22 ----- 7
正在处理 22 ----- 8
正在处理 22 ----- 9
正在处理 22 ----- 10
正在处理 22 ----- 11
正在处理 22 ----- 12
正在处理 22 ----- 13
正在处理 22 ----- 14
正在处理 22 ----- 15
正在处理 22 ----- 16
正在处理 22 ----- 17
正在处理 22 ----- 18
正在处理 22 ----- 19
正在处理 22 ----- 20
正在处理 22 ----- 21
正在处理 22 ----- 22
正在处理 22 ----- 23
正在处理 22 ----- 24
正在处理 22 ----- 25
正在处理 22 ----- 26
正在处理 22 ----- 27
正在处理 22 ----- 28
正在处理 22 ----- 29
正在处理 22 ----- 30
正在处理 22 ----- 31
正在处理 22 ----- 32
正在处理 22 ----- 33
正在处理 22 ----- 34
正在处理 22 ----- 35
正在处理 22 ----- 36
正在处理 22 ----- 37
正在处理 22 ----- 38
正在处理 22 ----- 39
正在处理 22 ----- 40
正在处理 22 ----- 41
正在处理 22 ----- 42
正在处理 22 ----- 43
正在处理 22 ----- 44
正在处理 22 ----- 45
正在处理 22 ----- 46
正在处理 22 ----- 47
正在处理 22 ----- 48
正在处理 22 ----- 49
正在处理 22 ----- 50
正在处理 22 ----- 51
正在处理 22 ----- 52
正在处理 22 ----- 53
正在处理 22 ----- 54
正在处理 22 ----- 55
正在处理 22 ----- 56
正在处理 22 ----- 57
正在处理 22 ----- 58
正在处理 22 ----- 59
正在处理 22 ----- 60
正在处理 22 ----- 61
正在处理 22 ----- 62
正在处理 22 ----- 63
正在处理 22 ----- 64
正在处理 22 ----- 65
正在处理 22 ----- 66
正在处理 22 ----- 67
正在处理 22 ----- 68
正在处理 22 ----- 69
正在处理 22 ----- 70
正在处理 22 ----- 71
正在处理 22 ----- 72
正在处理 22 ----- 73
正在处理 22 ----- 74
正在处理 22 ----- 75
正在处理 22 ----- 76
正在处理 22 ----- 77
正在处理 22 ----- 78
正在处理 22 ----- 79
正在处理 22 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 22
============================

正在读取第 23 个DF
初始化batch数据： 23
batch数据 组装完毕 ：23
batch_tensor数据 组装完毕 ：23,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 23 ----- 1
正在处理 23 ----- 2
正在处理 23 ----- 3
正在处理 23 ----- 4
正在处理 23 ----- 5
正在处理 23 ----- 6
正在处理 23 ----- 7
正在处理 23 ----- 8
正在处理 23 ----- 9
正在处理 23 ----- 10
正在处理 23 ----- 11
正在处理 23 ----- 12
正在处理 23 ----- 13
正在处理 23 ----- 14
正在处理 23 ----- 15
正在处理 23 ----- 16
正在处理 23 ----- 17
正在处理 23 ----- 18
正在处理 23 ----- 19
正在处理 23 ----- 20
正在处理 23 ----- 21
正在处理 23 ----- 22
正在处理 23 ----- 23
正在处理 23 ----- 24
正在处理 23 ----- 25
正在处理 23 ----- 26
正在处理 23 ----- 27
正在处理 23 ----- 28
正在处理 23 ----- 29
正在处理 23 ----- 30
正在处理 23 ----- 31
正在处理 23 ----- 32
正在处理 23 ----- 33
正在处理 23 ----- 34
正在处理 23 ----- 35
正在处理 23 ----- 36
正在处理 23 ----- 37
正在处理 23 ----- 38
正在处理 23 ----- 39
正在处理 23 ----- 40
正在处理 23 ----- 41
正在处理 23 ----- 42
正在处理 23 ----- 43
正在处理 23 ----- 44
正在处理 23 ----- 45
正在处理 23 ----- 46
正在处理 23 ----- 47
正在处理 23 ----- 48
正在处理 23 ----- 49
正在处理 23 ----- 50
正在处理 23 ----- 51
正在处理 23 ----- 52
正在处理 23 ----- 53
正在处理 23 ----- 54
正在处理 23 ----- 55
正在处理 23 ----- 56
正在处理 23 ----- 57
正在处理 23 ----- 58
正在处理 23 ----- 59
正在处理 23 ----- 60
正在处理 23 ----- 61
正在处理 23 ----- 62
正在处理 23 ----- 63
正在处理 23 ----- 64
正在处理 23 ----- 65
正在处理 23 ----- 66
正在处理 23 ----- 67
正在处理 23 ----- 68
正在处理 23 ----- 69
正在处理 23 ----- 70
正在处理 23 ----- 71
正在处理 23 ----- 72
正在处理 23 ----- 73
正在处理 23 ----- 74
正在处理 23 ----- 75
正在处理 23 ----- 76
正在处理 23 ----- 77
正在处理 23 ----- 78
正在处理 23 ----- 79
正在处理 23 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 23
============================

正在读取第 24 个DF
初始化batch数据： 24
batch数据 组装完毕 ：24
batch_tensor数据 组装完毕 ：24,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 24 ----- 1
正在处理 24 ----- 2
正在处理 24 ----- 3
正在处理 24 ----- 4
正在处理 24 ----- 5
正在处理 24 ----- 6
正在处理 24 ----- 7
正在处理 24 ----- 8
正在处理 24 ----- 9
正在处理 24 ----- 10
正在处理 24 ----- 11
正在处理 24 ----- 12
正在处理 24 ----- 13
正在处理 24 ----- 14
正在处理 24 ----- 15
正在处理 24 ----- 16
正在处理 24 ----- 17
正在处理 24 ----- 18
正在处理 24 ----- 19
正在处理 24 ----- 20
正在处理 24 ----- 21
正在处理 24 ----- 22
正在处理 24 ----- 23
正在处理 24 ----- 24
正在处理 24 ----- 25
正在处理 24 ----- 26
正在处理 24 ----- 27
正在处理 24 ----- 28
正在处理 24 ----- 29
正在处理 24 ----- 30
正在处理 24 ----- 31
正在处理 24 ----- 32
正在处理 24 ----- 33
正在处理 24 ----- 34
正在处理 24 ----- 35
正在处理 24 ----- 36
正在处理 24 ----- 37
正在处理 24 ----- 38
正在处理 24 ----- 39
正在处理 24 ----- 40
正在处理 24 ----- 41
正在处理 24 ----- 42
正在处理 24 ----- 43
正在处理 24 ----- 44
正在处理 24 ----- 45
正在处理 24 ----- 46
正在处理 24 ----- 47
正在处理 24 ----- 48
正在处理 24 ----- 49
正在处理 24 ----- 50
正在处理 24 ----- 51
正在处理 24 ----- 52
正在处理 24 ----- 53
正在处理 24 ----- 54
正在处理 24 ----- 55
正在处理 24 ----- 56
正在处理 24 ----- 57
正在处理 24 ----- 58
正在处理 24 ----- 59
正在处理 24 ----- 60
正在处理 24 ----- 61
正在处理 24 ----- 62
正在处理 24 ----- 63
正在处理 24 ----- 64
正在处理 24 ----- 65
正在处理 24 ----- 66
正在处理 24 ----- 67
正在处理 24 ----- 68
正在处理 24 ----- 69
正在处理 24 ----- 70
正在处理 24 ----- 71
正在处理 24 ----- 72
正在处理 24 ----- 73
正在处理 24 ----- 74
正在处理 24 ----- 75
正在处理 24 ----- 76
正在处理 24 ----- 77
正在处理 24 ----- 78
正在处理 24 ----- 79
正在处理 24 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 24
============================

正在读取第 25 个DF
初始化batch数据： 25
batch数据 组装完毕 ：25
batch_tensor数据 组装完毕 ：25,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 25 ----- 1
正在处理 25 ----- 2
正在处理 25 ----- 3
正在处理 25 ----- 4
正在处理 25 ----- 5
正在处理 25 ----- 6
正在处理 25 ----- 7
正在处理 25 ----- 8
正在处理 25 ----- 9
正在处理 25 ----- 10
正在处理 25 ----- 11
正在处理 25 ----- 12
正在处理 25 ----- 13
正在处理 25 ----- 14
正在处理 25 ----- 15
正在处理 25 ----- 16
正在处理 25 ----- 17
正在处理 25 ----- 18
正在处理 25 ----- 19
正在处理 25 ----- 20
正在处理 25 ----- 21
正在处理 25 ----- 22
正在处理 25 ----- 23
正在处理 25 ----- 24
正在处理 25 ----- 25
正在处理 25 ----- 26
正在处理 25 ----- 27
正在处理 25 ----- 28
正在处理 25 ----- 29
正在处理 25 ----- 30
正在处理 25 ----- 31
正在处理 25 ----- 32
正在处理 25 ----- 33
正在处理 25 ----- 34
正在处理 25 ----- 35
正在处理 25 ----- 36
正在处理 25 ----- 37
正在处理 25 ----- 38
正在处理 25 ----- 39
正在处理 25 ----- 40
正在处理 25 ----- 41
正在处理 25 ----- 42
正在处理 25 ----- 43
正在处理 25 ----- 44
正在处理 25 ----- 45
正在处理 25 ----- 46
正在处理 25 ----- 47
正在处理 25 ----- 48
正在处理 25 ----- 49
正在处理 25 ----- 50
正在处理 25 ----- 51
正在处理 25 ----- 52
正在处理 25 ----- 53
正在处理 25 ----- 54
正在处理 25 ----- 55
正在处理 25 ----- 56
正在处理 25 ----- 57
正在处理 25 ----- 58
正在处理 25 ----- 59
正在处理 25 ----- 60
正在处理 25 ----- 61
正在处理 25 ----- 62
正在处理 25 ----- 63
正在处理 25 ----- 64
正在处理 25 ----- 65
正在处理 25 ----- 66
正在处理 25 ----- 67
正在处理 25 ----- 68
正在处理 25 ----- 69
正在处理 25 ----- 70
正在处理 25 ----- 71
正在处理 25 ----- 72
正在处理 25 ----- 73
正在处理 25 ----- 74
正在处理 25 ----- 75
正在处理 25 ----- 76
正在处理 25 ----- 77
正在处理 25 ----- 78
正在处理 25 ----- 79
正在处理 25 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 25
============================

正在读取第 26 个DF
初始化batch数据： 26
batch数据 组装完毕 ：26
batch_tensor数据 组装完毕 ：26,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 26 ----- 1
正在处理 26 ----- 2
正在处理 26 ----- 3
正在处理 26 ----- 4
正在处理 26 ----- 5
正在处理 26 ----- 6
正在处理 26 ----- 7
正在处理 26 ----- 8
正在处理 26 ----- 9
正在处理 26 ----- 10
正在处理 26 ----- 11
正在处理 26 ----- 12
正在处理 26 ----- 13
正在处理 26 ----- 14
正在处理 26 ----- 15
正在处理 26 ----- 16
正在处理 26 ----- 17
正在处理 26 ----- 18
正在处理 26 ----- 19
正在处理 26 ----- 20
正在处理 26 ----- 21
正在处理 26 ----- 22
正在处理 26 ----- 23
正在处理 26 ----- 24
正在处理 26 ----- 25
正在处理 26 ----- 26
正在处理 26 ----- 27
正在处理 26 ----- 28
正在处理 26 ----- 29
正在处理 26 ----- 30
正在处理 26 ----- 31
正在处理 26 ----- 32
正在处理 26 ----- 33
正在处理 26 ----- 34
正在处理 26 ----- 35
正在处理 26 ----- 36
正在处理 26 ----- 37
正在处理 26 ----- 38
正在处理 26 ----- 39
正在处理 26 ----- 40
正在处理 26 ----- 41
正在处理 26 ----- 42
正在处理 26 ----- 43
正在处理 26 ----- 44
正在处理 26 ----- 45
正在处理 26 ----- 46
正在处理 26 ----- 47
正在处理 26 ----- 48
正在处理 26 ----- 49
正在处理 26 ----- 50
正在处理 26 ----- 51
正在处理 26 ----- 52
正在处理 26 ----- 53
正在处理 26 ----- 54
正在处理 26 ----- 55
正在处理 26 ----- 56
正在处理 26 ----- 57
正在处理 26 ----- 58
正在处理 26 ----- 59
正在处理 26 ----- 60
正在处理 26 ----- 61
正在处理 26 ----- 62
正在处理 26 ----- 63
正在处理 26 ----- 64
正在处理 26 ----- 65
正在处理 26 ----- 66
正在处理 26 ----- 67
正在处理 26 ----- 68
正在处理 26 ----- 69
正在处理 26 ----- 70
正在处理 26 ----- 71
正在处理 26 ----- 72
正在处理 26 ----- 73
正在处理 26 ----- 74
正在处理 26 ----- 75
正在处理 26 ----- 76
正在处理 26 ----- 77
正在处理 26 ----- 78
正在处理 26 ----- 79
正在处理 26 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 26
============================

正在读取第 27 个DF
初始化batch数据： 27
batch数据 组装完毕 ：27
batch_tensor数据 组装完毕 ：27,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 27 ----- 1
正在处理 27 ----- 2
正在处理 27 ----- 3
正在处理 27 ----- 4
正在处理 27 ----- 5
正在处理 27 ----- 6
正在处理 27 ----- 7
正在处理 27 ----- 8
正在处理 27 ----- 9
正在处理 27 ----- 10
正在处理 27 ----- 11
正在处理 27 ----- 12
正在处理 27 ----- 13
正在处理 27 ----- 14
正在处理 27 ----- 15
正在处理 27 ----- 16
正在处理 27 ----- 17
正在处理 27 ----- 18
正在处理 27 ----- 19
正在处理 27 ----- 20
正在处理 27 ----- 21
正在处理 27 ----- 22
正在处理 27 ----- 23
正在处理 27 ----- 24
正在处理 27 ----- 25
正在处理 27 ----- 26
正在处理 27 ----- 27
正在处理 27 ----- 28
正在处理 27 ----- 29
正在处理 27 ----- 30
正在处理 27 ----- 31
正在处理 27 ----- 32
正在处理 27 ----- 33
正在处理 27 ----- 34
正在处理 27 ----- 35
正在处理 27 ----- 36
正在处理 27 ----- 37
正在处理 27 ----- 38
正在处理 27 ----- 39
正在处理 27 ----- 40
正在处理 27 ----- 41
正在处理 27 ----- 42
正在处理 27 ----- 43
正在处理 27 ----- 44
正在处理 27 ----- 45
正在处理 27 ----- 46
正在处理 27 ----- 47
正在处理 27 ----- 48
正在处理 27 ----- 49
正在处理 27 ----- 50
正在处理 27 ----- 51
正在处理 27 ----- 52
正在处理 27 ----- 53
正在处理 27 ----- 54
正在处理 27 ----- 55
正在处理 27 ----- 56
正在处理 27 ----- 57
正在处理 27 ----- 58
正在处理 27 ----- 59
正在处理 27 ----- 60
正在处理 27 ----- 61
正在处理 27 ----- 62
正在处理 27 ----- 63
正在处理 27 ----- 64
正在处理 27 ----- 65
正在处理 27 ----- 66
正在处理 27 ----- 67
正在处理 27 ----- 68
正在处理 27 ----- 69
正在处理 27 ----- 70
正在处理 27 ----- 71
正在处理 27 ----- 72
正在处理 27 ----- 73
正在处理 27 ----- 74
正在处理 27 ----- 75
正在处理 27 ----- 76
正在处理 27 ----- 77
正在处理 27 ----- 78
正在处理 27 ----- 79
正在处理 27 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 27
============================

正在读取第 28 个DF
初始化batch数据： 28
batch数据 组装完毕 ：28
batch_tensor数据 组装完毕 ：28,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 28 ----- 1
正在处理 28 ----- 2
正在处理 28 ----- 3
正在处理 28 ----- 4
正在处理 28 ----- 5
正在处理 28 ----- 6
正在处理 28 ----- 7
正在处理 28 ----- 8
正在处理 28 ----- 9
正在处理 28 ----- 10
正在处理 28 ----- 11
正在处理 28 ----- 12
正在处理 28 ----- 13
正在处理 28 ----- 14
正在处理 28 ----- 15
正在处理 28 ----- 16
正在处理 28 ----- 17
正在处理 28 ----- 18
正在处理 28 ----- 19
正在处理 28 ----- 20
正在处理 28 ----- 21
正在处理 28 ----- 22
正在处理 28 ----- 23
正在处理 28 ----- 24
正在处理 28 ----- 25
正在处理 28 ----- 26
正在处理 28 ----- 27
正在处理 28 ----- 28
正在处理 28 ----- 29
正在处理 28 ----- 30
正在处理 28 ----- 31
正在处理 28 ----- 32
正在处理 28 ----- 33
正在处理 28 ----- 34
正在处理 28 ----- 35
正在处理 28 ----- 36
正在处理 28 ----- 37
正在处理 28 ----- 38
正在处理 28 ----- 39
正在处理 28 ----- 40
正在处理 28 ----- 41
正在处理 28 ----- 42
正在处理 28 ----- 43
正在处理 28 ----- 44
正在处理 28 ----- 45
正在处理 28 ----- 46
正在处理 28 ----- 47
正在处理 28 ----- 48
正在处理 28 ----- 49
正在处理 28 ----- 50
正在处理 28 ----- 51
正在处理 28 ----- 52
正在处理 28 ----- 53
正在处理 28 ----- 54
正在处理 28 ----- 55
正在处理 28 ----- 56
正在处理 28 ----- 57
正在处理 28 ----- 58
正在处理 28 ----- 59
正在处理 28 ----- 60
正在处理 28 ----- 61
正在处理 28 ----- 62
正在处理 28 ----- 63
正在处理 28 ----- 64
正在处理 28 ----- 65
正在处理 28 ----- 66
正在处理 28 ----- 67
正在处理 28 ----- 68
正在处理 28 ----- 69
正在处理 28 ----- 70
正在处理 28 ----- 71
正在处理 28 ----- 72
正在处理 28 ----- 73
正在处理 28 ----- 74
正在处理 28 ----- 75
正在处理 28 ----- 76
正在处理 28 ----- 77
正在处理 28 ----- 78
正在处理 28 ----- 79
正在处理 28 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 28
============================

正在读取第 29 个DF
初始化batch数据： 29
batch数据 组装完毕 ：29
batch_tensor数据 组装完毕 ：29,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 80 块， 开始调用模型
正在处理 29 ----- 1
正在处理 29 ----- 2
正在处理 29 ----- 3
正在处理 29 ----- 4
正在处理 29 ----- 5
正在处理 29 ----- 6
正在处理 29 ----- 7
正在处理 29 ----- 8
正在处理 29 ----- 9
正在处理 29 ----- 10
正在处理 29 ----- 11
正在处理 29 ----- 12
正在处理 29 ----- 13
正在处理 29 ----- 14
正在处理 29 ----- 15
正在处理 29 ----- 16
正在处理 29 ----- 17
正在处理 29 ----- 18
正在处理 29 ----- 19
正在处理 29 ----- 20
正在处理 29 ----- 21
正在处理 29 ----- 22
正在处理 29 ----- 23
正在处理 29 ----- 24
正在处理 29 ----- 25
正在处理 29 ----- 26
正在处理 29 ----- 27
正在处理 29 ----- 28
正在处理 29 ----- 29
正在处理 29 ----- 30
正在处理 29 ----- 31
正在处理 29 ----- 32
正在处理 29 ----- 33
正在处理 29 ----- 34
正在处理 29 ----- 35
正在处理 29 ----- 36
正在处理 29 ----- 37
正在处理 29 ----- 38
正在处理 29 ----- 39
正在处理 29 ----- 40
正在处理 29 ----- 41
正在处理 29 ----- 42
正在处理 29 ----- 43
正在处理 29 ----- 44
正在处理 29 ----- 45
正在处理 29 ----- 46
正在处理 29 ----- 47
正在处理 29 ----- 48
正在处理 29 ----- 49
正在处理 29 ----- 50
正在处理 29 ----- 51
正在处理 29 ----- 52
正在处理 29 ----- 53
正在处理 29 ----- 54
正在处理 29 ----- 55
正在处理 29 ----- 56
正在处理 29 ----- 57
正在处理 29 ----- 58
正在处理 29 ----- 59
正在处理 29 ----- 60
正在处理 29 ----- 61
正在处理 29 ----- 62
正在处理 29 ----- 63
正在处理 29 ----- 64
正在处理 29 ----- 65
正在处理 29 ----- 66
正在处理 29 ----- 67
正在处理 29 ----- 68
正在处理 29 ----- 69
正在处理 29 ----- 70
正在处理 29 ----- 71
正在处理 29 ----- 72
正在处理 29 ----- 73
正在处理 29 ----- 74
正在处理 29 ----- 75
正在处理 29 ----- 76
正在处理 29 ----- 77
正在处理 29 ----- 78
正在处理 29 ----- 79
正在处理 29 ----- 80

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 29
============================

正在读取第 30 个DF
初始化batch数据： 30
batch数据 组装完毕 ：30
batch_tensor数据 组装完毕 ：30,开始分块处理
分块处理完毕数据完毕，每块的长度为:64,一共有 28 块， 开始调用模型
正在处理 30 ----- 1
正在处理 30 ----- 2
正在处理 30 ----- 3
正在处理 30 ----- 4
正在处理 30 ----- 5
正在处理 30 ----- 6
正在处理 30 ----- 7
正在处理 30 ----- 8
正在处理 30 ----- 9
正在处理 30 ----- 10
正在处理 30 ----- 11
正在处理 30 ----- 12
正在处理 30 ----- 13
正在处理 30 ----- 14
正在处理 30 ----- 15
正在处理 30 ----- 16
正在处理 30 ----- 17
正在处理 30 ----- 18
正在处理 30 ----- 19
正在处理 30 ----- 20
正在处理 30 ----- 21
正在处理 30 ----- 22
正在处理 30 ----- 23
正在处理 30 ----- 24
正在处理 30 ----- 25
正在处理 30 ----- 26
正在处理 30 ----- 27
正在处理 30 ----- 28

/tmp/ipykernel_515/376242564.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 30
============================

#### 文件合并

In [100]:
n

208

In [106]:
folder_path = '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector'
file_names = [f'review_{i}.csv' for i in range(1, 1079)]

In [103]:
# 读取并合并所有CSV文件
df_combined = pd.concat((pd.read_csv(os.path.join(folder_path, file_name)) for file_name in file_names), ignore_index=True)

# 将合并后的DataFrame保存为新的CSV文件
output_file = '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/tip.csv'
df_combined.to_csv(output_file, index=False)

In [75]:
### 每100w存一次

In [76]:
# 初始化变量
chunksize = 1000000
df_combined = pd.DataFrame()
output_file_base = '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_part'
file_index = 1
row_count = 0

# 读取并合并所有CSV文件
for file_name in file_names:
    file_path = os.path.join(folder_path, file_name)
    for chunk in pd.read_csv(file_path, chunksize=chunksize):
        df_combined = pd.concat([df_combined, chunk], ignore_index=True)
        row_count += len(chunk)

        if row_count >= chunksize:
            output_file = f'{output_file_base}_{file_index}.csv'
            df_combined.to_csv(output_file, index=False)
            df_combined = pd.DataFrame()
            row_count = 0
            file_index += 1

# 保存剩余的DataFrame
if not df_combined.empty:
    output_file = f'{output_file_base}_{file_index}.csv'
    df_combined.to_csv(output_file, index=False)

In [107]:
# 删除原始的30个文件
for file_name in file_names:
    file_path = os.path.join(folder_path, file_name)
    try:
        os.remove(file_path)
        print(f"文件 {file_path} 已删除。")
    except FileNotFoundError:
        print(f"文件 {file_path} 不存在，无法删除。")

文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_2.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_3.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_4.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_5.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_6.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_7.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_8.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_9.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_10.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_11.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_12.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_13.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_14.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_15.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_16.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_17.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_18.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_19.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_20.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_21.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_22.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_23.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_24.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_25.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_26.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_27.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_28.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_29.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_30.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_31.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_32.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_33.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_34.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_35.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_36.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_37.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_38.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_39.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_40.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_41.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_42.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_43.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_44.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_45.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_46.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_47.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_48.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_49.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_50.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_51.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_52.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_53.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_54.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_55.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_56.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_57.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_58.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_59.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_60.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_61.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_62.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_63.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_64.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_65.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_66.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_67.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_68.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_69.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_70.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_71.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_72.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_73.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_74.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_75.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_76.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_77.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_78.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_79.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_80.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_81.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_82.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_83.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_84.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_85.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_86.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_87.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_88.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_89.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_90.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_91.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_92.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_93.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_94.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_95.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_96.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_97.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_98.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_99.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_100.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_101.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_102.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_103.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_104.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_105.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_106.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_107.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_108.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_109.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_110.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_111.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_112.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_113.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_114.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_115.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_116.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_117.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_118.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_119.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_120.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_121.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_122.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_123.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_124.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_125.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_126.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_127.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_128.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_129.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_130.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_131.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_132.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_133.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_134.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_135.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_136.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_137.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_138.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_139.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_140.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_141.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_142.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_143.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_144.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_145.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_146.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_147.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_148.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_149.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_150.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_151.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_152.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_153.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_154.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_155.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_156.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_157.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_158.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_159.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_160.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_161.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_162.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_163.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_164.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_165.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_166.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_167.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_168.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_169.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_170.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_171.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_172.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_173.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_174.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_175.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_176.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_177.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_178.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_179.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_180.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_181.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_182.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_183.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_184.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_185.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_186.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_187.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_188.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_189.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_190.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_191.csv 已删除。

文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_192.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_193.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_194.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_195.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_196.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_197.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_198.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_199.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_200.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_201.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_202.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_203.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_204.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_205.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_206.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_207.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_208.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_209.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_210.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_211.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_212.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_213.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_214.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_215.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_216.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_217.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_218.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_219.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_220.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_221.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_222.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_223.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_224.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_225.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_226.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_227.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_228.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_229.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_230.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_231.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_232.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_233.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_234.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_235.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_236.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_237.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_238.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_239.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_240.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_241.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_242.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_243.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_244.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_245.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_246.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_247.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_248.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_249.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_250.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_251.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_252.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_253.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_254.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_255.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_256.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_257.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_258.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_259.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_260.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_261.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_262.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_263.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_264.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_265.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_266.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_267.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_268.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_269.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_270.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_271.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_272.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_273.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_274.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_275.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_276.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_277.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_278.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_279.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_280.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_281.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_282.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_283.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_284.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_285.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_286.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_287.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_288.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_289.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_290.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_291.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_292.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_293.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_294.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_295.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_296.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_297.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_298.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_299.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_300.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_301.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_302.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_303.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_304.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_305.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_306.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_307.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_308.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_309.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_310.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_311.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_312.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_313.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_314.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_315.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_316.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_317.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_318.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_319.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_320.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_321.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_322.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_323.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_324.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_325.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_326.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_327.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_328.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_329.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_330.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_331.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_332.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_333.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_334.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_335.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_336.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_337.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_338.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_339.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_340.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_341.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_342.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_343.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_344.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_345.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_346.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_347.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_348.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_349.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_350.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_351.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_352.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_353.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_354.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_355.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_356.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_357.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_358.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_359.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_360.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_361.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_362.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_363.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_364.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_365.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_366.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_367.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_368.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_369.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_370.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_371.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_372.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_373.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_374.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_375.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_376.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_377.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_378.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_379.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_380.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_381.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_382.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_383.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_384.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_385.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_386.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_387.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_388.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_389.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_390.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_391.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_392.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_393.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_394.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_395.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_396.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_397.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_398.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_399.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_400.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_401.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_402.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_403.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_404.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_405.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_406.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_407.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_408.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_409.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_410.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_411.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_412.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_413.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_414.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_415.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_416.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_417.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_418.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_419.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_420.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_421.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_422.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_423.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_424.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_425.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_426.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_427.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_428.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_429.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_430.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_431.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_432.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_433.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_434.csv 已删除。

文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_435.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_436.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_437.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_438.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_439.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_440.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_441.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_442.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_443.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_444.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_445.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_446.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_447.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_448.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_449.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_450.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_451.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_452.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_453.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_454.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_455.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_456.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_457.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_458.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_459.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_460.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_461.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_462.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_463.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_464.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_465.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_466.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_467.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_468.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_469.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_470.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_471.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_472.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_473.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_474.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_475.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_476.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_477.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_478.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_479.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_480.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_481.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_482.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_483.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_484.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_485.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_486.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_487.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_488.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_489.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_490.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_491.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_492.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_493.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_494.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_495.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_496.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_497.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_498.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_499.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_500.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_501.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_502.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_503.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_504.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_505.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_506.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_507.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_508.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_509.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_510.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_511.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_512.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_513.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_514.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_515.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_516.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_517.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_518.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_519.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_520.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_521.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_522.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_523.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_524.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_525.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_526.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_527.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_528.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_529.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_530.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_531.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_532.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_533.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_534.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_535.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_536.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_537.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_538.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_539.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_540.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_541.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_542.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_543.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_544.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_545.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_546.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_547.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_548.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_549.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_550.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_551.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_552.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_553.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_554.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_555.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_556.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_557.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_558.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_559.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_560.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_561.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_562.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_563.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_564.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_565.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_566.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_567.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_568.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_569.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_570.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_571.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_572.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_573.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_574.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_575.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_576.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_577.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_578.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_579.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_580.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_581.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_582.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_583.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_584.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_585.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_586.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_587.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_588.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_589.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_590.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_591.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_592.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_593.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_594.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_595.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_596.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_597.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_598.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_599.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_600.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_601.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_602.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_603.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_604.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_605.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_606.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_607.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_608.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_609.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_610.csv 已删除。

文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_611.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_612.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_613.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_614.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_615.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_616.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_617.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_618.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_619.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_620.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_621.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_622.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_623.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_624.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_625.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_626.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_627.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_628.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_629.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_630.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_631.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_632.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_633.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_634.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_635.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_636.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_637.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_638.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_639.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_640.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_641.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_642.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_643.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_644.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_645.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_646.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_647.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_648.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_649.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_650.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_651.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_652.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_653.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_654.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_655.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_656.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_657.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_658.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_659.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_660.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_661.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_662.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_663.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_664.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_665.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_666.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_667.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_668.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_669.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_670.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_671.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_672.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_673.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_674.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_675.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_676.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_677.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_678.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_679.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_680.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_681.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_682.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_683.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_684.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_685.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_686.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_687.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_688.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_689.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_690.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_691.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_692.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_693.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_694.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_695.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_696.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_697.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_698.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_699.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_700.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_701.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_702.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_703.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_704.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_705.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_706.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_707.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_708.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_709.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_710.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_711.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_712.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_713.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_714.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_715.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_716.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_717.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_718.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_719.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_720.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_721.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_722.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_723.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_724.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_725.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_726.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_727.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_728.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_729.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_730.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_731.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_732.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_733.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_734.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_735.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_736.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_737.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_738.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_739.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_740.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_741.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_742.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_743.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_744.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_745.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_746.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_747.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_748.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_749.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_750.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_751.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_752.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_753.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_754.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_755.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_756.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_757.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_758.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_759.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_760.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_761.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_762.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_763.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_764.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_765.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_766.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_767.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_768.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_769.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_770.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_771.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_772.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_773.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_774.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_775.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_776.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_777.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_778.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_779.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_780.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_781.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_782.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_783.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_784.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_785.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_786.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_787.csv 已删除。

文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_788.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_789.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_790.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_791.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_792.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_793.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_794.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_795.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_796.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_797.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_798.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_799.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_800.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_801.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_802.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_803.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_804.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_805.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_806.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_807.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_808.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_809.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_810.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_811.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_812.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_813.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_814.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_815.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_816.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_817.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_818.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_819.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_820.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_821.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_822.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_823.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_824.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_825.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_826.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_827.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_828.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_829.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_830.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_831.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_832.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_833.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_834.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_835.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_836.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_837.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_838.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_839.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_840.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_841.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_842.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_843.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_844.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_845.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_846.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_847.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_848.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_849.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_850.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_851.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_852.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_853.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_854.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_855.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_856.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_857.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_858.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_859.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_860.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_861.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_862.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_863.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_864.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_865.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_866.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_867.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_868.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_869.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_870.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_871.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_872.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_873.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_874.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_875.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_876.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_877.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_878.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_879.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_880.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_881.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_882.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_883.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_884.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_885.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_886.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_887.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_888.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_889.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_890.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_891.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_892.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_893.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_894.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_895.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_896.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_897.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_898.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_899.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_900.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_901.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_902.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_903.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_904.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_905.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_906.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_907.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_908.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_909.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_910.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_911.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_912.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_913.csv 已删除。

文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_914.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_915.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_916.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_917.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_918.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_919.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_920.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_921.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_922.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_923.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_924.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_925.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_926.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_927.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_928.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_929.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_930.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_931.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_932.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_933.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_934.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_935.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_936.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_937.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_938.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_939.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_940.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_941.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_942.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_943.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_944.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_945.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_946.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_947.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_948.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_949.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_950.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_951.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_952.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_953.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_954.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_955.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_956.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_957.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_958.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_959.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_960.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_961.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_962.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_963.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_964.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_965.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_966.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_967.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_968.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_969.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_970.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_971.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_972.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_973.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_974.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_975.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_976.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_977.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_978.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_979.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_980.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_981.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_982.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_983.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_984.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_985.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_986.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_987.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_988.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_989.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_990.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_991.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_992.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_993.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_994.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_995.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_996.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_997.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_998.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_999.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1000.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1001.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1002.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1003.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1004.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1005.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1006.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1007.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1008.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1009.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1010.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1011.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1012.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1013.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1014.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1015.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1016.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1017.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1018.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1019.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1020.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1021.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1022.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1023.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1024.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1025.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1026.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1027.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1028.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1029.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1030.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1031.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1032.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1033.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1034.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1035.csv 已删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1036.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1037.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1038.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1039.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1040.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1041.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1042.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1043.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1044.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1045.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1046.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1047.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1048.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1049.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1050.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1051.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1052.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1053.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1054.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1055.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1056.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1057.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1058.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1059.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1060.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1061.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1062.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1063.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1064.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1065.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1066.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1067.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1068.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1069.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1070.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1071.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1072.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1073.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1074.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1075.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1076.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1077.csv 不存在，无法删除。
文件 /remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_1078.csv 不存在，无法删除。

In [109]:
demo = df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business.csv')

In [115]:
feature = demo.iloc[4]["feature"]

In [120]:
s = "select name,stars,id_1,feature_index_1$distance from vector(business,feature,array"+feature+",10, map[efSearch, 768]) order by feature_index_1$distance limit 10;"

In [121]:
s

'select name,stars,id_1,feature_index_1$distance from vector(business,feature,array[0.6412854790687561, 0.15557944774627686, -0.25583526492118835, -0.37156498432159424, -0.21899624168872833, -0.13379773497581482, 0.3629712462425232, 0.3158617913722992, 0.07918655127286911, -1.2644082307815552, -0.4443523585796356, 0.2287846803665161, -0.199891597032547, -0.2042980194091797, -0.4010559916496277, 0.1766739785671234, -0.04298792779445648, 0.2203962504863739, -0.2398119419813156, -0.27657991647720337, 0.059902504086494446, -0.029948631301522255, 0.7761920690536499, -0.06299848109483719, 0.06768635660409927, 0.06226615235209465, -0.012628177180886269, 0.2853887975215912, -0.05010503530502319, 0.020810255780816078, -0.1265525370836258, 0.43903887271881104, -0.06854730099439621, 0.13895283639431, -0.029223991557955742, 0.05612121894955635, -0.17995919287204742, -0.5310277342796326, -0.15090595185756683, -0.06863129138946533, -0.679302990436554, 0.06805437803268433, 0.34885767102241516, 0.04944754019379616, 0.15777179598808289, -0.031138332560658455, -0.039465900510549545, 0.1889103800058365, 0.07230258733034134, 0.2746462821960449, -0.0425560362637043, 0.20087869465351105, 0.1265622228384018, 0.04075806960463524, 0.16542555391788483, 0.07054939866065979, -0.34402135014533997, 0.1226094514131546, -0.4546525180339813, 0.1638977974653244, 0.20840589702129364, -0.03152713179588318, 0.21778742969036102, 0.20970234274864197, -0.013686350546777248, 0.12562225759029388, 0.0561109222471714, 0.3191783130168915, -0.5331653356552124, -0.0757986307144165, -0.20812813937664032, 0.16270628571510315, 0.3771948218345642, 0.6945478916168213, 0.13104888796806335, -0.6068427562713623, 0.7614081501960754, 0.4264674186706543, -0.29428812861442566, 0.14032351970672607, -0.22169402241706848, 0.2957829535007477, 0.07447046786546707, -0.25759193301200867, -0.4065801203250885, -0.18808534741401672, 0.0204213485121727, 0.05807042866945267, 0.16536639630794525, 0.2526991665363312, 0.17326030135154724, -0.10212908685207367, -0.3862137496471405, -0.1798415631055832, 0.21069705486297607, 0.15344806015491486, -0.18229426443576813, 0.5110833048820496, 6.761988639831543, -0.13365034759044647, 0.020314931869506836, 0.11123495548963547, -0.029882419854402542, -0.1613936871290207, 0.43222180008888245, -0.2537961006164551, 0.021344734355807304, -0.10352955758571625, 0.11863026022911072, 0.393513947725296, 0.3798511326313019, -0.08695802092552185, -0.013952570036053658, -0.22311587631702423, -0.36807993054389954, -0.20963266491889954, 0.05738532170653343, -0.24634408950805664, -0.04964344576001167, -0.4124217927455902, 0.05935000255703926, -0.3667452931404114, 1.6059560775756836, 0.28763440251350403, -0.21141140162944794, 0.05205255001783371, -0.058752212673425674, -0.34766316413879395, 0.22511225938796997, -0.18161293864250183, -0.3995664715766907, -0.14446745812892914, -0.08471856266260147, -0.0381423719227314, 0.048649776726961136, -0.05708805471658707, -0.009271540679037571, -0.08187846094369888, -0.7461380362510681, 0.007673399522900581, 0.009762155823409557, -0.2975803315639496, 0.09760691970586777, 0.05505179986357689, -0.3649955987930298, 3.1756129264831543, -0.28900712728500366, 0.135187029838562, 0.17409461736679077, -0.23679353296756744, 0.2526865303516388, -0.1129022091627121, -0.3863281011581421, -0.12083037197589874, -0.19660179316997528, -0.2564457356929779, 0.20734329521656036, 0.14314672350883484, 0.04203033819794655, -0.25707173347473145, -1.1566396951675415, 0.026637734845280647, -0.17950400710105896, 0.6073819398880005, 0.16336922347545624, -0.2883334159851074, 0.31923770904541016, -0.7416164875030518, 0.2588687241077423, 0.3551139831542969, 0.05229863524436951, 0.004359146114438772, -2.481839179992676, 0.43908703327178955, 0.1172216385602951, 0.368665486574173, 0.0007197632221505046, -0.07471346855163574, -0.07009207457304001, -0.13146641850471497, -0.15648898482322693, 0.03724607452750206, 0.05701941251754761, 0.048377275466918945, -0.6928982734680176, -0.09670194238424301, 0.255113810300827, -0.16448581218719482, 0.2663010060787201, 0.13341869413852692, 0.13807086646556854, -0.21069695055484772, -0.10691818594932556, -0.14663589000701904, 0.4385388493537903, 0.09761051088571548, 0.2573891282081604, -0.07083430141210556, -0.013758114539086819, 0.043114908039569855, -0.16108481585979462, 0.01893642172217369, -0.18037836253643036, 0.5467489957809448, 0.5704005360603333, 0.08265679329633713, -0.1187761202454567, 0.02498719096183777, 0.06803090870380402, -0.019735105335712433, -0.5086926221847534, 0.1409107744693756, -0.004207102581858635, 0.45950984954833984, 0.5147116184234619, -0.18912045657634735, -0.029987353831529617, 0.08049026131629944, -0.001042925170622766, 0.02932058461010456, -0.07113850861787796, 0.3072231411933899, -0.12146572023630142, -0.37801840901374817, -0.019419388845562935, 0.06754274666309357, -0.04526597261428833, 0.08672995120286942, -0.03849788010120392, -0.26725319027900696, 0.7929690480232239, -0.10061158239841461, -0.09686034917831421, -0.13935603201389313, 0.04397747665643692, -0.15906459093093872, -0.15836206078529358, 0.1325942575931549, 0.12967431545257568, 0.1693803369998932, -0.06124969199299812, -0.18897931277751923, 0.35612815618515015, -0.030037175863981247, -0.1919524073600769, -0.005011193919926882, 0.35191550850868225, 0.3475753664970398, 0.03900692239403725, 0.12879864871501923, 1.1285548210144043, 0.2050815373659134, -0.27540239691734314, -0.5593695044517517, -0.5096688866615295, 0.07286941260099411, -0.22607874870300293, -1.4245123863220215, -0.012467400170862675, -0.26689374446868896, 0.19321531057357788, -3.217945098876953, 0.322026789188385, 0.443021684885025, -0.07609403133392334, -0.0778215229511261, 0.03033360280096531, 0.19116513431072235, -0.20131096243858337, 0.036633700132369995, -0.345409095287323, -0.026781044900417328, -0.8007055521011353, 0.26827314496040344, 0.06596630811691284, 0.2663624882698059, 0.05141671374440193, 0.10804039984941483, -0.09308670461177826, -0.36954614520072937, -0.2325291931629181, 0.31744271516799927, -0.5142027735710144, 0.39921271800994873, -0.3887268602848053, 0.363794207572937, 0.3552219867706299, 0.06871631741523743, -0.13472124934196472, 4.375382423400879, 0.2997102737426758, 0.017048006877303123, 0.09662056714296341, -0.3894105553627014, 0.014304397627711296, 0.07179230451583862, -0.7294403314590454, -0.2297726422548294, -0.04530756548047066, 0.05184479430317879, -0.05504857003688812, -0.07945414632558823, -0.5945925116539001, -0.13852405548095703, -0.3911271095275879, 0.014346055686473846, 0.03125690296292305, 0.2232791781425476, -0.7989478707313538, 0.01308381836861372, 0.3178807497024536, 0.26578396558761597, -0.20783427357673645, 0.13857102394104004, -0.30016589164733887, -0.37902241945266724, -0.21495889127254486, 0.3954453766345978, -0.14053818583488464, -1.2099844217300415, -0.06176380440592766, -0.10804440081119537, -0.1546560674905777, -0.02881966531276703, 0.04106225445866585, 0.033461444079875946, 0.07695939391851425, -0.28209739923477173, 0.1684686541557312, -0.11179881542921066, -0.24722659587860107, -0.08038335293531418, -0.5114282369613647, -0.6059495210647583, -0.07904330641031265, -0.14243201911449432, -0.04829290881752968, 0.2078753113746643, -0.1953909546136856, 0.01896921917796135, -0.21277569234371185, 0.04134383425116539, -0.26093801856040955, -0.1329108327627182, 0.4050154685974121, 0.06236610934138298, 0.4155309796333313, -0.10361341387033463, -0.24027128517627716, 0.22714795172214508, 0.05139259621500969, 0.012589814141392708, -0.15910786390304565, -0.029766853898763657, 0.1153407171368599, 0.23285964131355286, -0.10815051943063736, -0.4898063540458679, 0.025864293798804283, -0.21891801059246063, -0.23684272170066833, -2.4638118743896484, 0.5842702984809875, 0.29013875126838684, -0.22263233363628387, -0.2033849060535431, -0.02554544247686863, 0.1276244819164276, 0.013593017123639584, 0.428493857383728, 0.3642480671405792, 0.13006019592285156, 0.5016305446624756, 0.0791512057185173, -0.626213014125824, -0.014060448855161667, 0.09019803255796432, 0.6681296229362488, -0.013689981773495674, -0.3849964141845703, -0.5311470627784729, 0.008430306799709797, 0.12884218990802765, 0.11420009285211563, 0.13522376120090485, 0.01754658669233322, 0.027458513155579567, -0.27452248334884644, 0.031716328114271164, -0.016589215025305748, 0.6377732753753662, 0.06758371740579605, 0.05703447386622429, -0.1325073540210724, -0.4612204432487488, 0.11838364601135254, -0.12352398037910461, 0.20185835659503937, 0.32649528980255127, -0.5704667568206787, -0.015064255334436893, 0.003894466208294034, -0.3017483651638031, -0.06561384350061417, -0.275358647108078, -0.03491336107254028, -0.07933850586414337, -0.1191990077495575, -1.5472592115402222, -0.13776448369026184, -0.04941845312714577, -0.1847553551197052, 0.0034417337737977505, 0.4288775324821472, 0.19974078238010406, 0.10483027249574661, 0.08932024985551834, 0.03409663960337639, 0.23914311826229095, 0.12064749002456665, 0.42980533838272095, 0.011981184594333172, -0.24243880808353424, -0.41109123826026917, -0.3742232322692871, 0.20917131006717682, -0.13470329344272614, 0.032456785440444946, 0.1780073195695877, 0.041379980742931366, -0.5968359112739563, -0.39283323287963867, 0.03177572786808014, -0.27814751863479614, -0.09540288895368576, -0.408033162355423, 0.12298809736967087, -0.3993181586265564, -0.07932176440954208, 5.765876293182373, -0.4602440297603607, 0.2408626824617386, -0.09547477215528488, 0.10072985291481018, -0.027066141366958618, 0.16729815304279327, 0.2648518979549408, 0.7569038271903992, -0.13603118062019348, -0.30430734157562256, -0.22302751243114471, 0.10433920472860336, 0.2189345359802246, -0.47115591168403625, 0.09746697545051575, 0.13980849087238312, 0.16784656047821045, -0.24774329364299774, -0.3063942790031433, -0.036580998450517654, 0.03244888782501221, -0.08541561663150787, -0.25461870431900024, 0.27041417360305786, 0.09497268497943878, 0.05566582456231117, -0.2485647350549698, -0.04545595869421959, -0.16573449969291687, -0.46584296226501465, 0.26373013854026794, 0.35395127534866333, 0.465528666973114, 0.07959255576133728, 0.04869231954216957, 0.22039487957954407, 0.0912989005446434, 0.3911885917186737, 0.1873430460691452, 0.19536356627941132, 0.18166552484035492, 1.0450451374053955, 0.1770704686641693, 0.47294649481773376, 0.24879015982151031, -0.059519700706005096, -0.4683517813682556, 0.2382289469242096, 0.09390144050121307, -0.05175814777612686, 0.27654585242271423, 0.2007182091474533, -0.16910359263420105, 0.2172907143831253, 0.08785069733858109, -0.06019114702939987, 0.0561172217130661, -0.09096597880125046, 0.20022739470005035, -0.016937486827373505, -0.02632037177681923, -0.3063742518424988, -0.0012970581883564591, 0.24116215109825134, -0.1563321053981781, 0.2734946012496948, -0.5146012902259827, -0.49035874009132385, -0.17579419910907745, -0.24803835153579712, 0.1321614384651184, -0.6732198596000671, 0.36888521909713745, 0.26412492990493774, -0.1510656177997589, -0.594932496547699, 0.44952696561813354, -0.02255520410835743, -0.20734180510044098, 0.06786978244781494, -0.3769454061985016, -0.22606344521045685, -0.23048283159732819, 0.12026451528072357, -0.019045699387788773, -0.6835096478462219, -0.48394453525543213, -0.012126674875617027, 0.24183453619480133, 0.09852293133735657, -0.21365474164485931, -0.004521215800195932, -0.4452787935733795, 0.16099616885185242, 0.25154364109039307, -0.19737111032009125, 0.050301335752010345, -0.038711294531822205, -0.013185424730181694, 0.4052408039569855, 0.3727719187736511, -0.06000426784157753, 0.3771072030067444, 0.13622693717479706, -0.30582574009895325, 0.015196154825389385, 0.10712325572967529, 0.1555064469575882, -0.09313179552555084, 0.48642614483833313, 0.05983343347907066, 0.09271050989627838, -0.031301721930503845, -0.15898850560188293, -0.20310166478157043, -0.09638804197311401, -0.5729055404663086, -6.520262241363525, 0.229413241147995, -0.03554635867476463, -0.0037381777074187994, -0.3282168209552765, -0.31238168478012085, 0.25653520226478577, 0.21109983325004578, 0.21310846507549286, 0.31749865412712097, -0.2925536632537842, -0.29079392552375793, -2.3374032974243164, -0.04724869504570961, -0.11663863807916641, 0.13180463016033173, -0.07329777628183365, -0.8990529179573059, -0.11030730605125427, 0.30578839778900146, -0.24765661358833313, 0.14954334497451782, 0.2811266779899597, 0.11944036185741425, 0.09454312920570374, 0.03669271990656853, 0.15782882273197174, -0.3038863241672516, -0.15434996783733368, 0.02737589366734028, 0.16627782583236694, 0.16212370991706848, 0.731241762638092, -0.030353832989931107, 0.03929981589317322, -0.32396405935287476, 0.2494877427816391, -0.1014723926782608, 0.304891437292099, -0.19563324749469757, -0.24702337384223938, 0.11946404725313187, 0.22184428572654724, 0.26311707496643066, -0.11423967033624649, -0.14207756519317627, -0.5748846530914307, -2.378263235092163, 0.191901296377182, -0.02535848878324032, 0.45634081959724426, 0.12243229895830154, -0.011304053477942944, -0.08187820762395859, -0.07797407358884811, -0.12292168289422989, -0.08637432008981705, 0.1584353893995285, 0.10801446437835693, -0.24030230939388275, -0.49898821115493774, -0.10499801486730576, 0.18980342149734497, -0.1679801493883133, 0.02977404184639454, 0.17540661990642548, -0.6013548374176025, -0.054703932255506516, -0.1802717000246048, -0.38785403966903687, 0.021198300644755363, -0.11077095568180084, -0.46283218264579773, 0.2071676254272461, 0.03668173402547836, 0.14060214161872864, -0.15881557762622833, -0.11619729548692703, -0.2766810655593872, -0.19814974069595337, -0.37887340784072876, -0.3726949989795685, 0.7403242588043213, 0.18957112729549408, 0.2191990613937378, -0.13707461953163147, -0.05733368918299675, 0.12098409980535507, -0.11709421873092651, -0.18855202198028564, 0.10196064412593842, -0.08510765433311462, -0.05662943050265312, 0.013733121566474438, -0.07242760807275772, 0.25306832790374756, -0.202158123254776, -0.13640671968460083, -0.517112672328949, -0.384064644575119, 0.0982154980301857, 0.15470287203788757, 0.2126229703426361, -0.36484405398368835, 0.13356471061706543, 0.04444843903183937, 2.779515266418457, 0.24612833559513092, -0.15463420748710632, 0.006238494999706745, -0.10910334438085556, 0.2875975966453552, 0.16661939024925232, 0.2000717669725418, 1.8188875913619995, 0.042376961559057236, -0.3959306478500366, -0.012511149980127811, -0.07996723055839539, 0.07851902395486832, -0.3424401581287384, 0.3707759380340576, 0.11683722585439682, 0.023796016350388527, -0.20422576367855072, 0.07370885461568832, 0.4734790027141571, -0.3678787648677826, 0.1569468080997467, -0.1888354867696762, -0.05800115317106247, -0.1564563661813736, 0.13363498449325562, -0.26033565402030945, -0.05860545113682747, -0.330984503030777, -0.2565193772315979, 0.18263036012649536, 0.1108197271823883, 0.924172043800354, -0.0705999955534935, 0.12889966368675232, 0.34365859627723694, 0.12125484645366669, 0.03592006117105484, -0.5270354747772217, 0.06516414880752563, -0.024243341758847237, -0.715309202671051, 0.6041077375411987, -0.33005934953689575, -0.15400733053684235, -0.4151691198348999, -0.26696640253067017, -0.05999228358268738, -0.23254673182964325, -0.11323783546686172, 0.01194083783775568, -0.0875229761004448, 0.15444165468215942, 0.03565589711070061, 0.12054229527711868, -0.7176302671432495, 0.19919270277023315, 0.09436269104480743, 0.1458994597196579, 0.13684865832328796, -0.06192939728498459, -0.009978041984140873, 0.07338862866163254, 0.10962152481079102, -0.1933247447013855, 0.30482611060142517, -0.2502959668636322, -0.33881115913391113, -0.17581647634506226, 0.20276999473571777, 0.1920021027326584, -2.41664981842041, 0.08005636185407639, -0.07733826339244843, -0.19806882739067078, -0.1399238258600235, -0.11560214310884476, 0.21884143352508545, 0.15022316575050354, 0.0768311470746994, 0.3898915648460388, -0.12095173448324203, 2.1684319972991943, -0.09620746970176697, -0.23619228601455688, 0.03872617706656456, -0.31728386878967285, 0.11130116134881973, 0.16525019705295563, 0.2309078574180603, -0.33016178011894226, -0.23863594233989716, 1.688394546508789, 0.452785849571228, 0.05620303004980087, 0.12281183153390884, -0.2512807548046112, -0.1326388567686081, 0.04701773077249527, 0.28100788593292236, 0.0949249118566513, -0.25205063819885254, 0.5074779987335205, -0.04333708807826042],10, map[efSearch, 768]) order by feature_index_1$distance limit 10;'

### handle review

In [37]:
review_data = []

# 打开JSON文件
with open('/remote-home/cs_acmis_wsf/ai4dingo/yelp/yelp_academic_dataset_review.json', 'r', encoding='utf-8') as file:
    # 逐行读取
    for line in file:
        # 解析每一行为JSON对象
        review = json.loads(line)
        review_id = review["review_id"]
        user_id = review["user_id"]
        business_id = review["business_id"]
        stars = review["stars"]
        useful = review["useful"]
        funny = review["funny"]
        cool = review["cool"]
        text = review["text"]
        review_date = review["date"]
        r = [review_id,user_id,business_id,stars,useful,funny,cool,text,review_date]
        review_data.append(r)

In [38]:
len(review_data)

6990280

In [39]:
review_df = pd.DataFrame(review_data,columns=["review_id","user_id","business_id","stars","useful","funny","cool","text","review_data"])

In [40]:
review_df= review_df.drop_duplicates(subset='text', keep='last')

In [41]:
review_df["text"] = review_df["text"].apply(handle_text)

In [42]:
review_df = review_df.dropna(subset=['text'])

In [43]:
review_df['length'] = review_df['text'].str.len()

In [47]:
max_len = int(review_df["length"].max())

In [46]:
review_df  = review_df[review_df["length"]<512]

In [50]:
tokenizer,model = bert_define()

Some weights of the model checkpoint at /remote-home/cs_acmis_wsf/ai4dingo/model/bert_english_pretrained were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [51]:
review_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,review_data,length
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,511
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30,339
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,243
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,1,2,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31,341
7,_ZeMknuYdlQcUqng_Im3yg,yfFzsLmaWF2d4Sr0UNbBgg,LHSTtnW3YHCeUkRDGyJOyw,5.0,2,0,0,Amazingly amazing wings and homemade bleu chee...,2015-08-07 02:29:16,192
...,...,...,...,...,...,...,...,...,...,...
6990272,wD5ZWao_vjyT2h4xmGam8Q,7L7GL5Pi2cf8mbm2Dpw4zw,e_E-jq9mwm7wk75k7Yi-Xw,5.0,1,0,1,It is very rare for a restaurant to be this go...,2022-01-17 22:36:01,336
6990273,zHZ-A1qyKDEgyZMDaD--wg,_XVdmFWSgTN6YlojUxixTA,6WaI-IN8ql0xpEKlb4q8tg,5.0,1,0,0,We redesigned my moms dress and mad it complet...,2022-01-17 20:59:01,209
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20,320
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10,395
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30,463

In [59]:
vector_count = len(review_df)

In [60]:
vector_count

4237560

In [61]:
n, batch_size, batch = closest_batch_size(vector_count)
print(f"vector_count: {vector_count}, n: {n}, batch_size: {batch_size}, batch: {batch}")

vector_count: 4237560, n: 6, batch_size: 64, batch: 66211

In [62]:
max_vector_count = 2**n * batch

In [63]:
rows_per_part = 4096
n =  math.ceil(vector_count / rows_per_part)

In [64]:
n

1035

In [65]:
split_dfs_review = split_dataframe(review_df, n,rows_per_part)

In [71]:
batch_size_num = 512

for i in range(252,len(split_dfs_review)):
    df = split_dfs_review[i]
    print(f'正在读取第 {i+1} 个DF')
    text = df["text"].tolist()
    
    print(f'初始化batch数据： {i+1}')
    batch_token, batch_segment, batch_mask = list(), list(), list()
    for t in text:
        # text 作 tokenizer 分词
        token = tokenizer.tokenize(t)
        token = ['[CLS]'] + token + ['[SEP]']
        token_id = tokenizer.convert_tokens_to_ids(token)  # 字转换vocab中的index

        # 加padding补齐及segment、mask
        padding = [0] * (max_len - len(token_id))
        mask = [1] * len(token_id) + padding
        segment = [0] * len(token_id) + padding
        token_id = token_id + padding

        batch_token.append(token_id)
        batch_segment.append(segment)
        batch_mask.append(mask)
        
    print(f'batch数据 组装完毕 ：{i+1}')
   
    batch_tensor_token = torch.tensor(batch_token)
    batch_tensor_segment = torch.tensor(batch_segment)
    batch_tensor_mask = torch.tensor(batch_mask)

    batch_len = len(batch_tensor_token)
    
    if torch.cuda.is_available():
        batch_tensor_token = batch_tensor_token.to('cuda:0')
        batch_tensor_segment = batch_tensor_segment.to('cuda:0')
        batch_tensor_mask = batch_tensor_mask.to('cuda:0')
    
    print(f'batch_tensor数据 组装完毕 ：{i+1},开始分块处理')
    
    batch_tensor_token_chunked = [batch_tensor_token[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    batch_tensor_segment_chunked = [batch_tensor_segment[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    batch_tensor_mask_chunked = [batch_tensor_mask[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    print(f'分块处理完毕数据完毕，每块的长度为:{batch_size_num},一共有 {len(batch_tensor_token_chunked)} 块， 开始调用模型')
    
    gc.collect()
    torch.cuda.empty_cache()
    text_vector = []
    
    try:
        for k in range(len(batch_tensor_token_chunked)):
            with torch.no_grad():
                print(f'正在处理 {i+1} ----- {k+1}')
                outputs = model(batch_tensor_token_chunked[k], token_type_ids=batch_tensor_segment_chunked[k], attention_mask=batch_tensor_mask_chunked[k])
                outputs = outputs[0][:, 0, :]  # 取cls向量
                for o in range(outputs.shape[0]):
                    text_vector.append(outputs[o])
        df["feature"] = [ tv.tolist() for tv in  text_vector] 
        df.to_csv(f'/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review_{i+1}.csv', index=False)
        print(f"文件写入完毕 {i+1}")
                    
    except Exception as e:
        print(f"出现异常 {i+1}: {e}")
        continue
            
    
    print('============================')
    print()

正在读取第 253 个DF
初始化batch数据： 253
batch数据 组装完毕 ：253
batch_tensor数据 组装完毕 ：253,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 253 ----- 1
正在处理 253 ----- 2
正在处理 253 ----- 3
正在处理 253 ----- 4
正在处理 253 ----- 5
正在处理 253 ----- 6
正在处理 253 ----- 7
正在处理 253 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 253
============================

正在读取第 254 个DF
初始化batch数据： 254
batch数据 组装完毕 ：254
batch_tensor数据 组装完毕 ：254,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 254 ----- 1
正在处理 254 ----- 2
正在处理 254 ----- 3
正在处理 254 ----- 4
正在处理 254 ----- 5
正在处理 254 ----- 6
正在处理 254 ----- 7
正在处理 254 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 254
============================

正在读取第 255 个DF
初始化batch数据： 255
batch数据 组装完毕 ：255
batch_tensor数据 组装完毕 ：255,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 255 ----- 1
正在处理 255 ----- 2
正在处理 255 ----- 3
正在处理 255 ----- 4
正在处理 255 ----- 5
正在处理 255 ----- 6
正在处理 255 ----- 7
正在处理 255 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 255
============================

正在读取第 256 个DF
初始化batch数据： 256
batch数据 组装完毕 ：256
batch_tensor数据 组装完毕 ：256,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 256 ----- 1
正在处理 256 ----- 2
正在处理 256 ----- 3
正在处理 256 ----- 4
正在处理 256 ----- 5
正在处理 256 ----- 6
正在处理 256 ----- 7
正在处理 256 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 256
============================

正在读取第 257 个DF
初始化batch数据： 257
batch数据 组装完毕 ：257
batch_tensor数据 组装完毕 ：257,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 257 ----- 1
正在处理 257 ----- 2
正在处理 257 ----- 3
正在处理 257 ----- 4
正在处理 257 ----- 5
正在处理 257 ----- 6
正在处理 257 ----- 7
正在处理 257 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 257
============================

正在读取第 258 个DF
初始化batch数据： 258
batch数据 组装完毕 ：258
batch_tensor数据 组装完毕 ：258,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 258 ----- 1
正在处理 258 ----- 2
正在处理 258 ----- 3
正在处理 258 ----- 4
正在处理 258 ----- 5
正在处理 258 ----- 6
正在处理 258 ----- 7
正在处理 258 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 258
============================

正在读取第 259 个DF
初始化batch数据： 259
batch数据 组装完毕 ：259
batch_tensor数据 组装完毕 ：259,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 259 ----- 1
正在处理 259 ----- 2
正在处理 259 ----- 3
正在处理 259 ----- 4
正在处理 259 ----- 5
正在处理 259 ----- 6
正在处理 259 ----- 7
正在处理 259 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 259
============================

正在读取第 260 个DF
初始化batch数据： 260
batch数据 组装完毕 ：260
batch_tensor数据 组装完毕 ：260,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 260 ----- 1
正在处理 260 ----- 2
正在处理 260 ----- 3
正在处理 260 ----- 4
正在处理 260 ----- 5
正在处理 260 ----- 6
正在处理 260 ----- 7
正在处理 260 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 260
============================

正在读取第 261 个DF
初始化batch数据： 261
batch数据 组装完毕 ：261
batch_tensor数据 组装完毕 ：261,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 261 ----- 1
正在处理 261 ----- 2
正在处理 261 ----- 3
正在处理 261 ----- 4
正在处理 261 ----- 5
正在处理 261 ----- 6
正在处理 261 ----- 7
正在处理 261 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 261
============================

正在读取第 262 个DF
初始化batch数据： 262
batch数据 组装完毕 ：262
batch_tensor数据 组装完毕 ：262,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 262 ----- 1
正在处理 262 ----- 2
正在处理 262 ----- 3
正在处理 262 ----- 4
正在处理 262 ----- 5
正在处理 262 ----- 6
正在处理 262 ----- 7
正在处理 262 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 262
============================

正在读取第 263 个DF
初始化batch数据： 263
batch数据 组装完毕 ：263
batch_tensor数据 组装完毕 ：263,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 263 ----- 1
正在处理 263 ----- 2
正在处理 263 ----- 3
正在处理 263 ----- 4
正在处理 263 ----- 5
正在处理 263 ----- 6
正在处理 263 ----- 7
正在处理 263 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 263
============================

正在读取第 264 个DF
初始化batch数据： 264
batch数据 组装完毕 ：264
batch_tensor数据 组装完毕 ：264,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 264 ----- 1
正在处理 264 ----- 2
正在处理 264 ----- 3
正在处理 264 ----- 4
正在处理 264 ----- 5
正在处理 264 ----- 6
正在处理 264 ----- 7
正在处理 264 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 264
============================

正在读取第 265 个DF
初始化batch数据： 265
batch数据 组装完毕 ：265
batch_tensor数据 组装完毕 ：265,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 265 ----- 1
正在处理 265 ----- 2
正在处理 265 ----- 3
正在处理 265 ----- 4
正在处理 265 ----- 5
正在处理 265 ----- 6
正在处理 265 ----- 7
正在处理 265 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 265
============================

正在读取第 266 个DF
初始化batch数据： 266
batch数据 组装完毕 ：266
batch_tensor数据 组装完毕 ：266,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 266 ----- 1
正在处理 266 ----- 2
正在处理 266 ----- 3
正在处理 266 ----- 4
正在处理 266 ----- 5
正在处理 266 ----- 6
正在处理 266 ----- 7
正在处理 266 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 266
============================

正在读取第 267 个DF
初始化batch数据： 267
batch数据 组装完毕 ：267
batch_tensor数据 组装完毕 ：267,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 267 ----- 1
正在处理 267 ----- 2
正在处理 267 ----- 3
正在处理 267 ----- 4
正在处理 267 ----- 5
正在处理 267 ----- 6
正在处理 267 ----- 7
正在处理 267 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 267
============================

正在读取第 268 个DF
初始化batch数据： 268
batch数据 组装完毕 ：268
batch_tensor数据 组装完毕 ：268,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 268 ----- 1
正在处理 268 ----- 2
正在处理 268 ----- 3
正在处理 268 ----- 4
正在处理 268 ----- 5
正在处理 268 ----- 6
正在处理 268 ----- 7
正在处理 268 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 268
============================

正在读取第 269 个DF
初始化batch数据： 269
batch数据 组装完毕 ：269
batch_tensor数据 组装完毕 ：269,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 269 ----- 1
正在处理 269 ----- 2
正在处理 269 ----- 3
正在处理 269 ----- 4
正在处理 269 ----- 5
正在处理 269 ----- 6
正在处理 269 ----- 7
正在处理 269 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 269
============================

正在读取第 270 个DF
初始化batch数据： 270
batch数据 组装完毕 ：270
batch_tensor数据 组装完毕 ：270,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 270 ----- 1
正在处理 270 ----- 2
正在处理 270 ----- 3
正在处理 270 ----- 4
正在处理 270 ----- 5
正在处理 270 ----- 6
正在处理 270 ----- 7
正在处理 270 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 270
============================

正在读取第 271 个DF
初始化batch数据： 271
batch数据 组装完毕 ：271
batch_tensor数据 组装完毕 ：271,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 271 ----- 1
正在处理 271 ----- 2
正在处理 271 ----- 3
正在处理 271 ----- 4
正在处理 271 ----- 5
正在处理 271 ----- 6
正在处理 271 ----- 7
正在处理 271 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 271
============================

正在读取第 272 个DF
初始化batch数据： 272
batch数据 组装完毕 ：272
batch_tensor数据 组装完毕 ：272,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 272 ----- 1
正在处理 272 ----- 2
正在处理 272 ----- 3
正在处理 272 ----- 4
正在处理 272 ----- 5
正在处理 272 ----- 6
正在处理 272 ----- 7
正在处理 272 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 272
============================

正在读取第 273 个DF
初始化batch数据： 273
batch数据 组装完毕 ：273
batch_tensor数据 组装完毕 ：273,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 273 ----- 1
正在处理 273 ----- 2
正在处理 273 ----- 3
正在处理 273 ----- 4
正在处理 273 ----- 5
正在处理 273 ----- 6
正在处理 273 ----- 7
正在处理 273 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 273
============================

正在读取第 274 个DF
初始化batch数据： 274
batch数据 组装完毕 ：274
batch_tensor数据 组装完毕 ：274,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 274 ----- 1
正在处理 274 ----- 2
正在处理 274 ----- 3
正在处理 274 ----- 4
正在处理 274 ----- 5
正在处理 274 ----- 6
正在处理 274 ----- 7
正在处理 274 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 274
============================

正在读取第 275 个DF
初始化batch数据： 275
batch数据 组装完毕 ：275
batch_tensor数据 组装完毕 ：275,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 275 ----- 1
正在处理 275 ----- 2
正在处理 275 ----- 3
正在处理 275 ----- 4
正在处理 275 ----- 5
正在处理 275 ----- 6
正在处理 275 ----- 7
正在处理 275 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 275
============================

正在读取第 276 个DF
初始化batch数据： 276
batch数据 组装完毕 ：276
batch_tensor数据 组装完毕 ：276,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 276 ----- 1
正在处理 276 ----- 2
正在处理 276 ----- 3
正在处理 276 ----- 4
正在处理 276 ----- 5
正在处理 276 ----- 6
正在处理 276 ----- 7
正在处理 276 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 276
============================

正在读取第 277 个DF
初始化batch数据： 277
batch数据 组装完毕 ：277
batch_tensor数据 组装完毕 ：277,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 277 ----- 1
正在处理 277 ----- 2
正在处理 277 ----- 3
正在处理 277 ----- 4
正在处理 277 ----- 5
正在处理 277 ----- 6
正在处理 277 ----- 7
正在处理 277 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 277
============================

正在读取第 278 个DF
初始化batch数据： 278
batch数据 组装完毕 ：278
batch_tensor数据 组装完毕 ：278,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 278 ----- 1
正在处理 278 ----- 2
正在处理 278 ----- 3
正在处理 278 ----- 4
正在处理 278 ----- 5
正在处理 278 ----- 6
正在处理 278 ----- 7
正在处理 278 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 278
============================

正在读取第 279 个DF
初始化batch数据： 279
batch数据 组装完毕 ：279
batch_tensor数据 组装完毕 ：279,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 279 ----- 1
正在处理 279 ----- 2
正在处理 279 ----- 3
正在处理 279 ----- 4
正在处理 279 ----- 5
正在处理 279 ----- 6
正在处理 279 ----- 7
正在处理 279 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 279
============================

正在读取第 280 个DF
初始化batch数据： 280
batch数据 组装完毕 ：280
batch_tensor数据 组装完毕 ：280,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 280 ----- 1
正在处理 280 ----- 2
正在处理 280 ----- 3
正在处理 280 ----- 4
正在处理 280 ----- 5
正在处理 280 ----- 6
正在处理 280 ----- 7
正在处理 280 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 280
============================

正在读取第 281 个DF
初始化batch数据： 281
batch数据 组装完毕 ：281
batch_tensor数据 组装完毕 ：281,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 281 ----- 1
正在处理 281 ----- 2
正在处理 281 ----- 3
正在处理 281 ----- 4
正在处理 281 ----- 5
正在处理 281 ----- 6
正在处理 281 ----- 7
正在处理 281 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 281
============================

正在读取第 282 个DF
初始化batch数据： 282
batch数据 组装完毕 ：282
batch_tensor数据 组装完毕 ：282,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 282 ----- 1
正在处理 282 ----- 2
正在处理 282 ----- 3
正在处理 282 ----- 4
正在处理 282 ----- 5
正在处理 282 ----- 6
正在处理 282 ----- 7
正在处理 282 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 282
============================

正在读取第 283 个DF
初始化batch数据： 283
batch数据 组装完毕 ：283
batch_tensor数据 组装完毕 ：283,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 283 ----- 1
正在处理 283 ----- 2
正在处理 283 ----- 3
正在处理 283 ----- 4
正在处理 283 ----- 5
正在处理 283 ----- 6
正在处理 283 ----- 7
正在处理 283 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 283
============================

正在读取第 284 个DF
初始化batch数据： 284
batch数据 组装完毕 ：284
batch_tensor数据 组装完毕 ：284,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 284 ----- 1
正在处理 284 ----- 2
正在处理 284 ----- 3
正在处理 284 ----- 4
正在处理 284 ----- 5
正在处理 284 ----- 6
正在处理 284 ----- 7
正在处理 284 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 284
============================

正在读取第 285 个DF
初始化batch数据： 285
batch数据 组装完毕 ：285
batch_tensor数据 组装完毕 ：285,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 285 ----- 1
正在处理 285 ----- 2
正在处理 285 ----- 3
正在处理 285 ----- 4
正在处理 285 ----- 5
正在处理 285 ----- 6
正在处理 285 ----- 7
正在处理 285 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 285
============================

正在读取第 286 个DF
初始化batch数据： 286
batch数据 组装完毕 ：286
batch_tensor数据 组装完毕 ：286,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 286 ----- 1
正在处理 286 ----- 2
正在处理 286 ----- 3
正在处理 286 ----- 4
正在处理 286 ----- 5
正在处理 286 ----- 6
正在处理 286 ----- 7
正在处理 286 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 286
============================

正在读取第 287 个DF
初始化batch数据： 287
batch数据 组装完毕 ：287
batch_tensor数据 组装完毕 ：287,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 287 ----- 1
正在处理 287 ----- 2
正在处理 287 ----- 3
正在处理 287 ----- 4
正在处理 287 ----- 5
正在处理 287 ----- 6
正在处理 287 ----- 7
正在处理 287 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 287
============================

正在读取第 288 个DF
初始化batch数据： 288
batch数据 组装完毕 ：288
batch_tensor数据 组装完毕 ：288,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 288 ----- 1
正在处理 288 ----- 2
正在处理 288 ----- 3
正在处理 288 ----- 4
正在处理 288 ----- 5
正在处理 288 ----- 6
正在处理 288 ----- 7
正在处理 288 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 288
============================

正在读取第 289 个DF
初始化batch数据： 289
batch数据 组装完毕 ：289
batch_tensor数据 组装完毕 ：289,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 289 ----- 1
正在处理 289 ----- 2
正在处理 289 ----- 3
正在处理 289 ----- 4
正在处理 289 ----- 5
正在处理 289 ----- 6
正在处理 289 ----- 7
正在处理 289 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 289
============================

正在读取第 290 个DF
初始化batch数据： 290
batch数据 组装完毕 ：290
batch_tensor数据 组装完毕 ：290,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 290 ----- 1
正在处理 290 ----- 2
正在处理 290 ----- 3
正在处理 290 ----- 4
正在处理 290 ----- 5
正在处理 290 ----- 6
正在处理 290 ----- 7
正在处理 290 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 290
============================

正在读取第 291 个DF
初始化batch数据： 291
batch数据 组装完毕 ：291
batch_tensor数据 组装完毕 ：291,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 291 ----- 1
正在处理 291 ----- 2
正在处理 291 ----- 3
正在处理 291 ----- 4
正在处理 291 ----- 5
正在处理 291 ----- 6
正在处理 291 ----- 7
正在处理 291 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 291
============================

正在读取第 292 个DF
初始化batch数据： 292
batch数据 组装完毕 ：292
batch_tensor数据 组装完毕 ：292,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 292 ----- 1
正在处理 292 ----- 2
正在处理 292 ----- 3
正在处理 292 ----- 4
正在处理 292 ----- 5
正在处理 292 ----- 6
正在处理 292 ----- 7
正在处理 292 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 292
============================

正在读取第 293 个DF
初始化batch数据： 293
batch数据 组装完毕 ：293
batch_tensor数据 组装完毕 ：293,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 293 ----- 1
正在处理 293 ----- 2
正在处理 293 ----- 3
正在处理 293 ----- 4
正在处理 293 ----- 5
正在处理 293 ----- 6
正在处理 293 ----- 7
正在处理 293 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 293
============================

正在读取第 294 个DF
初始化batch数据： 294
batch数据 组装完毕 ：294
batch_tensor数据 组装完毕 ：294,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 294 ----- 1
正在处理 294 ----- 2
正在处理 294 ----- 3
正在处理 294 ----- 4
正在处理 294 ----- 5
正在处理 294 ----- 6
正在处理 294 ----- 7
正在处理 294 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 294
============================

正在读取第 295 个DF
初始化batch数据： 295
batch数据 组装完毕 ：295
batch_tensor数据 组装完毕 ：295,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 295 ----- 1
正在处理 295 ----- 2
正在处理 295 ----- 3
正在处理 295 ----- 4
正在处理 295 ----- 5
正在处理 295 ----- 6
正在处理 295 ----- 7
正在处理 295 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 295
============================

正在读取第 296 个DF
初始化batch数据： 296
batch数据 组装完毕 ：296
batch_tensor数据 组装完毕 ：296,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 296 ----- 1
正在处理 296 ----- 2
正在处理 296 ----- 3
正在处理 296 ----- 4
正在处理 296 ----- 5
正在处理 296 ----- 6
正在处理 296 ----- 7
正在处理 296 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 296
============================

正在读取第 297 个DF
初始化batch数据： 297
batch数据 组装完毕 ：297
batch_tensor数据 组装完毕 ：297,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 297 ----- 1
正在处理 297 ----- 2
正在处理 297 ----- 3
正在处理 297 ----- 4
正在处理 297 ----- 5
正在处理 297 ----- 6
正在处理 297 ----- 7
正在处理 297 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 297
============================

正在读取第 298 个DF
初始化batch数据： 298
batch数据 组装完毕 ：298
batch_tensor数据 组装完毕 ：298,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 298 ----- 1
正在处理 298 ----- 2
正在处理 298 ----- 3
正在处理 298 ----- 4
正在处理 298 ----- 5
正在处理 298 ----- 6
正在处理 298 ----- 7
正在处理 298 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 298
============================

正在读取第 299 个DF
初始化batch数据： 299
batch数据 组装完毕 ：299
batch_tensor数据 组装完毕 ：299,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 299 ----- 1
正在处理 299 ----- 2
正在处理 299 ----- 3
正在处理 299 ----- 4
正在处理 299 ----- 5
正在处理 299 ----- 6
正在处理 299 ----- 7
正在处理 299 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 299
============================

正在读取第 300 个DF
初始化batch数据： 300
batch数据 组装完毕 ：300
batch_tensor数据 组装完毕 ：300,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 300 ----- 1
正在处理 300 ----- 2
正在处理 300 ----- 3
正在处理 300 ----- 4
正在处理 300 ----- 5
正在处理 300 ----- 6
正在处理 300 ----- 7
正在处理 300 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 300
============================

正在读取第 301 个DF
初始化batch数据： 301
batch数据 组装完毕 ：301
batch_tensor数据 组装完毕 ：301,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 301 ----- 1
正在处理 301 ----- 2
正在处理 301 ----- 3
正在处理 301 ----- 4
正在处理 301 ----- 5
正在处理 301 ----- 6
正在处理 301 ----- 7
正在处理 301 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 301
============================

正在读取第 302 个DF
初始化batch数据： 302
batch数据 组装完毕 ：302
batch_tensor数据 组装完毕 ：302,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 302 ----- 1
正在处理 302 ----- 2
正在处理 302 ----- 3
正在处理 302 ----- 4
正在处理 302 ----- 5
正在处理 302 ----- 6
正在处理 302 ----- 7
正在处理 302 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 302
============================

正在读取第 303 个DF
初始化batch数据： 303
batch数据 组装完毕 ：303
batch_tensor数据 组装完毕 ：303,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 303 ----- 1
正在处理 303 ----- 2
正在处理 303 ----- 3
正在处理 303 ----- 4
正在处理 303 ----- 5
正在处理 303 ----- 6
正在处理 303 ----- 7
正在处理 303 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 303
============================

正在读取第 304 个DF
初始化batch数据： 304
batch数据 组装完毕 ：304
batch_tensor数据 组装完毕 ：304,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 304 ----- 1
正在处理 304 ----- 2
正在处理 304 ----- 3
正在处理 304 ----- 4
正在处理 304 ----- 5
正在处理 304 ----- 6
正在处理 304 ----- 7
正在处理 304 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 304
============================

正在读取第 305 个DF
初始化batch数据： 305
batch数据 组装完毕 ：305
batch_tensor数据 组装完毕 ：305,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 305 ----- 1
正在处理 305 ----- 2
正在处理 305 ----- 3
正在处理 305 ----- 4
正在处理 305 ----- 5
正在处理 305 ----- 6
正在处理 305 ----- 7
正在处理 305 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 305
============================

正在读取第 306 个DF
初始化batch数据： 306
batch数据 组装完毕 ：306
batch_tensor数据 组装完毕 ：306,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 306 ----- 1
正在处理 306 ----- 2
正在处理 306 ----- 3
正在处理 306 ----- 4
正在处理 306 ----- 5
正在处理 306 ----- 6
正在处理 306 ----- 7
正在处理 306 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 306
============================

正在读取第 307 个DF
初始化batch数据： 307
batch数据 组装完毕 ：307
batch_tensor数据 组装完毕 ：307,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 307 ----- 1
正在处理 307 ----- 2
正在处理 307 ----- 3
正在处理 307 ----- 4
正在处理 307 ----- 5
正在处理 307 ----- 6
正在处理 307 ----- 7
正在处理 307 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 307
============================

正在读取第 308 个DF
初始化batch数据： 308
batch数据 组装完毕 ：308
batch_tensor数据 组装完毕 ：308,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 308 ----- 1
正在处理 308 ----- 2
正在处理 308 ----- 3
正在处理 308 ----- 4
正在处理 308 ----- 5
正在处理 308 ----- 6
正在处理 308 ----- 7
正在处理 308 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 308
============================

正在读取第 309 个DF
初始化batch数据： 309
batch数据 组装完毕 ：309
batch_tensor数据 组装完毕 ：309,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 309 ----- 1
正在处理 309 ----- 2
正在处理 309 ----- 3
正在处理 309 ----- 4
正在处理 309 ----- 5
正在处理 309 ----- 6
正在处理 309 ----- 7
正在处理 309 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 309
============================

正在读取第 310 个DF
初始化batch数据： 310
batch数据 组装完毕 ：310
batch_tensor数据 组装完毕 ：310,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 310 ----- 1
正在处理 310 ----- 2
正在处理 310 ----- 3
正在处理 310 ----- 4
正在处理 310 ----- 5
正在处理 310 ----- 6
正在处理 310 ----- 7
正在处理 310 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 310
============================

正在读取第 311 个DF
初始化batch数据： 311
batch数据 组装完毕 ：311
batch_tensor数据 组装完毕 ：311,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 311 ----- 1
正在处理 311 ----- 2
正在处理 311 ----- 3
正在处理 311 ----- 4
正在处理 311 ----- 5
正在处理 311 ----- 6
正在处理 311 ----- 7
正在处理 311 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 311
============================

正在读取第 312 个DF
初始化batch数据： 312
batch数据 组装完毕 ：312
batch_tensor数据 组装完毕 ：312,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 312 ----- 1
正在处理 312 ----- 2
正在处理 312 ----- 3
正在处理 312 ----- 4
正在处理 312 ----- 5
正在处理 312 ----- 6
正在处理 312 ----- 7
正在处理 312 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 312
============================

正在读取第 313 个DF
初始化batch数据： 313
batch数据 组装完毕 ：313
batch_tensor数据 组装完毕 ：313,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 313 ----- 1
正在处理 313 ----- 2
正在处理 313 ----- 3
正在处理 313 ----- 4
正在处理 313 ----- 5
正在处理 313 ----- 6
正在处理 313 ----- 7
正在处理 313 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 313
============================

正在读取第 314 个DF
初始化batch数据： 314
batch数据 组装完毕 ：314
batch_tensor数据 组装完毕 ：314,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 314 ----- 1
正在处理 314 ----- 2
正在处理 314 ----- 3
正在处理 314 ----- 4
正在处理 314 ----- 5
正在处理 314 ----- 6
正在处理 314 ----- 7
正在处理 314 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 314
============================

正在读取第 315 个DF
初始化batch数据： 315
batch数据 组装完毕 ：315
batch_tensor数据 组装完毕 ：315,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 315 ----- 1
正在处理 315 ----- 2
正在处理 315 ----- 3
正在处理 315 ----- 4
正在处理 315 ----- 5
正在处理 315 ----- 6
正在处理 315 ----- 7
正在处理 315 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 315
============================

正在读取第 316 个DF
初始化batch数据： 316
batch数据 组装完毕 ：316
batch_tensor数据 组装完毕 ：316,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 316 ----- 1
正在处理 316 ----- 2
正在处理 316 ----- 3
正在处理 316 ----- 4
正在处理 316 ----- 5
正在处理 316 ----- 6
正在处理 316 ----- 7
正在处理 316 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 316
============================

正在读取第 317 个DF
初始化batch数据： 317
batch数据 组装完毕 ：317
batch_tensor数据 组装完毕 ：317,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 317 ----- 1
正在处理 317 ----- 2
正在处理 317 ----- 3
正在处理 317 ----- 4
正在处理 317 ----- 5
正在处理 317 ----- 6
正在处理 317 ----- 7
正在处理 317 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 317
============================

正在读取第 318 个DF
初始化batch数据： 318
batch数据 组装完毕 ：318
batch_tensor数据 组装完毕 ：318,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 318 ----- 1
正在处理 318 ----- 2
正在处理 318 ----- 3
正在处理 318 ----- 4
正在处理 318 ----- 5
正在处理 318 ----- 6
正在处理 318 ----- 7
正在处理 318 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 318
============================

正在读取第 319 个DF
初始化batch数据： 319
batch数据 组装完毕 ：319
batch_tensor数据 组装完毕 ：319,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 319 ----- 1
正在处理 319 ----- 2
正在处理 319 ----- 3
正在处理 319 ----- 4
正在处理 319 ----- 5
正在处理 319 ----- 6
正在处理 319 ----- 7
正在处理 319 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 319
============================

正在读取第 320 个DF
初始化batch数据： 320
batch数据 组装完毕 ：320
batch_tensor数据 组装完毕 ：320,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 320 ----- 1
正在处理 320 ----- 2
正在处理 320 ----- 3
正在处理 320 ----- 4
正在处理 320 ----- 5
正在处理 320 ----- 6
正在处理 320 ----- 7
正在处理 320 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 320
============================

正在读取第 321 个DF
初始化batch数据： 321
batch数据 组装完毕 ：321
batch_tensor数据 组装完毕 ：321,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 321 ----- 1
正在处理 321 ----- 2
正在处理 321 ----- 3
正在处理 321 ----- 4
正在处理 321 ----- 5
正在处理 321 ----- 6
正在处理 321 ----- 7
正在处理 321 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 321
============================

正在读取第 322 个DF
初始化batch数据： 322
batch数据 组装完毕 ：322
batch_tensor数据 组装完毕 ：322,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 322 ----- 1
正在处理 322 ----- 2
正在处理 322 ----- 3
正在处理 322 ----- 4
正在处理 322 ----- 5
正在处理 322 ----- 6
正在处理 322 ----- 7
正在处理 322 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 322
============================

正在读取第 323 个DF
初始化batch数据： 323
batch数据 组装完毕 ：323
batch_tensor数据 组装完毕 ：323,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 323 ----- 1
正在处理 323 ----- 2
正在处理 323 ----- 3
正在处理 323 ----- 4
正在处理 323 ----- 5
正在处理 323 ----- 6
正在处理 323 ----- 7
正在处理 323 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 323
============================

正在读取第 324 个DF
初始化batch数据： 324
batch数据 组装完毕 ：324
batch_tensor数据 组装完毕 ：324,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 324 ----- 1
正在处理 324 ----- 2
正在处理 324 ----- 3
正在处理 324 ----- 4
正在处理 324 ----- 5
正在处理 324 ----- 6
正在处理 324 ----- 7
正在处理 324 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 324
============================

正在读取第 325 个DF
初始化batch数据： 325
batch数据 组装完毕 ：325
batch_tensor数据 组装完毕 ：325,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 325 ----- 1
正在处理 325 ----- 2
正在处理 325 ----- 3
正在处理 325 ----- 4
正在处理 325 ----- 5
正在处理 325 ----- 6
正在处理 325 ----- 7
正在处理 325 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 325
============================

正在读取第 326 个DF
初始化batch数据： 326
batch数据 组装完毕 ：326
batch_tensor数据 组装完毕 ：326,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 326 ----- 1
正在处理 326 ----- 2
正在处理 326 ----- 3
正在处理 326 ----- 4
正在处理 326 ----- 5
正在处理 326 ----- 6
正在处理 326 ----- 7
正在处理 326 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 326
============================

正在读取第 327 个DF
初始化batch数据： 327
batch数据 组装完毕 ：327
batch_tensor数据 组装完毕 ：327,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 327 ----- 1
正在处理 327 ----- 2
正在处理 327 ----- 3
正在处理 327 ----- 4
正在处理 327 ----- 5
正在处理 327 ----- 6
正在处理 327 ----- 7
正在处理 327 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 327
============================

正在读取第 328 个DF
初始化batch数据： 328
batch数据 组装完毕 ：328
batch_tensor数据 组装完毕 ：328,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 328 ----- 1
正在处理 328 ----- 2
正在处理 328 ----- 3
正在处理 328 ----- 4
正在处理 328 ----- 5
正在处理 328 ----- 6
正在处理 328 ----- 7
正在处理 328 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 328
============================

正在读取第 329 个DF
初始化batch数据： 329
batch数据 组装完毕 ：329
batch_tensor数据 组装完毕 ：329,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 329 ----- 1
正在处理 329 ----- 2
正在处理 329 ----- 3
正在处理 329 ----- 4
正在处理 329 ----- 5
正在处理 329 ----- 6
正在处理 329 ----- 7
正在处理 329 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 329
============================

正在读取第 330 个DF
初始化batch数据： 330
batch数据 组装完毕 ：330
batch_tensor数据 组装完毕 ：330,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 330 ----- 1
正在处理 330 ----- 2
正在处理 330 ----- 3
正在处理 330 ----- 4
正在处理 330 ----- 5
正在处理 330 ----- 6
正在处理 330 ----- 7
正在处理 330 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 330
============================

正在读取第 331 个DF
初始化batch数据： 331
batch数据 组装完毕 ：331
batch_tensor数据 组装完毕 ：331,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 331 ----- 1
正在处理 331 ----- 2
正在处理 331 ----- 3
正在处理 331 ----- 4
正在处理 331 ----- 5
正在处理 331 ----- 6
正在处理 331 ----- 7
正在处理 331 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 331
============================

正在读取第 332 个DF
初始化batch数据： 332
batch数据 组装完毕 ：332
batch_tensor数据 组装完毕 ：332,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 332 ----- 1
正在处理 332 ----- 2
正在处理 332 ----- 3
正在处理 332 ----- 4
正在处理 332 ----- 5
正在处理 332 ----- 6
正在处理 332 ----- 7
正在处理 332 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 332
============================

正在读取第 333 个DF
初始化batch数据： 333
batch数据 组装完毕 ：333
batch_tensor数据 组装完毕 ：333,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 333 ----- 1
正在处理 333 ----- 2
正在处理 333 ----- 3
正在处理 333 ----- 4
正在处理 333 ----- 5
正在处理 333 ----- 6
正在处理 333 ----- 7
正在处理 333 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 333
============================

正在读取第 334 个DF
初始化batch数据： 334
batch数据 组装完毕 ：334
batch_tensor数据 组装完毕 ：334,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 334 ----- 1
正在处理 334 ----- 2
正在处理 334 ----- 3
正在处理 334 ----- 4
正在处理 334 ----- 5
正在处理 334 ----- 6
正在处理 334 ----- 7
正在处理 334 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 334
============================

正在读取第 335 个DF
初始化batch数据： 335
batch数据 组装完毕 ：335
batch_tensor数据 组装完毕 ：335,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 335 ----- 1
正在处理 335 ----- 2
正在处理 335 ----- 3
正在处理 335 ----- 4
正在处理 335 ----- 5
正在处理 335 ----- 6
正在处理 335 ----- 7
正在处理 335 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 335
============================

正在读取第 336 个DF
初始化batch数据： 336
batch数据 组装完毕 ：336
batch_tensor数据 组装完毕 ：336,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 336 ----- 1
正在处理 336 ----- 2
正在处理 336 ----- 3
正在处理 336 ----- 4
正在处理 336 ----- 5
正在处理 336 ----- 6
正在处理 336 ----- 7
正在处理 336 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 336
============================

正在读取第 337 个DF
初始化batch数据： 337
batch数据 组装完毕 ：337
batch_tensor数据 组装完毕 ：337,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 337 ----- 1
正在处理 337 ----- 2
正在处理 337 ----- 3
正在处理 337 ----- 4
正在处理 337 ----- 5
正在处理 337 ----- 6
正在处理 337 ----- 7
正在处理 337 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 337
============================

正在读取第 338 个DF
初始化batch数据： 338
batch数据 组装完毕 ：338
batch_tensor数据 组装完毕 ：338,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 338 ----- 1
正在处理 338 ----- 2
正在处理 338 ----- 3
正在处理 338 ----- 4
正在处理 338 ----- 5
正在处理 338 ----- 6
正在处理 338 ----- 7
正在处理 338 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 338
============================

正在读取第 339 个DF
初始化batch数据： 339
batch数据 组装完毕 ：339
batch_tensor数据 组装完毕 ：339,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 339 ----- 1
正在处理 339 ----- 2
正在处理 339 ----- 3
正在处理 339 ----- 4
正在处理 339 ----- 5
正在处理 339 ----- 6
正在处理 339 ----- 7
正在处理 339 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 339
============================

正在读取第 340 个DF
初始化batch数据： 340
batch数据 组装完毕 ：340
batch_tensor数据 组装完毕 ：340,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 340 ----- 1
正在处理 340 ----- 2
正在处理 340 ----- 3
正在处理 340 ----- 4
正在处理 340 ----- 5
正在处理 340 ----- 6
正在处理 340 ----- 7
正在处理 340 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 340
============================

正在读取第 341 个DF
初始化batch数据： 341
batch数据 组装完毕 ：341
batch_tensor数据 组装完毕 ：341,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 341 ----- 1
正在处理 341 ----- 2
正在处理 341 ----- 3
正在处理 341 ----- 4
正在处理 341 ----- 5
正在处理 341 ----- 6
正在处理 341 ----- 7
正在处理 341 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 341
============================

正在读取第 342 个DF
初始化batch数据： 342
batch数据 组装完毕 ：342
batch_tensor数据 组装完毕 ：342,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 342 ----- 1
正在处理 342 ----- 2
正在处理 342 ----- 3
正在处理 342 ----- 4
正在处理 342 ----- 5
正在处理 342 ----- 6
正在处理 342 ----- 7
正在处理 342 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 342
============================

正在读取第 343 个DF
初始化batch数据： 343
batch数据 组装完毕 ：343
batch_tensor数据 组装完毕 ：343,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 343 ----- 1
正在处理 343 ----- 2
正在处理 343 ----- 3
正在处理 343 ----- 4
正在处理 343 ----- 5
正在处理 343 ----- 6
正在处理 343 ----- 7
正在处理 343 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 343
============================

正在读取第 344 个DF
初始化batch数据： 344
batch数据 组装完毕 ：344
batch_tensor数据 组装完毕 ：344,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 344 ----- 1
正在处理 344 ----- 2
正在处理 344 ----- 3
正在处理 344 ----- 4
正在处理 344 ----- 5
正在处理 344 ----- 6
正在处理 344 ----- 7
正在处理 344 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 344
============================

正在读取第 345 个DF
初始化batch数据： 345
batch数据 组装完毕 ：345
batch_tensor数据 组装完毕 ：345,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 345 ----- 1
正在处理 345 ----- 2
正在处理 345 ----- 3
正在处理 345 ----- 4
正在处理 345 ----- 5
正在处理 345 ----- 6
正在处理 345 ----- 7
正在处理 345 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 345
============================

正在读取第 346 个DF
初始化batch数据： 346
batch数据 组装完毕 ：346
batch_tensor数据 组装完毕 ：346,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 346 ----- 1
正在处理 346 ----- 2
正在处理 346 ----- 3
正在处理 346 ----- 4
正在处理 346 ----- 5
正在处理 346 ----- 6
正在处理 346 ----- 7
正在处理 346 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 346
============================

正在读取第 347 个DF
初始化batch数据： 347
batch数据 组装完毕 ：347
batch_tensor数据 组装完毕 ：347,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 347 ----- 1
正在处理 347 ----- 2
正在处理 347 ----- 3
正在处理 347 ----- 4
正在处理 347 ----- 5
正在处理 347 ----- 6
正在处理 347 ----- 7
正在处理 347 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 347
============================

正在读取第 348 个DF
初始化batch数据： 348
batch数据 组装完毕 ：348
batch_tensor数据 组装完毕 ：348,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 348 ----- 1
正在处理 348 ----- 2
正在处理 348 ----- 3
正在处理 348 ----- 4
正在处理 348 ----- 5
正在处理 348 ----- 6
正在处理 348 ----- 7
正在处理 348 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 348
============================

正在读取第 349 个DF
初始化batch数据： 349
batch数据 组装完毕 ：349
batch_tensor数据 组装完毕 ：349,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 349 ----- 1
正在处理 349 ----- 2
正在处理 349 ----- 3
正在处理 349 ----- 4
正在处理 349 ----- 5
正在处理 349 ----- 6
正在处理 349 ----- 7
正在处理 349 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 349
============================

正在读取第 350 个DF
初始化batch数据： 350
batch数据 组装完毕 ：350
batch_tensor数据 组装完毕 ：350,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 350 ----- 1
正在处理 350 ----- 2
正在处理 350 ----- 3
正在处理 350 ----- 4
正在处理 350 ----- 5
正在处理 350 ----- 6
正在处理 350 ----- 7
正在处理 350 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 350
============================

正在读取第 351 个DF
初始化batch数据： 351
batch数据 组装完毕 ：351
batch_tensor数据 组装完毕 ：351,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 351 ----- 1
正在处理 351 ----- 2
正在处理 351 ----- 3
正在处理 351 ----- 4
正在处理 351 ----- 5
正在处理 351 ----- 6
正在处理 351 ----- 7
正在处理 351 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 351
============================

正在读取第 352 个DF
初始化batch数据： 352
batch数据 组装完毕 ：352
batch_tensor数据 组装完毕 ：352,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 352 ----- 1
正在处理 352 ----- 2
正在处理 352 ----- 3
正在处理 352 ----- 4
正在处理 352 ----- 5
正在处理 352 ----- 6
正在处理 352 ----- 7
正在处理 352 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 352
============================

正在读取第 353 个DF
初始化batch数据： 353
batch数据 组装完毕 ：353
batch_tensor数据 组装完毕 ：353,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 353 ----- 1
正在处理 353 ----- 2
正在处理 353 ----- 3
正在处理 353 ----- 4
正在处理 353 ----- 5
正在处理 353 ----- 6
正在处理 353 ----- 7
正在处理 353 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 353
============================

正在读取第 354 个DF
初始化batch数据： 354
batch数据 组装完毕 ：354
batch_tensor数据 组装完毕 ：354,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 354 ----- 1
正在处理 354 ----- 2
正在处理 354 ----- 3
正在处理 354 ----- 4
正在处理 354 ----- 5
正在处理 354 ----- 6
正在处理 354 ----- 7
正在处理 354 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 354
============================

正在读取第 355 个DF
初始化batch数据： 355
batch数据 组装完毕 ：355
batch_tensor数据 组装完毕 ：355,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 355 ----- 1
正在处理 355 ----- 2
正在处理 355 ----- 3
正在处理 355 ----- 4
正在处理 355 ----- 5
正在处理 355 ----- 6
正在处理 355 ----- 7
正在处理 355 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 355
============================

正在读取第 356 个DF
初始化batch数据： 356
batch数据 组装完毕 ：356
batch_tensor数据 组装完毕 ：356,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 356 ----- 1
正在处理 356 ----- 2
正在处理 356 ----- 3
正在处理 356 ----- 4
正在处理 356 ----- 5
正在处理 356 ----- 6
正在处理 356 ----- 7
正在处理 356 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 356
============================

正在读取第 357 个DF
初始化batch数据： 357
batch数据 组装完毕 ：357
batch_tensor数据 组装完毕 ：357,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 357 ----- 1
正在处理 357 ----- 2
正在处理 357 ----- 3
正在处理 357 ----- 4
正在处理 357 ----- 5
正在处理 357 ----- 6
正在处理 357 ----- 7
正在处理 357 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 357
============================

正在读取第 358 个DF
初始化batch数据： 358
batch数据 组装完毕 ：358
batch_tensor数据 组装完毕 ：358,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 358 ----- 1
正在处理 358 ----- 2
正在处理 358 ----- 3
正在处理 358 ----- 4
正在处理 358 ----- 5
正在处理 358 ----- 6
正在处理 358 ----- 7
正在处理 358 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 358
============================

正在读取第 359 个DF
初始化batch数据： 359
batch数据 组装完毕 ：359
batch_tensor数据 组装完毕 ：359,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 359 ----- 1
正在处理 359 ----- 2
正在处理 359 ----- 3
正在处理 359 ----- 4
正在处理 359 ----- 5
正在处理 359 ----- 6
正在处理 359 ----- 7
正在处理 359 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 359
============================

正在读取第 360 个DF
初始化batch数据： 360
batch数据 组装完毕 ：360
batch_tensor数据 组装完毕 ：360,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 360 ----- 1
正在处理 360 ----- 2
正在处理 360 ----- 3
正在处理 360 ----- 4
正在处理 360 ----- 5
正在处理 360 ----- 6
正在处理 360 ----- 7
正在处理 360 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 360
============================

正在读取第 361 个DF
初始化batch数据： 361
batch数据 组装完毕 ：361
batch_tensor数据 组装完毕 ：361,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 361 ----- 1
正在处理 361 ----- 2
正在处理 361 ----- 3
正在处理 361 ----- 4
正在处理 361 ----- 5
正在处理 361 ----- 6
正在处理 361 ----- 7
正在处理 361 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 361
============================

正在读取第 362 个DF
初始化batch数据： 362
batch数据 组装完毕 ：362
batch_tensor数据 组装完毕 ：362,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 362 ----- 1
正在处理 362 ----- 2
正在处理 362 ----- 3
正在处理 362 ----- 4
正在处理 362 ----- 5
正在处理 362 ----- 6
正在处理 362 ----- 7
正在处理 362 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 362
============================

正在读取第 363 个DF
初始化batch数据： 363
batch数据 组装完毕 ：363
batch_tensor数据 组装完毕 ：363,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 363 ----- 1
正在处理 363 ----- 2
正在处理 363 ----- 3
正在处理 363 ----- 4
正在处理 363 ----- 5
正在处理 363 ----- 6
正在处理 363 ----- 7
正在处理 363 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 363
============================

正在读取第 364 个DF
初始化batch数据： 364
batch数据 组装完毕 ：364
batch_tensor数据 组装完毕 ：364,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 364 ----- 1
正在处理 364 ----- 2
正在处理 364 ----- 3
正在处理 364 ----- 4
正在处理 364 ----- 5
正在处理 364 ----- 6
正在处理 364 ----- 7
正在处理 364 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 364
============================

正在读取第 365 个DF
初始化batch数据： 365
batch数据 组装完毕 ：365
batch_tensor数据 组装完毕 ：365,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 365 ----- 1
正在处理 365 ----- 2
正在处理 365 ----- 3
正在处理 365 ----- 4
正在处理 365 ----- 5
正在处理 365 ----- 6
正在处理 365 ----- 7
正在处理 365 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 365
============================

正在读取第 366 个DF
初始化batch数据： 366
batch数据 组装完毕 ：366
batch_tensor数据 组装完毕 ：366,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 366 ----- 1
正在处理 366 ----- 2
正在处理 366 ----- 3
正在处理 366 ----- 4
正在处理 366 ----- 5
正在处理 366 ----- 6
正在处理 366 ----- 7
正在处理 366 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 366
============================

正在读取第 367 个DF
初始化batch数据： 367
batch数据 组装完毕 ：367
batch_tensor数据 组装完毕 ：367,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 367 ----- 1
正在处理 367 ----- 2
正在处理 367 ----- 3
正在处理 367 ----- 4
正在处理 367 ----- 5
正在处理 367 ----- 6
正在处理 367 ----- 7
正在处理 367 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 367
============================

正在读取第 368 个DF
初始化batch数据： 368
batch数据 组装完毕 ：368
batch_tensor数据 组装完毕 ：368,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 368 ----- 1
正在处理 368 ----- 2
正在处理 368 ----- 3
正在处理 368 ----- 4
正在处理 368 ----- 5
正在处理 368 ----- 6
正在处理 368 ----- 7
正在处理 368 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 368
============================

正在读取第 369 个DF
初始化batch数据： 369
batch数据 组装完毕 ：369
batch_tensor数据 组装完毕 ：369,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 369 ----- 1
正在处理 369 ----- 2
正在处理 369 ----- 3
正在处理 369 ----- 4
正在处理 369 ----- 5
正在处理 369 ----- 6
正在处理 369 ----- 7
正在处理 369 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 369
============================

正在读取第 370 个DF
初始化batch数据： 370
batch数据 组装完毕 ：370
batch_tensor数据 组装完毕 ：370,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 370 ----- 1
正在处理 370 ----- 2
正在处理 370 ----- 3
正在处理 370 ----- 4
正在处理 370 ----- 5
正在处理 370 ----- 6
正在处理 370 ----- 7
正在处理 370 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 370
============================

正在读取第 371 个DF
初始化batch数据： 371
batch数据 组装完毕 ：371
batch_tensor数据 组装完毕 ：371,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 371 ----- 1
正在处理 371 ----- 2
正在处理 371 ----- 3
正在处理 371 ----- 4
正在处理 371 ----- 5
正在处理 371 ----- 6
正在处理 371 ----- 7
正在处理 371 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 371
============================

正在读取第 372 个DF
初始化batch数据： 372
batch数据 组装完毕 ：372
batch_tensor数据 组装完毕 ：372,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 372 ----- 1
正在处理 372 ----- 2
正在处理 372 ----- 3
正在处理 372 ----- 4
正在处理 372 ----- 5
正在处理 372 ----- 6
正在处理 372 ----- 7
正在处理 372 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 372
============================

正在读取第 373 个DF
初始化batch数据： 373
batch数据 组装完毕 ：373
batch_tensor数据 组装完毕 ：373,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 373 ----- 1
正在处理 373 ----- 2
正在处理 373 ----- 3
正在处理 373 ----- 4
正在处理 373 ----- 5
正在处理 373 ----- 6
正在处理 373 ----- 7
正在处理 373 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 373
============================

正在读取第 374 个DF
初始化batch数据： 374
batch数据 组装完毕 ：374
batch_tensor数据 组装完毕 ：374,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 374 ----- 1
正在处理 374 ----- 2
正在处理 374 ----- 3
正在处理 374 ----- 4
正在处理 374 ----- 5
正在处理 374 ----- 6
正在处理 374 ----- 7
正在处理 374 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 374
============================

正在读取第 375 个DF
初始化batch数据： 375
batch数据 组装完毕 ：375
batch_tensor数据 组装完毕 ：375,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 375 ----- 1
正在处理 375 ----- 2
正在处理 375 ----- 3
正在处理 375 ----- 4
正在处理 375 ----- 5
正在处理 375 ----- 6
正在处理 375 ----- 7
正在处理 375 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 375
============================

正在读取第 376 个DF
初始化batch数据： 376
batch数据 组装完毕 ：376
batch_tensor数据 组装完毕 ：376,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 376 ----- 1
正在处理 376 ----- 2
正在处理 376 ----- 3
正在处理 376 ----- 4
正在处理 376 ----- 5
正在处理 376 ----- 6
正在处理 376 ----- 7
正在处理 376 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 376
============================

正在读取第 377 个DF
初始化batch数据： 377
batch数据 组装完毕 ：377
batch_tensor数据 组装完毕 ：377,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 377 ----- 1
正在处理 377 ----- 2
正在处理 377 ----- 3
正在处理 377 ----- 4
正在处理 377 ----- 5
正在处理 377 ----- 6
正在处理 377 ----- 7
正在处理 377 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 377
============================

正在读取第 378 个DF
初始化batch数据： 378
batch数据 组装完毕 ：378
batch_tensor数据 组装完毕 ：378,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 378 ----- 1
正在处理 378 ----- 2
正在处理 378 ----- 3
正在处理 378 ----- 4
正在处理 378 ----- 5
正在处理 378 ----- 6
正在处理 378 ----- 7
正在处理 378 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 378
============================

正在读取第 379 个DF
初始化batch数据： 379
batch数据 组装完毕 ：379
batch_tensor数据 组装完毕 ：379,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 379 ----- 1
正在处理 379 ----- 2
正在处理 379 ----- 3
正在处理 379 ----- 4
正在处理 379 ----- 5
正在处理 379 ----- 6
正在处理 379 ----- 7
正在处理 379 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 379
============================

正在读取第 380 个DF
初始化batch数据： 380
batch数据 组装完毕 ：380
batch_tensor数据 组装完毕 ：380,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 380 ----- 1
正在处理 380 ----- 2
正在处理 380 ----- 3
正在处理 380 ----- 4
正在处理 380 ----- 5
正在处理 380 ----- 6
正在处理 380 ----- 7
正在处理 380 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 380
============================

正在读取第 381 个DF
初始化batch数据： 381
batch数据 组装完毕 ：381
batch_tensor数据 组装完毕 ：381,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 381 ----- 1
正在处理 381 ----- 2
正在处理 381 ----- 3
正在处理 381 ----- 4
正在处理 381 ----- 5
正在处理 381 ----- 6
正在处理 381 ----- 7
正在处理 381 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 381
============================

正在读取第 382 个DF
初始化batch数据： 382
batch数据 组装完毕 ：382
batch_tensor数据 组装完毕 ：382,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 382 ----- 1
正在处理 382 ----- 2
正在处理 382 ----- 3
正在处理 382 ----- 4
正在处理 382 ----- 5
正在处理 382 ----- 6
正在处理 382 ----- 7
正在处理 382 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 382
============================

正在读取第 383 个DF
初始化batch数据： 383
batch数据 组装完毕 ：383
batch_tensor数据 组装完毕 ：383,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 383 ----- 1
正在处理 383 ----- 2
正在处理 383 ----- 3
正在处理 383 ----- 4
正在处理 383 ----- 5
正在处理 383 ----- 6
正在处理 383 ----- 7
正在处理 383 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 383
============================

正在读取第 384 个DF
初始化batch数据： 384
batch数据 组装完毕 ：384
batch_tensor数据 组装完毕 ：384,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 384 ----- 1
正在处理 384 ----- 2
正在处理 384 ----- 3
正在处理 384 ----- 4
正在处理 384 ----- 5
正在处理 384 ----- 6
正在处理 384 ----- 7
正在处理 384 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 384
============================

正在读取第 385 个DF
初始化batch数据： 385
batch数据 组装完毕 ：385
batch_tensor数据 组装完毕 ：385,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 385 ----- 1
正在处理 385 ----- 2
正在处理 385 ----- 3
正在处理 385 ----- 4
正在处理 385 ----- 5
正在处理 385 ----- 6
正在处理 385 ----- 7
正在处理 385 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 385
============================

正在读取第 386 个DF
初始化batch数据： 386
batch数据 组装完毕 ：386
batch_tensor数据 组装完毕 ：386,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 386 ----- 1
正在处理 386 ----- 2
正在处理 386 ----- 3
正在处理 386 ----- 4
正在处理 386 ----- 5
正在处理 386 ----- 6
正在处理 386 ----- 7
正在处理 386 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 386
============================

正在读取第 387 个DF
初始化batch数据： 387
batch数据 组装完毕 ：387
batch_tensor数据 组装完毕 ：387,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 387 ----- 1
正在处理 387 ----- 2
正在处理 387 ----- 3
正在处理 387 ----- 4
正在处理 387 ----- 5
正在处理 387 ----- 6
正在处理 387 ----- 7
正在处理 387 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 387
============================

正在读取第 388 个DF
初始化batch数据： 388
batch数据 组装完毕 ：388
batch_tensor数据 组装完毕 ：388,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 388 ----- 1
正在处理 388 ----- 2
正在处理 388 ----- 3
正在处理 388 ----- 4
正在处理 388 ----- 5
正在处理 388 ----- 6
正在处理 388 ----- 7
正在处理 388 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 388
============================

正在读取第 389 个DF
初始化batch数据： 389
batch数据 组装完毕 ：389
batch_tensor数据 组装完毕 ：389,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 389 ----- 1
正在处理 389 ----- 2
正在处理 389 ----- 3
正在处理 389 ----- 4
正在处理 389 ----- 5
正在处理 389 ----- 6
正在处理 389 ----- 7
正在处理 389 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 389
============================

正在读取第 390 个DF
初始化batch数据： 390
batch数据 组装完毕 ：390
batch_tensor数据 组装完毕 ：390,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 390 ----- 1
正在处理 390 ----- 2
正在处理 390 ----- 3
正在处理 390 ----- 4
正在处理 390 ----- 5
正在处理 390 ----- 6
正在处理 390 ----- 7
正在处理 390 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 390
============================

正在读取第 391 个DF
初始化batch数据： 391
batch数据 组装完毕 ：391
batch_tensor数据 组装完毕 ：391,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 391 ----- 1
正在处理 391 ----- 2
正在处理 391 ----- 3
正在处理 391 ----- 4
正在处理 391 ----- 5
正在处理 391 ----- 6
正在处理 391 ----- 7
正在处理 391 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 391
============================

正在读取第 392 个DF
初始化batch数据： 392
batch数据 组装完毕 ：392
batch_tensor数据 组装完毕 ：392,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 392 ----- 1
正在处理 392 ----- 2
正在处理 392 ----- 3
正在处理 392 ----- 4
正在处理 392 ----- 5
正在处理 392 ----- 6
正在处理 392 ----- 7
正在处理 392 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 392
============================

正在读取第 393 个DF
初始化batch数据： 393
batch数据 组装完毕 ：393
batch_tensor数据 组装完毕 ：393,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 393 ----- 1
正在处理 393 ----- 2
正在处理 393 ----- 3
正在处理 393 ----- 4
正在处理 393 ----- 5
正在处理 393 ----- 6
正在处理 393 ----- 7
正在处理 393 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 393
============================

正在读取第 394 个DF
初始化batch数据： 394
batch数据 组装完毕 ：394
batch_tensor数据 组装完毕 ：394,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 394 ----- 1
正在处理 394 ----- 2
正在处理 394 ----- 3
正在处理 394 ----- 4
正在处理 394 ----- 5
正在处理 394 ----- 6
正在处理 394 ----- 7
正在处理 394 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 394
============================

正在读取第 395 个DF
初始化batch数据： 395
batch数据 组装完毕 ：395
batch_tensor数据 组装完毕 ：395,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 395 ----- 1
正在处理 395 ----- 2
正在处理 395 ----- 3
正在处理 395 ----- 4
正在处理 395 ----- 5
正在处理 395 ----- 6
正在处理 395 ----- 7
正在处理 395 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 395
============================

正在读取第 396 个DF
初始化batch数据： 396
batch数据 组装完毕 ：396
batch_tensor数据 组装完毕 ：396,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 396 ----- 1
正在处理 396 ----- 2
正在处理 396 ----- 3
正在处理 396 ----- 4
正在处理 396 ----- 5
正在处理 396 ----- 6
正在处理 396 ----- 7
正在处理 396 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 396
============================

正在读取第 397 个DF
初始化batch数据： 397
batch数据 组装完毕 ：397
batch_tensor数据 组装完毕 ：397,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 397 ----- 1
正在处理 397 ----- 2
正在处理 397 ----- 3
正在处理 397 ----- 4
正在处理 397 ----- 5
正在处理 397 ----- 6
正在处理 397 ----- 7
正在处理 397 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 397
============================

正在读取第 398 个DF
初始化batch数据： 398
batch数据 组装完毕 ：398
batch_tensor数据 组装完毕 ：398,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 398 ----- 1
正在处理 398 ----- 2
正在处理 398 ----- 3
正在处理 398 ----- 4
正在处理 398 ----- 5
正在处理 398 ----- 6
正在处理 398 ----- 7
正在处理 398 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 398
============================

正在读取第 399 个DF
初始化batch数据： 399
batch数据 组装完毕 ：399
batch_tensor数据 组装完毕 ：399,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 399 ----- 1
正在处理 399 ----- 2
正在处理 399 ----- 3
正在处理 399 ----- 4
正在处理 399 ----- 5
正在处理 399 ----- 6
正在处理 399 ----- 7
正在处理 399 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 399
============================

正在读取第 400 个DF
初始化batch数据： 400
batch数据 组装完毕 ：400
batch_tensor数据 组装完毕 ：400,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 400 ----- 1
正在处理 400 ----- 2
正在处理 400 ----- 3
正在处理 400 ----- 4
正在处理 400 ----- 5
正在处理 400 ----- 6
正在处理 400 ----- 7
正在处理 400 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 400
============================

正在读取第 401 个DF
初始化batch数据： 401
batch数据 组装完毕 ：401
batch_tensor数据 组装完毕 ：401,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 401 ----- 1
正在处理 401 ----- 2
正在处理 401 ----- 3
正在处理 401 ----- 4
正在处理 401 ----- 5
正在处理 401 ----- 6
正在处理 401 ----- 7
正在处理 401 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 401
============================

正在读取第 402 个DF
初始化batch数据： 402
batch数据 组装完毕 ：402
batch_tensor数据 组装完毕 ：402,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 402 ----- 1
正在处理 402 ----- 2
正在处理 402 ----- 3
正在处理 402 ----- 4
正在处理 402 ----- 5
正在处理 402 ----- 6
正在处理 402 ----- 7
正在处理 402 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 402
============================

正在读取第 403 个DF
初始化batch数据： 403
batch数据 组装完毕 ：403
batch_tensor数据 组装完毕 ：403,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 403 ----- 1
正在处理 403 ----- 2
正在处理 403 ----- 3
正在处理 403 ----- 4
正在处理 403 ----- 5
正在处理 403 ----- 6
正在处理 403 ----- 7
正在处理 403 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 403
============================

正在读取第 404 个DF
初始化batch数据： 404
batch数据 组装完毕 ：404
batch_tensor数据 组装完毕 ：404,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 404 ----- 1
正在处理 404 ----- 2
正在处理 404 ----- 3
正在处理 404 ----- 4
正在处理 404 ----- 5
正在处理 404 ----- 6
正在处理 404 ----- 7
正在处理 404 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 404
============================

正在读取第 405 个DF
初始化batch数据： 405
batch数据 组装完毕 ：405
batch_tensor数据 组装完毕 ：405,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 405 ----- 1
正在处理 405 ----- 2
正在处理 405 ----- 3
正在处理 405 ----- 4
正在处理 405 ----- 5
正在处理 405 ----- 6
正在处理 405 ----- 7
正在处理 405 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 405
============================

正在读取第 406 个DF
初始化batch数据： 406
batch数据 组装完毕 ：406
batch_tensor数据 组装完毕 ：406,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 406 ----- 1
正在处理 406 ----- 2
正在处理 406 ----- 3
正在处理 406 ----- 4
正在处理 406 ----- 5
正在处理 406 ----- 6
正在处理 406 ----- 7
正在处理 406 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 406
============================

正在读取第 407 个DF
初始化batch数据： 407
batch数据 组装完毕 ：407
batch_tensor数据 组装完毕 ：407,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 407 ----- 1
正在处理 407 ----- 2
正在处理 407 ----- 3
正在处理 407 ----- 4
正在处理 407 ----- 5
正在处理 407 ----- 6
正在处理 407 ----- 7
正在处理 407 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 407
============================

正在读取第 408 个DF
初始化batch数据： 408
batch数据 组装完毕 ：408
batch_tensor数据 组装完毕 ：408,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 408 ----- 1
正在处理 408 ----- 2
正在处理 408 ----- 3
正在处理 408 ----- 4
正在处理 408 ----- 5
正在处理 408 ----- 6
正在处理 408 ----- 7
正在处理 408 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 408
============================

正在读取第 409 个DF
初始化batch数据： 409
batch数据 组装完毕 ：409
batch_tensor数据 组装完毕 ：409,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 409 ----- 1
正在处理 409 ----- 2
正在处理 409 ----- 3
正在处理 409 ----- 4
正在处理 409 ----- 5
正在处理 409 ----- 6
正在处理 409 ----- 7
正在处理 409 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 409
============================

正在读取第 410 个DF
初始化batch数据： 410
batch数据 组装完毕 ：410
batch_tensor数据 组装完毕 ：410,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 410 ----- 1
正在处理 410 ----- 2
正在处理 410 ----- 3
正在处理 410 ----- 4
正在处理 410 ----- 5
正在处理 410 ----- 6
正在处理 410 ----- 7
正在处理 410 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 410
============================

正在读取第 411 个DF
初始化batch数据： 411
batch数据 组装完毕 ：411
batch_tensor数据 组装完毕 ：411,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 411 ----- 1
正在处理 411 ----- 2
正在处理 411 ----- 3
正在处理 411 ----- 4
正在处理 411 ----- 5
正在处理 411 ----- 6
正在处理 411 ----- 7
正在处理 411 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 411
============================

正在读取第 412 个DF
初始化batch数据： 412
batch数据 组装完毕 ：412
batch_tensor数据 组装完毕 ：412,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 412 ----- 1
正在处理 412 ----- 2
正在处理 412 ----- 3
正在处理 412 ----- 4
正在处理 412 ----- 5
正在处理 412 ----- 6
正在处理 412 ----- 7
正在处理 412 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 412
============================

正在读取第 413 个DF
初始化batch数据： 413
batch数据 组装完毕 ：413
batch_tensor数据 组装完毕 ：413,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 413 ----- 1
正在处理 413 ----- 2
正在处理 413 ----- 3
正在处理 413 ----- 4
正在处理 413 ----- 5
正在处理 413 ----- 6
正在处理 413 ----- 7
正在处理 413 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 413
============================

正在读取第 414 个DF
初始化batch数据： 414
batch数据 组装完毕 ：414
batch_tensor数据 组装完毕 ：414,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 414 ----- 1
正在处理 414 ----- 2
正在处理 414 ----- 3
正在处理 414 ----- 4
正在处理 414 ----- 5
正在处理 414 ----- 6
正在处理 414 ----- 7
正在处理 414 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 414
============================

正在读取第 415 个DF
初始化batch数据： 415
batch数据 组装完毕 ：415
batch_tensor数据 组装完毕 ：415,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 415 ----- 1
正在处理 415 ----- 2
正在处理 415 ----- 3
正在处理 415 ----- 4
正在处理 415 ----- 5
正在处理 415 ----- 6
正在处理 415 ----- 7
正在处理 415 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 415
============================

正在读取第 416 个DF
初始化batch数据： 416
batch数据 组装完毕 ：416
batch_tensor数据 组装完毕 ：416,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 416 ----- 1
正在处理 416 ----- 2
正在处理 416 ----- 3
正在处理 416 ----- 4
正在处理 416 ----- 5
正在处理 416 ----- 6
正在处理 416 ----- 7
正在处理 416 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 416
============================

正在读取第 417 个DF
初始化batch数据： 417
batch数据 组装完毕 ：417
batch_tensor数据 组装完毕 ：417,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 417 ----- 1
正在处理 417 ----- 2
正在处理 417 ----- 3
正在处理 417 ----- 4
正在处理 417 ----- 5
正在处理 417 ----- 6
正在处理 417 ----- 7
正在处理 417 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 417
============================

正在读取第 418 个DF
初始化batch数据： 418
batch数据 组装完毕 ：418
batch_tensor数据 组装完毕 ：418,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 418 ----- 1
正在处理 418 ----- 2
正在处理 418 ----- 3
正在处理 418 ----- 4
正在处理 418 ----- 5
正在处理 418 ----- 6
正在处理 418 ----- 7
正在处理 418 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 418
============================

正在读取第 419 个DF
初始化batch数据： 419
batch数据 组装完毕 ：419
batch_tensor数据 组装完毕 ：419,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 419 ----- 1
正在处理 419 ----- 2
正在处理 419 ----- 3
正在处理 419 ----- 4
正在处理 419 ----- 5
正在处理 419 ----- 6
正在处理 419 ----- 7
正在处理 419 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 419
============================

正在读取第 420 个DF
初始化batch数据： 420
batch数据 组装完毕 ：420
batch_tensor数据 组装完毕 ：420,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 420 ----- 1
正在处理 420 ----- 2
正在处理 420 ----- 3
正在处理 420 ----- 4
正在处理 420 ----- 5
正在处理 420 ----- 6
正在处理 420 ----- 7
正在处理 420 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 420
============================

正在读取第 421 个DF
初始化batch数据： 421
batch数据 组装完毕 ：421
batch_tensor数据 组装完毕 ：421,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 421 ----- 1
正在处理 421 ----- 2
正在处理 421 ----- 3
正在处理 421 ----- 4
正在处理 421 ----- 5
正在处理 421 ----- 6
正在处理 421 ----- 7
正在处理 421 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 421
============================

正在读取第 422 个DF
初始化batch数据： 422
batch数据 组装完毕 ：422
batch_tensor数据 组装完毕 ：422,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 422 ----- 1
正在处理 422 ----- 2
正在处理 422 ----- 3
正在处理 422 ----- 4
正在处理 422 ----- 5
正在处理 422 ----- 6
正在处理 422 ----- 7
正在处理 422 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 422
============================

正在读取第 423 个DF
初始化batch数据： 423
batch数据 组装完毕 ：423
batch_tensor数据 组装完毕 ：423,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 423 ----- 1
正在处理 423 ----- 2
正在处理 423 ----- 3
正在处理 423 ----- 4
正在处理 423 ----- 5
正在处理 423 ----- 6
正在处理 423 ----- 7
正在处理 423 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 423
============================

正在读取第 424 个DF
初始化batch数据： 424
batch数据 组装完毕 ：424
batch_tensor数据 组装完毕 ：424,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 424 ----- 1
正在处理 424 ----- 2
正在处理 424 ----- 3
正在处理 424 ----- 4
正在处理 424 ----- 5
正在处理 424 ----- 6
正在处理 424 ----- 7
正在处理 424 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 424
============================

正在读取第 425 个DF
初始化batch数据： 425
batch数据 组装完毕 ：425
batch_tensor数据 组装完毕 ：425,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 425 ----- 1
正在处理 425 ----- 2
正在处理 425 ----- 3
正在处理 425 ----- 4
正在处理 425 ----- 5
正在处理 425 ----- 6
正在处理 425 ----- 7
正在处理 425 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 425
============================

正在读取第 426 个DF
初始化batch数据： 426
batch数据 组装完毕 ：426
batch_tensor数据 组装完毕 ：426,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 426 ----- 1
正在处理 426 ----- 2
正在处理 426 ----- 3
正在处理 426 ----- 4
正在处理 426 ----- 5
正在处理 426 ----- 6
正在处理 426 ----- 7
正在处理 426 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 426
============================

正在读取第 427 个DF
初始化batch数据： 427
batch数据 组装完毕 ：427
batch_tensor数据 组装完毕 ：427,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 427 ----- 1
正在处理 427 ----- 2
正在处理 427 ----- 3
正在处理 427 ----- 4
正在处理 427 ----- 5
正在处理 427 ----- 6
正在处理 427 ----- 7
正在处理 427 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 427
============================

正在读取第 428 个DF
初始化batch数据： 428
batch数据 组装完毕 ：428
batch_tensor数据 组装完毕 ：428,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 428 ----- 1
正在处理 428 ----- 2
正在处理 428 ----- 3
正在处理 428 ----- 4
正在处理 428 ----- 5
正在处理 428 ----- 6
正在处理 428 ----- 7
正在处理 428 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 428
============================

正在读取第 429 个DF
初始化batch数据： 429
batch数据 组装完毕 ：429
batch_tensor数据 组装完毕 ：429,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 429 ----- 1
正在处理 429 ----- 2
正在处理 429 ----- 3
正在处理 429 ----- 4
正在处理 429 ----- 5
正在处理 429 ----- 6
正在处理 429 ----- 7
正在处理 429 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 429
============================

正在读取第 430 个DF
初始化batch数据： 430
batch数据 组装完毕 ：430
batch_tensor数据 组装完毕 ：430,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 430 ----- 1
正在处理 430 ----- 2
正在处理 430 ----- 3
正在处理 430 ----- 4
正在处理 430 ----- 5
正在处理 430 ----- 6
正在处理 430 ----- 7
正在处理 430 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 430
============================

正在读取第 431 个DF
初始化batch数据： 431
batch数据 组装完毕 ：431
batch_tensor数据 组装完毕 ：431,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 431 ----- 1
正在处理 431 ----- 2
正在处理 431 ----- 3
正在处理 431 ----- 4
正在处理 431 ----- 5
正在处理 431 ----- 6
正在处理 431 ----- 7
正在处理 431 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 431
============================

正在读取第 432 个DF
初始化batch数据： 432
batch数据 组装完毕 ：432
batch_tensor数据 组装完毕 ：432,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 432 ----- 1
正在处理 432 ----- 2
正在处理 432 ----- 3
正在处理 432 ----- 4
正在处理 432 ----- 5
正在处理 432 ----- 6
正在处理 432 ----- 7
正在处理 432 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 432
============================

正在读取第 433 个DF
初始化batch数据： 433
batch数据 组装完毕 ：433
batch_tensor数据 组装完毕 ：433,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 433 ----- 1
正在处理 433 ----- 2
正在处理 433 ----- 3
正在处理 433 ----- 4
正在处理 433 ----- 5
正在处理 433 ----- 6
正在处理 433 ----- 7
正在处理 433 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 433
============================

正在读取第 434 个DF
初始化batch数据： 434
batch数据 组装完毕 ：434
batch_tensor数据 组装完毕 ：434,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 434 ----- 1
正在处理 434 ----- 2
正在处理 434 ----- 3
正在处理 434 ----- 4
正在处理 434 ----- 5
正在处理 434 ----- 6
正在处理 434 ----- 7
正在处理 434 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 434
============================

正在读取第 435 个DF
初始化batch数据： 435
batch数据 组装完毕 ：435
batch_tensor数据 组装完毕 ：435,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 435 ----- 1
正在处理 435 ----- 2
正在处理 435 ----- 3
正在处理 435 ----- 4
正在处理 435 ----- 5
正在处理 435 ----- 6
正在处理 435 ----- 7
正在处理 435 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 435
============================

正在读取第 436 个DF
初始化batch数据： 436
batch数据 组装完毕 ：436
batch_tensor数据 组装完毕 ：436,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 436 ----- 1
正在处理 436 ----- 2
正在处理 436 ----- 3
正在处理 436 ----- 4
正在处理 436 ----- 5
正在处理 436 ----- 6
正在处理 436 ----- 7
正在处理 436 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 436
============================

正在读取第 437 个DF
初始化batch数据： 437
batch数据 组装完毕 ：437
batch_tensor数据 组装完毕 ：437,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 437 ----- 1
正在处理 437 ----- 2
正在处理 437 ----- 3
正在处理 437 ----- 4
正在处理 437 ----- 5
正在处理 437 ----- 6
正在处理 437 ----- 7
正在处理 437 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 437
============================

正在读取第 438 个DF
初始化batch数据： 438
batch数据 组装完毕 ：438
batch_tensor数据 组装完毕 ：438,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 438 ----- 1
正在处理 438 ----- 2
正在处理 438 ----- 3
正在处理 438 ----- 4
正在处理 438 ----- 5
正在处理 438 ----- 6
正在处理 438 ----- 7
正在处理 438 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 438
============================

正在读取第 439 个DF
初始化batch数据： 439
batch数据 组装完毕 ：439
batch_tensor数据 组装完毕 ：439,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 439 ----- 1
正在处理 439 ----- 2
正在处理 439 ----- 3
正在处理 439 ----- 4
正在处理 439 ----- 5
正在处理 439 ----- 6
正在处理 439 ----- 7
正在处理 439 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 439
============================

正在读取第 440 个DF
初始化batch数据： 440
batch数据 组装完毕 ：440
batch_tensor数据 组装完毕 ：440,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 440 ----- 1
正在处理 440 ----- 2
正在处理 440 ----- 3
正在处理 440 ----- 4
正在处理 440 ----- 5
正在处理 440 ----- 6
正在处理 440 ----- 7
正在处理 440 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 440
============================

正在读取第 441 个DF
初始化batch数据： 441
batch数据 组装完毕 ：441
batch_tensor数据 组装完毕 ：441,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 441 ----- 1
正在处理 441 ----- 2
正在处理 441 ----- 3
正在处理 441 ----- 4
正在处理 441 ----- 5
正在处理 441 ----- 6
正在处理 441 ----- 7
正在处理 441 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 441
============================

正在读取第 442 个DF
初始化batch数据： 442
batch数据 组装完毕 ：442
batch_tensor数据 组装完毕 ：442,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 442 ----- 1
正在处理 442 ----- 2
正在处理 442 ----- 3
正在处理 442 ----- 4
正在处理 442 ----- 5
正在处理 442 ----- 6
正在处理 442 ----- 7
正在处理 442 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 442
============================

正在读取第 443 个DF
初始化batch数据： 443
batch数据 组装完毕 ：443
batch_tensor数据 组装完毕 ：443,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 443 ----- 1
正在处理 443 ----- 2
正在处理 443 ----- 3
正在处理 443 ----- 4
正在处理 443 ----- 5
正在处理 443 ----- 6
正在处理 443 ----- 7
正在处理 443 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 443
============================

正在读取第 444 个DF
初始化batch数据： 444
batch数据 组装完毕 ：444
batch_tensor数据 组装完毕 ：444,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 444 ----- 1
正在处理 444 ----- 2
正在处理 444 ----- 3
正在处理 444 ----- 4
正在处理 444 ----- 5
正在处理 444 ----- 6
正在处理 444 ----- 7
正在处理 444 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 444
============================

正在读取第 445 个DF
初始化batch数据： 445
batch数据 组装完毕 ：445
batch_tensor数据 组装完毕 ：445,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 445 ----- 1
正在处理 445 ----- 2
正在处理 445 ----- 3
正在处理 445 ----- 4
正在处理 445 ----- 5
正在处理 445 ----- 6
正在处理 445 ----- 7
正在处理 445 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 445
============================

正在读取第 446 个DF
初始化batch数据： 446
batch数据 组装完毕 ：446
batch_tensor数据 组装完毕 ：446,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 446 ----- 1
正在处理 446 ----- 2
正在处理 446 ----- 3
正在处理 446 ----- 4
正在处理 446 ----- 5
正在处理 446 ----- 6
正在处理 446 ----- 7
正在处理 446 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 446
============================

正在读取第 447 个DF
初始化batch数据： 447
batch数据 组装完毕 ：447
batch_tensor数据 组装完毕 ：447,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 447 ----- 1
正在处理 447 ----- 2
正在处理 447 ----- 3
正在处理 447 ----- 4
正在处理 447 ----- 5
正在处理 447 ----- 6
正在处理 447 ----- 7
正在处理 447 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 447
============================

正在读取第 448 个DF
初始化batch数据： 448
batch数据 组装完毕 ：448
batch_tensor数据 组装完毕 ：448,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 448 ----- 1
正在处理 448 ----- 2
正在处理 448 ----- 3
正在处理 448 ----- 4
正在处理 448 ----- 5
正在处理 448 ----- 6
正在处理 448 ----- 7
正在处理 448 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 448
============================

正在读取第 449 个DF
初始化batch数据： 449
batch数据 组装完毕 ：449
batch_tensor数据 组装完毕 ：449,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 449 ----- 1
正在处理 449 ----- 2
正在处理 449 ----- 3
正在处理 449 ----- 4
正在处理 449 ----- 5
正在处理 449 ----- 6
正在处理 449 ----- 7
正在处理 449 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 449
============================

正在读取第 450 个DF
初始化batch数据： 450
batch数据 组装完毕 ：450
batch_tensor数据 组装完毕 ：450,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 450 ----- 1
正在处理 450 ----- 2
正在处理 450 ----- 3
正在处理 450 ----- 4
正在处理 450 ----- 5
正在处理 450 ----- 6
正在处理 450 ----- 7
正在处理 450 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 450
============================

正在读取第 451 个DF
初始化batch数据： 451
batch数据 组装完毕 ：451
batch_tensor数据 组装完毕 ：451,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 451 ----- 1
正在处理 451 ----- 2
正在处理 451 ----- 3
正在处理 451 ----- 4
正在处理 451 ----- 5
正在处理 451 ----- 6
正在处理 451 ----- 7
正在处理 451 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 451
============================

正在读取第 452 个DF
初始化batch数据： 452
batch数据 组装完毕 ：452
batch_tensor数据 组装完毕 ：452,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 452 ----- 1
正在处理 452 ----- 2
正在处理 452 ----- 3
正在处理 452 ----- 4
正在处理 452 ----- 5
正在处理 452 ----- 6
正在处理 452 ----- 7
正在处理 452 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 452
============================

正在读取第 453 个DF
初始化batch数据： 453
batch数据 组装完毕 ：453
batch_tensor数据 组装完毕 ：453,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 453 ----- 1
正在处理 453 ----- 2
正在处理 453 ----- 3
正在处理 453 ----- 4
正在处理 453 ----- 5
正在处理 453 ----- 6
正在处理 453 ----- 7
正在处理 453 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 453
============================

正在读取第 454 个DF
初始化batch数据： 454
batch数据 组装完毕 ：454
batch_tensor数据 组装完毕 ：454,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 454 ----- 1
正在处理 454 ----- 2
正在处理 454 ----- 3
正在处理 454 ----- 4
正在处理 454 ----- 5
正在处理 454 ----- 6
正在处理 454 ----- 7
正在处理 454 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 454
============================

正在读取第 455 个DF
初始化batch数据： 455
batch数据 组装完毕 ：455
batch_tensor数据 组装完毕 ：455,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 455 ----- 1
正在处理 455 ----- 2
正在处理 455 ----- 3
正在处理 455 ----- 4
正在处理 455 ----- 5
正在处理 455 ----- 6
正在处理 455 ----- 7
正在处理 455 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 455
============================

正在读取第 456 个DF
初始化batch数据： 456
batch数据 组装完毕 ：456
batch_tensor数据 组装完毕 ：456,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 456 ----- 1
正在处理 456 ----- 2
正在处理 456 ----- 3
正在处理 456 ----- 4
正在处理 456 ----- 5
正在处理 456 ----- 6
正在处理 456 ----- 7
正在处理 456 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 456
============================

正在读取第 457 个DF
初始化batch数据： 457
batch数据 组装完毕 ：457
batch_tensor数据 组装完毕 ：457,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 457 ----- 1
正在处理 457 ----- 2
正在处理 457 ----- 3
正在处理 457 ----- 4
正在处理 457 ----- 5
正在处理 457 ----- 6
正在处理 457 ----- 7
正在处理 457 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 457
============================

正在读取第 458 个DF
初始化batch数据： 458
batch数据 组装完毕 ：458
batch_tensor数据 组装完毕 ：458,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 458 ----- 1
正在处理 458 ----- 2
正在处理 458 ----- 3
正在处理 458 ----- 4
正在处理 458 ----- 5
正在处理 458 ----- 6
正在处理 458 ----- 7
正在处理 458 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 458
============================

正在读取第 459 个DF
初始化batch数据： 459
batch数据 组装完毕 ：459
batch_tensor数据 组装完毕 ：459,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 459 ----- 1
正在处理 459 ----- 2
正在处理 459 ----- 3
正在处理 459 ----- 4
正在处理 459 ----- 5
正在处理 459 ----- 6
正在处理 459 ----- 7
正在处理 459 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 459
============================

正在读取第 460 个DF
初始化batch数据： 460
batch数据 组装完毕 ：460
batch_tensor数据 组装完毕 ：460,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 460 ----- 1
正在处理 460 ----- 2
正在处理 460 ----- 3
正在处理 460 ----- 4
正在处理 460 ----- 5
正在处理 460 ----- 6
正在处理 460 ----- 7
正在处理 460 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 460
============================

正在读取第 461 个DF
初始化batch数据： 461
batch数据 组装完毕 ：461
batch_tensor数据 组装完毕 ：461,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 461 ----- 1
正在处理 461 ----- 2
正在处理 461 ----- 3
正在处理 461 ----- 4
正在处理 461 ----- 5
正在处理 461 ----- 6
正在处理 461 ----- 7
正在处理 461 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 461
============================

正在读取第 462 个DF
初始化batch数据： 462
batch数据 组装完毕 ：462
batch_tensor数据 组装完毕 ：462,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 462 ----- 1
正在处理 462 ----- 2
正在处理 462 ----- 3
正在处理 462 ----- 4
正在处理 462 ----- 5
正在处理 462 ----- 6
正在处理 462 ----- 7
正在处理 462 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 462
============================

正在读取第 463 个DF
初始化batch数据： 463
batch数据 组装完毕 ：463
batch_tensor数据 组装完毕 ：463,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 463 ----- 1
正在处理 463 ----- 2
正在处理 463 ----- 3
正在处理 463 ----- 4
正在处理 463 ----- 5
正在处理 463 ----- 6
正在处理 463 ----- 7
正在处理 463 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 463
============================

正在读取第 464 个DF
初始化batch数据： 464
batch数据 组装完毕 ：464
batch_tensor数据 组装完毕 ：464,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 464 ----- 1
正在处理 464 ----- 2
正在处理 464 ----- 3
正在处理 464 ----- 4
正在处理 464 ----- 5
正在处理 464 ----- 6
正在处理 464 ----- 7
正在处理 464 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 464
============================

正在读取第 465 个DF
初始化batch数据： 465
batch数据 组装完毕 ：465
batch_tensor数据 组装完毕 ：465,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 465 ----- 1
正在处理 465 ----- 2
正在处理 465 ----- 3
正在处理 465 ----- 4
正在处理 465 ----- 5
正在处理 465 ----- 6
正在处理 465 ----- 7
正在处理 465 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 465
============================

正在读取第 466 个DF
初始化batch数据： 466
batch数据 组装完毕 ：466
batch_tensor数据 组装完毕 ：466,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 466 ----- 1
正在处理 466 ----- 2
正在处理 466 ----- 3
正在处理 466 ----- 4
正在处理 466 ----- 5
正在处理 466 ----- 6
正在处理 466 ----- 7
正在处理 466 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 466
============================

正在读取第 467 个DF
初始化batch数据： 467
batch数据 组装完毕 ：467
batch_tensor数据 组装完毕 ：467,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 467 ----- 1
正在处理 467 ----- 2
正在处理 467 ----- 3
正在处理 467 ----- 4
正在处理 467 ----- 5
正在处理 467 ----- 6
正在处理 467 ----- 7
正在处理 467 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 467
============================

正在读取第 468 个DF
初始化batch数据： 468
batch数据 组装完毕 ：468
batch_tensor数据 组装完毕 ：468,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 468 ----- 1
正在处理 468 ----- 2
正在处理 468 ----- 3
正在处理 468 ----- 4
正在处理 468 ----- 5
正在处理 468 ----- 6
正在处理 468 ----- 7
正在处理 468 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 468
============================

正在读取第 469 个DF
初始化batch数据： 469
batch数据 组装完毕 ：469
batch_tensor数据 组装完毕 ：469,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 469 ----- 1
正在处理 469 ----- 2
正在处理 469 ----- 3
正在处理 469 ----- 4
正在处理 469 ----- 5
正在处理 469 ----- 6
正在处理 469 ----- 7
正在处理 469 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 469
============================

正在读取第 470 个DF
初始化batch数据： 470
batch数据 组装完毕 ：470
batch_tensor数据 组装完毕 ：470,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 470 ----- 1
正在处理 470 ----- 2
正在处理 470 ----- 3
正在处理 470 ----- 4
正在处理 470 ----- 5
正在处理 470 ----- 6
正在处理 470 ----- 7
正在处理 470 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 470
============================

正在读取第 471 个DF
初始化batch数据： 471
batch数据 组装完毕 ：471
batch_tensor数据 组装完毕 ：471,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 471 ----- 1
正在处理 471 ----- 2
正在处理 471 ----- 3
正在处理 471 ----- 4
正在处理 471 ----- 5
正在处理 471 ----- 6
正在处理 471 ----- 7
正在处理 471 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 471
============================

正在读取第 472 个DF
初始化batch数据： 472
batch数据 组装完毕 ：472
batch_tensor数据 组装完毕 ：472,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 472 ----- 1
正在处理 472 ----- 2
正在处理 472 ----- 3
正在处理 472 ----- 4
正在处理 472 ----- 5
正在处理 472 ----- 6
正在处理 472 ----- 7
正在处理 472 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 472
============================

正在读取第 473 个DF
初始化batch数据： 473
batch数据 组装完毕 ：473
batch_tensor数据 组装完毕 ：473,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 473 ----- 1
正在处理 473 ----- 2
正在处理 473 ----- 3
正在处理 473 ----- 4
正在处理 473 ----- 5
正在处理 473 ----- 6
正在处理 473 ----- 7
正在处理 473 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 473
============================

正在读取第 474 个DF
初始化batch数据： 474
batch数据 组装完毕 ：474
batch_tensor数据 组装完毕 ：474,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 474 ----- 1
正在处理 474 ----- 2
正在处理 474 ----- 3
正在处理 474 ----- 4
正在处理 474 ----- 5
正在处理 474 ----- 6
正在处理 474 ----- 7
正在处理 474 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 474
============================

正在读取第 475 个DF
初始化batch数据： 475
batch数据 组装完毕 ：475
batch_tensor数据 组装完毕 ：475,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 475 ----- 1
正在处理 475 ----- 2
正在处理 475 ----- 3
正在处理 475 ----- 4
正在处理 475 ----- 5
正在处理 475 ----- 6
正在处理 475 ----- 7
正在处理 475 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 475
============================

正在读取第 476 个DF
初始化batch数据： 476
batch数据 组装完毕 ：476
batch_tensor数据 组装完毕 ：476,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 476 ----- 1
正在处理 476 ----- 2
正在处理 476 ----- 3
正在处理 476 ----- 4
正在处理 476 ----- 5
正在处理 476 ----- 6
正在处理 476 ----- 7
正在处理 476 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 476
============================

正在读取第 477 个DF
初始化batch数据： 477
batch数据 组装完毕 ：477
batch_tensor数据 组装完毕 ：477,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 477 ----- 1
正在处理 477 ----- 2
正在处理 477 ----- 3
正在处理 477 ----- 4
正在处理 477 ----- 5
正在处理 477 ----- 6
正在处理 477 ----- 7
正在处理 477 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 477
============================

正在读取第 478 个DF
初始化batch数据： 478
batch数据 组装完毕 ：478
batch_tensor数据 组装完毕 ：478,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 478 ----- 1
正在处理 478 ----- 2
正在处理 478 ----- 3
正在处理 478 ----- 4
正在处理 478 ----- 5
正在处理 478 ----- 6
正在处理 478 ----- 7
正在处理 478 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 478
============================

正在读取第 479 个DF
初始化batch数据： 479
batch数据 组装完毕 ：479
batch_tensor数据 组装完毕 ：479,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 479 ----- 1
正在处理 479 ----- 2
正在处理 479 ----- 3
正在处理 479 ----- 4
正在处理 479 ----- 5
正在处理 479 ----- 6
正在处理 479 ----- 7
正在处理 479 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 479
============================

正在读取第 480 个DF
初始化batch数据： 480
batch数据 组装完毕 ：480
batch_tensor数据 组装完毕 ：480,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 480 ----- 1
正在处理 480 ----- 2
正在处理 480 ----- 3
正在处理 480 ----- 4
正在处理 480 ----- 5
正在处理 480 ----- 6
正在处理 480 ----- 7
正在处理 480 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 480
============================

正在读取第 481 个DF
初始化batch数据： 481
batch数据 组装完毕 ：481
batch_tensor数据 组装完毕 ：481,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 481 ----- 1
正在处理 481 ----- 2
正在处理 481 ----- 3
正在处理 481 ----- 4
正在处理 481 ----- 5
正在处理 481 ----- 6
正在处理 481 ----- 7
正在处理 481 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 481
============================

正在读取第 482 个DF
初始化batch数据： 482
batch数据 组装完毕 ：482
batch_tensor数据 组装完毕 ：482,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 482 ----- 1
正在处理 482 ----- 2
正在处理 482 ----- 3
正在处理 482 ----- 4
正在处理 482 ----- 5
正在处理 482 ----- 6
正在处理 482 ----- 7
正在处理 482 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 482
============================

正在读取第 483 个DF
初始化batch数据： 483
batch数据 组装完毕 ：483
batch_tensor数据 组装完毕 ：483,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 483 ----- 1
正在处理 483 ----- 2
正在处理 483 ----- 3
正在处理 483 ----- 4
正在处理 483 ----- 5
正在处理 483 ----- 6
正在处理 483 ----- 7
正在处理 483 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 483
============================

正在读取第 484 个DF
初始化batch数据： 484
batch数据 组装完毕 ：484
batch_tensor数据 组装完毕 ：484,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 484 ----- 1
正在处理 484 ----- 2
正在处理 484 ----- 3
正在处理 484 ----- 4
正在处理 484 ----- 5
正在处理 484 ----- 6
正在处理 484 ----- 7
正在处理 484 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 484
============================

正在读取第 485 个DF
初始化batch数据： 485
batch数据 组装完毕 ：485
batch_tensor数据 组装完毕 ：485,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 485 ----- 1
正在处理 485 ----- 2
正在处理 485 ----- 3
正在处理 485 ----- 4
正在处理 485 ----- 5
正在处理 485 ----- 6
正在处理 485 ----- 7
正在处理 485 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 485
============================

正在读取第 486 个DF
初始化batch数据： 486
batch数据 组装完毕 ：486
batch_tensor数据 组装完毕 ：486,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 486 ----- 1
正在处理 486 ----- 2
正在处理 486 ----- 3
正在处理 486 ----- 4
正在处理 486 ----- 5
正在处理 486 ----- 6
正在处理 486 ----- 7
正在处理 486 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 486
============================

正在读取第 487 个DF
初始化batch数据： 487
batch数据 组装完毕 ：487
batch_tensor数据 组装完毕 ：487,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 487 ----- 1
正在处理 487 ----- 2
正在处理 487 ----- 3
正在处理 487 ----- 4
正在处理 487 ----- 5
正在处理 487 ----- 6
正在处理 487 ----- 7
正在处理 487 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 487
============================

正在读取第 488 个DF
初始化batch数据： 488
batch数据 组装完毕 ：488
batch_tensor数据 组装完毕 ：488,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 488 ----- 1
正在处理 488 ----- 2
正在处理 488 ----- 3
正在处理 488 ----- 4
正在处理 488 ----- 5
正在处理 488 ----- 6
正在处理 488 ----- 7
正在处理 488 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 488
============================

正在读取第 489 个DF
初始化batch数据： 489
batch数据 组装完毕 ：489
batch_tensor数据 组装完毕 ：489,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 489 ----- 1
正在处理 489 ----- 2
正在处理 489 ----- 3
正在处理 489 ----- 4
正在处理 489 ----- 5
正在处理 489 ----- 6
正在处理 489 ----- 7
正在处理 489 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 489
============================

正在读取第 490 个DF
初始化batch数据： 490
batch数据 组装完毕 ：490
batch_tensor数据 组装完毕 ：490,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 490 ----- 1
正在处理 490 ----- 2
正在处理 490 ----- 3
正在处理 490 ----- 4
正在处理 490 ----- 5
正在处理 490 ----- 6
正在处理 490 ----- 7
正在处理 490 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 490
============================

正在读取第 491 个DF
初始化batch数据： 491
batch数据 组装完毕 ：491
batch_tensor数据 组装完毕 ：491,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 491 ----- 1
正在处理 491 ----- 2
正在处理 491 ----- 3
正在处理 491 ----- 4
正在处理 491 ----- 5
正在处理 491 ----- 6
正在处理 491 ----- 7
正在处理 491 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 491
============================

正在读取第 492 个DF
初始化batch数据： 492
batch数据 组装完毕 ：492
batch_tensor数据 组装完毕 ：492,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 492 ----- 1
正在处理 492 ----- 2
正在处理 492 ----- 3
正在处理 492 ----- 4
正在处理 492 ----- 5
正在处理 492 ----- 6
正在处理 492 ----- 7
正在处理 492 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 492
============================

正在读取第 493 个DF
初始化batch数据： 493
batch数据 组装完毕 ：493
batch_tensor数据 组装完毕 ：493,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 493 ----- 1
正在处理 493 ----- 2
正在处理 493 ----- 3
正在处理 493 ----- 4
正在处理 493 ----- 5
正在处理 493 ----- 6
正在处理 493 ----- 7
正在处理 493 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 493
============================

正在读取第 494 个DF
初始化batch数据： 494
batch数据 组装完毕 ：494
batch_tensor数据 组装完毕 ：494,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 494 ----- 1
正在处理 494 ----- 2
正在处理 494 ----- 3
正在处理 494 ----- 4
正在处理 494 ----- 5
正在处理 494 ----- 6
正在处理 494 ----- 7
正在处理 494 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 494
============================

正在读取第 495 个DF
初始化batch数据： 495
batch数据 组装完毕 ：495
batch_tensor数据 组装完毕 ：495,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 495 ----- 1
正在处理 495 ----- 2
正在处理 495 ----- 3
正在处理 495 ----- 4
正在处理 495 ----- 5
正在处理 495 ----- 6
正在处理 495 ----- 7
正在处理 495 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 495
============================

正在读取第 496 个DF
初始化batch数据： 496
batch数据 组装完毕 ：496
batch_tensor数据 组装完毕 ：496,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 496 ----- 1
正在处理 496 ----- 2
正在处理 496 ----- 3
正在处理 496 ----- 4
正在处理 496 ----- 5
正在处理 496 ----- 6
正在处理 496 ----- 7
正在处理 496 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 496
============================

正在读取第 497 个DF
初始化batch数据： 497
batch数据 组装完毕 ：497
batch_tensor数据 组装完毕 ：497,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 497 ----- 1
正在处理 497 ----- 2
正在处理 497 ----- 3
正在处理 497 ----- 4
正在处理 497 ----- 5
正在处理 497 ----- 6
正在处理 497 ----- 7
正在处理 497 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 497
============================

正在读取第 498 个DF
初始化batch数据： 498
batch数据 组装完毕 ：498
batch_tensor数据 组装完毕 ：498,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 498 ----- 1
正在处理 498 ----- 2
正在处理 498 ----- 3
正在处理 498 ----- 4
正在处理 498 ----- 5
正在处理 498 ----- 6
正在处理 498 ----- 7
正在处理 498 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 498
============================

正在读取第 499 个DF
初始化batch数据： 499
batch数据 组装完毕 ：499
batch_tensor数据 组装完毕 ：499,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 499 ----- 1
正在处理 499 ----- 2
正在处理 499 ----- 3
正在处理 499 ----- 4
正在处理 499 ----- 5
正在处理 499 ----- 6
正在处理 499 ----- 7
正在处理 499 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 499
============================

正在读取第 500 个DF
初始化batch数据： 500
batch数据 组装完毕 ：500
batch_tensor数据 组装完毕 ：500,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 500 ----- 1
正在处理 500 ----- 2
正在处理 500 ----- 3
正在处理 500 ----- 4
正在处理 500 ----- 5
正在处理 500 ----- 6
正在处理 500 ----- 7
正在处理 500 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 500
============================

正在读取第 501 个DF
初始化batch数据： 501
batch数据 组装完毕 ：501
batch_tensor数据 组装完毕 ：501,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 501 ----- 1
正在处理 501 ----- 2
正在处理 501 ----- 3
正在处理 501 ----- 4
正在处理 501 ----- 5
正在处理 501 ----- 6
正在处理 501 ----- 7
正在处理 501 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 501
============================

正在读取第 502 个DF
初始化batch数据： 502
batch数据 组装完毕 ：502
batch_tensor数据 组装完毕 ：502,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 502 ----- 1
正在处理 502 ----- 2
正在处理 502 ----- 3
正在处理 502 ----- 4
正在处理 502 ----- 5
正在处理 502 ----- 6
正在处理 502 ----- 7
正在处理 502 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 502
============================

正在读取第 503 个DF
初始化batch数据： 503
batch数据 组装完毕 ：503
batch_tensor数据 组装完毕 ：503,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 503 ----- 1
正在处理 503 ----- 2
正在处理 503 ----- 3
正在处理 503 ----- 4
正在处理 503 ----- 5
正在处理 503 ----- 6
正在处理 503 ----- 7
正在处理 503 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 503
============================

正在读取第 504 个DF
初始化batch数据： 504
batch数据 组装完毕 ：504
batch_tensor数据 组装完毕 ：504,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 504 ----- 1
正在处理 504 ----- 2
正在处理 504 ----- 3
正在处理 504 ----- 4
正在处理 504 ----- 5
正在处理 504 ----- 6
正在处理 504 ----- 7
正在处理 504 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 504
============================

正在读取第 505 个DF
初始化batch数据： 505
batch数据 组装完毕 ：505
batch_tensor数据 组装完毕 ：505,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 505 ----- 1
正在处理 505 ----- 2
正在处理 505 ----- 3
正在处理 505 ----- 4
正在处理 505 ----- 5
正在处理 505 ----- 6
正在处理 505 ----- 7
正在处理 505 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 505
============================

正在读取第 506 个DF
初始化batch数据： 506
batch数据 组装完毕 ：506
batch_tensor数据 组装完毕 ：506,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 506 ----- 1
正在处理 506 ----- 2
正在处理 506 ----- 3
正在处理 506 ----- 4
正在处理 506 ----- 5
正在处理 506 ----- 6
正在处理 506 ----- 7
正在处理 506 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 506
============================

正在读取第 507 个DF
初始化batch数据： 507
batch数据 组装完毕 ：507
batch_tensor数据 组装完毕 ：507,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 507 ----- 1
正在处理 507 ----- 2
正在处理 507 ----- 3
正在处理 507 ----- 4
正在处理 507 ----- 5
正在处理 507 ----- 6
正在处理 507 ----- 7
正在处理 507 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 507
============================

正在读取第 508 个DF
初始化batch数据： 508
batch数据 组装完毕 ：508
batch_tensor数据 组装完毕 ：508,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 508 ----- 1
正在处理 508 ----- 2
正在处理 508 ----- 3
正在处理 508 ----- 4
正在处理 508 ----- 5
正在处理 508 ----- 6
正在处理 508 ----- 7
正在处理 508 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 508
============================

正在读取第 509 个DF
初始化batch数据： 509
batch数据 组装完毕 ：509
batch_tensor数据 组装完毕 ：509,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 509 ----- 1
正在处理 509 ----- 2
正在处理 509 ----- 3
正在处理 509 ----- 4
正在处理 509 ----- 5
正在处理 509 ----- 6
正在处理 509 ----- 7
正在处理 509 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 509
============================

正在读取第 510 个DF
初始化batch数据： 510
batch数据 组装完毕 ：510
batch_tensor数据 组装完毕 ：510,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 510 ----- 1
正在处理 510 ----- 2
正在处理 510 ----- 3
正在处理 510 ----- 4
正在处理 510 ----- 5
正在处理 510 ----- 6
正在处理 510 ----- 7
正在处理 510 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 510
============================

正在读取第 511 个DF
初始化batch数据： 511
batch数据 组装完毕 ：511
batch_tensor数据 组装完毕 ：511,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 511 ----- 1
正在处理 511 ----- 2
正在处理 511 ----- 3
正在处理 511 ----- 4
正在处理 511 ----- 5
正在处理 511 ----- 6
正在处理 511 ----- 7
正在处理 511 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 511
============================

正在读取第 512 个DF
初始化batch数据： 512
batch数据 组装完毕 ：512
batch_tensor数据 组装完毕 ：512,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 512 ----- 1
正在处理 512 ----- 2
正在处理 512 ----- 3
正在处理 512 ----- 4
正在处理 512 ----- 5
正在处理 512 ----- 6
正在处理 512 ----- 7
正在处理 512 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 512
============================

正在读取第 513 个DF
初始化batch数据： 513
batch数据 组装完毕 ：513
batch_tensor数据 组装完毕 ：513,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 513 ----- 1
正在处理 513 ----- 2
正在处理 513 ----- 3
正在处理 513 ----- 4
正在处理 513 ----- 5
正在处理 513 ----- 6
正在处理 513 ----- 7
正在处理 513 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 513
============================

正在读取第 514 个DF
初始化batch数据： 514
batch数据 组装完毕 ：514
batch_tensor数据 组装完毕 ：514,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 514 ----- 1
正在处理 514 ----- 2
正在处理 514 ----- 3
正在处理 514 ----- 4
正在处理 514 ----- 5
正在处理 514 ----- 6
正在处理 514 ----- 7
正在处理 514 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 514
============================

正在读取第 515 个DF
初始化batch数据： 515
batch数据 组装完毕 ：515
batch_tensor数据 组装完毕 ：515,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 515 ----- 1
正在处理 515 ----- 2
正在处理 515 ----- 3
正在处理 515 ----- 4
正在处理 515 ----- 5
正在处理 515 ----- 6
正在处理 515 ----- 7
正在处理 515 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 515
============================

正在读取第 516 个DF
初始化batch数据： 516
batch数据 组装完毕 ：516
batch_tensor数据 组装完毕 ：516,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 516 ----- 1
正在处理 516 ----- 2
正在处理 516 ----- 3
正在处理 516 ----- 4
正在处理 516 ----- 5
正在处理 516 ----- 6
正在处理 516 ----- 7
正在处理 516 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 516
============================

正在读取第 517 个DF
初始化batch数据： 517
batch数据 组装完毕 ：517
batch_tensor数据 组装完毕 ：517,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 517 ----- 1
正在处理 517 ----- 2
正在处理 517 ----- 3
正在处理 517 ----- 4
正在处理 517 ----- 5
正在处理 517 ----- 6
正在处理 517 ----- 7
正在处理 517 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 517
============================

正在读取第 518 个DF
初始化batch数据： 518
batch数据 组装完毕 ：518
batch_tensor数据 组装完毕 ：518,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 518 ----- 1
正在处理 518 ----- 2
正在处理 518 ----- 3
正在处理 518 ----- 4
正在处理 518 ----- 5
正在处理 518 ----- 6
正在处理 518 ----- 7
正在处理 518 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 518
============================

正在读取第 519 个DF
初始化batch数据： 519
batch数据 组装完毕 ：519
batch_tensor数据 组装完毕 ：519,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 519 ----- 1
正在处理 519 ----- 2
正在处理 519 ----- 3
正在处理 519 ----- 4
正在处理 519 ----- 5
正在处理 519 ----- 6
正在处理 519 ----- 7
正在处理 519 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 519
============================

正在读取第 520 个DF
初始化batch数据： 520
batch数据 组装完毕 ：520
batch_tensor数据 组装完毕 ：520,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 520 ----- 1
正在处理 520 ----- 2
正在处理 520 ----- 3
正在处理 520 ----- 4
正在处理 520 ----- 5
正在处理 520 ----- 6
正在处理 520 ----- 7
正在处理 520 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 520
============================

正在读取第 521 个DF
初始化batch数据： 521
batch数据 组装完毕 ：521
batch_tensor数据 组装完毕 ：521,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 521 ----- 1
正在处理 521 ----- 2
正在处理 521 ----- 3
正在处理 521 ----- 4
正在处理 521 ----- 5
正在处理 521 ----- 6
正在处理 521 ----- 7
正在处理 521 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 521
============================

正在读取第 522 个DF
初始化batch数据： 522
batch数据 组装完毕 ：522
batch_tensor数据 组装完毕 ：522,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 522 ----- 1
正在处理 522 ----- 2
正在处理 522 ----- 3
正在处理 522 ----- 4
正在处理 522 ----- 5
正在处理 522 ----- 6
正在处理 522 ----- 7
正在处理 522 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 522
============================

正在读取第 523 个DF
初始化batch数据： 523
batch数据 组装完毕 ：523
batch_tensor数据 组装完毕 ：523,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 523 ----- 1
正在处理 523 ----- 2
正在处理 523 ----- 3
正在处理 523 ----- 4
正在处理 523 ----- 5
正在处理 523 ----- 6
正在处理 523 ----- 7
正在处理 523 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 523
============================

正在读取第 524 个DF
初始化batch数据： 524
batch数据 组装完毕 ：524
batch_tensor数据 组装完毕 ：524,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 524 ----- 1
正在处理 524 ----- 2
正在处理 524 ----- 3
正在处理 524 ----- 4
正在处理 524 ----- 5
正在处理 524 ----- 6
正在处理 524 ----- 7
正在处理 524 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 524
============================

正在读取第 525 个DF
初始化batch数据： 525
batch数据 组装完毕 ：525
batch_tensor数据 组装完毕 ：525,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 525 ----- 1
正在处理 525 ----- 2
正在处理 525 ----- 3
正在处理 525 ----- 4
正在处理 525 ----- 5
正在处理 525 ----- 6
正在处理 525 ----- 7
正在处理 525 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 525
============================

正在读取第 526 个DF
初始化batch数据： 526
batch数据 组装完毕 ：526
batch_tensor数据 组装完毕 ：526,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 526 ----- 1
正在处理 526 ----- 2
正在处理 526 ----- 3
正在处理 526 ----- 4
正在处理 526 ----- 5
正在处理 526 ----- 6
正在处理 526 ----- 7
正在处理 526 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 526
============================

正在读取第 527 个DF
初始化batch数据： 527
batch数据 组装完毕 ：527
batch_tensor数据 组装完毕 ：527,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 527 ----- 1
正在处理 527 ----- 2
正在处理 527 ----- 3
正在处理 527 ----- 4
正在处理 527 ----- 5
正在处理 527 ----- 6
正在处理 527 ----- 7
正在处理 527 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 527
============================

正在读取第 528 个DF
初始化batch数据： 528
batch数据 组装完毕 ：528
batch_tensor数据 组装完毕 ：528,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 528 ----- 1
正在处理 528 ----- 2
正在处理 528 ----- 3
正在处理 528 ----- 4
正在处理 528 ----- 5
正在处理 528 ----- 6
正在处理 528 ----- 7
正在处理 528 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 528
============================

正在读取第 529 个DF
初始化batch数据： 529
batch数据 组装完毕 ：529
batch_tensor数据 组装完毕 ：529,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 529 ----- 1
正在处理 529 ----- 2
正在处理 529 ----- 3
正在处理 529 ----- 4
正在处理 529 ----- 5
正在处理 529 ----- 6
正在处理 529 ----- 7
正在处理 529 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 529
============================

正在读取第 530 个DF
初始化batch数据： 530
batch数据 组装完毕 ：530
batch_tensor数据 组装完毕 ：530,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 530 ----- 1
正在处理 530 ----- 2
正在处理 530 ----- 3
正在处理 530 ----- 4
正在处理 530 ----- 5
正在处理 530 ----- 6
正在处理 530 ----- 7
正在处理 530 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 530
============================

正在读取第 531 个DF
初始化batch数据： 531
batch数据 组装完毕 ：531
batch_tensor数据 组装完毕 ：531,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 531 ----- 1
正在处理 531 ----- 2
正在处理 531 ----- 3
正在处理 531 ----- 4
正在处理 531 ----- 5
正在处理 531 ----- 6
正在处理 531 ----- 7
正在处理 531 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 531
============================

正在读取第 532 个DF
初始化batch数据： 532
batch数据 组装完毕 ：532
batch_tensor数据 组装完毕 ：532,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 532 ----- 1
正在处理 532 ----- 2
正在处理 532 ----- 3
正在处理 532 ----- 4
正在处理 532 ----- 5
正在处理 532 ----- 6
正在处理 532 ----- 7
正在处理 532 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 532
============================

正在读取第 533 个DF
初始化batch数据： 533
batch数据 组装完毕 ：533
batch_tensor数据 组装完毕 ：533,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 533 ----- 1
正在处理 533 ----- 2
正在处理 533 ----- 3
正在处理 533 ----- 4
正在处理 533 ----- 5
正在处理 533 ----- 6
正在处理 533 ----- 7
正在处理 533 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 533
============================

正在读取第 534 个DF
初始化batch数据： 534
batch数据 组装完毕 ：534
batch_tensor数据 组装完毕 ：534,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 534 ----- 1
正在处理 534 ----- 2
正在处理 534 ----- 3
正在处理 534 ----- 4
正在处理 534 ----- 5
正在处理 534 ----- 6
正在处理 534 ----- 7
正在处理 534 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 534
============================

正在读取第 535 个DF
初始化batch数据： 535
batch数据 组装完毕 ：535
batch_tensor数据 组装完毕 ：535,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 535 ----- 1
正在处理 535 ----- 2
正在处理 535 ----- 3
正在处理 535 ----- 4
正在处理 535 ----- 5
正在处理 535 ----- 6
正在处理 535 ----- 7
正在处理 535 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 535
============================

正在读取第 536 个DF
初始化batch数据： 536
batch数据 组装完毕 ：536
batch_tensor数据 组装完毕 ：536,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 536 ----- 1
正在处理 536 ----- 2
正在处理 536 ----- 3
正在处理 536 ----- 4
正在处理 536 ----- 5
正在处理 536 ----- 6
正在处理 536 ----- 7
正在处理 536 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 536
============================

正在读取第 537 个DF
初始化batch数据： 537
batch数据 组装完毕 ：537
batch_tensor数据 组装完毕 ：537,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 537 ----- 1
正在处理 537 ----- 2
正在处理 537 ----- 3
正在处理 537 ----- 4
正在处理 537 ----- 5
正在处理 537 ----- 6
正在处理 537 ----- 7
正在处理 537 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 537
============================

正在读取第 538 个DF
初始化batch数据： 538
batch数据 组装完毕 ：538
batch_tensor数据 组装完毕 ：538,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 538 ----- 1
正在处理 538 ----- 2
正在处理 538 ----- 3
正在处理 538 ----- 4
正在处理 538 ----- 5
正在处理 538 ----- 6
正在处理 538 ----- 7
正在处理 538 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 538
============================

正在读取第 539 个DF
初始化batch数据： 539
batch数据 组装完毕 ：539
batch_tensor数据 组装完毕 ：539,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 539 ----- 1
正在处理 539 ----- 2
正在处理 539 ----- 3
正在处理 539 ----- 4
正在处理 539 ----- 5
正在处理 539 ----- 6
正在处理 539 ----- 7
正在处理 539 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 539
============================

正在读取第 540 个DF
初始化batch数据： 540
batch数据 组装完毕 ：540
batch_tensor数据 组装完毕 ：540,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 540 ----- 1
正在处理 540 ----- 2
正在处理 540 ----- 3
正在处理 540 ----- 4
正在处理 540 ----- 5
正在处理 540 ----- 6
正在处理 540 ----- 7
正在处理 540 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 540
============================

正在读取第 541 个DF
初始化batch数据： 541
batch数据 组装完毕 ：541
batch_tensor数据 组装完毕 ：541,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 541 ----- 1
正在处理 541 ----- 2
正在处理 541 ----- 3
正在处理 541 ----- 4
正在处理 541 ----- 5
正在处理 541 ----- 6
正在处理 541 ----- 7
正在处理 541 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 541
============================

正在读取第 542 个DF
初始化batch数据： 542
batch数据 组装完毕 ：542
batch_tensor数据 组装完毕 ：542,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 542 ----- 1
正在处理 542 ----- 2
正在处理 542 ----- 3
正在处理 542 ----- 4
正在处理 542 ----- 5
正在处理 542 ----- 6
正在处理 542 ----- 7
正在处理 542 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 542
============================

正在读取第 543 个DF
初始化batch数据： 543
batch数据 组装完毕 ：543
batch_tensor数据 组装完毕 ：543,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 543 ----- 1
正在处理 543 ----- 2
正在处理 543 ----- 3
正在处理 543 ----- 4
正在处理 543 ----- 5
正在处理 543 ----- 6
正在处理 543 ----- 7
正在处理 543 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 543
============================

正在读取第 544 个DF
初始化batch数据： 544
batch数据 组装完毕 ：544
batch_tensor数据 组装完毕 ：544,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 544 ----- 1
正在处理 544 ----- 2
正在处理 544 ----- 3
正在处理 544 ----- 4
正在处理 544 ----- 5
正在处理 544 ----- 6
正在处理 544 ----- 7
正在处理 544 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 544
============================

正在读取第 545 个DF
初始化batch数据： 545
batch数据 组装完毕 ：545
batch_tensor数据 组装完毕 ：545,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 545 ----- 1
正在处理 545 ----- 2
正在处理 545 ----- 3
正在处理 545 ----- 4
正在处理 545 ----- 5
正在处理 545 ----- 6
正在处理 545 ----- 7
正在处理 545 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 545
============================

正在读取第 546 个DF
初始化batch数据： 546
batch数据 组装完毕 ：546
batch_tensor数据 组装完毕 ：546,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 546 ----- 1
正在处理 546 ----- 2
正在处理 546 ----- 3
正在处理 546 ----- 4
正在处理 546 ----- 5
正在处理 546 ----- 6
正在处理 546 ----- 7
正在处理 546 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 546
============================

正在读取第 547 个DF
初始化batch数据： 547
batch数据 组装完毕 ：547
batch_tensor数据 组装完毕 ：547,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 547 ----- 1
正在处理 547 ----- 2
正在处理 547 ----- 3
正在处理 547 ----- 4
正在处理 547 ----- 5
正在处理 547 ----- 6
正在处理 547 ----- 7
正在处理 547 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 547
============================

正在读取第 548 个DF
初始化batch数据： 548
batch数据 组装完毕 ：548
batch_tensor数据 组装完毕 ：548,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 548 ----- 1
正在处理 548 ----- 2
正在处理 548 ----- 3
正在处理 548 ----- 4
正在处理 548 ----- 5
正在处理 548 ----- 6
正在处理 548 ----- 7
正在处理 548 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 548
============================

正在读取第 549 个DF
初始化batch数据： 549
batch数据 组装完毕 ：549
batch_tensor数据 组装完毕 ：549,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 549 ----- 1
正在处理 549 ----- 2
正在处理 549 ----- 3
正在处理 549 ----- 4
正在处理 549 ----- 5
正在处理 549 ----- 6
正在处理 549 ----- 7
正在处理 549 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 549
============================

正在读取第 550 个DF
初始化batch数据： 550
batch数据 组装完毕 ：550
batch_tensor数据 组装完毕 ：550,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 550 ----- 1
正在处理 550 ----- 2
正在处理 550 ----- 3
正在处理 550 ----- 4
正在处理 550 ----- 5
正在处理 550 ----- 6
正在处理 550 ----- 7
正在处理 550 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 550
============================

正在读取第 551 个DF
初始化batch数据： 551
batch数据 组装完毕 ：551
batch_tensor数据 组装完毕 ：551,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 551 ----- 1
正在处理 551 ----- 2
正在处理 551 ----- 3
正在处理 551 ----- 4
正在处理 551 ----- 5
正在处理 551 ----- 6
正在处理 551 ----- 7
正在处理 551 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 551
============================

正在读取第 552 个DF
初始化batch数据： 552
batch数据 组装完毕 ：552
batch_tensor数据 组装完毕 ：552,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 552 ----- 1
正在处理 552 ----- 2
正在处理 552 ----- 3
正在处理 552 ----- 4
正在处理 552 ----- 5
正在处理 552 ----- 6
正在处理 552 ----- 7
正在处理 552 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 552
============================

正在读取第 553 个DF
初始化batch数据： 553
batch数据 组装完毕 ：553
batch_tensor数据 组装完毕 ：553,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 553 ----- 1
正在处理 553 ----- 2
正在处理 553 ----- 3
正在处理 553 ----- 4
正在处理 553 ----- 5
正在处理 553 ----- 6
正在处理 553 ----- 7
正在处理 553 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 553
============================

正在读取第 554 个DF
初始化batch数据： 554
batch数据 组装完毕 ：554
batch_tensor数据 组装完毕 ：554,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 554 ----- 1
正在处理 554 ----- 2
正在处理 554 ----- 3
正在处理 554 ----- 4
正在处理 554 ----- 5
正在处理 554 ----- 6
正在处理 554 ----- 7
正在处理 554 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 554
============================

正在读取第 555 个DF
初始化batch数据： 555
batch数据 组装完毕 ：555
batch_tensor数据 组装完毕 ：555,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 555 ----- 1
正在处理 555 ----- 2
正在处理 555 ----- 3
正在处理 555 ----- 4
正在处理 555 ----- 5
正在处理 555 ----- 6
正在处理 555 ----- 7
正在处理 555 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 555
============================

正在读取第 556 个DF
初始化batch数据： 556
batch数据 组装完毕 ：556
batch_tensor数据 组装完毕 ：556,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 556 ----- 1
正在处理 556 ----- 2
正在处理 556 ----- 3
正在处理 556 ----- 4
正在处理 556 ----- 5
正在处理 556 ----- 6
正在处理 556 ----- 7
正在处理 556 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 556
============================

正在读取第 557 个DF
初始化batch数据： 557
batch数据 组装完毕 ：557
batch_tensor数据 组装完毕 ：557,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 557 ----- 1
正在处理 557 ----- 2
正在处理 557 ----- 3
正在处理 557 ----- 4
正在处理 557 ----- 5
正在处理 557 ----- 6
正在处理 557 ----- 7
正在处理 557 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 557
============================

正在读取第 558 个DF
初始化batch数据： 558
batch数据 组装完毕 ：558
batch_tensor数据 组装完毕 ：558,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 558 ----- 1
正在处理 558 ----- 2
正在处理 558 ----- 3
正在处理 558 ----- 4
正在处理 558 ----- 5
正在处理 558 ----- 6
正在处理 558 ----- 7
正在处理 558 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 558
============================

正在读取第 559 个DF
初始化batch数据： 559
batch数据 组装完毕 ：559
batch_tensor数据 组装完毕 ：559,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 559 ----- 1
正在处理 559 ----- 2
正在处理 559 ----- 3
正在处理 559 ----- 4
正在处理 559 ----- 5
正在处理 559 ----- 6
正在处理 559 ----- 7
正在处理 559 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 559
============================

正在读取第 560 个DF
初始化batch数据： 560
batch数据 组装完毕 ：560
batch_tensor数据 组装完毕 ：560,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 560 ----- 1
正在处理 560 ----- 2
正在处理 560 ----- 3
正在处理 560 ----- 4
正在处理 560 ----- 5
正在处理 560 ----- 6
正在处理 560 ----- 7
正在处理 560 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 560
============================

正在读取第 561 个DF
初始化batch数据： 561
batch数据 组装完毕 ：561
batch_tensor数据 组装完毕 ：561,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 561 ----- 1
正在处理 561 ----- 2
正在处理 561 ----- 3
正在处理 561 ----- 4
正在处理 561 ----- 5
正在处理 561 ----- 6
正在处理 561 ----- 7
正在处理 561 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 561
============================

正在读取第 562 个DF
初始化batch数据： 562
batch数据 组装完毕 ：562
batch_tensor数据 组装完毕 ：562,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 562 ----- 1
正在处理 562 ----- 2
正在处理 562 ----- 3
正在处理 562 ----- 4
正在处理 562 ----- 5
正在处理 562 ----- 6
正在处理 562 ----- 7
正在处理 562 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 562
============================

正在读取第 563 个DF
初始化batch数据： 563
batch数据 组装完毕 ：563
batch_tensor数据 组装完毕 ：563,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 563 ----- 1
正在处理 563 ----- 2
正在处理 563 ----- 3
正在处理 563 ----- 4
正在处理 563 ----- 5
正在处理 563 ----- 6
正在处理 563 ----- 7
正在处理 563 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 563
============================

正在读取第 564 个DF
初始化batch数据： 564
batch数据 组装完毕 ：564
batch_tensor数据 组装完毕 ：564,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 564 ----- 1
正在处理 564 ----- 2
正在处理 564 ----- 3
正在处理 564 ----- 4
正在处理 564 ----- 5
正在处理 564 ----- 6
正在处理 564 ----- 7
正在处理 564 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 564
============================

正在读取第 565 个DF
初始化batch数据： 565
batch数据 组装完毕 ：565
batch_tensor数据 组装完毕 ：565,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 565 ----- 1
正在处理 565 ----- 2
正在处理 565 ----- 3
正在处理 565 ----- 4
正在处理 565 ----- 5
正在处理 565 ----- 6
正在处理 565 ----- 7
正在处理 565 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 565
============================

正在读取第 566 个DF
初始化batch数据： 566
batch数据 组装完毕 ：566
batch_tensor数据 组装完毕 ：566,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 566 ----- 1
正在处理 566 ----- 2
正在处理 566 ----- 3
正在处理 566 ----- 4
正在处理 566 ----- 5
正在处理 566 ----- 6
正在处理 566 ----- 7
正在处理 566 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 566
============================

正在读取第 567 个DF
初始化batch数据： 567
batch数据 组装完毕 ：567
batch_tensor数据 组装完毕 ：567,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 567 ----- 1
正在处理 567 ----- 2
正在处理 567 ----- 3
正在处理 567 ----- 4
正在处理 567 ----- 5
正在处理 567 ----- 6
正在处理 567 ----- 7
正在处理 567 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 567
============================

正在读取第 568 个DF
初始化batch数据： 568
batch数据 组装完毕 ：568
batch_tensor数据 组装完毕 ：568,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 568 ----- 1
正在处理 568 ----- 2
正在处理 568 ----- 3
正在处理 568 ----- 4
正在处理 568 ----- 5
正在处理 568 ----- 6
正在处理 568 ----- 7
正在处理 568 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 568
============================

正在读取第 569 个DF
初始化batch数据： 569
batch数据 组装完毕 ：569
batch_tensor数据 组装完毕 ：569,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 569 ----- 1
正在处理 569 ----- 2
正在处理 569 ----- 3
正在处理 569 ----- 4
正在处理 569 ----- 5
正在处理 569 ----- 6
正在处理 569 ----- 7
正在处理 569 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 569
============================

正在读取第 570 个DF
初始化batch数据： 570
batch数据 组装完毕 ：570
batch_tensor数据 组装完毕 ：570,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 570 ----- 1
正在处理 570 ----- 2
正在处理 570 ----- 3
正在处理 570 ----- 4
正在处理 570 ----- 5
正在处理 570 ----- 6
正在处理 570 ----- 7
正在处理 570 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 570
============================

正在读取第 571 个DF
初始化batch数据： 571
batch数据 组装完毕 ：571
batch_tensor数据 组装完毕 ：571,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 571 ----- 1
正在处理 571 ----- 2
正在处理 571 ----- 3
正在处理 571 ----- 4
正在处理 571 ----- 5
正在处理 571 ----- 6
正在处理 571 ----- 7
正在处理 571 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 571
============================

正在读取第 572 个DF
初始化batch数据： 572
batch数据 组装完毕 ：572
batch_tensor数据 组装完毕 ：572,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 572 ----- 1
正在处理 572 ----- 2
正在处理 572 ----- 3
正在处理 572 ----- 4
正在处理 572 ----- 5
正在处理 572 ----- 6
正在处理 572 ----- 7
正在处理 572 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 572
============================

正在读取第 573 个DF
初始化batch数据： 573
batch数据 组装完毕 ：573
batch_tensor数据 组装完毕 ：573,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 573 ----- 1
正在处理 573 ----- 2
正在处理 573 ----- 3
正在处理 573 ----- 4
正在处理 573 ----- 5
正在处理 573 ----- 6
正在处理 573 ----- 7
正在处理 573 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 573
============================

正在读取第 574 个DF
初始化batch数据： 574
batch数据 组装完毕 ：574
batch_tensor数据 组装完毕 ：574,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 574 ----- 1
正在处理 574 ----- 2
正在处理 574 ----- 3
正在处理 574 ----- 4
正在处理 574 ----- 5
正在处理 574 ----- 6
正在处理 574 ----- 7
正在处理 574 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 574
============================

正在读取第 575 个DF
初始化batch数据： 575
batch数据 组装完毕 ：575
batch_tensor数据 组装完毕 ：575,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 575 ----- 1
正在处理 575 ----- 2
正在处理 575 ----- 3
正在处理 575 ----- 4
正在处理 575 ----- 5
正在处理 575 ----- 6
正在处理 575 ----- 7
正在处理 575 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 575
============================

正在读取第 576 个DF
初始化batch数据： 576
batch数据 组装完毕 ：576
batch_tensor数据 组装完毕 ：576,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 576 ----- 1
正在处理 576 ----- 2
正在处理 576 ----- 3
正在处理 576 ----- 4
正在处理 576 ----- 5
正在处理 576 ----- 6
正在处理 576 ----- 7
正在处理 576 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 576
============================

正在读取第 577 个DF
初始化batch数据： 577
batch数据 组装完毕 ：577
batch_tensor数据 组装完毕 ：577,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 577 ----- 1
正在处理 577 ----- 2
正在处理 577 ----- 3
正在处理 577 ----- 4
正在处理 577 ----- 5
正在处理 577 ----- 6
正在处理 577 ----- 7
正在处理 577 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 577
============================

正在读取第 578 个DF
初始化batch数据： 578
batch数据 组装完毕 ：578
batch_tensor数据 组装完毕 ：578,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 578 ----- 1
正在处理 578 ----- 2
正在处理 578 ----- 3
正在处理 578 ----- 4
正在处理 578 ----- 5
正在处理 578 ----- 6
正在处理 578 ----- 7
正在处理 578 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 578
============================

正在读取第 579 个DF
初始化batch数据： 579
batch数据 组装完毕 ：579
batch_tensor数据 组装完毕 ：579,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 579 ----- 1
正在处理 579 ----- 2
正在处理 579 ----- 3
正在处理 579 ----- 4
正在处理 579 ----- 5
正在处理 579 ----- 6
正在处理 579 ----- 7
正在处理 579 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 579
============================

正在读取第 580 个DF
初始化batch数据： 580
batch数据 组装完毕 ：580
batch_tensor数据 组装完毕 ：580,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 580 ----- 1
正在处理 580 ----- 2
正在处理 580 ----- 3
正在处理 580 ----- 4
正在处理 580 ----- 5
正在处理 580 ----- 6
正在处理 580 ----- 7
正在处理 580 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 580
============================

正在读取第 581 个DF
初始化batch数据： 581
batch数据 组装完毕 ：581
batch_tensor数据 组装完毕 ：581,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 581 ----- 1
正在处理 581 ----- 2
正在处理 581 ----- 3
正在处理 581 ----- 4
正在处理 581 ----- 5
正在处理 581 ----- 6
正在处理 581 ----- 7
正在处理 581 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 581
============================

正在读取第 582 个DF
初始化batch数据： 582
batch数据 组装完毕 ：582
batch_tensor数据 组装完毕 ：582,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 582 ----- 1
正在处理 582 ----- 2
正在处理 582 ----- 3
正在处理 582 ----- 4
正在处理 582 ----- 5
正在处理 582 ----- 6
正在处理 582 ----- 7
正在处理 582 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 582
============================

正在读取第 583 个DF
初始化batch数据： 583
batch数据 组装完毕 ：583
batch_tensor数据 组装完毕 ：583,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 583 ----- 1
正在处理 583 ----- 2
正在处理 583 ----- 3
正在处理 583 ----- 4
正在处理 583 ----- 5
正在处理 583 ----- 6
正在处理 583 ----- 7
正在处理 583 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 583
============================

正在读取第 584 个DF
初始化batch数据： 584
batch数据 组装完毕 ：584
batch_tensor数据 组装完毕 ：584,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 584 ----- 1
正在处理 584 ----- 2
正在处理 584 ----- 3
正在处理 584 ----- 4
正在处理 584 ----- 5
正在处理 584 ----- 6
正在处理 584 ----- 7
正在处理 584 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 584
============================

正在读取第 585 个DF
初始化batch数据： 585
batch数据 组装完毕 ：585
batch_tensor数据 组装完毕 ：585,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 585 ----- 1
正在处理 585 ----- 2
正在处理 585 ----- 3
正在处理 585 ----- 4
正在处理 585 ----- 5
正在处理 585 ----- 6
正在处理 585 ----- 7
正在处理 585 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 585
============================

正在读取第 586 个DF
初始化batch数据： 586
batch数据 组装完毕 ：586
batch_tensor数据 组装完毕 ：586,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 586 ----- 1
正在处理 586 ----- 2
正在处理 586 ----- 3
正在处理 586 ----- 4
正在处理 586 ----- 5
正在处理 586 ----- 6
正在处理 586 ----- 7
正在处理 586 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 586
============================

正在读取第 587 个DF
初始化batch数据： 587
batch数据 组装完毕 ：587
batch_tensor数据 组装完毕 ：587,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 587 ----- 1
正在处理 587 ----- 2
正在处理 587 ----- 3
正在处理 587 ----- 4
正在处理 587 ----- 5
正在处理 587 ----- 6
正在处理 587 ----- 7
正在处理 587 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 587
============================

正在读取第 588 个DF
初始化batch数据： 588
batch数据 组装完毕 ：588
batch_tensor数据 组装完毕 ：588,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 588 ----- 1
正在处理 588 ----- 2
正在处理 588 ----- 3
正在处理 588 ----- 4
正在处理 588 ----- 5
正在处理 588 ----- 6
正在处理 588 ----- 7
正在处理 588 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 588
============================

正在读取第 589 个DF
初始化batch数据： 589
batch数据 组装完毕 ：589
batch_tensor数据 组装完毕 ：589,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 589 ----- 1
正在处理 589 ----- 2
正在处理 589 ----- 3
正在处理 589 ----- 4
正在处理 589 ----- 5
正在处理 589 ----- 6
正在处理 589 ----- 7
正在处理 589 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 589
============================

正在读取第 590 个DF
初始化batch数据： 590
batch数据 组装完毕 ：590
batch_tensor数据 组装完毕 ：590,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 590 ----- 1
正在处理 590 ----- 2
正在处理 590 ----- 3
正在处理 590 ----- 4
正在处理 590 ----- 5
正在处理 590 ----- 6
正在处理 590 ----- 7
正在处理 590 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 590
============================

正在读取第 591 个DF
初始化batch数据： 591
batch数据 组装完毕 ：591
batch_tensor数据 组装完毕 ：591,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 591 ----- 1
正在处理 591 ----- 2
正在处理 591 ----- 3
正在处理 591 ----- 4
正在处理 591 ----- 5
正在处理 591 ----- 6
正在处理 591 ----- 7
正在处理 591 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 591
============================

正在读取第 592 个DF
初始化batch数据： 592
batch数据 组装完毕 ：592
batch_tensor数据 组装完毕 ：592,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 592 ----- 1
正在处理 592 ----- 2
正在处理 592 ----- 3
正在处理 592 ----- 4
正在处理 592 ----- 5
正在处理 592 ----- 6
正在处理 592 ----- 7
正在处理 592 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 592
============================

正在读取第 593 个DF
初始化batch数据： 593
batch数据 组装完毕 ：593
batch_tensor数据 组装完毕 ：593,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 593 ----- 1
正在处理 593 ----- 2
正在处理 593 ----- 3
正在处理 593 ----- 4
正在处理 593 ----- 5
正在处理 593 ----- 6
正在处理 593 ----- 7
正在处理 593 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 593
============================

正在读取第 594 个DF
初始化batch数据： 594
batch数据 组装完毕 ：594
batch_tensor数据 组装完毕 ：594,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 594 ----- 1
正在处理 594 ----- 2
正在处理 594 ----- 3
正在处理 594 ----- 4
正在处理 594 ----- 5
正在处理 594 ----- 6
正在处理 594 ----- 7
正在处理 594 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 594
============================

正在读取第 595 个DF
初始化batch数据： 595
batch数据 组装完毕 ：595
batch_tensor数据 组装完毕 ：595,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 595 ----- 1
正在处理 595 ----- 2
正在处理 595 ----- 3
正在处理 595 ----- 4
正在处理 595 ----- 5
正在处理 595 ----- 6
正在处理 595 ----- 7
正在处理 595 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 595
============================

正在读取第 596 个DF
初始化batch数据： 596
batch数据 组装完毕 ：596
batch_tensor数据 组装完毕 ：596,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 596 ----- 1
正在处理 596 ----- 2
正在处理 596 ----- 3
正在处理 596 ----- 4
正在处理 596 ----- 5
正在处理 596 ----- 6
正在处理 596 ----- 7
正在处理 596 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 596
============================

正在读取第 597 个DF
初始化batch数据： 597
batch数据 组装完毕 ：597
batch_tensor数据 组装完毕 ：597,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 597 ----- 1
正在处理 597 ----- 2
正在处理 597 ----- 3
正在处理 597 ----- 4
正在处理 597 ----- 5
正在处理 597 ----- 6
正在处理 597 ----- 7
正在处理 597 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 597
============================

正在读取第 598 个DF
初始化batch数据： 598
batch数据 组装完毕 ：598
batch_tensor数据 组装完毕 ：598,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 598 ----- 1
正在处理 598 ----- 2
正在处理 598 ----- 3
正在处理 598 ----- 4
正在处理 598 ----- 5
正在处理 598 ----- 6
正在处理 598 ----- 7
正在处理 598 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 598
============================

正在读取第 599 个DF
初始化batch数据： 599
batch数据 组装完毕 ：599
batch_tensor数据 组装完毕 ：599,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 599 ----- 1
正在处理 599 ----- 2
正在处理 599 ----- 3
正在处理 599 ----- 4
正在处理 599 ----- 5
正在处理 599 ----- 6
正在处理 599 ----- 7
正在处理 599 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 599
============================

正在读取第 600 个DF
初始化batch数据： 600
batch数据 组装完毕 ：600
batch_tensor数据 组装完毕 ：600,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 600 ----- 1
正在处理 600 ----- 2
正在处理 600 ----- 3
正在处理 600 ----- 4
正在处理 600 ----- 5
正在处理 600 ----- 6
正在处理 600 ----- 7
正在处理 600 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 600
============================

正在读取第 601 个DF
初始化batch数据： 601
batch数据 组装完毕 ：601
batch_tensor数据 组装完毕 ：601,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 601 ----- 1
正在处理 601 ----- 2
正在处理 601 ----- 3
正在处理 601 ----- 4
正在处理 601 ----- 5
正在处理 601 ----- 6
正在处理 601 ----- 7
正在处理 601 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 601
============================

正在读取第 602 个DF
初始化batch数据： 602
batch数据 组装完毕 ：602
batch_tensor数据 组装完毕 ：602,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 602 ----- 1
正在处理 602 ----- 2
正在处理 602 ----- 3
正在处理 602 ----- 4
正在处理 602 ----- 5
正在处理 602 ----- 6
正在处理 602 ----- 7
正在处理 602 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 602
============================

正在读取第 603 个DF
初始化batch数据： 603
batch数据 组装完毕 ：603
batch_tensor数据 组装完毕 ：603,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 603 ----- 1
正在处理 603 ----- 2
正在处理 603 ----- 3
正在处理 603 ----- 4
正在处理 603 ----- 5
正在处理 603 ----- 6
正在处理 603 ----- 7
正在处理 603 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 603
============================

正在读取第 604 个DF
初始化batch数据： 604
batch数据 组装完毕 ：604
batch_tensor数据 组装完毕 ：604,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 604 ----- 1
正在处理 604 ----- 2
正在处理 604 ----- 3
正在处理 604 ----- 4
正在处理 604 ----- 5
正在处理 604 ----- 6
正在处理 604 ----- 7
正在处理 604 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 604
============================

正在读取第 605 个DF
初始化batch数据： 605
batch数据 组装完毕 ：605
batch_tensor数据 组装完毕 ：605,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 605 ----- 1
正在处理 605 ----- 2
正在处理 605 ----- 3
正在处理 605 ----- 4
正在处理 605 ----- 5
正在处理 605 ----- 6
正在处理 605 ----- 7
正在处理 605 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 605
============================

正在读取第 606 个DF
初始化batch数据： 606
batch数据 组装完毕 ：606
batch_tensor数据 组装完毕 ：606,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 606 ----- 1
正在处理 606 ----- 2
正在处理 606 ----- 3
正在处理 606 ----- 4
正在处理 606 ----- 5
正在处理 606 ----- 6
正在处理 606 ----- 7
正在处理 606 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 606
============================

正在读取第 607 个DF
初始化batch数据： 607
batch数据 组装完毕 ：607
batch_tensor数据 组装完毕 ：607,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 607 ----- 1
正在处理 607 ----- 2
正在处理 607 ----- 3
正在处理 607 ----- 4
正在处理 607 ----- 5
正在处理 607 ----- 6
正在处理 607 ----- 7
正在处理 607 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 607
============================

正在读取第 608 个DF
初始化batch数据： 608
batch数据 组装完毕 ：608
batch_tensor数据 组装完毕 ：608,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 608 ----- 1
正在处理 608 ----- 2
正在处理 608 ----- 3
正在处理 608 ----- 4
正在处理 608 ----- 5
正在处理 608 ----- 6
正在处理 608 ----- 7
正在处理 608 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 608
============================

正在读取第 609 个DF
初始化batch数据： 609
batch数据 组装完毕 ：609
batch_tensor数据 组装完毕 ：609,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 609 ----- 1
正在处理 609 ----- 2
正在处理 609 ----- 3
正在处理 609 ----- 4
正在处理 609 ----- 5
正在处理 609 ----- 6
正在处理 609 ----- 7
正在处理 609 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 609
============================

正在读取第 610 个DF
初始化batch数据： 610
batch数据 组装完毕 ：610
batch_tensor数据 组装完毕 ：610,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 610 ----- 1
正在处理 610 ----- 2
正在处理 610 ----- 3
正在处理 610 ----- 4
正在处理 610 ----- 5
正在处理 610 ----- 6
正在处理 610 ----- 7
正在处理 610 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 610
============================

正在读取第 611 个DF
初始化batch数据： 611
batch数据 组装完毕 ：611
batch_tensor数据 组装完毕 ：611,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 611 ----- 1
正在处理 611 ----- 2
正在处理 611 ----- 3
正在处理 611 ----- 4
正在处理 611 ----- 5
正在处理 611 ----- 6
正在处理 611 ----- 7
正在处理 611 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 611
============================

正在读取第 612 个DF
初始化batch数据： 612
batch数据 组装完毕 ：612
batch_tensor数据 组装完毕 ：612,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 612 ----- 1
正在处理 612 ----- 2
正在处理 612 ----- 3
正在处理 612 ----- 4
正在处理 612 ----- 5
正在处理 612 ----- 6
正在处理 612 ----- 7
正在处理 612 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 612
============================

正在读取第 613 个DF
初始化batch数据： 613
batch数据 组装完毕 ：613
batch_tensor数据 组装完毕 ：613,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 613 ----- 1
正在处理 613 ----- 2
正在处理 613 ----- 3
正在处理 613 ----- 4
正在处理 613 ----- 5
正在处理 613 ----- 6
正在处理 613 ----- 7
正在处理 613 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 613
============================

正在读取第 614 个DF
初始化batch数据： 614
batch数据 组装完毕 ：614
batch_tensor数据 组装完毕 ：614,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 614 ----- 1
正在处理 614 ----- 2
正在处理 614 ----- 3
正在处理 614 ----- 4
正在处理 614 ----- 5
正在处理 614 ----- 6
正在处理 614 ----- 7
正在处理 614 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 614
============================

正在读取第 615 个DF
初始化batch数据： 615
batch数据 组装完毕 ：615
batch_tensor数据 组装完毕 ：615,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 615 ----- 1
正在处理 615 ----- 2
正在处理 615 ----- 3
正在处理 615 ----- 4
正在处理 615 ----- 5
正在处理 615 ----- 6
正在处理 615 ----- 7
正在处理 615 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 615
============================

正在读取第 616 个DF
初始化batch数据： 616
batch数据 组装完毕 ：616
batch_tensor数据 组装完毕 ：616,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 616 ----- 1
正在处理 616 ----- 2
正在处理 616 ----- 3
正在处理 616 ----- 4
正在处理 616 ----- 5
正在处理 616 ----- 6
正在处理 616 ----- 7
正在处理 616 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 616
============================

正在读取第 617 个DF
初始化batch数据： 617
batch数据 组装完毕 ：617
batch_tensor数据 组装完毕 ：617,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 617 ----- 1
正在处理 617 ----- 2
正在处理 617 ----- 3
正在处理 617 ----- 4
正在处理 617 ----- 5
正在处理 617 ----- 6
正在处理 617 ----- 7
正在处理 617 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 617
============================

正在读取第 618 个DF
初始化batch数据： 618
batch数据 组装完毕 ：618
batch_tensor数据 组装完毕 ：618,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 618 ----- 1
正在处理 618 ----- 2
正在处理 618 ----- 3
正在处理 618 ----- 4
正在处理 618 ----- 5
正在处理 618 ----- 6
正在处理 618 ----- 7
正在处理 618 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 618
============================

正在读取第 619 个DF
初始化batch数据： 619
batch数据 组装完毕 ：619
batch_tensor数据 组装完毕 ：619,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 619 ----- 1
正在处理 619 ----- 2
正在处理 619 ----- 3
正在处理 619 ----- 4
正在处理 619 ----- 5
正在处理 619 ----- 6
正在处理 619 ----- 7
正在处理 619 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 619
============================

正在读取第 620 个DF
初始化batch数据： 620
batch数据 组装完毕 ：620
batch_tensor数据 组装完毕 ：620,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 620 ----- 1
正在处理 620 ----- 2
正在处理 620 ----- 3
正在处理 620 ----- 4
正在处理 620 ----- 5
正在处理 620 ----- 6
正在处理 620 ----- 7
正在处理 620 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 620
============================

正在读取第 621 个DF
初始化batch数据： 621
batch数据 组装完毕 ：621
batch_tensor数据 组装完毕 ：621,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 621 ----- 1
正在处理 621 ----- 2
正在处理 621 ----- 3
正在处理 621 ----- 4
正在处理 621 ----- 5
正在处理 621 ----- 6
正在处理 621 ----- 7
正在处理 621 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 621
============================

正在读取第 622 个DF
初始化batch数据： 622
batch数据 组装完毕 ：622
batch_tensor数据 组装完毕 ：622,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 622 ----- 1
正在处理 622 ----- 2
正在处理 622 ----- 3
正在处理 622 ----- 4
正在处理 622 ----- 5
正在处理 622 ----- 6
正在处理 622 ----- 7
正在处理 622 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 622
============================

正在读取第 623 个DF
初始化batch数据： 623
batch数据 组装完毕 ：623
batch_tensor数据 组装完毕 ：623,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 623 ----- 1
正在处理 623 ----- 2
正在处理 623 ----- 3
正在处理 623 ----- 4
正在处理 623 ----- 5
正在处理 623 ----- 6
正在处理 623 ----- 7
正在处理 623 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 623
============================

正在读取第 624 个DF
初始化batch数据： 624
batch数据 组装完毕 ：624
batch_tensor数据 组装完毕 ：624,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 624 ----- 1
正在处理 624 ----- 2
正在处理 624 ----- 3
正在处理 624 ----- 4
正在处理 624 ----- 5
正在处理 624 ----- 6
正在处理 624 ----- 7
正在处理 624 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 624
============================

正在读取第 625 个DF
初始化batch数据： 625
batch数据 组装完毕 ：625
batch_tensor数据 组装完毕 ：625,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 625 ----- 1
正在处理 625 ----- 2
正在处理 625 ----- 3
正在处理 625 ----- 4
正在处理 625 ----- 5
正在处理 625 ----- 6
正在处理 625 ----- 7
正在处理 625 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 625
============================

正在读取第 626 个DF
初始化batch数据： 626
batch数据 组装完毕 ：626
batch_tensor数据 组装完毕 ：626,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 626 ----- 1
正在处理 626 ----- 2
正在处理 626 ----- 3
正在处理 626 ----- 4
正在处理 626 ----- 5
正在处理 626 ----- 6
正在处理 626 ----- 7
正在处理 626 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 626
============================

正在读取第 627 个DF
初始化batch数据： 627
batch数据 组装完毕 ：627
batch_tensor数据 组装完毕 ：627,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 627 ----- 1
正在处理 627 ----- 2
正在处理 627 ----- 3
正在处理 627 ----- 4
正在处理 627 ----- 5
正在处理 627 ----- 6
正在处理 627 ----- 7
正在处理 627 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 627
============================

正在读取第 628 个DF
初始化batch数据： 628
batch数据 组装完毕 ：628
batch_tensor数据 组装完毕 ：628,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 628 ----- 1
正在处理 628 ----- 2
正在处理 628 ----- 3
正在处理 628 ----- 4
正在处理 628 ----- 5
正在处理 628 ----- 6
正在处理 628 ----- 7
正在处理 628 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 628
============================

正在读取第 629 个DF
初始化batch数据： 629
batch数据 组装完毕 ：629
batch_tensor数据 组装完毕 ：629,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 629 ----- 1
正在处理 629 ----- 2
正在处理 629 ----- 3
正在处理 629 ----- 4
正在处理 629 ----- 5
正在处理 629 ----- 6
正在处理 629 ----- 7
正在处理 629 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 629
============================

正在读取第 630 个DF
初始化batch数据： 630
batch数据 组装完毕 ：630
batch_tensor数据 组装完毕 ：630,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 630 ----- 1
正在处理 630 ----- 2
正在处理 630 ----- 3
正在处理 630 ----- 4
正在处理 630 ----- 5
正在处理 630 ----- 6
正在处理 630 ----- 7
正在处理 630 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 630
============================

正在读取第 631 个DF
初始化batch数据： 631
batch数据 组装完毕 ：631
batch_tensor数据 组装完毕 ：631,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 631 ----- 1
正在处理 631 ----- 2
正在处理 631 ----- 3
正在处理 631 ----- 4
正在处理 631 ----- 5
正在处理 631 ----- 6
正在处理 631 ----- 7
正在处理 631 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 631
============================

正在读取第 632 个DF
初始化batch数据： 632
batch数据 组装完毕 ：632
batch_tensor数据 组装完毕 ：632,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 632 ----- 1
正在处理 632 ----- 2
正在处理 632 ----- 3
正在处理 632 ----- 4
正在处理 632 ----- 5
正在处理 632 ----- 6
正在处理 632 ----- 7
正在处理 632 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 632
============================

正在读取第 633 个DF
初始化batch数据： 633
batch数据 组装完毕 ：633
batch_tensor数据 组装完毕 ：633,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 633 ----- 1
正在处理 633 ----- 2
正在处理 633 ----- 3
正在处理 633 ----- 4
正在处理 633 ----- 5
正在处理 633 ----- 6
正在处理 633 ----- 7
正在处理 633 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 633
============================

正在读取第 634 个DF
初始化batch数据： 634
batch数据 组装完毕 ：634
batch_tensor数据 组装完毕 ：634,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 634 ----- 1
正在处理 634 ----- 2
正在处理 634 ----- 3
正在处理 634 ----- 4
正在处理 634 ----- 5
正在处理 634 ----- 6
正在处理 634 ----- 7
正在处理 634 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 634
============================

正在读取第 635 个DF
初始化batch数据： 635
batch数据 组装完毕 ：635
batch_tensor数据 组装完毕 ：635,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 635 ----- 1
正在处理 635 ----- 2
正在处理 635 ----- 3
正在处理 635 ----- 4
正在处理 635 ----- 5
正在处理 635 ----- 6
正在处理 635 ----- 7
正在处理 635 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 635
============================

正在读取第 636 个DF
初始化batch数据： 636
batch数据 组装完毕 ：636
batch_tensor数据 组装完毕 ：636,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 636 ----- 1
正在处理 636 ----- 2
正在处理 636 ----- 3
正在处理 636 ----- 4
正在处理 636 ----- 5
正在处理 636 ----- 6
正在处理 636 ----- 7
正在处理 636 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 636
============================

正在读取第 637 个DF
初始化batch数据： 637
batch数据 组装完毕 ：637
batch_tensor数据 组装完毕 ：637,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 637 ----- 1
正在处理 637 ----- 2
正在处理 637 ----- 3
正在处理 637 ----- 4
正在处理 637 ----- 5
正在处理 637 ----- 6
正在处理 637 ----- 7
正在处理 637 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 637
============================

正在读取第 638 个DF
初始化batch数据： 638
batch数据 组装完毕 ：638
batch_tensor数据 组装完毕 ：638,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 638 ----- 1
正在处理 638 ----- 2
正在处理 638 ----- 3
正在处理 638 ----- 4
正在处理 638 ----- 5
正在处理 638 ----- 6
正在处理 638 ----- 7
正在处理 638 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 638
============================

正在读取第 639 个DF
初始化batch数据： 639
batch数据 组装完毕 ：639
batch_tensor数据 组装完毕 ：639,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 639 ----- 1
正在处理 639 ----- 2
正在处理 639 ----- 3
正在处理 639 ----- 4
正在处理 639 ----- 5
正在处理 639 ----- 6
正在处理 639 ----- 7
正在处理 639 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 639
============================

正在读取第 640 个DF
初始化batch数据： 640
batch数据 组装完毕 ：640
batch_tensor数据 组装完毕 ：640,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 640 ----- 1
正在处理 640 ----- 2
正在处理 640 ----- 3
正在处理 640 ----- 4
正在处理 640 ----- 5
正在处理 640 ----- 6
正在处理 640 ----- 7
正在处理 640 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 640
============================

正在读取第 641 个DF
初始化batch数据： 641
batch数据 组装完毕 ：641
batch_tensor数据 组装完毕 ：641,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 641 ----- 1
正在处理 641 ----- 2
正在处理 641 ----- 3
正在处理 641 ----- 4
正在处理 641 ----- 5
正在处理 641 ----- 6
正在处理 641 ----- 7
正在处理 641 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 641
============================

正在读取第 642 个DF
初始化batch数据： 642
batch数据 组装完毕 ：642
batch_tensor数据 组装完毕 ：642,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 642 ----- 1
正在处理 642 ----- 2
正在处理 642 ----- 3
正在处理 642 ----- 4
正在处理 642 ----- 5
正在处理 642 ----- 6
正在处理 642 ----- 7
正在处理 642 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 642
============================

正在读取第 643 个DF
初始化batch数据： 643
batch数据 组装完毕 ：643
batch_tensor数据 组装完毕 ：643,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 643 ----- 1
正在处理 643 ----- 2
正在处理 643 ----- 3
正在处理 643 ----- 4
正在处理 643 ----- 5
正在处理 643 ----- 6
正在处理 643 ----- 7
正在处理 643 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 643
============================

正在读取第 644 个DF
初始化batch数据： 644
batch数据 组装完毕 ：644
batch_tensor数据 组装完毕 ：644,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 644 ----- 1
正在处理 644 ----- 2
正在处理 644 ----- 3
正在处理 644 ----- 4
正在处理 644 ----- 5
正在处理 644 ----- 6
正在处理 644 ----- 7
正在处理 644 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 644
============================

正在读取第 645 个DF
初始化batch数据： 645
batch数据 组装完毕 ：645
batch_tensor数据 组装完毕 ：645,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 645 ----- 1
正在处理 645 ----- 2
正在处理 645 ----- 3
正在处理 645 ----- 4
正在处理 645 ----- 5
正在处理 645 ----- 6
正在处理 645 ----- 7
正在处理 645 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 645
============================

正在读取第 646 个DF
初始化batch数据： 646
batch数据 组装完毕 ：646
batch_tensor数据 组装完毕 ：646,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 646 ----- 1
正在处理 646 ----- 2
正在处理 646 ----- 3
正在处理 646 ----- 4
正在处理 646 ----- 5
正在处理 646 ----- 6
正在处理 646 ----- 7
正在处理 646 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 646
============================

正在读取第 647 个DF
初始化batch数据： 647
batch数据 组装完毕 ：647
batch_tensor数据 组装完毕 ：647,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 647 ----- 1
正在处理 647 ----- 2
正在处理 647 ----- 3
正在处理 647 ----- 4
正在处理 647 ----- 5
正在处理 647 ----- 6
正在处理 647 ----- 7
正在处理 647 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 647
============================

正在读取第 648 个DF
初始化batch数据： 648
batch数据 组装完毕 ：648
batch_tensor数据 组装完毕 ：648,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 648 ----- 1
正在处理 648 ----- 2
正在处理 648 ----- 3
正在处理 648 ----- 4
正在处理 648 ----- 5
正在处理 648 ----- 6
正在处理 648 ----- 7
正在处理 648 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 648
============================

正在读取第 649 个DF
初始化batch数据： 649
batch数据 组装完毕 ：649
batch_tensor数据 组装完毕 ：649,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 649 ----- 1
正在处理 649 ----- 2
正在处理 649 ----- 3
正在处理 649 ----- 4
正在处理 649 ----- 5
正在处理 649 ----- 6
正在处理 649 ----- 7
正在处理 649 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 649
============================

正在读取第 650 个DF
初始化batch数据： 650
batch数据 组装完毕 ：650
batch_tensor数据 组装完毕 ：650,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 650 ----- 1
正在处理 650 ----- 2
正在处理 650 ----- 3
正在处理 650 ----- 4
正在处理 650 ----- 5
正在处理 650 ----- 6
正在处理 650 ----- 7
正在处理 650 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 650
============================

正在读取第 651 个DF
初始化batch数据： 651
batch数据 组装完毕 ：651
batch_tensor数据 组装完毕 ：651,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 651 ----- 1
正在处理 651 ----- 2
正在处理 651 ----- 3
正在处理 651 ----- 4
正在处理 651 ----- 5
正在处理 651 ----- 6
正在处理 651 ----- 7
正在处理 651 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 651
============================

正在读取第 652 个DF
初始化batch数据： 652
batch数据 组装完毕 ：652
batch_tensor数据 组装完毕 ：652,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 652 ----- 1
正在处理 652 ----- 2
正在处理 652 ----- 3
正在处理 652 ----- 4
正在处理 652 ----- 5
正在处理 652 ----- 6
正在处理 652 ----- 7
正在处理 652 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 652
============================

正在读取第 653 个DF
初始化batch数据： 653
batch数据 组装完毕 ：653
batch_tensor数据 组装完毕 ：653,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 653 ----- 1
正在处理 653 ----- 2
正在处理 653 ----- 3
正在处理 653 ----- 4
正在处理 653 ----- 5
正在处理 653 ----- 6
正在处理 653 ----- 7
正在处理 653 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 653
============================

正在读取第 654 个DF
初始化batch数据： 654
batch数据 组装完毕 ：654
batch_tensor数据 组装完毕 ：654,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 654 ----- 1
正在处理 654 ----- 2
正在处理 654 ----- 3
正在处理 654 ----- 4
正在处理 654 ----- 5
正在处理 654 ----- 6
正在处理 654 ----- 7
正在处理 654 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 654
============================

正在读取第 655 个DF
初始化batch数据： 655
batch数据 组装完毕 ：655
batch_tensor数据 组装完毕 ：655,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 655 ----- 1
正在处理 655 ----- 2
正在处理 655 ----- 3
正在处理 655 ----- 4
正在处理 655 ----- 5
正在处理 655 ----- 6
正在处理 655 ----- 7
正在处理 655 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 655
============================

正在读取第 656 个DF
初始化batch数据： 656
batch数据 组装完毕 ：656
batch_tensor数据 组装完毕 ：656,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 656 ----- 1
正在处理 656 ----- 2
正在处理 656 ----- 3
正在处理 656 ----- 4
正在处理 656 ----- 5
正在处理 656 ----- 6
正在处理 656 ----- 7
正在处理 656 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 656
============================

正在读取第 657 个DF
初始化batch数据： 657
batch数据 组装完毕 ：657
batch_tensor数据 组装完毕 ：657,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 657 ----- 1
正在处理 657 ----- 2
正在处理 657 ----- 3
正在处理 657 ----- 4
正在处理 657 ----- 5
正在处理 657 ----- 6
正在处理 657 ----- 7
正在处理 657 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 657
============================

正在读取第 658 个DF
初始化batch数据： 658
batch数据 组装完毕 ：658
batch_tensor数据 组装完毕 ：658,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 658 ----- 1
正在处理 658 ----- 2
正在处理 658 ----- 3
正在处理 658 ----- 4
正在处理 658 ----- 5
正在处理 658 ----- 6
正在处理 658 ----- 7
正在处理 658 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 658
============================

正在读取第 659 个DF
初始化batch数据： 659
batch数据 组装完毕 ：659
batch_tensor数据 组装完毕 ：659,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 659 ----- 1
正在处理 659 ----- 2
正在处理 659 ----- 3
正在处理 659 ----- 4
正在处理 659 ----- 5
正在处理 659 ----- 6
正在处理 659 ----- 7
正在处理 659 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 659
============================

正在读取第 660 个DF
初始化batch数据： 660
batch数据 组装完毕 ：660
batch_tensor数据 组装完毕 ：660,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 660 ----- 1
正在处理 660 ----- 2
正在处理 660 ----- 3
正在处理 660 ----- 4
正在处理 660 ----- 5
正在处理 660 ----- 6
正在处理 660 ----- 7
正在处理 660 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 660
============================

正在读取第 661 个DF
初始化batch数据： 661
batch数据 组装完毕 ：661
batch_tensor数据 组装完毕 ：661,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 661 ----- 1
正在处理 661 ----- 2
正在处理 661 ----- 3
正在处理 661 ----- 4
正在处理 661 ----- 5
正在处理 661 ----- 6
正在处理 661 ----- 7
正在处理 661 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 661
============================

正在读取第 662 个DF
初始化batch数据： 662
batch数据 组装完毕 ：662
batch_tensor数据 组装完毕 ：662,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 662 ----- 1
正在处理 662 ----- 2
正在处理 662 ----- 3
正在处理 662 ----- 4
正在处理 662 ----- 5
正在处理 662 ----- 6
正在处理 662 ----- 7
正在处理 662 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 662
============================

正在读取第 663 个DF
初始化batch数据： 663
batch数据 组装完毕 ：663
batch_tensor数据 组装完毕 ：663,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 663 ----- 1
正在处理 663 ----- 2
正在处理 663 ----- 3
正在处理 663 ----- 4
正在处理 663 ----- 5
正在处理 663 ----- 6
正在处理 663 ----- 7
正在处理 663 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 663
============================

正在读取第 664 个DF
初始化batch数据： 664
batch数据 组装完毕 ：664
batch_tensor数据 组装完毕 ：664,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 664 ----- 1
正在处理 664 ----- 2
正在处理 664 ----- 3
正在处理 664 ----- 4
正在处理 664 ----- 5
正在处理 664 ----- 6
正在处理 664 ----- 7
正在处理 664 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 664
============================

正在读取第 665 个DF
初始化batch数据： 665
batch数据 组装完毕 ：665
batch_tensor数据 组装完毕 ：665,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 665 ----- 1
正在处理 665 ----- 2
正在处理 665 ----- 3
正在处理 665 ----- 4
正在处理 665 ----- 5
正在处理 665 ----- 6
正在处理 665 ----- 7
正在处理 665 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 665
============================

正在读取第 666 个DF
初始化batch数据： 666
batch数据 组装完毕 ：666
batch_tensor数据 组装完毕 ：666,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 666 ----- 1
正在处理 666 ----- 2
正在处理 666 ----- 3
正在处理 666 ----- 4
正在处理 666 ----- 5
正在处理 666 ----- 6
正在处理 666 ----- 7
正在处理 666 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 666
============================

正在读取第 667 个DF
初始化batch数据： 667
batch数据 组装完毕 ：667
batch_tensor数据 组装完毕 ：667,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 667 ----- 1
正在处理 667 ----- 2
正在处理 667 ----- 3
正在处理 667 ----- 4
正在处理 667 ----- 5
正在处理 667 ----- 6
正在处理 667 ----- 7
正在处理 667 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 667
============================

正在读取第 668 个DF
初始化batch数据： 668
batch数据 组装完毕 ：668
batch_tensor数据 组装完毕 ：668,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 668 ----- 1
正在处理 668 ----- 2
正在处理 668 ----- 3
正在处理 668 ----- 4
正在处理 668 ----- 5
正在处理 668 ----- 6
正在处理 668 ----- 7
正在处理 668 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 668
============================

正在读取第 669 个DF
初始化batch数据： 669
batch数据 组装完毕 ：669
batch_tensor数据 组装完毕 ：669,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 669 ----- 1
正在处理 669 ----- 2
正在处理 669 ----- 3
正在处理 669 ----- 4
正在处理 669 ----- 5
正在处理 669 ----- 6
正在处理 669 ----- 7
正在处理 669 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 669
============================

正在读取第 670 个DF
初始化batch数据： 670
batch数据 组装完毕 ：670
batch_tensor数据 组装完毕 ：670,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 670 ----- 1
正在处理 670 ----- 2
正在处理 670 ----- 3
正在处理 670 ----- 4
正在处理 670 ----- 5
正在处理 670 ----- 6
正在处理 670 ----- 7
正在处理 670 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 670
============================

正在读取第 671 个DF
初始化batch数据： 671
batch数据 组装完毕 ：671
batch_tensor数据 组装完毕 ：671,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 671 ----- 1
正在处理 671 ----- 2
正在处理 671 ----- 3
正在处理 671 ----- 4
正在处理 671 ----- 5
正在处理 671 ----- 6
正在处理 671 ----- 7
正在处理 671 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 671
============================

正在读取第 672 个DF
初始化batch数据： 672
batch数据 组装完毕 ：672
batch_tensor数据 组装完毕 ：672,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 672 ----- 1
正在处理 672 ----- 2
正在处理 672 ----- 3
正在处理 672 ----- 4
正在处理 672 ----- 5
正在处理 672 ----- 6
正在处理 672 ----- 7
正在处理 672 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 672
============================

正在读取第 673 个DF
初始化batch数据： 673
batch数据 组装完毕 ：673
batch_tensor数据 组装完毕 ：673,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 673 ----- 1
正在处理 673 ----- 2
正在处理 673 ----- 3
正在处理 673 ----- 4
正在处理 673 ----- 5
正在处理 673 ----- 6
正在处理 673 ----- 7
正在处理 673 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 673
============================

正在读取第 674 个DF
初始化batch数据： 674
batch数据 组装完毕 ：674
batch_tensor数据 组装完毕 ：674,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 674 ----- 1
正在处理 674 ----- 2
正在处理 674 ----- 3
正在处理 674 ----- 4
正在处理 674 ----- 5
正在处理 674 ----- 6
正在处理 674 ----- 7
正在处理 674 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 674
============================

正在读取第 675 个DF
初始化batch数据： 675
batch数据 组装完毕 ：675
batch_tensor数据 组装完毕 ：675,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 675 ----- 1
正在处理 675 ----- 2
正在处理 675 ----- 3
正在处理 675 ----- 4
正在处理 675 ----- 5
正在处理 675 ----- 6
正在处理 675 ----- 7
正在处理 675 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 675
============================

正在读取第 676 个DF
初始化batch数据： 676
batch数据 组装完毕 ：676
batch_tensor数据 组装完毕 ：676,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 676 ----- 1
正在处理 676 ----- 2
正在处理 676 ----- 3
正在处理 676 ----- 4
正在处理 676 ----- 5
正在处理 676 ----- 6
正在处理 676 ----- 7
正在处理 676 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 676
============================

正在读取第 677 个DF
初始化batch数据： 677
batch数据 组装完毕 ：677
batch_tensor数据 组装完毕 ：677,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 677 ----- 1
正在处理 677 ----- 2
正在处理 677 ----- 3
正在处理 677 ----- 4
正在处理 677 ----- 5
正在处理 677 ----- 6
正在处理 677 ----- 7
正在处理 677 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 677
============================

正在读取第 678 个DF
初始化batch数据： 678
batch数据 组装完毕 ：678
batch_tensor数据 组装完毕 ：678,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 678 ----- 1
正在处理 678 ----- 2
正在处理 678 ----- 3
正在处理 678 ----- 4
正在处理 678 ----- 5
正在处理 678 ----- 6
正在处理 678 ----- 7
正在处理 678 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 678
============================

正在读取第 679 个DF
初始化batch数据： 679
batch数据 组装完毕 ：679
batch_tensor数据 组装完毕 ：679,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 679 ----- 1
正在处理 679 ----- 2
正在处理 679 ----- 3
正在处理 679 ----- 4
正在处理 679 ----- 5
正在处理 679 ----- 6
正在处理 679 ----- 7
正在处理 679 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 679
============================

正在读取第 680 个DF
初始化batch数据： 680
batch数据 组装完毕 ：680
batch_tensor数据 组装完毕 ：680,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 680 ----- 1
正在处理 680 ----- 2
正在处理 680 ----- 3
正在处理 680 ----- 4
正在处理 680 ----- 5
正在处理 680 ----- 6
正在处理 680 ----- 7
正在处理 680 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 680
============================

正在读取第 681 个DF
初始化batch数据： 681
batch数据 组装完毕 ：681
batch_tensor数据 组装完毕 ：681,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 681 ----- 1
正在处理 681 ----- 2
正在处理 681 ----- 3
正在处理 681 ----- 4
正在处理 681 ----- 5
正在处理 681 ----- 6
正在处理 681 ----- 7
正在处理 681 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 681
============================

正在读取第 682 个DF
初始化batch数据： 682
batch数据 组装完毕 ：682
batch_tensor数据 组装完毕 ：682,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 682 ----- 1
正在处理 682 ----- 2
正在处理 682 ----- 3
正在处理 682 ----- 4
正在处理 682 ----- 5
正在处理 682 ----- 6
正在处理 682 ----- 7
正在处理 682 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 682
============================

正在读取第 683 个DF
初始化batch数据： 683
batch数据 组装完毕 ：683
batch_tensor数据 组装完毕 ：683,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 683 ----- 1
正在处理 683 ----- 2
正在处理 683 ----- 3
正在处理 683 ----- 4
正在处理 683 ----- 5
正在处理 683 ----- 6
正在处理 683 ----- 7
正在处理 683 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 683
============================

正在读取第 684 个DF
初始化batch数据： 684
batch数据 组装完毕 ：684
batch_tensor数据 组装完毕 ：684,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 684 ----- 1
正在处理 684 ----- 2
正在处理 684 ----- 3
正在处理 684 ----- 4
正在处理 684 ----- 5
正在处理 684 ----- 6
正在处理 684 ----- 7
正在处理 684 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 684
============================

正在读取第 685 个DF
初始化batch数据： 685
batch数据 组装完毕 ：685
batch_tensor数据 组装完毕 ：685,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 685 ----- 1
正在处理 685 ----- 2
正在处理 685 ----- 3
正在处理 685 ----- 4
正在处理 685 ----- 5
正在处理 685 ----- 6
正在处理 685 ----- 7
正在处理 685 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 685
============================

正在读取第 686 个DF
初始化batch数据： 686
batch数据 组装完毕 ：686
batch_tensor数据 组装完毕 ：686,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 686 ----- 1
正在处理 686 ----- 2
正在处理 686 ----- 3
正在处理 686 ----- 4
正在处理 686 ----- 5
正在处理 686 ----- 6
正在处理 686 ----- 7
正在处理 686 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 686
============================

正在读取第 687 个DF
初始化batch数据： 687
batch数据 组装完毕 ：687
batch_tensor数据 组装完毕 ：687,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 687 ----- 1
正在处理 687 ----- 2
正在处理 687 ----- 3
正在处理 687 ----- 4
正在处理 687 ----- 5
正在处理 687 ----- 6
正在处理 687 ----- 7
正在处理 687 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 687
============================

正在读取第 688 个DF
初始化batch数据： 688
batch数据 组装完毕 ：688
batch_tensor数据 组装完毕 ：688,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 688 ----- 1
正在处理 688 ----- 2
正在处理 688 ----- 3
正在处理 688 ----- 4
正在处理 688 ----- 5
正在处理 688 ----- 6
正在处理 688 ----- 7
正在处理 688 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 688
============================

正在读取第 689 个DF
初始化batch数据： 689
batch数据 组装完毕 ：689
batch_tensor数据 组装完毕 ：689,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 689 ----- 1
正在处理 689 ----- 2
正在处理 689 ----- 3
正在处理 689 ----- 4
正在处理 689 ----- 5
正在处理 689 ----- 6
正在处理 689 ----- 7
正在处理 689 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 689
============================

正在读取第 690 个DF
初始化batch数据： 690
batch数据 组装完毕 ：690
batch_tensor数据 组装完毕 ：690,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 690 ----- 1
正在处理 690 ----- 2
正在处理 690 ----- 3
正在处理 690 ----- 4
正在处理 690 ----- 5
正在处理 690 ----- 6
正在处理 690 ----- 7
正在处理 690 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 690
============================

正在读取第 691 个DF
初始化batch数据： 691
batch数据 组装完毕 ：691
batch_tensor数据 组装完毕 ：691,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 691 ----- 1
正在处理 691 ----- 2
正在处理 691 ----- 3
正在处理 691 ----- 4
正在处理 691 ----- 5
正在处理 691 ----- 6
正在处理 691 ----- 7
正在处理 691 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 691
============================

正在读取第 692 个DF
初始化batch数据： 692
batch数据 组装完毕 ：692
batch_tensor数据 组装完毕 ：692,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 692 ----- 1
正在处理 692 ----- 2
正在处理 692 ----- 3
正在处理 692 ----- 4
正在处理 692 ----- 5
正在处理 692 ----- 6
正在处理 692 ----- 7
正在处理 692 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 692
============================

正在读取第 693 个DF
初始化batch数据： 693
batch数据 组装完毕 ：693
batch_tensor数据 组装完毕 ：693,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 693 ----- 1
正在处理 693 ----- 2
正在处理 693 ----- 3
正在处理 693 ----- 4
正在处理 693 ----- 5
正在处理 693 ----- 6
正在处理 693 ----- 7
正在处理 693 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 693
============================

正在读取第 694 个DF
初始化batch数据： 694
batch数据 组装完毕 ：694
batch_tensor数据 组装完毕 ：694,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 694 ----- 1
正在处理 694 ----- 2
正在处理 694 ----- 3
正在处理 694 ----- 4
正在处理 694 ----- 5
正在处理 694 ----- 6
正在处理 694 ----- 7
正在处理 694 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 694
============================

正在读取第 695 个DF
初始化batch数据： 695
batch数据 组装完毕 ：695
batch_tensor数据 组装完毕 ：695,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 695 ----- 1
正在处理 695 ----- 2
正在处理 695 ----- 3
正在处理 695 ----- 4
正在处理 695 ----- 5
正在处理 695 ----- 6
正在处理 695 ----- 7
正在处理 695 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 695
============================

正在读取第 696 个DF
初始化batch数据： 696
batch数据 组装完毕 ：696
batch_tensor数据 组装完毕 ：696,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 696 ----- 1
正在处理 696 ----- 2
正在处理 696 ----- 3
正在处理 696 ----- 4
正在处理 696 ----- 5
正在处理 696 ----- 6
正在处理 696 ----- 7
正在处理 696 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 696
============================

正在读取第 697 个DF
初始化batch数据： 697
batch数据 组装完毕 ：697
batch_tensor数据 组装完毕 ：697,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 697 ----- 1
正在处理 697 ----- 2
正在处理 697 ----- 3
正在处理 697 ----- 4
正在处理 697 ----- 5
正在处理 697 ----- 6
正在处理 697 ----- 7
正在处理 697 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 697
============================

正在读取第 698 个DF
初始化batch数据： 698
batch数据 组装完毕 ：698
batch_tensor数据 组装完毕 ：698,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 698 ----- 1
正在处理 698 ----- 2
正在处理 698 ----- 3
正在处理 698 ----- 4
正在处理 698 ----- 5
正在处理 698 ----- 6
正在处理 698 ----- 7
正在处理 698 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 698
============================

正在读取第 699 个DF
初始化batch数据： 699
batch数据 组装完毕 ：699
batch_tensor数据 组装完毕 ：699,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 699 ----- 1
正在处理 699 ----- 2
正在处理 699 ----- 3
正在处理 699 ----- 4
正在处理 699 ----- 5
正在处理 699 ----- 6
正在处理 699 ----- 7
正在处理 699 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 699
============================

正在读取第 700 个DF
初始化batch数据： 700
batch数据 组装完毕 ：700
batch_tensor数据 组装完毕 ：700,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 700 ----- 1
正在处理 700 ----- 2
正在处理 700 ----- 3
正在处理 700 ----- 4
正在处理 700 ----- 5
正在处理 700 ----- 6
正在处理 700 ----- 7
正在处理 700 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 700
============================

正在读取第 701 个DF
初始化batch数据： 701
batch数据 组装完毕 ：701
batch_tensor数据 组装完毕 ：701,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 701 ----- 1
正在处理 701 ----- 2
正在处理 701 ----- 3
正在处理 701 ----- 4
正在处理 701 ----- 5
正在处理 701 ----- 6
正在处理 701 ----- 7
正在处理 701 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 701
============================

正在读取第 702 个DF
初始化batch数据： 702
batch数据 组装完毕 ：702
batch_tensor数据 组装完毕 ：702,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 702 ----- 1
正在处理 702 ----- 2
正在处理 702 ----- 3
正在处理 702 ----- 4
正在处理 702 ----- 5
正在处理 702 ----- 6
正在处理 702 ----- 7
正在处理 702 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 702
============================

正在读取第 703 个DF
初始化batch数据： 703
batch数据 组装完毕 ：703
batch_tensor数据 组装完毕 ：703,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 703 ----- 1
正在处理 703 ----- 2
正在处理 703 ----- 3
正在处理 703 ----- 4
正在处理 703 ----- 5
正在处理 703 ----- 6
正在处理 703 ----- 7
正在处理 703 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 703
============================

正在读取第 704 个DF
初始化batch数据： 704
batch数据 组装完毕 ：704
batch_tensor数据 组装完毕 ：704,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 704 ----- 1
正在处理 704 ----- 2
正在处理 704 ----- 3
正在处理 704 ----- 4
正在处理 704 ----- 5
正在处理 704 ----- 6
正在处理 704 ----- 7
正在处理 704 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 704
============================

正在读取第 705 个DF
初始化batch数据： 705
batch数据 组装完毕 ：705
batch_tensor数据 组装完毕 ：705,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 705 ----- 1
正在处理 705 ----- 2
正在处理 705 ----- 3
正在处理 705 ----- 4
正在处理 705 ----- 5
正在处理 705 ----- 6
正在处理 705 ----- 7
正在处理 705 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 705
============================

正在读取第 706 个DF
初始化batch数据： 706
batch数据 组装完毕 ：706
batch_tensor数据 组装完毕 ：706,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 706 ----- 1
正在处理 706 ----- 2
正在处理 706 ----- 3
正在处理 706 ----- 4
正在处理 706 ----- 5
正在处理 706 ----- 6
正在处理 706 ----- 7
正在处理 706 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 706
============================

正在读取第 707 个DF
初始化batch数据： 707
batch数据 组装完毕 ：707
batch_tensor数据 组装完毕 ：707,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 707 ----- 1
正在处理 707 ----- 2
正在处理 707 ----- 3
正在处理 707 ----- 4
正在处理 707 ----- 5
正在处理 707 ----- 6
正在处理 707 ----- 7
正在处理 707 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 707
============================

正在读取第 708 个DF
初始化batch数据： 708
batch数据 组装完毕 ：708
batch_tensor数据 组装完毕 ：708,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 708 ----- 1
正在处理 708 ----- 2
正在处理 708 ----- 3
正在处理 708 ----- 4
正在处理 708 ----- 5
正在处理 708 ----- 6
正在处理 708 ----- 7
正在处理 708 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 708
============================

正在读取第 709 个DF
初始化batch数据： 709
batch数据 组装完毕 ：709
batch_tensor数据 组装完毕 ：709,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 709 ----- 1
正在处理 709 ----- 2
正在处理 709 ----- 3
正在处理 709 ----- 4
正在处理 709 ----- 5
正在处理 709 ----- 6
正在处理 709 ----- 7
正在处理 709 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 709
============================

正在读取第 710 个DF
初始化batch数据： 710
batch数据 组装完毕 ：710
batch_tensor数据 组装完毕 ：710,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 710 ----- 1
正在处理 710 ----- 2
正在处理 710 ----- 3
正在处理 710 ----- 4
正在处理 710 ----- 5
正在处理 710 ----- 6
正在处理 710 ----- 7
正在处理 710 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 710
============================

正在读取第 711 个DF
初始化batch数据： 711
batch数据 组装完毕 ：711
batch_tensor数据 组装完毕 ：711,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 711 ----- 1
正在处理 711 ----- 2
正在处理 711 ----- 3
正在处理 711 ----- 4
正在处理 711 ----- 5
正在处理 711 ----- 6
正在处理 711 ----- 7
正在处理 711 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 711
============================

正在读取第 712 个DF
初始化batch数据： 712
batch数据 组装完毕 ：712
batch_tensor数据 组装完毕 ：712,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 712 ----- 1
正在处理 712 ----- 2
正在处理 712 ----- 3
正在处理 712 ----- 4
正在处理 712 ----- 5
正在处理 712 ----- 6
正在处理 712 ----- 7
正在处理 712 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 712
============================

正在读取第 713 个DF
初始化batch数据： 713
batch数据 组装完毕 ：713
batch_tensor数据 组装完毕 ：713,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 713 ----- 1
正在处理 713 ----- 2
正在处理 713 ----- 3
正在处理 713 ----- 4
正在处理 713 ----- 5
正在处理 713 ----- 6
正在处理 713 ----- 7
正在处理 713 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 713
============================

正在读取第 714 个DF
初始化batch数据： 714
batch数据 组装完毕 ：714
batch_tensor数据 组装完毕 ：714,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 714 ----- 1
正在处理 714 ----- 2
正在处理 714 ----- 3
正在处理 714 ----- 4
正在处理 714 ----- 5
正在处理 714 ----- 6
正在处理 714 ----- 7
正在处理 714 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 714
============================

正在读取第 715 个DF
初始化batch数据： 715
batch数据 组装完毕 ：715
batch_tensor数据 组装完毕 ：715,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 715 ----- 1
正在处理 715 ----- 2
正在处理 715 ----- 3
正在处理 715 ----- 4
正在处理 715 ----- 5
正在处理 715 ----- 6
正在处理 715 ----- 7
正在处理 715 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 715
============================

正在读取第 716 个DF
初始化batch数据： 716
batch数据 组装完毕 ：716
batch_tensor数据 组装完毕 ：716,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 716 ----- 1
正在处理 716 ----- 2
正在处理 716 ----- 3
正在处理 716 ----- 4
正在处理 716 ----- 5
正在处理 716 ----- 6
正在处理 716 ----- 7
正在处理 716 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 716
============================

正在读取第 717 个DF
初始化batch数据： 717
batch数据 组装完毕 ：717
batch_tensor数据 组装完毕 ：717,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 717 ----- 1
正在处理 717 ----- 2
正在处理 717 ----- 3
正在处理 717 ----- 4
正在处理 717 ----- 5
正在处理 717 ----- 6
正在处理 717 ----- 7
正在处理 717 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 717
============================

正在读取第 718 个DF
初始化batch数据： 718
batch数据 组装完毕 ：718
batch_tensor数据 组装完毕 ：718,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 718 ----- 1
正在处理 718 ----- 2
正在处理 718 ----- 3
正在处理 718 ----- 4
正在处理 718 ----- 5
正在处理 718 ----- 6
正在处理 718 ----- 7
正在处理 718 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 718
============================

正在读取第 719 个DF
初始化batch数据： 719
batch数据 组装完毕 ：719
batch_tensor数据 组装完毕 ：719,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 719 ----- 1
正在处理 719 ----- 2
正在处理 719 ----- 3
正在处理 719 ----- 4
正在处理 719 ----- 5
正在处理 719 ----- 6
正在处理 719 ----- 7
正在处理 719 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 719
============================

正在读取第 720 个DF
初始化batch数据： 720
batch数据 组装完毕 ：720
batch_tensor数据 组装完毕 ：720,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 720 ----- 1
正在处理 720 ----- 2
正在处理 720 ----- 3
正在处理 720 ----- 4
正在处理 720 ----- 5
正在处理 720 ----- 6
正在处理 720 ----- 7
正在处理 720 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 720
============================

正在读取第 721 个DF
初始化batch数据： 721
batch数据 组装完毕 ：721
batch_tensor数据 组装完毕 ：721,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 721 ----- 1
正在处理 721 ----- 2
正在处理 721 ----- 3
正在处理 721 ----- 4
正在处理 721 ----- 5
正在处理 721 ----- 6
正在处理 721 ----- 7
正在处理 721 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 721
============================

正在读取第 722 个DF
初始化batch数据： 722
batch数据 组装完毕 ：722
batch_tensor数据 组装完毕 ：722,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 722 ----- 1
正在处理 722 ----- 2
正在处理 722 ----- 3
正在处理 722 ----- 4
正在处理 722 ----- 5
正在处理 722 ----- 6
正在处理 722 ----- 7
正在处理 722 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 722
============================

正在读取第 723 个DF
初始化batch数据： 723
batch数据 组装完毕 ：723
batch_tensor数据 组装完毕 ：723,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 723 ----- 1
正在处理 723 ----- 2
正在处理 723 ----- 3
正在处理 723 ----- 4
正在处理 723 ----- 5
正在处理 723 ----- 6
正在处理 723 ----- 7
正在处理 723 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 723
============================

正在读取第 724 个DF
初始化batch数据： 724
batch数据 组装完毕 ：724
batch_tensor数据 组装完毕 ：724,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 724 ----- 1
正在处理 724 ----- 2
正在处理 724 ----- 3
正在处理 724 ----- 4
正在处理 724 ----- 5
正在处理 724 ----- 6
正在处理 724 ----- 7
正在处理 724 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 724
============================

正在读取第 725 个DF
初始化batch数据： 725
batch数据 组装完毕 ：725
batch_tensor数据 组装完毕 ：725,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 725 ----- 1
正在处理 725 ----- 2
正在处理 725 ----- 3
正在处理 725 ----- 4
正在处理 725 ----- 5
正在处理 725 ----- 6
正在处理 725 ----- 7
正在处理 725 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 725
============================

正在读取第 726 个DF
初始化batch数据： 726
batch数据 组装完毕 ：726
batch_tensor数据 组装完毕 ：726,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 726 ----- 1
正在处理 726 ----- 2
正在处理 726 ----- 3
正在处理 726 ----- 4
正在处理 726 ----- 5
正在处理 726 ----- 6
正在处理 726 ----- 7
正在处理 726 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 726
============================

正在读取第 727 个DF
初始化batch数据： 727
batch数据 组装完毕 ：727
batch_tensor数据 组装完毕 ：727,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 727 ----- 1
正在处理 727 ----- 2
正在处理 727 ----- 3
正在处理 727 ----- 4
正在处理 727 ----- 5
正在处理 727 ----- 6
正在处理 727 ----- 7
正在处理 727 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 727
============================

正在读取第 728 个DF
初始化batch数据： 728
batch数据 组装完毕 ：728
batch_tensor数据 组装完毕 ：728,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 728 ----- 1
正在处理 728 ----- 2
正在处理 728 ----- 3
正在处理 728 ----- 4
正在处理 728 ----- 5
正在处理 728 ----- 6
正在处理 728 ----- 7
正在处理 728 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 728
============================

正在读取第 729 个DF
初始化batch数据： 729
batch数据 组装完毕 ：729
batch_tensor数据 组装完毕 ：729,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 729 ----- 1
正在处理 729 ----- 2
正在处理 729 ----- 3
正在处理 729 ----- 4
正在处理 729 ----- 5
正在处理 729 ----- 6
正在处理 729 ----- 7
正在处理 729 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 729
============================

正在读取第 730 个DF
初始化batch数据： 730
batch数据 组装完毕 ：730
batch_tensor数据 组装完毕 ：730,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 730 ----- 1
正在处理 730 ----- 2
正在处理 730 ----- 3
正在处理 730 ----- 4
正在处理 730 ----- 5
正在处理 730 ----- 6
正在处理 730 ----- 7
正在处理 730 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 730
============================

正在读取第 731 个DF
初始化batch数据： 731
batch数据 组装完毕 ：731
batch_tensor数据 组装完毕 ：731,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 731 ----- 1
正在处理 731 ----- 2
正在处理 731 ----- 3
正在处理 731 ----- 4
正在处理 731 ----- 5
正在处理 731 ----- 6
正在处理 731 ----- 7
正在处理 731 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 731
============================

正在读取第 732 个DF
初始化batch数据： 732
batch数据 组装完毕 ：732
batch_tensor数据 组装完毕 ：732,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 732 ----- 1
正在处理 732 ----- 2
正在处理 732 ----- 3
正在处理 732 ----- 4
正在处理 732 ----- 5
正在处理 732 ----- 6
正在处理 732 ----- 7
正在处理 732 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 732
============================

正在读取第 733 个DF
初始化batch数据： 733
batch数据 组装完毕 ：733
batch_tensor数据 组装完毕 ：733,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 733 ----- 1
正在处理 733 ----- 2
正在处理 733 ----- 3
正在处理 733 ----- 4
正在处理 733 ----- 5
正在处理 733 ----- 6
正在处理 733 ----- 7
正在处理 733 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 733
============================

正在读取第 734 个DF
初始化batch数据： 734
batch数据 组装完毕 ：734
batch_tensor数据 组装完毕 ：734,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 734 ----- 1
正在处理 734 ----- 2
正在处理 734 ----- 3
正在处理 734 ----- 4
正在处理 734 ----- 5
正在处理 734 ----- 6
正在处理 734 ----- 7
正在处理 734 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 734
============================

正在读取第 735 个DF
初始化batch数据： 735
batch数据 组装完毕 ：735
batch_tensor数据 组装完毕 ：735,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 735 ----- 1
正在处理 735 ----- 2
正在处理 735 ----- 3
正在处理 735 ----- 4
正在处理 735 ----- 5
正在处理 735 ----- 6
正在处理 735 ----- 7
正在处理 735 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 735
============================

正在读取第 736 个DF
初始化batch数据： 736
batch数据 组装完毕 ：736
batch_tensor数据 组装完毕 ：736,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 736 ----- 1
正在处理 736 ----- 2
正在处理 736 ----- 3
正在处理 736 ----- 4
正在处理 736 ----- 5
正在处理 736 ----- 6
正在处理 736 ----- 7
正在处理 736 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 736
============================

正在读取第 737 个DF
初始化batch数据： 737
batch数据 组装完毕 ：737
batch_tensor数据 组装完毕 ：737,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 737 ----- 1
正在处理 737 ----- 2
正在处理 737 ----- 3
正在处理 737 ----- 4
正在处理 737 ----- 5
正在处理 737 ----- 6
正在处理 737 ----- 7
正在处理 737 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 737
============================

正在读取第 738 个DF
初始化batch数据： 738
batch数据 组装完毕 ：738
batch_tensor数据 组装完毕 ：738,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 738 ----- 1
正在处理 738 ----- 2
正在处理 738 ----- 3
正在处理 738 ----- 4
正在处理 738 ----- 5
正在处理 738 ----- 6
正在处理 738 ----- 7
正在处理 738 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 738
============================

正在读取第 739 个DF
初始化batch数据： 739
batch数据 组装完毕 ：739
batch_tensor数据 组装完毕 ：739,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 739 ----- 1
正在处理 739 ----- 2
正在处理 739 ----- 3
正在处理 739 ----- 4
正在处理 739 ----- 5
正在处理 739 ----- 6
正在处理 739 ----- 7
正在处理 739 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 739
============================

正在读取第 740 个DF
初始化batch数据： 740
batch数据 组装完毕 ：740
batch_tensor数据 组装完毕 ：740,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 740 ----- 1
正在处理 740 ----- 2
正在处理 740 ----- 3
正在处理 740 ----- 4
正在处理 740 ----- 5
正在处理 740 ----- 6
正在处理 740 ----- 7
正在处理 740 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 740
============================

正在读取第 741 个DF
初始化batch数据： 741
batch数据 组装完毕 ：741
batch_tensor数据 组装完毕 ：741,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 741 ----- 1
正在处理 741 ----- 2
正在处理 741 ----- 3
正在处理 741 ----- 4
正在处理 741 ----- 5
正在处理 741 ----- 6
正在处理 741 ----- 7
正在处理 741 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 741
============================

正在读取第 742 个DF
初始化batch数据： 742
batch数据 组装完毕 ：742
batch_tensor数据 组装完毕 ：742,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 742 ----- 1
正在处理 742 ----- 2
正在处理 742 ----- 3
正在处理 742 ----- 4
正在处理 742 ----- 5
正在处理 742 ----- 6
正在处理 742 ----- 7
正在处理 742 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 742
============================

正在读取第 743 个DF
初始化batch数据： 743
batch数据 组装完毕 ：743
batch_tensor数据 组装完毕 ：743,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 743 ----- 1
正在处理 743 ----- 2
正在处理 743 ----- 3
正在处理 743 ----- 4
正在处理 743 ----- 5
正在处理 743 ----- 6
正在处理 743 ----- 7
正在处理 743 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 743
============================

正在读取第 744 个DF
初始化batch数据： 744
batch数据 组装完毕 ：744
batch_tensor数据 组装完毕 ：744,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 744 ----- 1
正在处理 744 ----- 2
正在处理 744 ----- 3
正在处理 744 ----- 4
正在处理 744 ----- 5
正在处理 744 ----- 6
正在处理 744 ----- 7
正在处理 744 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 744
============================

正在读取第 745 个DF
初始化batch数据： 745
batch数据 组装完毕 ：745
batch_tensor数据 组装完毕 ：745,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 745 ----- 1
正在处理 745 ----- 2
正在处理 745 ----- 3
正在处理 745 ----- 4
正在处理 745 ----- 5
正在处理 745 ----- 6
正在处理 745 ----- 7
正在处理 745 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 745
============================

正在读取第 746 个DF
初始化batch数据： 746
batch数据 组装完毕 ：746
batch_tensor数据 组装完毕 ：746,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 746 ----- 1
正在处理 746 ----- 2
正在处理 746 ----- 3
正在处理 746 ----- 4
正在处理 746 ----- 5
正在处理 746 ----- 6
正在处理 746 ----- 7
正在处理 746 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 746
============================

正在读取第 747 个DF
初始化batch数据： 747
batch数据 组装完毕 ：747
batch_tensor数据 组装完毕 ：747,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 747 ----- 1
正在处理 747 ----- 2
正在处理 747 ----- 3
正在处理 747 ----- 4
正在处理 747 ----- 5
正在处理 747 ----- 6
正在处理 747 ----- 7
正在处理 747 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 747
============================

正在读取第 748 个DF
初始化batch数据： 748
batch数据 组装完毕 ：748
batch_tensor数据 组装完毕 ：748,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 748 ----- 1
正在处理 748 ----- 2
正在处理 748 ----- 3
正在处理 748 ----- 4
正在处理 748 ----- 5
正在处理 748 ----- 6
正在处理 748 ----- 7
正在处理 748 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 748
============================

正在读取第 749 个DF
初始化batch数据： 749
batch数据 组装完毕 ：749
batch_tensor数据 组装完毕 ：749,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 749 ----- 1
正在处理 749 ----- 2
正在处理 749 ----- 3
正在处理 749 ----- 4
正在处理 749 ----- 5
正在处理 749 ----- 6
正在处理 749 ----- 7
正在处理 749 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 749
============================

正在读取第 750 个DF
初始化batch数据： 750
batch数据 组装完毕 ：750
batch_tensor数据 组装完毕 ：750,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 750 ----- 1
正在处理 750 ----- 2
正在处理 750 ----- 3
正在处理 750 ----- 4
正在处理 750 ----- 5
正在处理 750 ----- 6
正在处理 750 ----- 7
正在处理 750 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 750
============================

正在读取第 751 个DF
初始化batch数据： 751
batch数据 组装完毕 ：751
batch_tensor数据 组装完毕 ：751,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 751 ----- 1
正在处理 751 ----- 2
正在处理 751 ----- 3
正在处理 751 ----- 4
正在处理 751 ----- 5
正在处理 751 ----- 6
正在处理 751 ----- 7
正在处理 751 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 751
============================

正在读取第 752 个DF
初始化batch数据： 752
batch数据 组装完毕 ：752
batch_tensor数据 组装完毕 ：752,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 752 ----- 1
正在处理 752 ----- 2
正在处理 752 ----- 3
正在处理 752 ----- 4
正在处理 752 ----- 5
正在处理 752 ----- 6
正在处理 752 ----- 7
正在处理 752 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 752
============================

正在读取第 753 个DF
初始化batch数据： 753
batch数据 组装完毕 ：753
batch_tensor数据 组装完毕 ：753,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 753 ----- 1
正在处理 753 ----- 2
正在处理 753 ----- 3
正在处理 753 ----- 4
正在处理 753 ----- 5
正在处理 753 ----- 6
正在处理 753 ----- 7
正在处理 753 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 753
============================

正在读取第 754 个DF
初始化batch数据： 754
batch数据 组装完毕 ：754
batch_tensor数据 组装完毕 ：754,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 754 ----- 1
正在处理 754 ----- 2
正在处理 754 ----- 3
正在处理 754 ----- 4
正在处理 754 ----- 5
正在处理 754 ----- 6
正在处理 754 ----- 7
正在处理 754 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 754
============================

正在读取第 755 个DF
初始化batch数据： 755
batch数据 组装完毕 ：755
batch_tensor数据 组装完毕 ：755,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 755 ----- 1
正在处理 755 ----- 2
正在处理 755 ----- 3
正在处理 755 ----- 4
正在处理 755 ----- 5
正在处理 755 ----- 6
正在处理 755 ----- 7
正在处理 755 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 755
============================

正在读取第 756 个DF
初始化batch数据： 756
batch数据 组装完毕 ：756
batch_tensor数据 组装完毕 ：756,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 756 ----- 1
正在处理 756 ----- 2
正在处理 756 ----- 3
正在处理 756 ----- 4
正在处理 756 ----- 5
正在处理 756 ----- 6
正在处理 756 ----- 7
正在处理 756 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 756
============================

正在读取第 757 个DF
初始化batch数据： 757
batch数据 组装完毕 ：757
batch_tensor数据 组装完毕 ：757,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 757 ----- 1
正在处理 757 ----- 2
正在处理 757 ----- 3
正在处理 757 ----- 4
正在处理 757 ----- 5
正在处理 757 ----- 6
正在处理 757 ----- 7
正在处理 757 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 757
============================

正在读取第 758 个DF
初始化batch数据： 758
batch数据 组装完毕 ：758
batch_tensor数据 组装完毕 ：758,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 758 ----- 1
正在处理 758 ----- 2
正在处理 758 ----- 3
正在处理 758 ----- 4
正在处理 758 ----- 5
正在处理 758 ----- 6
正在处理 758 ----- 7
正在处理 758 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 758
============================

正在读取第 759 个DF
初始化batch数据： 759
batch数据 组装完毕 ：759
batch_tensor数据 组装完毕 ：759,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 759 ----- 1
正在处理 759 ----- 2
正在处理 759 ----- 3
正在处理 759 ----- 4
正在处理 759 ----- 5
正在处理 759 ----- 6
正在处理 759 ----- 7
正在处理 759 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 759
============================

正在读取第 760 个DF
初始化batch数据： 760
batch数据 组装完毕 ：760
batch_tensor数据 组装完毕 ：760,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 760 ----- 1
正在处理 760 ----- 2
正在处理 760 ----- 3
正在处理 760 ----- 4
正在处理 760 ----- 5
正在处理 760 ----- 6
正在处理 760 ----- 7
正在处理 760 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 760
============================

正在读取第 761 个DF
初始化batch数据： 761
batch数据 组装完毕 ：761
batch_tensor数据 组装完毕 ：761,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 761 ----- 1
正在处理 761 ----- 2
正在处理 761 ----- 3
正在处理 761 ----- 4
正在处理 761 ----- 5
正在处理 761 ----- 6
正在处理 761 ----- 7
正在处理 761 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 761
============================

正在读取第 762 个DF
初始化batch数据： 762
batch数据 组装完毕 ：762
batch_tensor数据 组装完毕 ：762,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 762 ----- 1
正在处理 762 ----- 2
正在处理 762 ----- 3
正在处理 762 ----- 4
正在处理 762 ----- 5
正在处理 762 ----- 6
正在处理 762 ----- 7
正在处理 762 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 762
============================

正在读取第 763 个DF
初始化batch数据： 763
batch数据 组装完毕 ：763
batch_tensor数据 组装完毕 ：763,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 763 ----- 1
正在处理 763 ----- 2
正在处理 763 ----- 3
正在处理 763 ----- 4
正在处理 763 ----- 5
正在处理 763 ----- 6
正在处理 763 ----- 7
正在处理 763 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 763
============================

正在读取第 764 个DF
初始化batch数据： 764
batch数据 组装完毕 ：764
batch_tensor数据 组装完毕 ：764,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 764 ----- 1
正在处理 764 ----- 2
正在处理 764 ----- 3
正在处理 764 ----- 4
正在处理 764 ----- 5
正在处理 764 ----- 6
正在处理 764 ----- 7
正在处理 764 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 764
============================

正在读取第 765 个DF
初始化batch数据： 765
batch数据 组装完毕 ：765
batch_tensor数据 组装完毕 ：765,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 765 ----- 1
正在处理 765 ----- 2
正在处理 765 ----- 3
正在处理 765 ----- 4
正在处理 765 ----- 5
正在处理 765 ----- 6
正在处理 765 ----- 7
正在处理 765 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 765
============================

正在读取第 766 个DF
初始化batch数据： 766
batch数据 组装完毕 ：766
batch_tensor数据 组装完毕 ：766,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 766 ----- 1
正在处理 766 ----- 2
正在处理 766 ----- 3
正在处理 766 ----- 4
正在处理 766 ----- 5
正在处理 766 ----- 6
正在处理 766 ----- 7
正在处理 766 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 766
============================

正在读取第 767 个DF
初始化batch数据： 767
batch数据 组装完毕 ：767
batch_tensor数据 组装完毕 ：767,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 767 ----- 1
正在处理 767 ----- 2
正在处理 767 ----- 3
正在处理 767 ----- 4
正在处理 767 ----- 5
正在处理 767 ----- 6
正在处理 767 ----- 7
正在处理 767 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 767
============================

正在读取第 768 个DF
初始化batch数据： 768
batch数据 组装完毕 ：768
batch_tensor数据 组装完毕 ：768,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 768 ----- 1
正在处理 768 ----- 2
正在处理 768 ----- 3
正在处理 768 ----- 4
正在处理 768 ----- 5
正在处理 768 ----- 6
正在处理 768 ----- 7
正在处理 768 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 768
============================

正在读取第 769 个DF
初始化batch数据： 769
batch数据 组装完毕 ：769
batch_tensor数据 组装完毕 ：769,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 769 ----- 1
正在处理 769 ----- 2
正在处理 769 ----- 3
正在处理 769 ----- 4
正在处理 769 ----- 5
正在处理 769 ----- 6
正在处理 769 ----- 7
正在处理 769 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 769
============================

正在读取第 770 个DF
初始化batch数据： 770
batch数据 组装完毕 ：770
batch_tensor数据 组装完毕 ：770,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 770 ----- 1
正在处理 770 ----- 2
正在处理 770 ----- 3
正在处理 770 ----- 4
正在处理 770 ----- 5
正在处理 770 ----- 6
正在处理 770 ----- 7
正在处理 770 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 770
============================

正在读取第 771 个DF
初始化batch数据： 771
batch数据 组装完毕 ：771
batch_tensor数据 组装完毕 ：771,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 771 ----- 1
正在处理 771 ----- 2
正在处理 771 ----- 3
正在处理 771 ----- 4
正在处理 771 ----- 5
正在处理 771 ----- 6
正在处理 771 ----- 7
正在处理 771 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 771
============================

正在读取第 772 个DF
初始化batch数据： 772
batch数据 组装完毕 ：772
batch_tensor数据 组装完毕 ：772,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 772 ----- 1
正在处理 772 ----- 2
正在处理 772 ----- 3
正在处理 772 ----- 4
正在处理 772 ----- 5
正在处理 772 ----- 6
正在处理 772 ----- 7
正在处理 772 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 772
============================

正在读取第 773 个DF
初始化batch数据： 773
batch数据 组装完毕 ：773
batch_tensor数据 组装完毕 ：773,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 773 ----- 1
正在处理 773 ----- 2
正在处理 773 ----- 3
正在处理 773 ----- 4
正在处理 773 ----- 5
正在处理 773 ----- 6
正在处理 773 ----- 7
正在处理 773 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 773
============================

正在读取第 774 个DF
初始化batch数据： 774
batch数据 组装完毕 ：774
batch_tensor数据 组装完毕 ：774,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 774 ----- 1
正在处理 774 ----- 2
正在处理 774 ----- 3
正在处理 774 ----- 4
正在处理 774 ----- 5
正在处理 774 ----- 6
正在处理 774 ----- 7
正在处理 774 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 774
============================

正在读取第 775 个DF
初始化batch数据： 775
batch数据 组装完毕 ：775
batch_tensor数据 组装完毕 ：775,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 775 ----- 1
正在处理 775 ----- 2
正在处理 775 ----- 3
正在处理 775 ----- 4
正在处理 775 ----- 5
正在处理 775 ----- 6
正在处理 775 ----- 7
正在处理 775 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 775
============================

正在读取第 776 个DF
初始化batch数据： 776
batch数据 组装完毕 ：776
batch_tensor数据 组装完毕 ：776,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 776 ----- 1
正在处理 776 ----- 2
正在处理 776 ----- 3
正在处理 776 ----- 4
正在处理 776 ----- 5
正在处理 776 ----- 6
正在处理 776 ----- 7
正在处理 776 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 776
============================

正在读取第 777 个DF
初始化batch数据： 777
batch数据 组装完毕 ：777
batch_tensor数据 组装完毕 ：777,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 777 ----- 1
正在处理 777 ----- 2
正在处理 777 ----- 3
正在处理 777 ----- 4
正在处理 777 ----- 5
正在处理 777 ----- 6
正在处理 777 ----- 7
正在处理 777 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 777
============================

正在读取第 778 个DF
初始化batch数据： 778
batch数据 组装完毕 ：778
batch_tensor数据 组装完毕 ：778,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 778 ----- 1
正在处理 778 ----- 2
正在处理 778 ----- 3
正在处理 778 ----- 4
正在处理 778 ----- 5
正在处理 778 ----- 6
正在处理 778 ----- 7
正在处理 778 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 778
============================

正在读取第 779 个DF
初始化batch数据： 779
batch数据 组装完毕 ：779
batch_tensor数据 组装完毕 ：779,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 779 ----- 1
正在处理 779 ----- 2
正在处理 779 ----- 3
正在处理 779 ----- 4
正在处理 779 ----- 5
正在处理 779 ----- 6
正在处理 779 ----- 7
正在处理 779 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 779
============================

正在读取第 780 个DF
初始化batch数据： 780
batch数据 组装完毕 ：780
batch_tensor数据 组装完毕 ：780,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 780 ----- 1
正在处理 780 ----- 2
正在处理 780 ----- 3
正在处理 780 ----- 4
正在处理 780 ----- 5
正在处理 780 ----- 6
正在处理 780 ----- 7
正在处理 780 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 780
============================

正在读取第 781 个DF
初始化batch数据： 781
batch数据 组装完毕 ：781
batch_tensor数据 组装完毕 ：781,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 781 ----- 1
正在处理 781 ----- 2
正在处理 781 ----- 3
正在处理 781 ----- 4
正在处理 781 ----- 5
正在处理 781 ----- 6
正在处理 781 ----- 7
正在处理 781 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 781
============================

正在读取第 782 个DF
初始化batch数据： 782
batch数据 组装完毕 ：782
batch_tensor数据 组装完毕 ：782,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 782 ----- 1
正在处理 782 ----- 2
正在处理 782 ----- 3
正在处理 782 ----- 4
正在处理 782 ----- 5
正在处理 782 ----- 6
正在处理 782 ----- 7
正在处理 782 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 782
============================

正在读取第 783 个DF
初始化batch数据： 783
batch数据 组装完毕 ：783
batch_tensor数据 组装完毕 ：783,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 783 ----- 1
正在处理 783 ----- 2
正在处理 783 ----- 3
正在处理 783 ----- 4
正在处理 783 ----- 5
正在处理 783 ----- 6
正在处理 783 ----- 7
正在处理 783 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 783
============================

正在读取第 784 个DF
初始化batch数据： 784
batch数据 组装完毕 ：784
batch_tensor数据 组装完毕 ：784,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 784 ----- 1
正在处理 784 ----- 2
正在处理 784 ----- 3
正在处理 784 ----- 4
正在处理 784 ----- 5
正在处理 784 ----- 6
正在处理 784 ----- 7
正在处理 784 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 784
============================

正在读取第 785 个DF
初始化batch数据： 785
batch数据 组装完毕 ：785
batch_tensor数据 组装完毕 ：785,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 785 ----- 1
正在处理 785 ----- 2
正在处理 785 ----- 3
正在处理 785 ----- 4
正在处理 785 ----- 5
正在处理 785 ----- 6
正在处理 785 ----- 7
正在处理 785 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 785
============================

正在读取第 786 个DF
初始化batch数据： 786
batch数据 组装完毕 ：786
batch_tensor数据 组装完毕 ：786,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 786 ----- 1
正在处理 786 ----- 2
正在处理 786 ----- 3
正在处理 786 ----- 4
正在处理 786 ----- 5
正在处理 786 ----- 6
正在处理 786 ----- 7
正在处理 786 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 786
============================

正在读取第 787 个DF
初始化batch数据： 787
batch数据 组装完毕 ：787
batch_tensor数据 组装完毕 ：787,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 787 ----- 1
正在处理 787 ----- 2
正在处理 787 ----- 3
正在处理 787 ----- 4
正在处理 787 ----- 5
正在处理 787 ----- 6
正在处理 787 ----- 7
正在处理 787 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 787
============================

正在读取第 788 个DF
初始化batch数据： 788
batch数据 组装完毕 ：788
batch_tensor数据 组装完毕 ：788,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 788 ----- 1
正在处理 788 ----- 2
正在处理 788 ----- 3
正在处理 788 ----- 4
正在处理 788 ----- 5
正在处理 788 ----- 6
正在处理 788 ----- 7
正在处理 788 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 788
============================

正在读取第 789 个DF
初始化batch数据： 789
batch数据 组装完毕 ：789
batch_tensor数据 组装完毕 ：789,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 789 ----- 1
正在处理 789 ----- 2
正在处理 789 ----- 3
正在处理 789 ----- 4
正在处理 789 ----- 5
正在处理 789 ----- 6
正在处理 789 ----- 7
正在处理 789 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 789
============================

正在读取第 790 个DF
初始化batch数据： 790
batch数据 组装完毕 ：790
batch_tensor数据 组装完毕 ：790,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 790 ----- 1
正在处理 790 ----- 2
正在处理 790 ----- 3
正在处理 790 ----- 4
正在处理 790 ----- 5
正在处理 790 ----- 6
正在处理 790 ----- 7
正在处理 790 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 790
============================

正在读取第 791 个DF
初始化batch数据： 791
batch数据 组装完毕 ：791
batch_tensor数据 组装完毕 ：791,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 791 ----- 1
正在处理 791 ----- 2
正在处理 791 ----- 3
正在处理 791 ----- 4
正在处理 791 ----- 5
正在处理 791 ----- 6
正在处理 791 ----- 7
正在处理 791 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 791
============================

正在读取第 792 个DF
初始化batch数据： 792
batch数据 组装完毕 ：792
batch_tensor数据 组装完毕 ：792,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 792 ----- 1
正在处理 792 ----- 2
正在处理 792 ----- 3
正在处理 792 ----- 4
正在处理 792 ----- 5
正在处理 792 ----- 6
正在处理 792 ----- 7
正在处理 792 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 792
============================

正在读取第 793 个DF
初始化batch数据： 793
batch数据 组装完毕 ：793
batch_tensor数据 组装完毕 ：793,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 793 ----- 1
正在处理 793 ----- 2
正在处理 793 ----- 3
正在处理 793 ----- 4
正在处理 793 ----- 5
正在处理 793 ----- 6
正在处理 793 ----- 7
正在处理 793 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 793
============================

正在读取第 794 个DF
初始化batch数据： 794
batch数据 组装完毕 ：794
batch_tensor数据 组装完毕 ：794,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 794 ----- 1
正在处理 794 ----- 2
正在处理 794 ----- 3
正在处理 794 ----- 4
正在处理 794 ----- 5
正在处理 794 ----- 6
正在处理 794 ----- 7
正在处理 794 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 794
============================

正在读取第 795 个DF
初始化batch数据： 795
batch数据 组装完毕 ：795
batch_tensor数据 组装完毕 ：795,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 795 ----- 1
正在处理 795 ----- 2
正在处理 795 ----- 3
正在处理 795 ----- 4
正在处理 795 ----- 5
正在处理 795 ----- 6
正在处理 795 ----- 7
正在处理 795 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 795
============================

正在读取第 796 个DF
初始化batch数据： 796
batch数据 组装完毕 ：796
batch_tensor数据 组装完毕 ：796,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 796 ----- 1
正在处理 796 ----- 2
正在处理 796 ----- 3
正在处理 796 ----- 4
正在处理 796 ----- 5
正在处理 796 ----- 6
正在处理 796 ----- 7
正在处理 796 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 796
============================

正在读取第 797 个DF
初始化batch数据： 797
batch数据 组装完毕 ：797
batch_tensor数据 组装完毕 ：797,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 797 ----- 1
正在处理 797 ----- 2
正在处理 797 ----- 3
正在处理 797 ----- 4
正在处理 797 ----- 5
正在处理 797 ----- 6
正在处理 797 ----- 7
正在处理 797 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 797
============================

正在读取第 798 个DF
初始化batch数据： 798
batch数据 组装完毕 ：798
batch_tensor数据 组装完毕 ：798,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 798 ----- 1
正在处理 798 ----- 2
正在处理 798 ----- 3
正在处理 798 ----- 4
正在处理 798 ----- 5
正在处理 798 ----- 6
正在处理 798 ----- 7
正在处理 798 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 798
============================

正在读取第 799 个DF
初始化batch数据： 799
batch数据 组装完毕 ：799
batch_tensor数据 组装完毕 ：799,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 799 ----- 1
正在处理 799 ----- 2
正在处理 799 ----- 3
正在处理 799 ----- 4
正在处理 799 ----- 5
正在处理 799 ----- 6
正在处理 799 ----- 7
正在处理 799 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 799
============================

正在读取第 800 个DF
初始化batch数据： 800
batch数据 组装完毕 ：800
batch_tensor数据 组装完毕 ：800,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 800 ----- 1
正在处理 800 ----- 2
正在处理 800 ----- 3
正在处理 800 ----- 4
正在处理 800 ----- 5
正在处理 800 ----- 6
正在处理 800 ----- 7
正在处理 800 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 800
============================

正在读取第 801 个DF
初始化batch数据： 801
batch数据 组装完毕 ：801
batch_tensor数据 组装完毕 ：801,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 801 ----- 1
正在处理 801 ----- 2
正在处理 801 ----- 3
正在处理 801 ----- 4
正在处理 801 ----- 5
正在处理 801 ----- 6
正在处理 801 ----- 7
正在处理 801 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 801
============================

正在读取第 802 个DF
初始化batch数据： 802
batch数据 组装完毕 ：802
batch_tensor数据 组装完毕 ：802,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 802 ----- 1
正在处理 802 ----- 2
正在处理 802 ----- 3
正在处理 802 ----- 4
正在处理 802 ----- 5
正在处理 802 ----- 6
正在处理 802 ----- 7
正在处理 802 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 802
============================

正在读取第 803 个DF
初始化batch数据： 803
batch数据 组装完毕 ：803
batch_tensor数据 组装完毕 ：803,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 803 ----- 1
正在处理 803 ----- 2
正在处理 803 ----- 3
正在处理 803 ----- 4
正在处理 803 ----- 5
正在处理 803 ----- 6
正在处理 803 ----- 7
正在处理 803 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 803
============================

正在读取第 804 个DF
初始化batch数据： 804
batch数据 组装完毕 ：804
batch_tensor数据 组装完毕 ：804,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 804 ----- 1
正在处理 804 ----- 2
正在处理 804 ----- 3
正在处理 804 ----- 4
正在处理 804 ----- 5
正在处理 804 ----- 6
正在处理 804 ----- 7
正在处理 804 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 804
============================

正在读取第 805 个DF
初始化batch数据： 805
batch数据 组装完毕 ：805
batch_tensor数据 组装完毕 ：805,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 805 ----- 1
正在处理 805 ----- 2
正在处理 805 ----- 3
正在处理 805 ----- 4
正在处理 805 ----- 5
正在处理 805 ----- 6
正在处理 805 ----- 7
正在处理 805 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 805
============================

正在读取第 806 个DF
初始化batch数据： 806
batch数据 组装完毕 ：806
batch_tensor数据 组装完毕 ：806,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 806 ----- 1
正在处理 806 ----- 2
正在处理 806 ----- 3
正在处理 806 ----- 4
正在处理 806 ----- 5
正在处理 806 ----- 6
正在处理 806 ----- 7
正在处理 806 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 806
============================

正在读取第 807 个DF
初始化batch数据： 807
batch数据 组装完毕 ：807
batch_tensor数据 组装完毕 ：807,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 807 ----- 1
正在处理 807 ----- 2
正在处理 807 ----- 3
正在处理 807 ----- 4
正在处理 807 ----- 5
正在处理 807 ----- 6
正在处理 807 ----- 7
正在处理 807 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 807
============================

正在读取第 808 个DF
初始化batch数据： 808
batch数据 组装完毕 ：808
batch_tensor数据 组装完毕 ：808,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 808 ----- 1
正在处理 808 ----- 2
正在处理 808 ----- 3
正在处理 808 ----- 4
正在处理 808 ----- 5
正在处理 808 ----- 6
正在处理 808 ----- 7
正在处理 808 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 808
============================

正在读取第 809 个DF
初始化batch数据： 809
batch数据 组装完毕 ：809
batch_tensor数据 组装完毕 ：809,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 809 ----- 1
正在处理 809 ----- 2
正在处理 809 ----- 3
正在处理 809 ----- 4
正在处理 809 ----- 5
正在处理 809 ----- 6
正在处理 809 ----- 7
正在处理 809 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 809
============================

正在读取第 810 个DF
初始化batch数据： 810
batch数据 组装完毕 ：810
batch_tensor数据 组装完毕 ：810,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 810 ----- 1
正在处理 810 ----- 2
正在处理 810 ----- 3
正在处理 810 ----- 4
正在处理 810 ----- 5
正在处理 810 ----- 6
正在处理 810 ----- 7
正在处理 810 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 810
============================

正在读取第 811 个DF
初始化batch数据： 811
batch数据 组装完毕 ：811
batch_tensor数据 组装完毕 ：811,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 811 ----- 1
正在处理 811 ----- 2
正在处理 811 ----- 3
正在处理 811 ----- 4
正在处理 811 ----- 5
正在处理 811 ----- 6
正在处理 811 ----- 7
正在处理 811 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 811
============================

正在读取第 812 个DF
初始化batch数据： 812
batch数据 组装完毕 ：812
batch_tensor数据 组装完毕 ：812,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 812 ----- 1
正在处理 812 ----- 2
正在处理 812 ----- 3
正在处理 812 ----- 4
正在处理 812 ----- 5
正在处理 812 ----- 6
正在处理 812 ----- 7
正在处理 812 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 812
============================

正在读取第 813 个DF
初始化batch数据： 813
batch数据 组装完毕 ：813
batch_tensor数据 组装完毕 ：813,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 813 ----- 1
正在处理 813 ----- 2
正在处理 813 ----- 3
正在处理 813 ----- 4
正在处理 813 ----- 5
正在处理 813 ----- 6
正在处理 813 ----- 7
正在处理 813 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 813
============================

正在读取第 814 个DF
初始化batch数据： 814
batch数据 组装完毕 ：814
batch_tensor数据 组装完毕 ：814,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 814 ----- 1
正在处理 814 ----- 2
正在处理 814 ----- 3
正在处理 814 ----- 4
正在处理 814 ----- 5
正在处理 814 ----- 6
正在处理 814 ----- 7
正在处理 814 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 814
============================

正在读取第 815 个DF
初始化batch数据： 815
batch数据 组装完毕 ：815
batch_tensor数据 组装完毕 ：815,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 815 ----- 1
正在处理 815 ----- 2
正在处理 815 ----- 3
正在处理 815 ----- 4
正在处理 815 ----- 5
正在处理 815 ----- 6
正在处理 815 ----- 7
正在处理 815 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 815
============================

正在读取第 816 个DF
初始化batch数据： 816
batch数据 组装完毕 ：816
batch_tensor数据 组装完毕 ：816,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 816 ----- 1
正在处理 816 ----- 2
正在处理 816 ----- 3
正在处理 816 ----- 4
正在处理 816 ----- 5
正在处理 816 ----- 6
正在处理 816 ----- 7
正在处理 816 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 816
============================

正在读取第 817 个DF
初始化batch数据： 817
batch数据 组装完毕 ：817
batch_tensor数据 组装完毕 ：817,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 817 ----- 1
正在处理 817 ----- 2
正在处理 817 ----- 3
正在处理 817 ----- 4
正在处理 817 ----- 5
正在处理 817 ----- 6
正在处理 817 ----- 7
正在处理 817 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 817
============================

正在读取第 818 个DF
初始化batch数据： 818
batch数据 组装完毕 ：818
batch_tensor数据 组装完毕 ：818,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 818 ----- 1
正在处理 818 ----- 2
正在处理 818 ----- 3
正在处理 818 ----- 4
正在处理 818 ----- 5
正在处理 818 ----- 6
正在处理 818 ----- 7
正在处理 818 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 818
============================

正在读取第 819 个DF
初始化batch数据： 819
batch数据 组装完毕 ：819
batch_tensor数据 组装完毕 ：819,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 819 ----- 1
正在处理 819 ----- 2
正在处理 819 ----- 3
正在处理 819 ----- 4
正在处理 819 ----- 5
正在处理 819 ----- 6
正在处理 819 ----- 7
正在处理 819 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 819
============================

正在读取第 820 个DF
初始化batch数据： 820
batch数据 组装完毕 ：820
batch_tensor数据 组装完毕 ：820,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 820 ----- 1
正在处理 820 ----- 2
正在处理 820 ----- 3
正在处理 820 ----- 4
正在处理 820 ----- 5
正在处理 820 ----- 6
正在处理 820 ----- 7
正在处理 820 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 820
============================

正在读取第 821 个DF
初始化batch数据： 821
batch数据 组装完毕 ：821
batch_tensor数据 组装完毕 ：821,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 821 ----- 1
正在处理 821 ----- 2
正在处理 821 ----- 3
正在处理 821 ----- 4
正在处理 821 ----- 5
正在处理 821 ----- 6
正在处理 821 ----- 7
正在处理 821 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 821
============================

正在读取第 822 个DF
初始化batch数据： 822
batch数据 组装完毕 ：822
batch_tensor数据 组装完毕 ：822,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 822 ----- 1
正在处理 822 ----- 2
正在处理 822 ----- 3
正在处理 822 ----- 4
正在处理 822 ----- 5
正在处理 822 ----- 6
正在处理 822 ----- 7
正在处理 822 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 822
============================

正在读取第 823 个DF
初始化batch数据： 823
batch数据 组装完毕 ：823
batch_tensor数据 组装完毕 ：823,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 823 ----- 1
正在处理 823 ----- 2
正在处理 823 ----- 3
正在处理 823 ----- 4
正在处理 823 ----- 5
正在处理 823 ----- 6
正在处理 823 ----- 7
正在处理 823 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 823
============================

正在读取第 824 个DF
初始化batch数据： 824
batch数据 组装完毕 ：824
batch_tensor数据 组装完毕 ：824,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 824 ----- 1
正在处理 824 ----- 2
正在处理 824 ----- 3
正在处理 824 ----- 4
正在处理 824 ----- 5
正在处理 824 ----- 6
正在处理 824 ----- 7
正在处理 824 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 824
============================

正在读取第 825 个DF
初始化batch数据： 825
batch数据 组装完毕 ：825
batch_tensor数据 组装完毕 ：825,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 825 ----- 1
正在处理 825 ----- 2
正在处理 825 ----- 3
正在处理 825 ----- 4
正在处理 825 ----- 5
正在处理 825 ----- 6
正在处理 825 ----- 7
正在处理 825 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 825
============================

正在读取第 826 个DF
初始化batch数据： 826
batch数据 组装完毕 ：826
batch_tensor数据 组装完毕 ：826,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 826 ----- 1
正在处理 826 ----- 2
正在处理 826 ----- 3
正在处理 826 ----- 4
正在处理 826 ----- 5
正在处理 826 ----- 6
正在处理 826 ----- 7
正在处理 826 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 826
============================

正在读取第 827 个DF
初始化batch数据： 827
batch数据 组装完毕 ：827
batch_tensor数据 组装完毕 ：827,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 827 ----- 1
正在处理 827 ----- 2
正在处理 827 ----- 3
正在处理 827 ----- 4
正在处理 827 ----- 5
正在处理 827 ----- 6
正在处理 827 ----- 7
正在处理 827 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 827
============================

正在读取第 828 个DF
初始化batch数据： 828
batch数据 组装完毕 ：828
batch_tensor数据 组装完毕 ：828,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 828 ----- 1
正在处理 828 ----- 2
正在处理 828 ----- 3
正在处理 828 ----- 4
正在处理 828 ----- 5
正在处理 828 ----- 6
正在处理 828 ----- 7
正在处理 828 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 828
============================

正在读取第 829 个DF
初始化batch数据： 829
batch数据 组装完毕 ：829
batch_tensor数据 组装完毕 ：829,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 829 ----- 1
正在处理 829 ----- 2
正在处理 829 ----- 3
正在处理 829 ----- 4
正在处理 829 ----- 5
正在处理 829 ----- 6
正在处理 829 ----- 7
正在处理 829 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 829
============================

正在读取第 830 个DF
初始化batch数据： 830
batch数据 组装完毕 ：830
batch_tensor数据 组装完毕 ：830,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 830 ----- 1
正在处理 830 ----- 2
正在处理 830 ----- 3
正在处理 830 ----- 4
正在处理 830 ----- 5
正在处理 830 ----- 6
正在处理 830 ----- 7
正在处理 830 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 830
============================

正在读取第 831 个DF
初始化batch数据： 831
batch数据 组装完毕 ：831
batch_tensor数据 组装完毕 ：831,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 831 ----- 1
正在处理 831 ----- 2
正在处理 831 ----- 3
正在处理 831 ----- 4
正在处理 831 ----- 5
正在处理 831 ----- 6
正在处理 831 ----- 7
正在处理 831 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 831
============================

正在读取第 832 个DF
初始化batch数据： 832
batch数据 组装完毕 ：832
batch_tensor数据 组装完毕 ：832,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 832 ----- 1
正在处理 832 ----- 2
正在处理 832 ----- 3
正在处理 832 ----- 4
正在处理 832 ----- 5
正在处理 832 ----- 6
正在处理 832 ----- 7
正在处理 832 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 832
============================

正在读取第 833 个DF
初始化batch数据： 833
batch数据 组装完毕 ：833
batch_tensor数据 组装完毕 ：833,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 833 ----- 1
正在处理 833 ----- 2
正在处理 833 ----- 3
正在处理 833 ----- 4
正在处理 833 ----- 5
正在处理 833 ----- 6
正在处理 833 ----- 7
正在处理 833 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 833
============================

正在读取第 834 个DF
初始化batch数据： 834
batch数据 组装完毕 ：834
batch_tensor数据 组装完毕 ：834,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 834 ----- 1
正在处理 834 ----- 2
正在处理 834 ----- 3
正在处理 834 ----- 4
正在处理 834 ----- 5
正在处理 834 ----- 6
正在处理 834 ----- 7
正在处理 834 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 834
============================

正在读取第 835 个DF
初始化batch数据： 835
batch数据 组装完毕 ：835
batch_tensor数据 组装完毕 ：835,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 835 ----- 1
正在处理 835 ----- 2
正在处理 835 ----- 3
正在处理 835 ----- 4
正在处理 835 ----- 5
正在处理 835 ----- 6
正在处理 835 ----- 7
正在处理 835 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 835
============================

正在读取第 836 个DF
初始化batch数据： 836
batch数据 组装完毕 ：836
batch_tensor数据 组装完毕 ：836,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 836 ----- 1
正在处理 836 ----- 2
正在处理 836 ----- 3
正在处理 836 ----- 4
正在处理 836 ----- 5
正在处理 836 ----- 6
正在处理 836 ----- 7
正在处理 836 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 836
============================

正在读取第 837 个DF
初始化batch数据： 837
batch数据 组装完毕 ：837
batch_tensor数据 组装完毕 ：837,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 837 ----- 1
正在处理 837 ----- 2
正在处理 837 ----- 3
正在处理 837 ----- 4
正在处理 837 ----- 5
正在处理 837 ----- 6
正在处理 837 ----- 7
正在处理 837 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 837
============================

正在读取第 838 个DF
初始化batch数据： 838
batch数据 组装完毕 ：838
batch_tensor数据 组装完毕 ：838,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 838 ----- 1
正在处理 838 ----- 2
正在处理 838 ----- 3
正在处理 838 ----- 4
正在处理 838 ----- 5
正在处理 838 ----- 6
正在处理 838 ----- 7
正在处理 838 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 838
============================

正在读取第 839 个DF
初始化batch数据： 839
batch数据 组装完毕 ：839
batch_tensor数据 组装完毕 ：839,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 839 ----- 1
正在处理 839 ----- 2
正在处理 839 ----- 3
正在处理 839 ----- 4
正在处理 839 ----- 5
正在处理 839 ----- 6
正在处理 839 ----- 7
正在处理 839 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 839
============================

正在读取第 840 个DF
初始化batch数据： 840
batch数据 组装完毕 ：840
batch_tensor数据 组装完毕 ：840,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 840 ----- 1
正在处理 840 ----- 2
正在处理 840 ----- 3
正在处理 840 ----- 4
正在处理 840 ----- 5
正在处理 840 ----- 6
正在处理 840 ----- 7
正在处理 840 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 840
============================

正在读取第 841 个DF
初始化batch数据： 841
batch数据 组装完毕 ：841
batch_tensor数据 组装完毕 ：841,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 841 ----- 1
正在处理 841 ----- 2
正在处理 841 ----- 3
正在处理 841 ----- 4
正在处理 841 ----- 5
正在处理 841 ----- 6
正在处理 841 ----- 7
正在处理 841 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 841
============================

正在读取第 842 个DF
初始化batch数据： 842
batch数据 组装完毕 ：842
batch_tensor数据 组装完毕 ：842,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 842 ----- 1
正在处理 842 ----- 2
正在处理 842 ----- 3
正在处理 842 ----- 4
正在处理 842 ----- 5
正在处理 842 ----- 6
正在处理 842 ----- 7
正在处理 842 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 842
============================

正在读取第 843 个DF
初始化batch数据： 843
batch数据 组装完毕 ：843
batch_tensor数据 组装完毕 ：843,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 843 ----- 1
正在处理 843 ----- 2
正在处理 843 ----- 3
正在处理 843 ----- 4
正在处理 843 ----- 5
正在处理 843 ----- 6
正在处理 843 ----- 7
正在处理 843 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 843
============================

正在读取第 844 个DF
初始化batch数据： 844
batch数据 组装完毕 ：844
batch_tensor数据 组装完毕 ：844,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 844 ----- 1
正在处理 844 ----- 2
正在处理 844 ----- 3
正在处理 844 ----- 4
正在处理 844 ----- 5
正在处理 844 ----- 6
正在处理 844 ----- 7
正在处理 844 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 844
============================

正在读取第 845 个DF
初始化batch数据： 845
batch数据 组装完毕 ：845
batch_tensor数据 组装完毕 ：845,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 845 ----- 1
正在处理 845 ----- 2
正在处理 845 ----- 3
正在处理 845 ----- 4
正在处理 845 ----- 5
正在处理 845 ----- 6
正在处理 845 ----- 7
正在处理 845 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 845
============================

正在读取第 846 个DF
初始化batch数据： 846
batch数据 组装完毕 ：846
batch_tensor数据 组装完毕 ：846,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 846 ----- 1
正在处理 846 ----- 2
正在处理 846 ----- 3
正在处理 846 ----- 4
正在处理 846 ----- 5
正在处理 846 ----- 6
正在处理 846 ----- 7
正在处理 846 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 846
============================

正在读取第 847 个DF
初始化batch数据： 847
batch数据 组装完毕 ：847
batch_tensor数据 组装完毕 ：847,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 847 ----- 1
正在处理 847 ----- 2
正在处理 847 ----- 3
正在处理 847 ----- 4
正在处理 847 ----- 5
正在处理 847 ----- 6
正在处理 847 ----- 7
正在处理 847 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 847
============================

正在读取第 848 个DF
初始化batch数据： 848
batch数据 组装完毕 ：848
batch_tensor数据 组装完毕 ：848,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 848 ----- 1
正在处理 848 ----- 2
正在处理 848 ----- 3
正在处理 848 ----- 4
正在处理 848 ----- 5
正在处理 848 ----- 6
正在处理 848 ----- 7
正在处理 848 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 848
============================

正在读取第 849 个DF
初始化batch数据： 849
batch数据 组装完毕 ：849
batch_tensor数据 组装完毕 ：849,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 849 ----- 1
正在处理 849 ----- 2
正在处理 849 ----- 3
正在处理 849 ----- 4
正在处理 849 ----- 5
正在处理 849 ----- 6
正在处理 849 ----- 7
正在处理 849 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 849
============================

正在读取第 850 个DF
初始化batch数据： 850
batch数据 组装完毕 ：850
batch_tensor数据 组装完毕 ：850,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 850 ----- 1
正在处理 850 ----- 2
正在处理 850 ----- 3
正在处理 850 ----- 4
正在处理 850 ----- 5
正在处理 850 ----- 6
正在处理 850 ----- 7
正在处理 850 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 850
============================

正在读取第 851 个DF
初始化batch数据： 851
batch数据 组装完毕 ：851
batch_tensor数据 组装完毕 ：851,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 851 ----- 1
正在处理 851 ----- 2
正在处理 851 ----- 3
正在处理 851 ----- 4
正在处理 851 ----- 5
正在处理 851 ----- 6
正在处理 851 ----- 7
正在处理 851 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 851
============================

正在读取第 852 个DF
初始化batch数据： 852
batch数据 组装完毕 ：852
batch_tensor数据 组装完毕 ：852,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 852 ----- 1
正在处理 852 ----- 2
正在处理 852 ----- 3
正在处理 852 ----- 4
正在处理 852 ----- 5
正在处理 852 ----- 6
正在处理 852 ----- 7
正在处理 852 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 852
============================

正在读取第 853 个DF
初始化batch数据： 853
batch数据 组装完毕 ：853
batch_tensor数据 组装完毕 ：853,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 853 ----- 1
正在处理 853 ----- 2
正在处理 853 ----- 3
正在处理 853 ----- 4
正在处理 853 ----- 5
正在处理 853 ----- 6
正在处理 853 ----- 7
正在处理 853 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 853
============================

正在读取第 854 个DF
初始化batch数据： 854
batch数据 组装完毕 ：854
batch_tensor数据 组装完毕 ：854,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 854 ----- 1
正在处理 854 ----- 2
正在处理 854 ----- 3
正在处理 854 ----- 4
正在处理 854 ----- 5
正在处理 854 ----- 6
正在处理 854 ----- 7
正在处理 854 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 854
============================

正在读取第 855 个DF
初始化batch数据： 855
batch数据 组装完毕 ：855
batch_tensor数据 组装完毕 ：855,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 855 ----- 1
正在处理 855 ----- 2
正在处理 855 ----- 3
正在处理 855 ----- 4
正在处理 855 ----- 5
正在处理 855 ----- 6
正在处理 855 ----- 7
正在处理 855 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 855
============================

正在读取第 856 个DF
初始化batch数据： 856
batch数据 组装完毕 ：856
batch_tensor数据 组装完毕 ：856,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 856 ----- 1
正在处理 856 ----- 2
正在处理 856 ----- 3
正在处理 856 ----- 4
正在处理 856 ----- 5
正在处理 856 ----- 6
正在处理 856 ----- 7
正在处理 856 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 856
============================

正在读取第 857 个DF
初始化batch数据： 857
batch数据 组装完毕 ：857
batch_tensor数据 组装完毕 ：857,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 857 ----- 1
正在处理 857 ----- 2
正在处理 857 ----- 3
正在处理 857 ----- 4
正在处理 857 ----- 5
正在处理 857 ----- 6
正在处理 857 ----- 7
正在处理 857 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 857
============================

正在读取第 858 个DF
初始化batch数据： 858
batch数据 组装完毕 ：858
batch_tensor数据 组装完毕 ：858,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 858 ----- 1
正在处理 858 ----- 2
正在处理 858 ----- 3
正在处理 858 ----- 4
正在处理 858 ----- 5
正在处理 858 ----- 6
正在处理 858 ----- 7
正在处理 858 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 858
============================

正在读取第 859 个DF
初始化batch数据： 859
batch数据 组装完毕 ：859
batch_tensor数据 组装完毕 ：859,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 859 ----- 1
正在处理 859 ----- 2
正在处理 859 ----- 3
正在处理 859 ----- 4
正在处理 859 ----- 5
正在处理 859 ----- 6
正在处理 859 ----- 7
正在处理 859 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 859
============================

正在读取第 860 个DF
初始化batch数据： 860
batch数据 组装完毕 ：860
batch_tensor数据 组装完毕 ：860,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 860 ----- 1
正在处理 860 ----- 2
正在处理 860 ----- 3
正在处理 860 ----- 4
正在处理 860 ----- 5
正在处理 860 ----- 6
正在处理 860 ----- 7
正在处理 860 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 860
============================

正在读取第 861 个DF
初始化batch数据： 861
batch数据 组装完毕 ：861
batch_tensor数据 组装完毕 ：861,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 861 ----- 1
正在处理 861 ----- 2
正在处理 861 ----- 3
正在处理 861 ----- 4
正在处理 861 ----- 5
正在处理 861 ----- 6
正在处理 861 ----- 7
正在处理 861 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 861
============================

正在读取第 862 个DF
初始化batch数据： 862
batch数据 组装完毕 ：862
batch_tensor数据 组装完毕 ：862,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 862 ----- 1
正在处理 862 ----- 2
正在处理 862 ----- 3
正在处理 862 ----- 4
正在处理 862 ----- 5
正在处理 862 ----- 6
正在处理 862 ----- 7
正在处理 862 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 862
============================

正在读取第 863 个DF
初始化batch数据： 863
batch数据 组装完毕 ：863
batch_tensor数据 组装完毕 ：863,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 863 ----- 1
正在处理 863 ----- 2
正在处理 863 ----- 3
正在处理 863 ----- 4
正在处理 863 ----- 5
正在处理 863 ----- 6
正在处理 863 ----- 7
正在处理 863 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 863
============================

正在读取第 864 个DF
初始化batch数据： 864
batch数据 组装完毕 ：864
batch_tensor数据 组装完毕 ：864,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 864 ----- 1
正在处理 864 ----- 2
正在处理 864 ----- 3
正在处理 864 ----- 4
正在处理 864 ----- 5
正在处理 864 ----- 6
正在处理 864 ----- 7
正在处理 864 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 864
============================

正在读取第 865 个DF
初始化batch数据： 865
batch数据 组装完毕 ：865
batch_tensor数据 组装完毕 ：865,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 865 ----- 1
正在处理 865 ----- 2
正在处理 865 ----- 3
正在处理 865 ----- 4
正在处理 865 ----- 5
正在处理 865 ----- 6
正在处理 865 ----- 7
正在处理 865 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 865
============================

正在读取第 866 个DF
初始化batch数据： 866
batch数据 组装完毕 ：866
batch_tensor数据 组装完毕 ：866,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 866 ----- 1
正在处理 866 ----- 2
正在处理 866 ----- 3
正在处理 866 ----- 4
正在处理 866 ----- 5
正在处理 866 ----- 6
正在处理 866 ----- 7
正在处理 866 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 866
============================

正在读取第 867 个DF
初始化batch数据： 867
batch数据 组装完毕 ：867
batch_tensor数据 组装完毕 ：867,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 867 ----- 1
正在处理 867 ----- 2
正在处理 867 ----- 3
正在处理 867 ----- 4
正在处理 867 ----- 5
正在处理 867 ----- 6
正在处理 867 ----- 7
正在处理 867 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 867
============================

正在读取第 868 个DF
初始化batch数据： 868
batch数据 组装完毕 ：868
batch_tensor数据 组装完毕 ：868,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 868 ----- 1
正在处理 868 ----- 2
正在处理 868 ----- 3
正在处理 868 ----- 4
正在处理 868 ----- 5
正在处理 868 ----- 6
正在处理 868 ----- 7
正在处理 868 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 868
============================

正在读取第 869 个DF
初始化batch数据： 869
batch数据 组装完毕 ：869
batch_tensor数据 组装完毕 ：869,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 869 ----- 1
正在处理 869 ----- 2
正在处理 869 ----- 3
正在处理 869 ----- 4
正在处理 869 ----- 5
正在处理 869 ----- 6
正在处理 869 ----- 7
正在处理 869 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 869
============================

正在读取第 870 个DF
初始化batch数据： 870
batch数据 组装完毕 ：870
batch_tensor数据 组装完毕 ：870,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 870 ----- 1
正在处理 870 ----- 2
正在处理 870 ----- 3
正在处理 870 ----- 4
正在处理 870 ----- 5
正在处理 870 ----- 6
正在处理 870 ----- 7
正在处理 870 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 870
============================

正在读取第 871 个DF
初始化batch数据： 871
batch数据 组装完毕 ：871
batch_tensor数据 组装完毕 ：871,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 871 ----- 1
正在处理 871 ----- 2
正在处理 871 ----- 3
正在处理 871 ----- 4
正在处理 871 ----- 5
正在处理 871 ----- 6
正在处理 871 ----- 7
正在处理 871 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 871
============================

正在读取第 872 个DF
初始化batch数据： 872
batch数据 组装完毕 ：872
batch_tensor数据 组装完毕 ：872,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 872 ----- 1
正在处理 872 ----- 2
正在处理 872 ----- 3
正在处理 872 ----- 4
正在处理 872 ----- 5
正在处理 872 ----- 6
正在处理 872 ----- 7
正在处理 872 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 872
============================

正在读取第 873 个DF
初始化batch数据： 873
batch数据 组装完毕 ：873
batch_tensor数据 组装完毕 ：873,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 873 ----- 1
正在处理 873 ----- 2
正在处理 873 ----- 3
正在处理 873 ----- 4
正在处理 873 ----- 5
正在处理 873 ----- 6
正在处理 873 ----- 7
正在处理 873 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 873
============================

正在读取第 874 个DF
初始化batch数据： 874
batch数据 组装完毕 ：874
batch_tensor数据 组装完毕 ：874,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 874 ----- 1
正在处理 874 ----- 2
正在处理 874 ----- 3
正在处理 874 ----- 4
正在处理 874 ----- 5
正在处理 874 ----- 6
正在处理 874 ----- 7
正在处理 874 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 874
============================

正在读取第 875 个DF
初始化batch数据： 875
batch数据 组装完毕 ：875
batch_tensor数据 组装完毕 ：875,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 875 ----- 1
正在处理 875 ----- 2
正在处理 875 ----- 3
正在处理 875 ----- 4
正在处理 875 ----- 5
正在处理 875 ----- 6
正在处理 875 ----- 7
正在处理 875 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 875
============================

正在读取第 876 个DF
初始化batch数据： 876
batch数据 组装完毕 ：876
batch_tensor数据 组装完毕 ：876,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 876 ----- 1
正在处理 876 ----- 2
正在处理 876 ----- 3
正在处理 876 ----- 4
正在处理 876 ----- 5
正在处理 876 ----- 6
正在处理 876 ----- 7
正在处理 876 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 876
============================

正在读取第 877 个DF
初始化batch数据： 877
batch数据 组装完毕 ：877
batch_tensor数据 组装完毕 ：877,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 877 ----- 1
正在处理 877 ----- 2
正在处理 877 ----- 3
正在处理 877 ----- 4
正在处理 877 ----- 5
正在处理 877 ----- 6
正在处理 877 ----- 7
正在处理 877 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 877
============================

正在读取第 878 个DF
初始化batch数据： 878
batch数据 组装完毕 ：878
batch_tensor数据 组装完毕 ：878,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 878 ----- 1
正在处理 878 ----- 2
正在处理 878 ----- 3
正在处理 878 ----- 4
正在处理 878 ----- 5
正在处理 878 ----- 6
正在处理 878 ----- 7
正在处理 878 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 878
============================

正在读取第 879 个DF
初始化batch数据： 879
batch数据 组装完毕 ：879
batch_tensor数据 组装完毕 ：879,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 879 ----- 1
正在处理 879 ----- 2
正在处理 879 ----- 3
正在处理 879 ----- 4
正在处理 879 ----- 5
正在处理 879 ----- 6
正在处理 879 ----- 7
正在处理 879 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 879
============================

正在读取第 880 个DF
初始化batch数据： 880
batch数据 组装完毕 ：880
batch_tensor数据 组装完毕 ：880,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 880 ----- 1
正在处理 880 ----- 2
正在处理 880 ----- 3
正在处理 880 ----- 4
正在处理 880 ----- 5
正在处理 880 ----- 6
正在处理 880 ----- 7
正在处理 880 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 880
============================

正在读取第 881 个DF
初始化batch数据： 881
batch数据 组装完毕 ：881
batch_tensor数据 组装完毕 ：881,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 881 ----- 1
正在处理 881 ----- 2
正在处理 881 ----- 3
正在处理 881 ----- 4
正在处理 881 ----- 5
正在处理 881 ----- 6
正在处理 881 ----- 7
正在处理 881 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 881
============================

正在读取第 882 个DF
初始化batch数据： 882
batch数据 组装完毕 ：882
batch_tensor数据 组装完毕 ：882,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 882 ----- 1
正在处理 882 ----- 2
正在处理 882 ----- 3
正在处理 882 ----- 4
正在处理 882 ----- 5
正在处理 882 ----- 6
正在处理 882 ----- 7
正在处理 882 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 882
============================

正在读取第 883 个DF
初始化batch数据： 883
batch数据 组装完毕 ：883
batch_tensor数据 组装完毕 ：883,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 883 ----- 1
正在处理 883 ----- 2
正在处理 883 ----- 3
正在处理 883 ----- 4
正在处理 883 ----- 5
正在处理 883 ----- 6
正在处理 883 ----- 7
正在处理 883 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 883
============================

正在读取第 884 个DF
初始化batch数据： 884
batch数据 组装完毕 ：884
batch_tensor数据 组装完毕 ：884,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 884 ----- 1
正在处理 884 ----- 2
正在处理 884 ----- 3
正在处理 884 ----- 4
正在处理 884 ----- 5
正在处理 884 ----- 6
正在处理 884 ----- 7
正在处理 884 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 884
============================

正在读取第 885 个DF
初始化batch数据： 885
batch数据 组装完毕 ：885
batch_tensor数据 组装完毕 ：885,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 885 ----- 1
正在处理 885 ----- 2
正在处理 885 ----- 3
正在处理 885 ----- 4
正在处理 885 ----- 5
正在处理 885 ----- 6
正在处理 885 ----- 7
正在处理 885 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 885
============================

正在读取第 886 个DF
初始化batch数据： 886
batch数据 组装完毕 ：886
batch_tensor数据 组装完毕 ：886,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 886 ----- 1
正在处理 886 ----- 2
正在处理 886 ----- 3
正在处理 886 ----- 4
正在处理 886 ----- 5
正在处理 886 ----- 6
正在处理 886 ----- 7
正在处理 886 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 886
============================

正在读取第 887 个DF
初始化batch数据： 887
batch数据 组装完毕 ：887
batch_tensor数据 组装完毕 ：887,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 887 ----- 1
正在处理 887 ----- 2
正在处理 887 ----- 3
正在处理 887 ----- 4
正在处理 887 ----- 5
正在处理 887 ----- 6
正在处理 887 ----- 7
正在处理 887 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 887
============================

正在读取第 888 个DF
初始化batch数据： 888
batch数据 组装完毕 ：888
batch_tensor数据 组装完毕 ：888,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 888 ----- 1
正在处理 888 ----- 2
正在处理 888 ----- 3
正在处理 888 ----- 4
正在处理 888 ----- 5
正在处理 888 ----- 6
正在处理 888 ----- 7
正在处理 888 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 888
============================

正在读取第 889 个DF
初始化batch数据： 889
batch数据 组装完毕 ：889
batch_tensor数据 组装完毕 ：889,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 889 ----- 1
正在处理 889 ----- 2
正在处理 889 ----- 3
正在处理 889 ----- 4
正在处理 889 ----- 5
正在处理 889 ----- 6
正在处理 889 ----- 7
正在处理 889 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 889
============================

正在读取第 890 个DF
初始化batch数据： 890
batch数据 组装完毕 ：890
batch_tensor数据 组装完毕 ：890,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 890 ----- 1
正在处理 890 ----- 2
正在处理 890 ----- 3
正在处理 890 ----- 4
正在处理 890 ----- 5
正在处理 890 ----- 6
正在处理 890 ----- 7
正在处理 890 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 890
============================

正在读取第 891 个DF
初始化batch数据： 891
batch数据 组装完毕 ：891
batch_tensor数据 组装完毕 ：891,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 891 ----- 1
正在处理 891 ----- 2
正在处理 891 ----- 3
正在处理 891 ----- 4
正在处理 891 ----- 5
正在处理 891 ----- 6
正在处理 891 ----- 7
正在处理 891 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 891
============================

正在读取第 892 个DF
初始化batch数据： 892
batch数据 组装完毕 ：892
batch_tensor数据 组装完毕 ：892,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 892 ----- 1
正在处理 892 ----- 2
正在处理 892 ----- 3
正在处理 892 ----- 4
正在处理 892 ----- 5
正在处理 892 ----- 6
正在处理 892 ----- 7
正在处理 892 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 892
============================

正在读取第 893 个DF
初始化batch数据： 893
batch数据 组装完毕 ：893
batch_tensor数据 组装完毕 ：893,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 893 ----- 1
正在处理 893 ----- 2
正在处理 893 ----- 3
正在处理 893 ----- 4
正在处理 893 ----- 5
正在处理 893 ----- 6
正在处理 893 ----- 7
正在处理 893 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 893
============================

正在读取第 894 个DF
初始化batch数据： 894
batch数据 组装完毕 ：894
batch_tensor数据 组装完毕 ：894,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 894 ----- 1
正在处理 894 ----- 2
正在处理 894 ----- 3
正在处理 894 ----- 4
正在处理 894 ----- 5
正在处理 894 ----- 6
正在处理 894 ----- 7
正在处理 894 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 894
============================

正在读取第 895 个DF
初始化batch数据： 895
batch数据 组装完毕 ：895
batch_tensor数据 组装完毕 ：895,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 895 ----- 1
正在处理 895 ----- 2
正在处理 895 ----- 3
正在处理 895 ----- 4
正在处理 895 ----- 5
正在处理 895 ----- 6
正在处理 895 ----- 7
正在处理 895 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 895
============================

正在读取第 896 个DF
初始化batch数据： 896
batch数据 组装完毕 ：896
batch_tensor数据 组装完毕 ：896,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 896 ----- 1
正在处理 896 ----- 2
正在处理 896 ----- 3
正在处理 896 ----- 4
正在处理 896 ----- 5
正在处理 896 ----- 6
正在处理 896 ----- 7
正在处理 896 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 896
============================

正在读取第 897 个DF
初始化batch数据： 897
batch数据 组装完毕 ：897
batch_tensor数据 组装完毕 ：897,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 897 ----- 1
正在处理 897 ----- 2
正在处理 897 ----- 3
正在处理 897 ----- 4
正在处理 897 ----- 5
正在处理 897 ----- 6
正在处理 897 ----- 7
正在处理 897 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 897
============================

正在读取第 898 个DF
初始化batch数据： 898
batch数据 组装完毕 ：898
batch_tensor数据 组装完毕 ：898,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 898 ----- 1
正在处理 898 ----- 2
正在处理 898 ----- 3
正在处理 898 ----- 4
正在处理 898 ----- 5
正在处理 898 ----- 6
正在处理 898 ----- 7
正在处理 898 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 898
============================

正在读取第 899 个DF
初始化batch数据： 899
batch数据 组装完毕 ：899
batch_tensor数据 组装完毕 ：899,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 899 ----- 1
正在处理 899 ----- 2
正在处理 899 ----- 3
正在处理 899 ----- 4
正在处理 899 ----- 5
正在处理 899 ----- 6
正在处理 899 ----- 7
正在处理 899 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 899
============================

正在读取第 900 个DF
初始化batch数据： 900
batch数据 组装完毕 ：900
batch_tensor数据 组装完毕 ：900,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 900 ----- 1
正在处理 900 ----- 2
正在处理 900 ----- 3
正在处理 900 ----- 4
正在处理 900 ----- 5
正在处理 900 ----- 6
正在处理 900 ----- 7
正在处理 900 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 900
============================

正在读取第 901 个DF
初始化batch数据： 901
batch数据 组装完毕 ：901
batch_tensor数据 组装完毕 ：901,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 901 ----- 1
正在处理 901 ----- 2
正在处理 901 ----- 3
正在处理 901 ----- 4
正在处理 901 ----- 5
正在处理 901 ----- 6
正在处理 901 ----- 7
正在处理 901 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 901
============================

正在读取第 902 个DF
初始化batch数据： 902
batch数据 组装完毕 ：902
batch_tensor数据 组装完毕 ：902,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 902 ----- 1
正在处理 902 ----- 2
正在处理 902 ----- 3
正在处理 902 ----- 4
正在处理 902 ----- 5
正在处理 902 ----- 6
正在处理 902 ----- 7
正在处理 902 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 902
============================

正在读取第 903 个DF
初始化batch数据： 903
batch数据 组装完毕 ：903
batch_tensor数据 组装完毕 ：903,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 903 ----- 1
正在处理 903 ----- 2
正在处理 903 ----- 3
正在处理 903 ----- 4
正在处理 903 ----- 5
正在处理 903 ----- 6
正在处理 903 ----- 7
正在处理 903 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 903
============================

正在读取第 904 个DF
初始化batch数据： 904
batch数据 组装完毕 ：904
batch_tensor数据 组装完毕 ：904,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 904 ----- 1
正在处理 904 ----- 2
正在处理 904 ----- 3
正在处理 904 ----- 4
正在处理 904 ----- 5
正在处理 904 ----- 6
正在处理 904 ----- 7
正在处理 904 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 904
============================

正在读取第 905 个DF
初始化batch数据： 905
batch数据 组装完毕 ：905
batch_tensor数据 组装完毕 ：905,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 905 ----- 1
正在处理 905 ----- 2
正在处理 905 ----- 3
正在处理 905 ----- 4
正在处理 905 ----- 5
正在处理 905 ----- 6
正在处理 905 ----- 7
正在处理 905 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 905
============================

正在读取第 906 个DF
初始化batch数据： 906
batch数据 组装完毕 ：906
batch_tensor数据 组装完毕 ：906,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 906 ----- 1
正在处理 906 ----- 2
正在处理 906 ----- 3
正在处理 906 ----- 4
正在处理 906 ----- 5
正在处理 906 ----- 6
正在处理 906 ----- 7
正在处理 906 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 906
============================

正在读取第 907 个DF
初始化batch数据： 907
batch数据 组装完毕 ：907
batch_tensor数据 组装完毕 ：907,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 907 ----- 1
正在处理 907 ----- 2
正在处理 907 ----- 3
正在处理 907 ----- 4
正在处理 907 ----- 5
正在处理 907 ----- 6
正在处理 907 ----- 7
正在处理 907 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 907
============================

正在读取第 908 个DF
初始化batch数据： 908
batch数据 组装完毕 ：908
batch_tensor数据 组装完毕 ：908,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 908 ----- 1
正在处理 908 ----- 2
正在处理 908 ----- 3
正在处理 908 ----- 4
正在处理 908 ----- 5
正在处理 908 ----- 6
正在处理 908 ----- 7
正在处理 908 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 908
============================

正在读取第 909 个DF
初始化batch数据： 909
batch数据 组装完毕 ：909
batch_tensor数据 组装完毕 ：909,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 909 ----- 1
正在处理 909 ----- 2
正在处理 909 ----- 3
正在处理 909 ----- 4
正在处理 909 ----- 5
正在处理 909 ----- 6
正在处理 909 ----- 7
正在处理 909 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 909
============================

正在读取第 910 个DF
初始化batch数据： 910
batch数据 组装完毕 ：910
batch_tensor数据 组装完毕 ：910,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 910 ----- 1
正在处理 910 ----- 2
正在处理 910 ----- 3
正在处理 910 ----- 4
正在处理 910 ----- 5
正在处理 910 ----- 6
正在处理 910 ----- 7
正在处理 910 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 910
============================

正在读取第 911 个DF
初始化batch数据： 911
batch数据 组装完毕 ：911
batch_tensor数据 组装完毕 ：911,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 911 ----- 1
正在处理 911 ----- 2
正在处理 911 ----- 3
正在处理 911 ----- 4
正在处理 911 ----- 5
正在处理 911 ----- 6
正在处理 911 ----- 7
正在处理 911 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 911
============================

正在读取第 912 个DF
初始化batch数据： 912
batch数据 组装完毕 ：912
batch_tensor数据 组装完毕 ：912,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 912 ----- 1
正在处理 912 ----- 2
正在处理 912 ----- 3
正在处理 912 ----- 4
正在处理 912 ----- 5
正在处理 912 ----- 6
正在处理 912 ----- 7
正在处理 912 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 912
============================

正在读取第 913 个DF
初始化batch数据： 913
batch数据 组装完毕 ：913
batch_tensor数据 组装完毕 ：913,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 913 ----- 1
正在处理 913 ----- 2
正在处理 913 ----- 3
正在处理 913 ----- 4
正在处理 913 ----- 5
正在处理 913 ----- 6
正在处理 913 ----- 7
正在处理 913 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 913
============================

正在读取第 914 个DF
初始化batch数据： 914
batch数据 组装完毕 ：914
batch_tensor数据 组装完毕 ：914,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 914 ----- 1
正在处理 914 ----- 2
正在处理 914 ----- 3
正在处理 914 ----- 4
正在处理 914 ----- 5
正在处理 914 ----- 6
正在处理 914 ----- 7
正在处理 914 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 914
============================

正在读取第 915 个DF
初始化batch数据： 915
batch数据 组装完毕 ：915
batch_tensor数据 组装完毕 ：915,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 915 ----- 1
正在处理 915 ----- 2
正在处理 915 ----- 3
正在处理 915 ----- 4
正在处理 915 ----- 5
正在处理 915 ----- 6
正在处理 915 ----- 7
正在处理 915 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 915
============================

正在读取第 916 个DF
初始化batch数据： 916
batch数据 组装完毕 ：916
batch_tensor数据 组装完毕 ：916,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 916 ----- 1
正在处理 916 ----- 2
正在处理 916 ----- 3
正在处理 916 ----- 4
正在处理 916 ----- 5
正在处理 916 ----- 6
正在处理 916 ----- 7
正在处理 916 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 916
============================

正在读取第 917 个DF
初始化batch数据： 917
batch数据 组装完毕 ：917
batch_tensor数据 组装完毕 ：917,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 917 ----- 1
正在处理 917 ----- 2
正在处理 917 ----- 3
正在处理 917 ----- 4
正在处理 917 ----- 5
正在处理 917 ----- 6
正在处理 917 ----- 7
正在处理 917 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 917
============================

正在读取第 918 个DF
初始化batch数据： 918
batch数据 组装完毕 ：918
batch_tensor数据 组装完毕 ：918,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 918 ----- 1
正在处理 918 ----- 2
正在处理 918 ----- 3
正在处理 918 ----- 4
正在处理 918 ----- 5
正在处理 918 ----- 6
正在处理 918 ----- 7
正在处理 918 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 918
============================

正在读取第 919 个DF
初始化batch数据： 919
batch数据 组装完毕 ：919
batch_tensor数据 组装完毕 ：919,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 919 ----- 1
正在处理 919 ----- 2
正在处理 919 ----- 3
正在处理 919 ----- 4
正在处理 919 ----- 5
正在处理 919 ----- 6
正在处理 919 ----- 7
正在处理 919 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 919
============================

正在读取第 920 个DF
初始化batch数据： 920
batch数据 组装完毕 ：920
batch_tensor数据 组装完毕 ：920,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 920 ----- 1
正在处理 920 ----- 2
正在处理 920 ----- 3
正在处理 920 ----- 4
正在处理 920 ----- 5
正在处理 920 ----- 6
正在处理 920 ----- 7
正在处理 920 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 920
============================

正在读取第 921 个DF
初始化batch数据： 921
batch数据 组装完毕 ：921
batch_tensor数据 组装完毕 ：921,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 921 ----- 1
正在处理 921 ----- 2
正在处理 921 ----- 3
正在处理 921 ----- 4
正在处理 921 ----- 5
正在处理 921 ----- 6
正在处理 921 ----- 7
正在处理 921 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 921
============================

正在读取第 922 个DF
初始化batch数据： 922
batch数据 组装完毕 ：922
batch_tensor数据 组装完毕 ：922,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 922 ----- 1
正在处理 922 ----- 2
正在处理 922 ----- 3
正在处理 922 ----- 4
正在处理 922 ----- 5
正在处理 922 ----- 6
正在处理 922 ----- 7
正在处理 922 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 922
============================

正在读取第 923 个DF
初始化batch数据： 923
batch数据 组装完毕 ：923
batch_tensor数据 组装完毕 ：923,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 923 ----- 1
正在处理 923 ----- 2
正在处理 923 ----- 3
正在处理 923 ----- 4
正在处理 923 ----- 5
正在处理 923 ----- 6
正在处理 923 ----- 7
正在处理 923 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 923
============================

正在读取第 924 个DF
初始化batch数据： 924
batch数据 组装完毕 ：924
batch_tensor数据 组装完毕 ：924,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 924 ----- 1
正在处理 924 ----- 2
正在处理 924 ----- 3
正在处理 924 ----- 4
正在处理 924 ----- 5
正在处理 924 ----- 6
正在处理 924 ----- 7
正在处理 924 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 924
============================

正在读取第 925 个DF
初始化batch数据： 925
batch数据 组装完毕 ：925
batch_tensor数据 组装完毕 ：925,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 925 ----- 1
正在处理 925 ----- 2
正在处理 925 ----- 3
正在处理 925 ----- 4
正在处理 925 ----- 5
正在处理 925 ----- 6
正在处理 925 ----- 7
正在处理 925 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 925
============================

正在读取第 926 个DF
初始化batch数据： 926
batch数据 组装完毕 ：926
batch_tensor数据 组装完毕 ：926,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 926 ----- 1
正在处理 926 ----- 2
正在处理 926 ----- 3
正在处理 926 ----- 4
正在处理 926 ----- 5
正在处理 926 ----- 6
正在处理 926 ----- 7
正在处理 926 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 926
============================

正在读取第 927 个DF
初始化batch数据： 927
batch数据 组装完毕 ：927
batch_tensor数据 组装完毕 ：927,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 927 ----- 1
正在处理 927 ----- 2
正在处理 927 ----- 3
正在处理 927 ----- 4
正在处理 927 ----- 5
正在处理 927 ----- 6
正在处理 927 ----- 7
正在处理 927 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 927
============================

正在读取第 928 个DF
初始化batch数据： 928
batch数据 组装完毕 ：928
batch_tensor数据 组装完毕 ：928,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 928 ----- 1
正在处理 928 ----- 2
正在处理 928 ----- 3
正在处理 928 ----- 4
正在处理 928 ----- 5
正在处理 928 ----- 6
正在处理 928 ----- 7
正在处理 928 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 928
============================

正在读取第 929 个DF
初始化batch数据： 929
batch数据 组装完毕 ：929
batch_tensor数据 组装完毕 ：929,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 929 ----- 1
正在处理 929 ----- 2
正在处理 929 ----- 3
正在处理 929 ----- 4
正在处理 929 ----- 5
正在处理 929 ----- 6
正在处理 929 ----- 7
正在处理 929 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 929
============================

正在读取第 930 个DF
初始化batch数据： 930
batch数据 组装完毕 ：930
batch_tensor数据 组装完毕 ：930,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 930 ----- 1
正在处理 930 ----- 2
正在处理 930 ----- 3
正在处理 930 ----- 4
正在处理 930 ----- 5
正在处理 930 ----- 6
正在处理 930 ----- 7
正在处理 930 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 930
============================

正在读取第 931 个DF
初始化batch数据： 931
batch数据 组装完毕 ：931
batch_tensor数据 组装完毕 ：931,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 931 ----- 1
正在处理 931 ----- 2
正在处理 931 ----- 3
正在处理 931 ----- 4
正在处理 931 ----- 5
正在处理 931 ----- 6
正在处理 931 ----- 7
正在处理 931 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 931
============================

正在读取第 932 个DF
初始化batch数据： 932
batch数据 组装完毕 ：932
batch_tensor数据 组装完毕 ：932,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 932 ----- 1
正在处理 932 ----- 2
正在处理 932 ----- 3
正在处理 932 ----- 4
正在处理 932 ----- 5
正在处理 932 ----- 6
正在处理 932 ----- 7
正在处理 932 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 932
============================

正在读取第 933 个DF
初始化batch数据： 933
batch数据 组装完毕 ：933
batch_tensor数据 组装完毕 ：933,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 933 ----- 1
正在处理 933 ----- 2
正在处理 933 ----- 3
正在处理 933 ----- 4
正在处理 933 ----- 5
正在处理 933 ----- 6
正在处理 933 ----- 7
正在处理 933 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 933
============================

正在读取第 934 个DF
初始化batch数据： 934
batch数据 组装完毕 ：934
batch_tensor数据 组装完毕 ：934,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 934 ----- 1
正在处理 934 ----- 2
正在处理 934 ----- 3
正在处理 934 ----- 4
正在处理 934 ----- 5
正在处理 934 ----- 6
正在处理 934 ----- 7
正在处理 934 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 934
============================

正在读取第 935 个DF
初始化batch数据： 935
batch数据 组装完毕 ：935
batch_tensor数据 组装完毕 ：935,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 935 ----- 1
正在处理 935 ----- 2
正在处理 935 ----- 3
正在处理 935 ----- 4
正在处理 935 ----- 5
正在处理 935 ----- 6
正在处理 935 ----- 7
正在处理 935 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 935
============================

正在读取第 936 个DF
初始化batch数据： 936
batch数据 组装完毕 ：936
batch_tensor数据 组装完毕 ：936,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 936 ----- 1
正在处理 936 ----- 2
正在处理 936 ----- 3
正在处理 936 ----- 4
正在处理 936 ----- 5
正在处理 936 ----- 6
正在处理 936 ----- 7
正在处理 936 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 936
============================

正在读取第 937 个DF
初始化batch数据： 937
batch数据 组装完毕 ：937
batch_tensor数据 组装完毕 ：937,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 937 ----- 1
正在处理 937 ----- 2
正在处理 937 ----- 3
正在处理 937 ----- 4
正在处理 937 ----- 5
正在处理 937 ----- 6
正在处理 937 ----- 7
正在处理 937 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 937
============================

正在读取第 938 个DF
初始化batch数据： 938
batch数据 组装完毕 ：938
batch_tensor数据 组装完毕 ：938,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 938 ----- 1
正在处理 938 ----- 2
正在处理 938 ----- 3
正在处理 938 ----- 4
正在处理 938 ----- 5
正在处理 938 ----- 6
正在处理 938 ----- 7
正在处理 938 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 938
============================

正在读取第 939 个DF
初始化batch数据： 939
batch数据 组装完毕 ：939
batch_tensor数据 组装完毕 ：939,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 939 ----- 1
正在处理 939 ----- 2
正在处理 939 ----- 3
正在处理 939 ----- 4
正在处理 939 ----- 5
正在处理 939 ----- 6
正在处理 939 ----- 7
正在处理 939 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 939
============================

正在读取第 940 个DF
初始化batch数据： 940
batch数据 组装完毕 ：940
batch_tensor数据 组装完毕 ：940,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 940 ----- 1
正在处理 940 ----- 2
正在处理 940 ----- 3
正在处理 940 ----- 4
正在处理 940 ----- 5
正在处理 940 ----- 6
正在处理 940 ----- 7
正在处理 940 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 940
============================

正在读取第 941 个DF
初始化batch数据： 941
batch数据 组装完毕 ：941
batch_tensor数据 组装完毕 ：941,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 941 ----- 1
正在处理 941 ----- 2
正在处理 941 ----- 3
正在处理 941 ----- 4
正在处理 941 ----- 5
正在处理 941 ----- 6
正在处理 941 ----- 7
正在处理 941 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 941
============================

正在读取第 942 个DF
初始化batch数据： 942
batch数据 组装完毕 ：942
batch_tensor数据 组装完毕 ：942,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 942 ----- 1
正在处理 942 ----- 2
正在处理 942 ----- 3
正在处理 942 ----- 4
正在处理 942 ----- 5
正在处理 942 ----- 6
正在处理 942 ----- 7
正在处理 942 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 942
============================

正在读取第 943 个DF
初始化batch数据： 943
batch数据 组装完毕 ：943
batch_tensor数据 组装完毕 ：943,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 943 ----- 1
正在处理 943 ----- 2
正在处理 943 ----- 3
正在处理 943 ----- 4
正在处理 943 ----- 5
正在处理 943 ----- 6
正在处理 943 ----- 7
正在处理 943 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 943
============================

正在读取第 944 个DF
初始化batch数据： 944
batch数据 组装完毕 ：944
batch_tensor数据 组装完毕 ：944,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 944 ----- 1
正在处理 944 ----- 2
正在处理 944 ----- 3
正在处理 944 ----- 4
正在处理 944 ----- 5
正在处理 944 ----- 6
正在处理 944 ----- 7
正在处理 944 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 944
============================

正在读取第 945 个DF
初始化batch数据： 945
batch数据 组装完毕 ：945
batch_tensor数据 组装完毕 ：945,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 945 ----- 1
正在处理 945 ----- 2
正在处理 945 ----- 3
正在处理 945 ----- 4
正在处理 945 ----- 5
正在处理 945 ----- 6
正在处理 945 ----- 7
正在处理 945 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 945
============================

正在读取第 946 个DF
初始化batch数据： 946
batch数据 组装完毕 ：946
batch_tensor数据 组装完毕 ：946,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 946 ----- 1
正在处理 946 ----- 2
正在处理 946 ----- 3
正在处理 946 ----- 4
正在处理 946 ----- 5
正在处理 946 ----- 6
正在处理 946 ----- 7
正在处理 946 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 946
============================

正在读取第 947 个DF
初始化batch数据： 947
batch数据 组装完毕 ：947
batch_tensor数据 组装完毕 ：947,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 947 ----- 1
正在处理 947 ----- 2
正在处理 947 ----- 3
正在处理 947 ----- 4
正在处理 947 ----- 5
正在处理 947 ----- 6
正在处理 947 ----- 7
正在处理 947 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 947
============================

正在读取第 948 个DF
初始化batch数据： 948
batch数据 组装完毕 ：948
batch_tensor数据 组装完毕 ：948,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 948 ----- 1
正在处理 948 ----- 2
正在处理 948 ----- 3
正在处理 948 ----- 4
正在处理 948 ----- 5
正在处理 948 ----- 6
正在处理 948 ----- 7
正在处理 948 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 948
============================

正在读取第 949 个DF
初始化batch数据： 949
batch数据 组装完毕 ：949
batch_tensor数据 组装完毕 ：949,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 949 ----- 1
正在处理 949 ----- 2
正在处理 949 ----- 3
正在处理 949 ----- 4
正在处理 949 ----- 5
正在处理 949 ----- 6
正在处理 949 ----- 7
正在处理 949 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 949
============================

正在读取第 950 个DF
初始化batch数据： 950
batch数据 组装完毕 ：950
batch_tensor数据 组装完毕 ：950,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 950 ----- 1
正在处理 950 ----- 2
正在处理 950 ----- 3
正在处理 950 ----- 4
正在处理 950 ----- 5
正在处理 950 ----- 6
正在处理 950 ----- 7
正在处理 950 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 950
============================

正在读取第 951 个DF
初始化batch数据： 951
batch数据 组装完毕 ：951
batch_tensor数据 组装完毕 ：951,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 951 ----- 1
正在处理 951 ----- 2
正在处理 951 ----- 3
正在处理 951 ----- 4
正在处理 951 ----- 5
正在处理 951 ----- 6
正在处理 951 ----- 7
正在处理 951 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 951
============================

正在读取第 952 个DF
初始化batch数据： 952
batch数据 组装完毕 ：952
batch_tensor数据 组装完毕 ：952,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 952 ----- 1
正在处理 952 ----- 2
正在处理 952 ----- 3
正在处理 952 ----- 4
正在处理 952 ----- 5
正在处理 952 ----- 6
正在处理 952 ----- 7
正在处理 952 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 952
============================

正在读取第 953 个DF
初始化batch数据： 953
batch数据 组装完毕 ：953
batch_tensor数据 组装完毕 ：953,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 953 ----- 1
正在处理 953 ----- 2
正在处理 953 ----- 3
正在处理 953 ----- 4
正在处理 953 ----- 5
正在处理 953 ----- 6
正在处理 953 ----- 7
正在处理 953 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 953
============================

正在读取第 954 个DF
初始化batch数据： 954
batch数据 组装完毕 ：954
batch_tensor数据 组装完毕 ：954,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 954 ----- 1
正在处理 954 ----- 2
正在处理 954 ----- 3
正在处理 954 ----- 4
正在处理 954 ----- 5
正在处理 954 ----- 6
正在处理 954 ----- 7
正在处理 954 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 954
============================

正在读取第 955 个DF
初始化batch数据： 955
batch数据 组装完毕 ：955
batch_tensor数据 组装完毕 ：955,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 955 ----- 1
正在处理 955 ----- 2
正在处理 955 ----- 3
正在处理 955 ----- 4
正在处理 955 ----- 5
正在处理 955 ----- 6
正在处理 955 ----- 7
正在处理 955 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 955
============================

正在读取第 956 个DF
初始化batch数据： 956
batch数据 组装完毕 ：956
batch_tensor数据 组装完毕 ：956,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 956 ----- 1
正在处理 956 ----- 2
正在处理 956 ----- 3
正在处理 956 ----- 4
正在处理 956 ----- 5
正在处理 956 ----- 6
正在处理 956 ----- 7
正在处理 956 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 956
============================

正在读取第 957 个DF
初始化batch数据： 957
batch数据 组装完毕 ：957
batch_tensor数据 组装完毕 ：957,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 957 ----- 1
正在处理 957 ----- 2
正在处理 957 ----- 3
正在处理 957 ----- 4
正在处理 957 ----- 5
正在处理 957 ----- 6
正在处理 957 ----- 7
正在处理 957 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 957
============================

正在读取第 958 个DF
初始化batch数据： 958
batch数据 组装完毕 ：958
batch_tensor数据 组装完毕 ：958,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 958 ----- 1
正在处理 958 ----- 2
正在处理 958 ----- 3
正在处理 958 ----- 4
正在处理 958 ----- 5
正在处理 958 ----- 6
正在处理 958 ----- 7
正在处理 958 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 958
============================

正在读取第 959 个DF
初始化batch数据： 959
batch数据 组装完毕 ：959
batch_tensor数据 组装完毕 ：959,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 959 ----- 1
正在处理 959 ----- 2
正在处理 959 ----- 3
正在处理 959 ----- 4
正在处理 959 ----- 5
正在处理 959 ----- 6
正在处理 959 ----- 7
正在处理 959 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 959
============================

正在读取第 960 个DF
初始化batch数据： 960
batch数据 组装完毕 ：960
batch_tensor数据 组装完毕 ：960,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 960 ----- 1
正在处理 960 ----- 2
正在处理 960 ----- 3
正在处理 960 ----- 4
正在处理 960 ----- 5
正在处理 960 ----- 6
正在处理 960 ----- 7
正在处理 960 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 960
============================

正在读取第 961 个DF
初始化batch数据： 961
batch数据 组装完毕 ：961
batch_tensor数据 组装完毕 ：961,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 961 ----- 1
正在处理 961 ----- 2
正在处理 961 ----- 3
正在处理 961 ----- 4
正在处理 961 ----- 5
正在处理 961 ----- 6
正在处理 961 ----- 7
正在处理 961 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 961
============================

正在读取第 962 个DF
初始化batch数据： 962
batch数据 组装完毕 ：962
batch_tensor数据 组装完毕 ：962,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 962 ----- 1
正在处理 962 ----- 2
正在处理 962 ----- 3
正在处理 962 ----- 4
正在处理 962 ----- 5
正在处理 962 ----- 6
正在处理 962 ----- 7
正在处理 962 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 962
============================

正在读取第 963 个DF
初始化batch数据： 963
batch数据 组装完毕 ：963
batch_tensor数据 组装完毕 ：963,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 963 ----- 1
正在处理 963 ----- 2
正在处理 963 ----- 3
正在处理 963 ----- 4
正在处理 963 ----- 5
正在处理 963 ----- 6
正在处理 963 ----- 7
正在处理 963 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 963
============================

正在读取第 964 个DF
初始化batch数据： 964
batch数据 组装完毕 ：964
batch_tensor数据 组装完毕 ：964,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 964 ----- 1
正在处理 964 ----- 2
正在处理 964 ----- 3
正在处理 964 ----- 4
正在处理 964 ----- 5
正在处理 964 ----- 6
正在处理 964 ----- 7
正在处理 964 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 964
============================

正在读取第 965 个DF
初始化batch数据： 965
batch数据 组装完毕 ：965
batch_tensor数据 组装完毕 ：965,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 965 ----- 1
正在处理 965 ----- 2
正在处理 965 ----- 3
正在处理 965 ----- 4
正在处理 965 ----- 5
正在处理 965 ----- 6
正在处理 965 ----- 7
正在处理 965 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 965
============================

正在读取第 966 个DF
初始化batch数据： 966
batch数据 组装完毕 ：966
batch_tensor数据 组装完毕 ：966,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 966 ----- 1
正在处理 966 ----- 2
正在处理 966 ----- 3
正在处理 966 ----- 4
正在处理 966 ----- 5
正在处理 966 ----- 6
正在处理 966 ----- 7
正在处理 966 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 966
============================

正在读取第 967 个DF
初始化batch数据： 967
batch数据 组装完毕 ：967
batch_tensor数据 组装完毕 ：967,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 967 ----- 1
正在处理 967 ----- 2
正在处理 967 ----- 3
正在处理 967 ----- 4
正在处理 967 ----- 5
正在处理 967 ----- 6
正在处理 967 ----- 7
正在处理 967 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 967
============================

正在读取第 968 个DF
初始化batch数据： 968
batch数据 组装完毕 ：968
batch_tensor数据 组装完毕 ：968,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 968 ----- 1
正在处理 968 ----- 2
正在处理 968 ----- 3
正在处理 968 ----- 4
正在处理 968 ----- 5
正在处理 968 ----- 6
正在处理 968 ----- 7
正在处理 968 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 968
============================

正在读取第 969 个DF
初始化batch数据： 969
batch数据 组装完毕 ：969
batch_tensor数据 组装完毕 ：969,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 969 ----- 1
正在处理 969 ----- 2
正在处理 969 ----- 3
正在处理 969 ----- 4
正在处理 969 ----- 5
正在处理 969 ----- 6
正在处理 969 ----- 7
正在处理 969 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 969
============================

正在读取第 970 个DF
初始化batch数据： 970
batch数据 组装完毕 ：970
batch_tensor数据 组装完毕 ：970,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 970 ----- 1
正在处理 970 ----- 2
正在处理 970 ----- 3
正在处理 970 ----- 4
正在处理 970 ----- 5
正在处理 970 ----- 6
正在处理 970 ----- 7
正在处理 970 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 970
============================

正在读取第 971 个DF
初始化batch数据： 971
batch数据 组装完毕 ：971
batch_tensor数据 组装完毕 ：971,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 971 ----- 1
正在处理 971 ----- 2
正在处理 971 ----- 3
正在处理 971 ----- 4
正在处理 971 ----- 5
正在处理 971 ----- 6
正在处理 971 ----- 7
正在处理 971 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 971
============================

正在读取第 972 个DF
初始化batch数据： 972
batch数据 组装完毕 ：972
batch_tensor数据 组装完毕 ：972,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 972 ----- 1
正在处理 972 ----- 2
正在处理 972 ----- 3
正在处理 972 ----- 4
正在处理 972 ----- 5
正在处理 972 ----- 6
正在处理 972 ----- 7
正在处理 972 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 972
============================

正在读取第 973 个DF
初始化batch数据： 973
batch数据 组装完毕 ：973
batch_tensor数据 组装完毕 ：973,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 973 ----- 1
正在处理 973 ----- 2
正在处理 973 ----- 3
正在处理 973 ----- 4
正在处理 973 ----- 5
正在处理 973 ----- 6
正在处理 973 ----- 7
正在处理 973 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 973
============================

正在读取第 974 个DF
初始化batch数据： 974
batch数据 组装完毕 ：974
batch_tensor数据 组装完毕 ：974,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 974 ----- 1
正在处理 974 ----- 2
正在处理 974 ----- 3
正在处理 974 ----- 4
正在处理 974 ----- 5
正在处理 974 ----- 6
正在处理 974 ----- 7
正在处理 974 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 974
============================

正在读取第 975 个DF
初始化batch数据： 975
batch数据 组装完毕 ：975
batch_tensor数据 组装完毕 ：975,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 975 ----- 1
正在处理 975 ----- 2
正在处理 975 ----- 3
正在处理 975 ----- 4
正在处理 975 ----- 5
正在处理 975 ----- 6
正在处理 975 ----- 7
正在处理 975 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 975
============================

正在读取第 976 个DF
初始化batch数据： 976
batch数据 组装完毕 ：976
batch_tensor数据 组装完毕 ：976,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 976 ----- 1
正在处理 976 ----- 2
正在处理 976 ----- 3
正在处理 976 ----- 4
正在处理 976 ----- 5
正在处理 976 ----- 6
正在处理 976 ----- 7
正在处理 976 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 976
============================

正在读取第 977 个DF
初始化batch数据： 977
batch数据 组装完毕 ：977
batch_tensor数据 组装完毕 ：977,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 977 ----- 1
正在处理 977 ----- 2
正在处理 977 ----- 3
正在处理 977 ----- 4
正在处理 977 ----- 5
正在处理 977 ----- 6
正在处理 977 ----- 7
正在处理 977 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 977
============================

正在读取第 978 个DF
初始化batch数据： 978
batch数据 组装完毕 ：978
batch_tensor数据 组装完毕 ：978,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 978 ----- 1
正在处理 978 ----- 2
正在处理 978 ----- 3
正在处理 978 ----- 4
正在处理 978 ----- 5
正在处理 978 ----- 6
正在处理 978 ----- 7
正在处理 978 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 978
============================

正在读取第 979 个DF
初始化batch数据： 979
batch数据 组装完毕 ：979
batch_tensor数据 组装完毕 ：979,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 979 ----- 1
正在处理 979 ----- 2
正在处理 979 ----- 3
正在处理 979 ----- 4
正在处理 979 ----- 5
正在处理 979 ----- 6
正在处理 979 ----- 7
正在处理 979 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 979
============================

正在读取第 980 个DF
初始化batch数据： 980
batch数据 组装完毕 ：980
batch_tensor数据 组装完毕 ：980,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 980 ----- 1
正在处理 980 ----- 2
正在处理 980 ----- 3
正在处理 980 ----- 4
正在处理 980 ----- 5
正在处理 980 ----- 6
正在处理 980 ----- 7
正在处理 980 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 980
============================

正在读取第 981 个DF
初始化batch数据： 981
batch数据 组装完毕 ：981
batch_tensor数据 组装完毕 ：981,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 981 ----- 1
正在处理 981 ----- 2
正在处理 981 ----- 3
正在处理 981 ----- 4
正在处理 981 ----- 5
正在处理 981 ----- 6
正在处理 981 ----- 7
正在处理 981 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 981
============================

正在读取第 982 个DF
初始化batch数据： 982
batch数据 组装完毕 ：982
batch_tensor数据 组装完毕 ：982,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 982 ----- 1
正在处理 982 ----- 2
正在处理 982 ----- 3
正在处理 982 ----- 4
正在处理 982 ----- 5
正在处理 982 ----- 6
正在处理 982 ----- 7
正在处理 982 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 982
============================

正在读取第 983 个DF
初始化batch数据： 983
batch数据 组装完毕 ：983
batch_tensor数据 组装完毕 ：983,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 983 ----- 1
正在处理 983 ----- 2
正在处理 983 ----- 3
正在处理 983 ----- 4
正在处理 983 ----- 5
正在处理 983 ----- 6
正在处理 983 ----- 7
正在处理 983 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 983
============================

正在读取第 984 个DF
初始化batch数据： 984
batch数据 组装完毕 ：984
batch_tensor数据 组装完毕 ：984,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 984 ----- 1
正在处理 984 ----- 2
正在处理 984 ----- 3
正在处理 984 ----- 4
正在处理 984 ----- 5
正在处理 984 ----- 6
正在处理 984 ----- 7
正在处理 984 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 984
============================

正在读取第 985 个DF
初始化batch数据： 985
batch数据 组装完毕 ：985
batch_tensor数据 组装完毕 ：985,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 985 ----- 1
正在处理 985 ----- 2
正在处理 985 ----- 3
正在处理 985 ----- 4
正在处理 985 ----- 5
正在处理 985 ----- 6
正在处理 985 ----- 7
正在处理 985 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 985
============================

正在读取第 986 个DF
初始化batch数据： 986
batch数据 组装完毕 ：986
batch_tensor数据 组装完毕 ：986,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 986 ----- 1
正在处理 986 ----- 2
正在处理 986 ----- 3
正在处理 986 ----- 4
正在处理 986 ----- 5
正在处理 986 ----- 6
正在处理 986 ----- 7
正在处理 986 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 986
============================

正在读取第 987 个DF
初始化batch数据： 987
batch数据 组装完毕 ：987
batch_tensor数据 组装完毕 ：987,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 987 ----- 1
正在处理 987 ----- 2
正在处理 987 ----- 3
正在处理 987 ----- 4
正在处理 987 ----- 5
正在处理 987 ----- 6
正在处理 987 ----- 7
正在处理 987 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 987
============================

正在读取第 988 个DF
初始化batch数据： 988
batch数据 组装完毕 ：988
batch_tensor数据 组装完毕 ：988,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 988 ----- 1
正在处理 988 ----- 2
正在处理 988 ----- 3
正在处理 988 ----- 4
正在处理 988 ----- 5
正在处理 988 ----- 6
正在处理 988 ----- 7
正在处理 988 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 988
============================

正在读取第 989 个DF
初始化batch数据： 989
batch数据 组装完毕 ：989
batch_tensor数据 组装完毕 ：989,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 989 ----- 1
正在处理 989 ----- 2
正在处理 989 ----- 3
正在处理 989 ----- 4
正在处理 989 ----- 5
正在处理 989 ----- 6
正在处理 989 ----- 7
正在处理 989 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 989
============================

正在读取第 990 个DF
初始化batch数据： 990
batch数据 组装完毕 ：990
batch_tensor数据 组装完毕 ：990,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 990 ----- 1
正在处理 990 ----- 2
正在处理 990 ----- 3
正在处理 990 ----- 4
正在处理 990 ----- 5
正在处理 990 ----- 6
正在处理 990 ----- 7
正在处理 990 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 990
============================

正在读取第 991 个DF
初始化batch数据： 991
batch数据 组装完毕 ：991
batch_tensor数据 组装完毕 ：991,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 991 ----- 1
正在处理 991 ----- 2
正在处理 991 ----- 3
正在处理 991 ----- 4
正在处理 991 ----- 5
正在处理 991 ----- 6
正在处理 991 ----- 7
正在处理 991 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 991
============================

正在读取第 992 个DF
初始化batch数据： 992
batch数据 组装完毕 ：992
batch_tensor数据 组装完毕 ：992,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 992 ----- 1
正在处理 992 ----- 2
正在处理 992 ----- 3
正在处理 992 ----- 4
正在处理 992 ----- 5
正在处理 992 ----- 6
正在处理 992 ----- 7
正在处理 992 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 992
============================

正在读取第 993 个DF
初始化batch数据： 993
batch数据 组装完毕 ：993
batch_tensor数据 组装完毕 ：993,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 993 ----- 1
正在处理 993 ----- 2
正在处理 993 ----- 3
正在处理 993 ----- 4
正在处理 993 ----- 5
正在处理 993 ----- 6
正在处理 993 ----- 7
正在处理 993 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 993
============================

正在读取第 994 个DF
初始化batch数据： 994
batch数据 组装完毕 ：994
batch_tensor数据 组装完毕 ：994,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 994 ----- 1
正在处理 994 ----- 2
正在处理 994 ----- 3
正在处理 994 ----- 4
正在处理 994 ----- 5
正在处理 994 ----- 6
正在处理 994 ----- 7
正在处理 994 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 994
============================

正在读取第 995 个DF
初始化batch数据： 995
batch数据 组装完毕 ：995
batch_tensor数据 组装完毕 ：995,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 995 ----- 1
正在处理 995 ----- 2
正在处理 995 ----- 3
正在处理 995 ----- 4
正在处理 995 ----- 5
正在处理 995 ----- 6
正在处理 995 ----- 7
正在处理 995 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 995
============================

正在读取第 996 个DF
初始化batch数据： 996
batch数据 组装完毕 ：996
batch_tensor数据 组装完毕 ：996,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 996 ----- 1
正在处理 996 ----- 2
正在处理 996 ----- 3
正在处理 996 ----- 4
正在处理 996 ----- 5
正在处理 996 ----- 6
正在处理 996 ----- 7
正在处理 996 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 996
============================

正在读取第 997 个DF
初始化batch数据： 997
batch数据 组装完毕 ：997
batch_tensor数据 组装完毕 ：997,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 997 ----- 1
正在处理 997 ----- 2
正在处理 997 ----- 3
正在处理 997 ----- 4
正在处理 997 ----- 5
正在处理 997 ----- 6
正在处理 997 ----- 7
正在处理 997 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 997
============================

正在读取第 998 个DF
初始化batch数据： 998
batch数据 组装完毕 ：998
batch_tensor数据 组装完毕 ：998,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 998 ----- 1
正在处理 998 ----- 2
正在处理 998 ----- 3
正在处理 998 ----- 4
正在处理 998 ----- 5
正在处理 998 ----- 6
正在处理 998 ----- 7
正在处理 998 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 998
============================

正在读取第 999 个DF
初始化batch数据： 999
batch数据 组装完毕 ：999
batch_tensor数据 组装完毕 ：999,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 999 ----- 1
正在处理 999 ----- 2
正在处理 999 ----- 3
正在处理 999 ----- 4
正在处理 999 ----- 5
正在处理 999 ----- 6
正在处理 999 ----- 7
正在处理 999 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 999
============================

正在读取第 1000 个DF
初始化batch数据： 1000
batch数据 组装完毕 ：1000
batch_tensor数据 组装完毕 ：1000,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1000 ----- 1
正在处理 1000 ----- 2
正在处理 1000 ----- 3
正在处理 1000 ----- 4
正在处理 1000 ----- 5
正在处理 1000 ----- 6
正在处理 1000 ----- 7
正在处理 1000 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1000
============================

正在读取第 1001 个DF
初始化batch数据： 1001
batch数据 组装完毕 ：1001
batch_tensor数据 组装完毕 ：1001,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1001 ----- 1
正在处理 1001 ----- 2
正在处理 1001 ----- 3
正在处理 1001 ----- 4
正在处理 1001 ----- 5
正在处理 1001 ----- 6
正在处理 1001 ----- 7
正在处理 1001 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1001
============================

正在读取第 1002 个DF
初始化batch数据： 1002
batch数据 组装完毕 ：1002
batch_tensor数据 组装完毕 ：1002,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1002 ----- 1
正在处理 1002 ----- 2
正在处理 1002 ----- 3
正在处理 1002 ----- 4
正在处理 1002 ----- 5
正在处理 1002 ----- 6
正在处理 1002 ----- 7
正在处理 1002 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1002
============================

正在读取第 1003 个DF
初始化batch数据： 1003
batch数据 组装完毕 ：1003
batch_tensor数据 组装完毕 ：1003,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1003 ----- 1
正在处理 1003 ----- 2
正在处理 1003 ----- 3
正在处理 1003 ----- 4
正在处理 1003 ----- 5
正在处理 1003 ----- 6
正在处理 1003 ----- 7
正在处理 1003 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1003
============================

正在读取第 1004 个DF
初始化batch数据： 1004
batch数据 组装完毕 ：1004
batch_tensor数据 组装完毕 ：1004,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1004 ----- 1
正在处理 1004 ----- 2
正在处理 1004 ----- 3
正在处理 1004 ----- 4
正在处理 1004 ----- 5
正在处理 1004 ----- 6
正在处理 1004 ----- 7
正在处理 1004 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1004
============================

正在读取第 1005 个DF
初始化batch数据： 1005
batch数据 组装完毕 ：1005
batch_tensor数据 组装完毕 ：1005,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1005 ----- 1
正在处理 1005 ----- 2
正在处理 1005 ----- 3
正在处理 1005 ----- 4
正在处理 1005 ----- 5
正在处理 1005 ----- 6
正在处理 1005 ----- 7
正在处理 1005 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1005
============================

正在读取第 1006 个DF
初始化batch数据： 1006
batch数据 组装完毕 ：1006
batch_tensor数据 组装完毕 ：1006,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1006 ----- 1
正在处理 1006 ----- 2
正在处理 1006 ----- 3
正在处理 1006 ----- 4
正在处理 1006 ----- 5
正在处理 1006 ----- 6
正在处理 1006 ----- 7
正在处理 1006 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1006
============================

正在读取第 1007 个DF
初始化batch数据： 1007
batch数据 组装完毕 ：1007
batch_tensor数据 组装完毕 ：1007,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1007 ----- 1
正在处理 1007 ----- 2
正在处理 1007 ----- 3
正在处理 1007 ----- 4
正在处理 1007 ----- 5
正在处理 1007 ----- 6
正在处理 1007 ----- 7
正在处理 1007 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1007
============================

正在读取第 1008 个DF
初始化batch数据： 1008
batch数据 组装完毕 ：1008
batch_tensor数据 组装完毕 ：1008,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1008 ----- 1
正在处理 1008 ----- 2
正在处理 1008 ----- 3
正在处理 1008 ----- 4
正在处理 1008 ----- 5
正在处理 1008 ----- 6
正在处理 1008 ----- 7
正在处理 1008 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1008
============================

正在读取第 1009 个DF
初始化batch数据： 1009
batch数据 组装完毕 ：1009
batch_tensor数据 组装完毕 ：1009,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1009 ----- 1
正在处理 1009 ----- 2
正在处理 1009 ----- 3
正在处理 1009 ----- 4
正在处理 1009 ----- 5
正在处理 1009 ----- 6
正在处理 1009 ----- 7
正在处理 1009 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1009
============================

正在读取第 1010 个DF
初始化batch数据： 1010
batch数据 组装完毕 ：1010
batch_tensor数据 组装完毕 ：1010,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1010 ----- 1
正在处理 1010 ----- 2
正在处理 1010 ----- 3
正在处理 1010 ----- 4
正在处理 1010 ----- 5
正在处理 1010 ----- 6
正在处理 1010 ----- 7
正在处理 1010 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1010
============================

正在读取第 1011 个DF
初始化batch数据： 1011
batch数据 组装完毕 ：1011
batch_tensor数据 组装完毕 ：1011,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1011 ----- 1
正在处理 1011 ----- 2
正在处理 1011 ----- 3
正在处理 1011 ----- 4
正在处理 1011 ----- 5
正在处理 1011 ----- 6
正在处理 1011 ----- 7
正在处理 1011 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1011
============================

正在读取第 1012 个DF
初始化batch数据： 1012
batch数据 组装完毕 ：1012
batch_tensor数据 组装完毕 ：1012,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1012 ----- 1
正在处理 1012 ----- 2
正在处理 1012 ----- 3
正在处理 1012 ----- 4
正在处理 1012 ----- 5
正在处理 1012 ----- 6
正在处理 1012 ----- 7
正在处理 1012 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1012
============================

正在读取第 1013 个DF
初始化batch数据： 1013
batch数据 组装完毕 ：1013
batch_tensor数据 组装完毕 ：1013,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1013 ----- 1
正在处理 1013 ----- 2
正在处理 1013 ----- 3
正在处理 1013 ----- 4
正在处理 1013 ----- 5
正在处理 1013 ----- 6
正在处理 1013 ----- 7
正在处理 1013 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1013
============================

正在读取第 1014 个DF
初始化batch数据： 1014
batch数据 组装完毕 ：1014
batch_tensor数据 组装完毕 ：1014,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1014 ----- 1
正在处理 1014 ----- 2
正在处理 1014 ----- 3
正在处理 1014 ----- 4
正在处理 1014 ----- 5
正在处理 1014 ----- 6
正在处理 1014 ----- 7
正在处理 1014 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1014
============================

正在读取第 1015 个DF
初始化batch数据： 1015
batch数据 组装完毕 ：1015
batch_tensor数据 组装完毕 ：1015,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1015 ----- 1
正在处理 1015 ----- 2
正在处理 1015 ----- 3
正在处理 1015 ----- 4
正在处理 1015 ----- 5
正在处理 1015 ----- 6
正在处理 1015 ----- 7
正在处理 1015 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1015
============================

正在读取第 1016 个DF
初始化batch数据： 1016
batch数据 组装完毕 ：1016
batch_tensor数据 组装完毕 ：1016,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1016 ----- 1
正在处理 1016 ----- 2
正在处理 1016 ----- 3
正在处理 1016 ----- 4
正在处理 1016 ----- 5
正在处理 1016 ----- 6
正在处理 1016 ----- 7
正在处理 1016 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1016
============================

正在读取第 1017 个DF
初始化batch数据： 1017
batch数据 组装完毕 ：1017
batch_tensor数据 组装完毕 ：1017,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1017 ----- 1
正在处理 1017 ----- 2
正在处理 1017 ----- 3
正在处理 1017 ----- 4
正在处理 1017 ----- 5
正在处理 1017 ----- 6
正在处理 1017 ----- 7
正在处理 1017 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1017
============================

正在读取第 1018 个DF
初始化batch数据： 1018
batch数据 组装完毕 ：1018
batch_tensor数据 组装完毕 ：1018,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1018 ----- 1
正在处理 1018 ----- 2
正在处理 1018 ----- 3
正在处理 1018 ----- 4
正在处理 1018 ----- 5
正在处理 1018 ----- 6
正在处理 1018 ----- 7
正在处理 1018 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1018
============================

正在读取第 1019 个DF
初始化batch数据： 1019
batch数据 组装完毕 ：1019
batch_tensor数据 组装完毕 ：1019,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1019 ----- 1
正在处理 1019 ----- 2
正在处理 1019 ----- 3
正在处理 1019 ----- 4
正在处理 1019 ----- 5
正在处理 1019 ----- 6
正在处理 1019 ----- 7
正在处理 1019 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1019
============================

正在读取第 1020 个DF
初始化batch数据： 1020
batch数据 组装完毕 ：1020
batch_tensor数据 组装完毕 ：1020,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1020 ----- 1
正在处理 1020 ----- 2
正在处理 1020 ----- 3
正在处理 1020 ----- 4
正在处理 1020 ----- 5
正在处理 1020 ----- 6
正在处理 1020 ----- 7
正在处理 1020 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1020
============================

正在读取第 1021 个DF
初始化batch数据： 1021
batch数据 组装完毕 ：1021
batch_tensor数据 组装完毕 ：1021,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1021 ----- 1
正在处理 1021 ----- 2
正在处理 1021 ----- 3
正在处理 1021 ----- 4
正在处理 1021 ----- 5
正在处理 1021 ----- 6
正在处理 1021 ----- 7
正在处理 1021 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1021
============================

正在读取第 1022 个DF
初始化batch数据： 1022
batch数据 组装完毕 ：1022
batch_tensor数据 组装完毕 ：1022,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1022 ----- 1
正在处理 1022 ----- 2
正在处理 1022 ----- 3
正在处理 1022 ----- 4
正在处理 1022 ----- 5
正在处理 1022 ----- 6
正在处理 1022 ----- 7
正在处理 1022 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1022
============================

正在读取第 1023 个DF
初始化batch数据： 1023
batch数据 组装完毕 ：1023
batch_tensor数据 组装完毕 ：1023,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1023 ----- 1
正在处理 1023 ----- 2
正在处理 1023 ----- 3
正在处理 1023 ----- 4
正在处理 1023 ----- 5
正在处理 1023 ----- 6
正在处理 1023 ----- 7
正在处理 1023 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1023
============================

正在读取第 1024 个DF
初始化batch数据： 1024
batch数据 组装完毕 ：1024
batch_tensor数据 组装完毕 ：1024,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1024 ----- 1
正在处理 1024 ----- 2
正在处理 1024 ----- 3
正在处理 1024 ----- 4
正在处理 1024 ----- 5
正在处理 1024 ----- 6
正在处理 1024 ----- 7
正在处理 1024 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1024
============================

正在读取第 1025 个DF
初始化batch数据： 1025
batch数据 组装完毕 ：1025
batch_tensor数据 组装完毕 ：1025,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1025 ----- 1
正在处理 1025 ----- 2
正在处理 1025 ----- 3
正在处理 1025 ----- 4
正在处理 1025 ----- 5
正在处理 1025 ----- 6
正在处理 1025 ----- 7
正在处理 1025 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1025
============================

正在读取第 1026 个DF
初始化batch数据： 1026
batch数据 组装完毕 ：1026
batch_tensor数据 组装完毕 ：1026,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1026 ----- 1
正在处理 1026 ----- 2
正在处理 1026 ----- 3
正在处理 1026 ----- 4
正在处理 1026 ----- 5
正在处理 1026 ----- 6
正在处理 1026 ----- 7
正在处理 1026 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1026
============================

正在读取第 1027 个DF
初始化batch数据： 1027
batch数据 组装完毕 ：1027
batch_tensor数据 组装完毕 ：1027,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1027 ----- 1
正在处理 1027 ----- 2
正在处理 1027 ----- 3
正在处理 1027 ----- 4
正在处理 1027 ----- 5
正在处理 1027 ----- 6
正在处理 1027 ----- 7
正在处理 1027 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1027
============================

正在读取第 1028 个DF
初始化batch数据： 1028
batch数据 组装完毕 ：1028
batch_tensor数据 组装完毕 ：1028,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1028 ----- 1
正在处理 1028 ----- 2
正在处理 1028 ----- 3
正在处理 1028 ----- 4
正在处理 1028 ----- 5
正在处理 1028 ----- 6
正在处理 1028 ----- 7
正在处理 1028 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1028
============================

正在读取第 1029 个DF
初始化batch数据： 1029
batch数据 组装完毕 ：1029
batch_tensor数据 组装完毕 ：1029,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1029 ----- 1
正在处理 1029 ----- 2
正在处理 1029 ----- 3
正在处理 1029 ----- 4
正在处理 1029 ----- 5
正在处理 1029 ----- 6
正在处理 1029 ----- 7
正在处理 1029 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1029
============================

正在读取第 1030 个DF
初始化batch数据： 1030
batch数据 组装完毕 ：1030
batch_tensor数据 组装完毕 ：1030,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1030 ----- 1
正在处理 1030 ----- 2
正在处理 1030 ----- 3
正在处理 1030 ----- 4
正在处理 1030 ----- 5
正在处理 1030 ----- 6
正在处理 1030 ----- 7
正在处理 1030 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1030
============================

正在读取第 1031 个DF
初始化batch数据： 1031
batch数据 组装完毕 ：1031
batch_tensor数据 组装完毕 ：1031,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1031 ----- 1
正在处理 1031 ----- 2
正在处理 1031 ----- 3
正在处理 1031 ----- 4
正在处理 1031 ----- 5
正在处理 1031 ----- 6
正在处理 1031 ----- 7
正在处理 1031 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1031
============================

正在读取第 1032 个DF
初始化batch数据： 1032
batch数据 组装完毕 ：1032
batch_tensor数据 组装完毕 ：1032,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1032 ----- 1
正在处理 1032 ----- 2
正在处理 1032 ----- 3
正在处理 1032 ----- 4
正在处理 1032 ----- 5
正在处理 1032 ----- 6
正在处理 1032 ----- 7
正在处理 1032 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1032
============================

正在读取第 1033 个DF
初始化batch数据： 1033
batch数据 组装完毕 ：1033
batch_tensor数据 组装完毕 ：1033,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1033 ----- 1
正在处理 1033 ----- 2
正在处理 1033 ----- 3
正在处理 1033 ----- 4
正在处理 1033 ----- 5
正在处理 1033 ----- 6
正在处理 1033 ----- 7
正在处理 1033 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1033
============================

正在读取第 1034 个DF
初始化batch数据： 1034
batch数据 组装完毕 ：1034
batch_tensor数据 组装完毕 ：1034,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1034 ----- 1
正在处理 1034 ----- 2
正在处理 1034 ----- 3
正在处理 1034 ----- 4
正在处理 1034 ----- 5
正在处理 1034 ----- 6
正在处理 1034 ----- 7
正在处理 1034 ----- 8

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1034
============================

正在读取第 1035 个DF
初始化batch数据： 1035
batch数据 组装完毕 ：1035
batch_tensor数据 组装完毕 ：1035,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 5 块， 开始调用模型
正在处理 1035 ----- 1
正在处理 1035 ----- 2
正在处理 1035 ----- 3
正在处理 1035 ----- 4
正在处理 1035 ----- 5

/tmp/ipykernel_474/1690566335.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1035
============================

### handle tip

In [79]:
tip_data = []

# 打开JSON文件
with open('/remote-home/cs_acmis_wsf/ai4dingo/yelp/yelp_academic_dataset_tip.json', 'r', encoding='utf-8') as file:
    # 逐行读取
    for line in file:
        # 解析每一行为JSON对象
        tip = json.loads(line)
        user_id = tip["user_id"]
        business_id = tip["business_id"]
        text = tip["text"]
        date = tip["date"]
        compliment_count = tip["compliment_count"]
        r = [user_id,business_id,text,date,compliment_count]
        tip_data.append(r)

In [80]:
tip_df = pd.DataFrame(tip_data,columns=["user_id","business_id","text","date","compliment_count"])

In [83]:
tip_df= tip_df.drop_duplicates(subset='text', keep='last')

In [85]:
tip_df["text"] = tip_df["text"].apply(handle_text)

/tmp/ipykernel_474/302868527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tip_df["text"] = tip_df["text"].apply(handle_text)

In [86]:
tip_df = tip_df.dropna(subset=['text'])

In [88]:
tip_df['length'] = tip_df['text'].str.len()

In [89]:
max_len = int(tip_df["length"].max())

In [91]:
max_len

500

In [92]:
tokenizer,model = bert_define()

Some weights of the model checkpoint at /remote-home/cs_acmis_wsf/ai4dingo/model/bert_english_pretrained were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [93]:
vector_count = len(tip_df)

In [94]:
vector_count

851033

In [95]:
n, batch_size, batch = closest_batch_size(vector_count)
print(f"vector_count: {vector_count}, n: {n}, batch_size: {batch_size}, batch: {batch}")

vector_count: 851033, n: 6, batch_size: 64, batch: 13297

In [96]:
rows_per_part = 4096
n =  math.ceil(vector_count / rows_per_part)

In [97]:
n

208

In [98]:
split_dfs_tip = split_dataframe(tip_df, n,rows_per_part)

In [99]:
batch_size_num = 512

for i in range(len(split_dfs_tip)):
    df = split_dfs_tip[i]
    print(f'正在读取第 {i+1} 个DataFrame')
    text = df["text"].tolist()
    
    print(f'初始化batch数据： {i+1}')
    batch_token, batch_segment, batch_mask = list(), list(), list()
    for t in text:
        # text 作 tokenizer 分词
        token = tokenizer.tokenize(t)
        token = ['[CLS]'] + token + ['[SEP]']
        token_id = tokenizer.convert_tokens_to_ids(token)  # 字转换vocab中的index

        # 加padding补齐及segment、mask
        padding = [0] * (max_len - len(token_id))
        mask = [1] * len(token_id) + padding
        segment = [0] * len(token_id) + padding
        token_id = token_id + padding

        batch_token.append(token_id)
        batch_segment.append(segment)
        batch_mask.append(mask)
        
    print(f'batch数据 组装完毕 ：{i+1}')
   
    batch_tensor_token = torch.tensor(batch_token)
    batch_tensor_segment = torch.tensor(batch_segment)
    batch_tensor_mask = torch.tensor(batch_mask)

    batch_len = len(batch_tensor_token)
    
    if torch.cuda.is_available():
        batch_tensor_token = batch_tensor_token.to('cuda:0')
        batch_tensor_segment = batch_tensor_segment.to('cuda:0')
        batch_tensor_mask = batch_tensor_mask.to('cuda:0')
    
    print(f'batch_tensor数据 组装完毕 ：{i+1},开始分块处理')
    
    batch_tensor_token_chunked = [batch_tensor_token[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    batch_tensor_segment_chunked = [batch_tensor_segment[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    batch_tensor_mask_chunked = [batch_tensor_mask[i:i+batch_size_num] for i in range(0,batch_len,batch_size_num)]

    print(f'分块处理完毕数据完毕，每块的长度为:{batch_size_num},一共有 {len(batch_tensor_token_chunked)} 块， 开始调用模型')
    
    gc.collect()
    torch.cuda.empty_cache()
    text_vector = []
    
    try:
        for k in range(len(batch_tensor_token_chunked)):
            with torch.no_grad():
                print(f'正在处理 {i+1} ----- {k+1}')
                outputs = model(batch_tensor_token_chunked[k], token_type_ids=batch_tensor_segment_chunked[k], attention_mask=batch_tensor_mask_chunked[k])
                outputs = outputs[0][:, 0, :]  # 取cls向量
                for o in range(outputs.shape[0]):
                    text_vector.append(outputs[o])
        df["feature"] = [ tv.tolist() for tv in  text_vector] 
        df.to_csv(f'/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/tip_{i+1}.csv', index=False)
        print(f"文件写入完毕 {i+1}")
                    
    except Exception as e:
        print(f"出现异常 {i+1}: {e}")
        continue
            
    
    print('============================')
    print()

正在读取第 1 个DataFrame
初始化batch数据： 1
batch数据 组装完毕 ：1
batch_tensor数据 组装完毕 ：1,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 1 ----- 1
正在处理 1 ----- 2
正在处理 1 ----- 3
正在处理 1 ----- 4
正在处理 1 ----- 5
正在处理 1 ----- 6
正在处理 1 ----- 7
正在处理 1 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 1
============================

正在读取第 2 个DataFrame
初始化batch数据： 2
batch数据 组装完毕 ：2
batch_tensor数据 组装完毕 ：2,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 2 ----- 1
正在处理 2 ----- 2
正在处理 2 ----- 3
正在处理 2 ----- 4
正在处理 2 ----- 5
正在处理 2 ----- 6
正在处理 2 ----- 7
正在处理 2 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 2
============================

正在读取第 3 个DataFrame
初始化batch数据： 3
batch数据 组装完毕 ：3
batch_tensor数据 组装完毕 ：3,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 3 ----- 1
正在处理 3 ----- 2
正在处理 3 ----- 3
正在处理 3 ----- 4
正在处理 3 ----- 5
正在处理 3 ----- 6
正在处理 3 ----- 7
正在处理 3 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 3
============================

正在读取第 4 个DataFrame
初始化batch数据： 4
batch数据 组装完毕 ：4
batch_tensor数据 组装完毕 ：4,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 4 ----- 1
正在处理 4 ----- 2
正在处理 4 ----- 3
正在处理 4 ----- 4
正在处理 4 ----- 5
正在处理 4 ----- 6
正在处理 4 ----- 7
正在处理 4 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 4
============================

正在读取第 5 个DataFrame
初始化batch数据： 5
batch数据 组装完毕 ：5
batch_tensor数据 组装完毕 ：5,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 5 ----- 1
正在处理 5 ----- 2
正在处理 5 ----- 3
正在处理 5 ----- 4
正在处理 5 ----- 5
正在处理 5 ----- 6
正在处理 5 ----- 7
正在处理 5 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 5
============================

正在读取第 6 个DataFrame
初始化batch数据： 6
batch数据 组装完毕 ：6
batch_tensor数据 组装完毕 ：6,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 6 ----- 1
正在处理 6 ----- 2
正在处理 6 ----- 3
正在处理 6 ----- 4
正在处理 6 ----- 5
正在处理 6 ----- 6
正在处理 6 ----- 7
正在处理 6 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 6
============================

正在读取第 7 个DataFrame
初始化batch数据： 7
batch数据 组装完毕 ：7
batch_tensor数据 组装完毕 ：7,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 7 ----- 1
正在处理 7 ----- 2
正在处理 7 ----- 3
正在处理 7 ----- 4
正在处理 7 ----- 5
正在处理 7 ----- 6
正在处理 7 ----- 7
正在处理 7 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 7
============================

正在读取第 8 个DataFrame
初始化batch数据： 8
batch数据 组装完毕 ：8
batch_tensor数据 组装完毕 ：8,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 8 ----- 1
正在处理 8 ----- 2
正在处理 8 ----- 3
正在处理 8 ----- 4
正在处理 8 ----- 5
正在处理 8 ----- 6
正在处理 8 ----- 7
正在处理 8 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 8
============================

正在读取第 9 个DataFrame
初始化batch数据： 9
batch数据 组装完毕 ：9
batch_tensor数据 组装完毕 ：9,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 9 ----- 1
正在处理 9 ----- 2
正在处理 9 ----- 3
正在处理 9 ----- 4
正在处理 9 ----- 5
正在处理 9 ----- 6
正在处理 9 ----- 7
正在处理 9 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 9
============================

正在读取第 10 个DataFrame
初始化batch数据： 10
batch数据 组装完毕 ：10
batch_tensor数据 组装完毕 ：10,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 10 ----- 1
正在处理 10 ----- 2
正在处理 10 ----- 3
正在处理 10 ----- 4
正在处理 10 ----- 5
正在处理 10 ----- 6
正在处理 10 ----- 7
正在处理 10 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 10
============================

正在读取第 11 个DataFrame
初始化batch数据： 11
batch数据 组装完毕 ：11
batch_tensor数据 组装完毕 ：11,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 11 ----- 1
正在处理 11 ----- 2
正在处理 11 ----- 3
正在处理 11 ----- 4
正在处理 11 ----- 5
正在处理 11 ----- 6
正在处理 11 ----- 7
正在处理 11 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 11
============================

正在读取第 12 个DataFrame
初始化batch数据： 12
batch数据 组装完毕 ：12
batch_tensor数据 组装完毕 ：12,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 12 ----- 1
正在处理 12 ----- 2
正在处理 12 ----- 3
正在处理 12 ----- 4
正在处理 12 ----- 5
正在处理 12 ----- 6
正在处理 12 ----- 7
正在处理 12 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 12
============================

正在读取第 13 个DataFrame
初始化batch数据： 13
batch数据 组装完毕 ：13
batch_tensor数据 组装完毕 ：13,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 13 ----- 1
正在处理 13 ----- 2
正在处理 13 ----- 3
正在处理 13 ----- 4
正在处理 13 ----- 5
正在处理 13 ----- 6
正在处理 13 ----- 7
正在处理 13 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 13
============================

正在读取第 14 个DataFrame
初始化batch数据： 14
batch数据 组装完毕 ：14
batch_tensor数据 组装完毕 ：14,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 14 ----- 1
正在处理 14 ----- 2
正在处理 14 ----- 3
正在处理 14 ----- 4
正在处理 14 ----- 5
正在处理 14 ----- 6
正在处理 14 ----- 7
正在处理 14 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 14
============================

正在读取第 15 个DataFrame
初始化batch数据： 15
batch数据 组装完毕 ：15
batch_tensor数据 组装完毕 ：15,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 15 ----- 1
正在处理 15 ----- 2
正在处理 15 ----- 3
正在处理 15 ----- 4
正在处理 15 ----- 5
正在处理 15 ----- 6
正在处理 15 ----- 7
正在处理 15 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 15
============================

正在读取第 16 个DataFrame
初始化batch数据： 16
batch数据 组装完毕 ：16
batch_tensor数据 组装完毕 ：16,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 16 ----- 1
正在处理 16 ----- 2
正在处理 16 ----- 3
正在处理 16 ----- 4
正在处理 16 ----- 5
正在处理 16 ----- 6
正在处理 16 ----- 7
正在处理 16 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 16
============================

正在读取第 17 个DataFrame
初始化batch数据： 17
batch数据 组装完毕 ：17
batch_tensor数据 组装完毕 ：17,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 17 ----- 1
正在处理 17 ----- 2
正在处理 17 ----- 3
正在处理 17 ----- 4
正在处理 17 ----- 5
正在处理 17 ----- 6
正在处理 17 ----- 7
正在处理 17 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 17
============================

正在读取第 18 个DataFrame
初始化batch数据： 18
batch数据 组装完毕 ：18
batch_tensor数据 组装完毕 ：18,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 18 ----- 1
正在处理 18 ----- 2
正在处理 18 ----- 3
正在处理 18 ----- 4
正在处理 18 ----- 5
正在处理 18 ----- 6
正在处理 18 ----- 7
正在处理 18 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 18
============================

正在读取第 19 个DataFrame
初始化batch数据： 19
batch数据 组装完毕 ：19
batch_tensor数据 组装完毕 ：19,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 19 ----- 1
正在处理 19 ----- 2
正在处理 19 ----- 3
正在处理 19 ----- 4
正在处理 19 ----- 5
正在处理 19 ----- 6
正在处理 19 ----- 7
正在处理 19 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 19
============================

正在读取第 20 个DataFrame
初始化batch数据： 20
batch数据 组装完毕 ：20
batch_tensor数据 组装完毕 ：20,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 20 ----- 1
正在处理 20 ----- 2
正在处理 20 ----- 3
正在处理 20 ----- 4
正在处理 20 ----- 5
正在处理 20 ----- 6
正在处理 20 ----- 7
正在处理 20 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 20
============================

正在读取第 21 个DataFrame
初始化batch数据： 21
batch数据 组装完毕 ：21
batch_tensor数据 组装完毕 ：21,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 21 ----- 1
正在处理 21 ----- 2
正在处理 21 ----- 3
正在处理 21 ----- 4
正在处理 21 ----- 5
正在处理 21 ----- 6
正在处理 21 ----- 7
正在处理 21 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 21
============================

正在读取第 22 个DataFrame
初始化batch数据： 22
batch数据 组装完毕 ：22
batch_tensor数据 组装完毕 ：22,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 22 ----- 1
正在处理 22 ----- 2
正在处理 22 ----- 3
正在处理 22 ----- 4
正在处理 22 ----- 5
正在处理 22 ----- 6
正在处理 22 ----- 7
正在处理 22 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 22
============================

正在读取第 23 个DataFrame
初始化batch数据： 23
batch数据 组装完毕 ：23
batch_tensor数据 组装完毕 ：23,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 23 ----- 1
正在处理 23 ----- 2
正在处理 23 ----- 3
正在处理 23 ----- 4
正在处理 23 ----- 5
正在处理 23 ----- 6
正在处理 23 ----- 7
正在处理 23 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 23
============================

正在读取第 24 个DataFrame
初始化batch数据： 24
batch数据 组装完毕 ：24
batch_tensor数据 组装完毕 ：24,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 24 ----- 1
正在处理 24 ----- 2
正在处理 24 ----- 3
正在处理 24 ----- 4
正在处理 24 ----- 5
正在处理 24 ----- 6
正在处理 24 ----- 7
正在处理 24 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 24
============================

正在读取第 25 个DataFrame
初始化batch数据： 25
batch数据 组装完毕 ：25
batch_tensor数据 组装完毕 ：25,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 25 ----- 1
正在处理 25 ----- 2
正在处理 25 ----- 3
正在处理 25 ----- 4
正在处理 25 ----- 5
正在处理 25 ----- 6
正在处理 25 ----- 7
正在处理 25 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 25
============================

正在读取第 26 个DataFrame
初始化batch数据： 26
batch数据 组装完毕 ：26
batch_tensor数据 组装完毕 ：26,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 26 ----- 1
正在处理 26 ----- 2
正在处理 26 ----- 3
正在处理 26 ----- 4
正在处理 26 ----- 5
正在处理 26 ----- 6
正在处理 26 ----- 7
正在处理 26 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 26
============================

正在读取第 27 个DataFrame
初始化batch数据： 27
batch数据 组装完毕 ：27
batch_tensor数据 组装完毕 ：27,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 27 ----- 1
正在处理 27 ----- 2
正在处理 27 ----- 3
正在处理 27 ----- 4
正在处理 27 ----- 5
正在处理 27 ----- 6
正在处理 27 ----- 7
正在处理 27 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 27
============================

正在读取第 28 个DataFrame
初始化batch数据： 28
batch数据 组装完毕 ：28
batch_tensor数据 组装完毕 ：28,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 28 ----- 1
正在处理 28 ----- 2
正在处理 28 ----- 3
正在处理 28 ----- 4
正在处理 28 ----- 5
正在处理 28 ----- 6
正在处理 28 ----- 7
正在处理 28 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 28
============================

正在读取第 29 个DataFrame
初始化batch数据： 29
batch数据 组装完毕 ：29
batch_tensor数据 组装完毕 ：29,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 29 ----- 1
正在处理 29 ----- 2
正在处理 29 ----- 3
正在处理 29 ----- 4
正在处理 29 ----- 5
正在处理 29 ----- 6
正在处理 29 ----- 7
正在处理 29 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 29
============================

正在读取第 30 个DataFrame
初始化batch数据： 30
batch数据 组装完毕 ：30
batch_tensor数据 组装完毕 ：30,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 30 ----- 1
正在处理 30 ----- 2
正在处理 30 ----- 3
正在处理 30 ----- 4
正在处理 30 ----- 5
正在处理 30 ----- 6
正在处理 30 ----- 7
正在处理 30 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 30
============================

正在读取第 31 个DataFrame
初始化batch数据： 31
batch数据 组装完毕 ：31
batch_tensor数据 组装完毕 ：31,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 31 ----- 1
正在处理 31 ----- 2
正在处理 31 ----- 3
正在处理 31 ----- 4
正在处理 31 ----- 5
正在处理 31 ----- 6
正在处理 31 ----- 7
正在处理 31 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 31
============================

正在读取第 32 个DataFrame
初始化batch数据： 32
batch数据 组装完毕 ：32
batch_tensor数据 组装完毕 ：32,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 32 ----- 1
正在处理 32 ----- 2
正在处理 32 ----- 3
正在处理 32 ----- 4
正在处理 32 ----- 5
正在处理 32 ----- 6
正在处理 32 ----- 7
正在处理 32 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 32
============================

正在读取第 33 个DataFrame
初始化batch数据： 33
batch数据 组装完毕 ：33
batch_tensor数据 组装完毕 ：33,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 33 ----- 1
正在处理 33 ----- 2
正在处理 33 ----- 3
正在处理 33 ----- 4
正在处理 33 ----- 5
正在处理 33 ----- 6
正在处理 33 ----- 7
正在处理 33 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 33
============================

正在读取第 34 个DataFrame
初始化batch数据： 34
batch数据 组装完毕 ：34
batch_tensor数据 组装完毕 ：34,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 34 ----- 1
正在处理 34 ----- 2
正在处理 34 ----- 3
正在处理 34 ----- 4
正在处理 34 ----- 5
正在处理 34 ----- 6
正在处理 34 ----- 7
正在处理 34 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 34
============================

正在读取第 35 个DataFrame
初始化batch数据： 35
batch数据 组装完毕 ：35
batch_tensor数据 组装完毕 ：35,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 35 ----- 1
正在处理 35 ----- 2
正在处理 35 ----- 3
正在处理 35 ----- 4
正在处理 35 ----- 5
正在处理 35 ----- 6
正在处理 35 ----- 7
正在处理 35 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 35
============================

正在读取第 36 个DataFrame
初始化batch数据： 36
batch数据 组装完毕 ：36
batch_tensor数据 组装完毕 ：36,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 36 ----- 1
正在处理 36 ----- 2
正在处理 36 ----- 3
正在处理 36 ----- 4
正在处理 36 ----- 5
正在处理 36 ----- 6
正在处理 36 ----- 7
正在处理 36 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 36
============================

正在读取第 37 个DataFrame
初始化batch数据： 37
batch数据 组装完毕 ：37
batch_tensor数据 组装完毕 ：37,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 37 ----- 1
正在处理 37 ----- 2
正在处理 37 ----- 3
正在处理 37 ----- 4
正在处理 37 ----- 5
正在处理 37 ----- 6
正在处理 37 ----- 7
正在处理 37 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 37
============================

正在读取第 38 个DataFrame
初始化batch数据： 38
batch数据 组装完毕 ：38
batch_tensor数据 组装完毕 ：38,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 38 ----- 1
正在处理 38 ----- 2
正在处理 38 ----- 3
正在处理 38 ----- 4
正在处理 38 ----- 5
正在处理 38 ----- 6
正在处理 38 ----- 7
正在处理 38 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 38
============================

正在读取第 39 个DataFrame
初始化batch数据： 39
batch数据 组装完毕 ：39
batch_tensor数据 组装完毕 ：39,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 39 ----- 1
正在处理 39 ----- 2
正在处理 39 ----- 3
正在处理 39 ----- 4
正在处理 39 ----- 5
正在处理 39 ----- 6
正在处理 39 ----- 7
正在处理 39 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 39
============================

正在读取第 40 个DataFrame
初始化batch数据： 40
batch数据 组装完毕 ：40
batch_tensor数据 组装完毕 ：40,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 40 ----- 1
正在处理 40 ----- 2
正在处理 40 ----- 3
正在处理 40 ----- 4
正在处理 40 ----- 5
正在处理 40 ----- 6
正在处理 40 ----- 7
正在处理 40 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 40
============================

正在读取第 41 个DataFrame
初始化batch数据： 41
batch数据 组装完毕 ：41
batch_tensor数据 组装完毕 ：41,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 41 ----- 1
正在处理 41 ----- 2
正在处理 41 ----- 3
正在处理 41 ----- 4
正在处理 41 ----- 5
正在处理 41 ----- 6
正在处理 41 ----- 7
正在处理 41 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 41
============================

正在读取第 42 个DataFrame
初始化batch数据： 42
batch数据 组装完毕 ：42
batch_tensor数据 组装完毕 ：42,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 42 ----- 1
正在处理 42 ----- 2
正在处理 42 ----- 3
正在处理 42 ----- 4
正在处理 42 ----- 5
正在处理 42 ----- 6
正在处理 42 ----- 7
正在处理 42 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 42
============================

正在读取第 43 个DataFrame
初始化batch数据： 43
batch数据 组装完毕 ：43
batch_tensor数据 组装完毕 ：43,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 43 ----- 1
正在处理 43 ----- 2
正在处理 43 ----- 3
正在处理 43 ----- 4
正在处理 43 ----- 5
正在处理 43 ----- 6
正在处理 43 ----- 7
正在处理 43 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 43
============================

正在读取第 44 个DataFrame
初始化batch数据： 44
batch数据 组装完毕 ：44
batch_tensor数据 组装完毕 ：44,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 44 ----- 1
正在处理 44 ----- 2
正在处理 44 ----- 3
正在处理 44 ----- 4
正在处理 44 ----- 5
正在处理 44 ----- 6
正在处理 44 ----- 7
正在处理 44 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 44
============================

正在读取第 45 个DataFrame
初始化batch数据： 45
batch数据 组装完毕 ：45
batch_tensor数据 组装完毕 ：45,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 45 ----- 1
正在处理 45 ----- 2
正在处理 45 ----- 3
正在处理 45 ----- 4
正在处理 45 ----- 5
正在处理 45 ----- 6
正在处理 45 ----- 7
正在处理 45 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 45
============================

正在读取第 46 个DataFrame
初始化batch数据： 46
batch数据 组装完毕 ：46
batch_tensor数据 组装完毕 ：46,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 46 ----- 1
正在处理 46 ----- 2
正在处理 46 ----- 3
正在处理 46 ----- 4
正在处理 46 ----- 5
正在处理 46 ----- 6
正在处理 46 ----- 7
正在处理 46 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 46
============================

正在读取第 47 个DataFrame
初始化batch数据： 47
batch数据 组装完毕 ：47
batch_tensor数据 组装完毕 ：47,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 47 ----- 1
正在处理 47 ----- 2
正在处理 47 ----- 3
正在处理 47 ----- 4
正在处理 47 ----- 5
正在处理 47 ----- 6
正在处理 47 ----- 7
正在处理 47 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 47
============================

正在读取第 48 个DataFrame
初始化batch数据： 48
batch数据 组装完毕 ：48
batch_tensor数据 组装完毕 ：48,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 48 ----- 1
正在处理 48 ----- 2
正在处理 48 ----- 3
正在处理 48 ----- 4
正在处理 48 ----- 5
正在处理 48 ----- 6
正在处理 48 ----- 7
正在处理 48 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 48
============================

正在读取第 49 个DataFrame
初始化batch数据： 49
batch数据 组装完毕 ：49
batch_tensor数据 组装完毕 ：49,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 49 ----- 1
正在处理 49 ----- 2
正在处理 49 ----- 3
正在处理 49 ----- 4
正在处理 49 ----- 5
正在处理 49 ----- 6
正在处理 49 ----- 7
正在处理 49 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 49
============================

正在读取第 50 个DataFrame
初始化batch数据： 50
batch数据 组装完毕 ：50
batch_tensor数据 组装完毕 ：50,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 50 ----- 1
正在处理 50 ----- 2
正在处理 50 ----- 3
正在处理 50 ----- 4
正在处理 50 ----- 5
正在处理 50 ----- 6
正在处理 50 ----- 7
正在处理 50 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 50
============================

正在读取第 51 个DataFrame
初始化batch数据： 51
batch数据 组装完毕 ：51
batch_tensor数据 组装完毕 ：51,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 51 ----- 1
正在处理 51 ----- 2
正在处理 51 ----- 3
正在处理 51 ----- 4
正在处理 51 ----- 5
正在处理 51 ----- 6
正在处理 51 ----- 7
正在处理 51 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 51
============================

正在读取第 52 个DataFrame
初始化batch数据： 52
batch数据 组装完毕 ：52
batch_tensor数据 组装完毕 ：52,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 52 ----- 1
正在处理 52 ----- 2
正在处理 52 ----- 3
正在处理 52 ----- 4
正在处理 52 ----- 5
正在处理 52 ----- 6
正在处理 52 ----- 7
正在处理 52 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 52
============================

正在读取第 53 个DataFrame
初始化batch数据： 53
batch数据 组装完毕 ：53
batch_tensor数据 组装完毕 ：53,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 53 ----- 1
正在处理 53 ----- 2
正在处理 53 ----- 3
正在处理 53 ----- 4
正在处理 53 ----- 5
正在处理 53 ----- 6
正在处理 53 ----- 7
正在处理 53 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 53
============================

正在读取第 54 个DataFrame
初始化batch数据： 54
batch数据 组装完毕 ：54
batch_tensor数据 组装完毕 ：54,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 54 ----- 1
正在处理 54 ----- 2
正在处理 54 ----- 3
正在处理 54 ----- 4
正在处理 54 ----- 5
正在处理 54 ----- 6
正在处理 54 ----- 7
正在处理 54 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 54
============================

正在读取第 55 个DataFrame
初始化batch数据： 55
batch数据 组装完毕 ：55
batch_tensor数据 组装完毕 ：55,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 55 ----- 1
正在处理 55 ----- 2
正在处理 55 ----- 3
正在处理 55 ----- 4
正在处理 55 ----- 5
正在处理 55 ----- 6
正在处理 55 ----- 7
正在处理 55 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 55
============================

正在读取第 56 个DataFrame
初始化batch数据： 56
batch数据 组装完毕 ：56
batch_tensor数据 组装完毕 ：56,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 56 ----- 1
正在处理 56 ----- 2
正在处理 56 ----- 3
正在处理 56 ----- 4
正在处理 56 ----- 5
正在处理 56 ----- 6
正在处理 56 ----- 7
正在处理 56 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 56
============================

正在读取第 57 个DataFrame
初始化batch数据： 57
batch数据 组装完毕 ：57
batch_tensor数据 组装完毕 ：57,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 57 ----- 1
正在处理 57 ----- 2
正在处理 57 ----- 3
正在处理 57 ----- 4
正在处理 57 ----- 5
正在处理 57 ----- 6
正在处理 57 ----- 7
正在处理 57 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 57
============================

正在读取第 58 个DataFrame
初始化batch数据： 58
batch数据 组装完毕 ：58
batch_tensor数据 组装完毕 ：58,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 58 ----- 1
正在处理 58 ----- 2
正在处理 58 ----- 3
正在处理 58 ----- 4
正在处理 58 ----- 5
正在处理 58 ----- 6
正在处理 58 ----- 7
正在处理 58 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 58
============================

正在读取第 59 个DataFrame
初始化batch数据： 59
batch数据 组装完毕 ：59
batch_tensor数据 组装完毕 ：59,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 59 ----- 1
正在处理 59 ----- 2
正在处理 59 ----- 3
正在处理 59 ----- 4
正在处理 59 ----- 5
正在处理 59 ----- 6
正在处理 59 ----- 7
正在处理 59 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 59
============================

正在读取第 60 个DataFrame
初始化batch数据： 60
batch数据 组装完毕 ：60
batch_tensor数据 组装完毕 ：60,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 60 ----- 1
正在处理 60 ----- 2
正在处理 60 ----- 3
正在处理 60 ----- 4
正在处理 60 ----- 5
正在处理 60 ----- 6
正在处理 60 ----- 7
正在处理 60 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 60
============================

正在读取第 61 个DataFrame
初始化batch数据： 61
batch数据 组装完毕 ：61
batch_tensor数据 组装完毕 ：61,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 61 ----- 1
正在处理 61 ----- 2
正在处理 61 ----- 3
正在处理 61 ----- 4
正在处理 61 ----- 5
正在处理 61 ----- 6
正在处理 61 ----- 7
正在处理 61 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 61
============================

正在读取第 62 个DataFrame
初始化batch数据： 62
batch数据 组装完毕 ：62
batch_tensor数据 组装完毕 ：62,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 62 ----- 1
正在处理 62 ----- 2
正在处理 62 ----- 3
正在处理 62 ----- 4
正在处理 62 ----- 5
正在处理 62 ----- 6
正在处理 62 ----- 7
正在处理 62 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 62
============================

正在读取第 63 个DataFrame
初始化batch数据： 63
batch数据 组装完毕 ：63
batch_tensor数据 组装完毕 ：63,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 63 ----- 1
正在处理 63 ----- 2
正在处理 63 ----- 3
正在处理 63 ----- 4
正在处理 63 ----- 5
正在处理 63 ----- 6
正在处理 63 ----- 7
正在处理 63 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 63
============================

正在读取第 64 个DataFrame
初始化batch数据： 64
batch数据 组装完毕 ：64
batch_tensor数据 组装完毕 ：64,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 64 ----- 1
正在处理 64 ----- 2
正在处理 64 ----- 3
正在处理 64 ----- 4
正在处理 64 ----- 5
正在处理 64 ----- 6
正在处理 64 ----- 7
正在处理 64 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 64
============================

正在读取第 65 个DataFrame
初始化batch数据： 65
batch数据 组装完毕 ：65
batch_tensor数据 组装完毕 ：65,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 65 ----- 1
正在处理 65 ----- 2
正在处理 65 ----- 3
正在处理 65 ----- 4
正在处理 65 ----- 5
正在处理 65 ----- 6
正在处理 65 ----- 7
正在处理 65 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 65
============================

正在读取第 66 个DataFrame
初始化batch数据： 66
batch数据 组装完毕 ：66
batch_tensor数据 组装完毕 ：66,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 66 ----- 1
正在处理 66 ----- 2
正在处理 66 ----- 3
正在处理 66 ----- 4
正在处理 66 ----- 5
正在处理 66 ----- 6
正在处理 66 ----- 7
正在处理 66 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 66
============================

正在读取第 67 个DataFrame
初始化batch数据： 67
batch数据 组装完毕 ：67
batch_tensor数据 组装完毕 ：67,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 67 ----- 1
正在处理 67 ----- 2
正在处理 67 ----- 3
正在处理 67 ----- 4
正在处理 67 ----- 5
正在处理 67 ----- 6
正在处理 67 ----- 7
正在处理 67 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 67
============================

正在读取第 68 个DataFrame
初始化batch数据： 68
batch数据 组装完毕 ：68
batch_tensor数据 组装完毕 ：68,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 68 ----- 1
正在处理 68 ----- 2
正在处理 68 ----- 3
正在处理 68 ----- 4
正在处理 68 ----- 5
正在处理 68 ----- 6
正在处理 68 ----- 7
正在处理 68 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 68
============================

正在读取第 69 个DataFrame
初始化batch数据： 69
batch数据 组装完毕 ：69
batch_tensor数据 组装完毕 ：69,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 69 ----- 1
正在处理 69 ----- 2
正在处理 69 ----- 3
正在处理 69 ----- 4
正在处理 69 ----- 5
正在处理 69 ----- 6
正在处理 69 ----- 7
正在处理 69 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 69
============================

正在读取第 70 个DataFrame
初始化batch数据： 70
batch数据 组装完毕 ：70
batch_tensor数据 组装完毕 ：70,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 70 ----- 1
正在处理 70 ----- 2
正在处理 70 ----- 3
正在处理 70 ----- 4
正在处理 70 ----- 5
正在处理 70 ----- 6
正在处理 70 ----- 7
正在处理 70 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 70
============================

正在读取第 71 个DataFrame
初始化batch数据： 71
batch数据 组装完毕 ：71
batch_tensor数据 组装完毕 ：71,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 71 ----- 1
正在处理 71 ----- 2
正在处理 71 ----- 3
正在处理 71 ----- 4
正在处理 71 ----- 5
正在处理 71 ----- 6
正在处理 71 ----- 7
正在处理 71 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 71
============================

正在读取第 72 个DataFrame
初始化batch数据： 72
batch数据 组装完毕 ：72
batch_tensor数据 组装完毕 ：72,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 72 ----- 1
正在处理 72 ----- 2
正在处理 72 ----- 3
正在处理 72 ----- 4
正在处理 72 ----- 5
正在处理 72 ----- 6
正在处理 72 ----- 7
正在处理 72 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 72
============================

正在读取第 73 个DataFrame
初始化batch数据： 73
batch数据 组装完毕 ：73
batch_tensor数据 组装完毕 ：73,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 73 ----- 1
正在处理 73 ----- 2
正在处理 73 ----- 3
正在处理 73 ----- 4
正在处理 73 ----- 5
正在处理 73 ----- 6
正在处理 73 ----- 7
正在处理 73 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 73
============================

正在读取第 74 个DataFrame
初始化batch数据： 74
batch数据 组装完毕 ：74
batch_tensor数据 组装完毕 ：74,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 74 ----- 1
正在处理 74 ----- 2
正在处理 74 ----- 3
正在处理 74 ----- 4
正在处理 74 ----- 5
正在处理 74 ----- 6
正在处理 74 ----- 7
正在处理 74 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 74
============================

正在读取第 75 个DataFrame
初始化batch数据： 75
batch数据 组装完毕 ：75
batch_tensor数据 组装完毕 ：75,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 75 ----- 1
正在处理 75 ----- 2
正在处理 75 ----- 3
正在处理 75 ----- 4
正在处理 75 ----- 5
正在处理 75 ----- 6
正在处理 75 ----- 7
正在处理 75 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 75
============================

正在读取第 76 个DataFrame
初始化batch数据： 76
batch数据 组装完毕 ：76
batch_tensor数据 组装完毕 ：76,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 76 ----- 1
正在处理 76 ----- 2
正在处理 76 ----- 3
正在处理 76 ----- 4
正在处理 76 ----- 5
正在处理 76 ----- 6
正在处理 76 ----- 7
正在处理 76 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 76
============================

正在读取第 77 个DataFrame
初始化batch数据： 77
batch数据 组装完毕 ：77
batch_tensor数据 组装完毕 ：77,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 77 ----- 1
正在处理 77 ----- 2
正在处理 77 ----- 3
正在处理 77 ----- 4
正在处理 77 ----- 5
正在处理 77 ----- 6
正在处理 77 ----- 7
正在处理 77 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 77
============================

正在读取第 78 个DataFrame
初始化batch数据： 78
batch数据 组装完毕 ：78
batch_tensor数据 组装完毕 ：78,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 78 ----- 1
正在处理 78 ----- 2
正在处理 78 ----- 3
正在处理 78 ----- 4
正在处理 78 ----- 5
正在处理 78 ----- 6
正在处理 78 ----- 7
正在处理 78 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 78
============================

正在读取第 79 个DataFrame
初始化batch数据： 79
batch数据 组装完毕 ：79
batch_tensor数据 组装完毕 ：79,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 79 ----- 1
正在处理 79 ----- 2
正在处理 79 ----- 3
正在处理 79 ----- 4
正在处理 79 ----- 5
正在处理 79 ----- 6
正在处理 79 ----- 7
正在处理 79 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 79
============================

正在读取第 80 个DataFrame
初始化batch数据： 80
batch数据 组装完毕 ：80
batch_tensor数据 组装完毕 ：80,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 80 ----- 1
正在处理 80 ----- 2
正在处理 80 ----- 3
正在处理 80 ----- 4
正在处理 80 ----- 5
正在处理 80 ----- 6
正在处理 80 ----- 7
正在处理 80 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 80
============================

正在读取第 81 个DataFrame
初始化batch数据： 81
batch数据 组装完毕 ：81
batch_tensor数据 组装完毕 ：81,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 81 ----- 1
正在处理 81 ----- 2
正在处理 81 ----- 3
正在处理 81 ----- 4
正在处理 81 ----- 5
正在处理 81 ----- 6
正在处理 81 ----- 7
正在处理 81 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 81
============================

正在读取第 82 个DataFrame
初始化batch数据： 82
batch数据 组装完毕 ：82
batch_tensor数据 组装完毕 ：82,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 82 ----- 1
正在处理 82 ----- 2
正在处理 82 ----- 3
正在处理 82 ----- 4
正在处理 82 ----- 5
正在处理 82 ----- 6
正在处理 82 ----- 7
正在处理 82 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 82
============================

正在读取第 83 个DataFrame
初始化batch数据： 83
batch数据 组装完毕 ：83
batch_tensor数据 组装完毕 ：83,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 83 ----- 1
正在处理 83 ----- 2
正在处理 83 ----- 3
正在处理 83 ----- 4
正在处理 83 ----- 5
正在处理 83 ----- 6
正在处理 83 ----- 7
正在处理 83 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 83
============================

正在读取第 84 个DataFrame
初始化batch数据： 84
batch数据 组装完毕 ：84
batch_tensor数据 组装完毕 ：84,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 84 ----- 1
正在处理 84 ----- 2
正在处理 84 ----- 3
正在处理 84 ----- 4
正在处理 84 ----- 5
正在处理 84 ----- 6
正在处理 84 ----- 7
正在处理 84 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 84
============================

正在读取第 85 个DataFrame
初始化batch数据： 85
batch数据 组装完毕 ：85
batch_tensor数据 组装完毕 ：85,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 85 ----- 1
正在处理 85 ----- 2
正在处理 85 ----- 3
正在处理 85 ----- 4
正在处理 85 ----- 5
正在处理 85 ----- 6
正在处理 85 ----- 7
正在处理 85 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 85
============================

正在读取第 86 个DataFrame
初始化batch数据： 86
batch数据 组装完毕 ：86
batch_tensor数据 组装完毕 ：86,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 86 ----- 1
正在处理 86 ----- 2
正在处理 86 ----- 3
正在处理 86 ----- 4
正在处理 86 ----- 5
正在处理 86 ----- 6
正在处理 86 ----- 7
正在处理 86 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 86
============================

正在读取第 87 个DataFrame
初始化batch数据： 87
batch数据 组装完毕 ：87
batch_tensor数据 组装完毕 ：87,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 87 ----- 1
正在处理 87 ----- 2
正在处理 87 ----- 3
正在处理 87 ----- 4
正在处理 87 ----- 5
正在处理 87 ----- 6
正在处理 87 ----- 7
正在处理 87 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 87
============================

正在读取第 88 个DataFrame
初始化batch数据： 88
batch数据 组装完毕 ：88
batch_tensor数据 组装完毕 ：88,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 88 ----- 1
正在处理 88 ----- 2
正在处理 88 ----- 3
正在处理 88 ----- 4
正在处理 88 ----- 5
正在处理 88 ----- 6
正在处理 88 ----- 7
正在处理 88 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 88
============================

正在读取第 89 个DataFrame
初始化batch数据： 89
batch数据 组装完毕 ：89
batch_tensor数据 组装完毕 ：89,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 89 ----- 1
正在处理 89 ----- 2
正在处理 89 ----- 3
正在处理 89 ----- 4
正在处理 89 ----- 5
正在处理 89 ----- 6
正在处理 89 ----- 7
正在处理 89 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 89
============================

正在读取第 90 个DataFrame
初始化batch数据： 90
batch数据 组装完毕 ：90
batch_tensor数据 组装完毕 ：90,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 90 ----- 1
正在处理 90 ----- 2
正在处理 90 ----- 3
正在处理 90 ----- 4
正在处理 90 ----- 5
正在处理 90 ----- 6
正在处理 90 ----- 7
正在处理 90 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 90
============================

正在读取第 91 个DataFrame
初始化batch数据： 91
batch数据 组装完毕 ：91
batch_tensor数据 组装完毕 ：91,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 91 ----- 1
正在处理 91 ----- 2
正在处理 91 ----- 3
正在处理 91 ----- 4
正在处理 91 ----- 5
正在处理 91 ----- 6
正在处理 91 ----- 7
正在处理 91 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 91
============================

正在读取第 92 个DataFrame
初始化batch数据： 92
batch数据 组装完毕 ：92
batch_tensor数据 组装完毕 ：92,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 92 ----- 1
正在处理 92 ----- 2
正在处理 92 ----- 3
正在处理 92 ----- 4
正在处理 92 ----- 5
正在处理 92 ----- 6
正在处理 92 ----- 7
正在处理 92 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 92
============================

正在读取第 93 个DataFrame
初始化batch数据： 93
batch数据 组装完毕 ：93
batch_tensor数据 组装完毕 ：93,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 93 ----- 1
正在处理 93 ----- 2
正在处理 93 ----- 3
正在处理 93 ----- 4
正在处理 93 ----- 5
正在处理 93 ----- 6
正在处理 93 ----- 7
正在处理 93 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 93
============================

正在读取第 94 个DataFrame
初始化batch数据： 94
batch数据 组装完毕 ：94
batch_tensor数据 组装完毕 ：94,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 94 ----- 1
正在处理 94 ----- 2
正在处理 94 ----- 3
正在处理 94 ----- 4
正在处理 94 ----- 5
正在处理 94 ----- 6
正在处理 94 ----- 7
正在处理 94 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 94
============================

正在读取第 95 个DataFrame
初始化batch数据： 95
batch数据 组装完毕 ：95
batch_tensor数据 组装完毕 ：95,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 95 ----- 1
正在处理 95 ----- 2
正在处理 95 ----- 3
正在处理 95 ----- 4
正在处理 95 ----- 5
正在处理 95 ----- 6
正在处理 95 ----- 7
正在处理 95 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 95
============================

正在读取第 96 个DataFrame
初始化batch数据： 96
batch数据 组装完毕 ：96
batch_tensor数据 组装完毕 ：96,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 96 ----- 1
正在处理 96 ----- 2
正在处理 96 ----- 3
正在处理 96 ----- 4
正在处理 96 ----- 5
正在处理 96 ----- 6
正在处理 96 ----- 7
正在处理 96 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 96
============================

正在读取第 97 个DataFrame
初始化batch数据： 97
batch数据 组装完毕 ：97
batch_tensor数据 组装完毕 ：97,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 97 ----- 1
正在处理 97 ----- 2
正在处理 97 ----- 3
正在处理 97 ----- 4
正在处理 97 ----- 5
正在处理 97 ----- 6
正在处理 97 ----- 7
正在处理 97 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 97
============================

正在读取第 98 个DataFrame
初始化batch数据： 98
batch数据 组装完毕 ：98
batch_tensor数据 组装完毕 ：98,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 98 ----- 1
正在处理 98 ----- 2
正在处理 98 ----- 3
正在处理 98 ----- 4
正在处理 98 ----- 5
正在处理 98 ----- 6
正在处理 98 ----- 7
正在处理 98 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 98
============================

正在读取第 99 个DataFrame
初始化batch数据： 99
batch数据 组装完毕 ：99
batch_tensor数据 组装完毕 ：99,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 99 ----- 1
正在处理 99 ----- 2
正在处理 99 ----- 3
正在处理 99 ----- 4
正在处理 99 ----- 5
正在处理 99 ----- 6
正在处理 99 ----- 7
正在处理 99 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 99
============================

正在读取第 100 个DataFrame
初始化batch数据： 100
batch数据 组装完毕 ：100
batch_tensor数据 组装完毕 ：100,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 100 ----- 1
正在处理 100 ----- 2
正在处理 100 ----- 3
正在处理 100 ----- 4
正在处理 100 ----- 5
正在处理 100 ----- 6
正在处理 100 ----- 7
正在处理 100 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 100
============================

正在读取第 101 个DataFrame
初始化batch数据： 101
batch数据 组装完毕 ：101
batch_tensor数据 组装完毕 ：101,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 101 ----- 1
正在处理 101 ----- 2
正在处理 101 ----- 3
正在处理 101 ----- 4
正在处理 101 ----- 5
正在处理 101 ----- 6
正在处理 101 ----- 7
正在处理 101 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 101
============================

正在读取第 102 个DataFrame
初始化batch数据： 102
batch数据 组装完毕 ：102
batch_tensor数据 组装完毕 ：102,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 102 ----- 1
正在处理 102 ----- 2
正在处理 102 ----- 3
正在处理 102 ----- 4
正在处理 102 ----- 5
正在处理 102 ----- 6
正在处理 102 ----- 7
正在处理 102 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 102
============================

正在读取第 103 个DataFrame
初始化batch数据： 103
batch数据 组装完毕 ：103
batch_tensor数据 组装完毕 ：103,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 103 ----- 1
正在处理 103 ----- 2
正在处理 103 ----- 3
正在处理 103 ----- 4
正在处理 103 ----- 5
正在处理 103 ----- 6
正在处理 103 ----- 7
正在处理 103 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 103
============================

正在读取第 104 个DataFrame
初始化batch数据： 104
batch数据 组装完毕 ：104
batch_tensor数据 组装完毕 ：104,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 104 ----- 1
正在处理 104 ----- 2
正在处理 104 ----- 3
正在处理 104 ----- 4
正在处理 104 ----- 5
正在处理 104 ----- 6
正在处理 104 ----- 7
正在处理 104 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 104
============================

正在读取第 105 个DataFrame
初始化batch数据： 105
batch数据 组装完毕 ：105
batch_tensor数据 组装完毕 ：105,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 105 ----- 1
正在处理 105 ----- 2
正在处理 105 ----- 3
正在处理 105 ----- 4
正在处理 105 ----- 5
正在处理 105 ----- 6
正在处理 105 ----- 7
正在处理 105 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 105
============================

正在读取第 106 个DataFrame
初始化batch数据： 106
batch数据 组装完毕 ：106
batch_tensor数据 组装完毕 ：106,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 106 ----- 1
正在处理 106 ----- 2
正在处理 106 ----- 3
正在处理 106 ----- 4
正在处理 106 ----- 5
正在处理 106 ----- 6
正在处理 106 ----- 7
正在处理 106 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 106
============================

正在读取第 107 个DataFrame
初始化batch数据： 107
batch数据 组装完毕 ：107
batch_tensor数据 组装完毕 ：107,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 107 ----- 1
正在处理 107 ----- 2
正在处理 107 ----- 3
正在处理 107 ----- 4
正在处理 107 ----- 5
正在处理 107 ----- 6
正在处理 107 ----- 7
正在处理 107 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 107
============================

正在读取第 108 个DataFrame
初始化batch数据： 108
batch数据 组装完毕 ：108
batch_tensor数据 组装完毕 ：108,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 108 ----- 1
正在处理 108 ----- 2
正在处理 108 ----- 3
正在处理 108 ----- 4
正在处理 108 ----- 5
正在处理 108 ----- 6
正在处理 108 ----- 7
正在处理 108 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 108
============================

正在读取第 109 个DataFrame
初始化batch数据： 109
batch数据 组装完毕 ：109
batch_tensor数据 组装完毕 ：109,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 109 ----- 1
正在处理 109 ----- 2
正在处理 109 ----- 3
正在处理 109 ----- 4
正在处理 109 ----- 5
正在处理 109 ----- 6
正在处理 109 ----- 7
正在处理 109 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 109
============================

正在读取第 110 个DataFrame
初始化batch数据： 110
batch数据 组装完毕 ：110
batch_tensor数据 组装完毕 ：110,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 110 ----- 1
正在处理 110 ----- 2
正在处理 110 ----- 3
正在处理 110 ----- 4
正在处理 110 ----- 5
正在处理 110 ----- 6
正在处理 110 ----- 7
正在处理 110 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 110
============================

正在读取第 111 个DataFrame
初始化batch数据： 111
batch数据 组装完毕 ：111
batch_tensor数据 组装完毕 ：111,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 111 ----- 1
正在处理 111 ----- 2
正在处理 111 ----- 3
正在处理 111 ----- 4
正在处理 111 ----- 5
正在处理 111 ----- 6
正在处理 111 ----- 7
正在处理 111 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 111
============================

正在读取第 112 个DataFrame
初始化batch数据： 112
batch数据 组装完毕 ：112
batch_tensor数据 组装完毕 ：112,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 112 ----- 1
正在处理 112 ----- 2
正在处理 112 ----- 3
正在处理 112 ----- 4
正在处理 112 ----- 5
正在处理 112 ----- 6
正在处理 112 ----- 7
正在处理 112 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 112
============================

正在读取第 113 个DataFrame
初始化batch数据： 113
batch数据 组装完毕 ：113
batch_tensor数据 组装完毕 ：113,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 113 ----- 1
正在处理 113 ----- 2
正在处理 113 ----- 3
正在处理 113 ----- 4
正在处理 113 ----- 5
正在处理 113 ----- 6
正在处理 113 ----- 7
正在处理 113 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 113
============================

正在读取第 114 个DataFrame
初始化batch数据： 114
batch数据 组装完毕 ：114
batch_tensor数据 组装完毕 ：114,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 114 ----- 1
正在处理 114 ----- 2
正在处理 114 ----- 3
正在处理 114 ----- 4
正在处理 114 ----- 5
正在处理 114 ----- 6
正在处理 114 ----- 7
正在处理 114 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 114
============================

正在读取第 115 个DataFrame
初始化batch数据： 115
batch数据 组装完毕 ：115
batch_tensor数据 组装完毕 ：115,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 115 ----- 1
正在处理 115 ----- 2
正在处理 115 ----- 3
正在处理 115 ----- 4
正在处理 115 ----- 5
正在处理 115 ----- 6
正在处理 115 ----- 7
正在处理 115 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 115
============================

正在读取第 116 个DataFrame
初始化batch数据： 116
batch数据 组装完毕 ：116
batch_tensor数据 组装完毕 ：116,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 116 ----- 1
正在处理 116 ----- 2
正在处理 116 ----- 3
正在处理 116 ----- 4
正在处理 116 ----- 5
正在处理 116 ----- 6
正在处理 116 ----- 7
正在处理 116 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 116
============================

正在读取第 117 个DataFrame
初始化batch数据： 117
batch数据 组装完毕 ：117
batch_tensor数据 组装完毕 ：117,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 117 ----- 1
正在处理 117 ----- 2
正在处理 117 ----- 3
正在处理 117 ----- 4
正在处理 117 ----- 5
正在处理 117 ----- 6
正在处理 117 ----- 7
正在处理 117 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 117
============================

正在读取第 118 个DataFrame
初始化batch数据： 118
batch数据 组装完毕 ：118
batch_tensor数据 组装完毕 ：118,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 118 ----- 1
正在处理 118 ----- 2
正在处理 118 ----- 3
正在处理 118 ----- 4
正在处理 118 ----- 5
正在处理 118 ----- 6
正在处理 118 ----- 7
正在处理 118 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 118
============================

正在读取第 119 个DataFrame
初始化batch数据： 119
batch数据 组装完毕 ：119
batch_tensor数据 组装完毕 ：119,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 119 ----- 1
正在处理 119 ----- 2
正在处理 119 ----- 3
正在处理 119 ----- 4
正在处理 119 ----- 5
正在处理 119 ----- 6
正在处理 119 ----- 7
正在处理 119 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 119
============================

正在读取第 120 个DataFrame
初始化batch数据： 120
batch数据 组装完毕 ：120
batch_tensor数据 组装完毕 ：120,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 120 ----- 1
正在处理 120 ----- 2
正在处理 120 ----- 3
正在处理 120 ----- 4
正在处理 120 ----- 5
正在处理 120 ----- 6
正在处理 120 ----- 7
正在处理 120 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 120
============================

正在读取第 121 个DataFrame
初始化batch数据： 121
batch数据 组装完毕 ：121
batch_tensor数据 组装完毕 ：121,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 121 ----- 1
正在处理 121 ----- 2
正在处理 121 ----- 3
正在处理 121 ----- 4
正在处理 121 ----- 5
正在处理 121 ----- 6
正在处理 121 ----- 7
正在处理 121 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 121
============================

正在读取第 122 个DataFrame
初始化batch数据： 122
batch数据 组装完毕 ：122
batch_tensor数据 组装完毕 ：122,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 122 ----- 1
正在处理 122 ----- 2
正在处理 122 ----- 3
正在处理 122 ----- 4
正在处理 122 ----- 5
正在处理 122 ----- 6
正在处理 122 ----- 7
正在处理 122 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 122
============================

正在读取第 123 个DataFrame
初始化batch数据： 123
batch数据 组装完毕 ：123
batch_tensor数据 组装完毕 ：123,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 123 ----- 1
正在处理 123 ----- 2
正在处理 123 ----- 3
正在处理 123 ----- 4
正在处理 123 ----- 5
正在处理 123 ----- 6
正在处理 123 ----- 7
正在处理 123 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 123
============================

正在读取第 124 个DataFrame
初始化batch数据： 124
batch数据 组装完毕 ：124
batch_tensor数据 组装完毕 ：124,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 124 ----- 1
正在处理 124 ----- 2
正在处理 124 ----- 3
正在处理 124 ----- 4
正在处理 124 ----- 5
正在处理 124 ----- 6
正在处理 124 ----- 7
正在处理 124 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 124
============================

正在读取第 125 个DataFrame
初始化batch数据： 125
batch数据 组装完毕 ：125
batch_tensor数据 组装完毕 ：125,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 125 ----- 1
正在处理 125 ----- 2
正在处理 125 ----- 3
正在处理 125 ----- 4
正在处理 125 ----- 5
正在处理 125 ----- 6
正在处理 125 ----- 7
正在处理 125 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 125
============================

正在读取第 126 个DataFrame
初始化batch数据： 126
batch数据 组装完毕 ：126
batch_tensor数据 组装完毕 ：126,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 126 ----- 1
正在处理 126 ----- 2
正在处理 126 ----- 3
正在处理 126 ----- 4
正在处理 126 ----- 5
正在处理 126 ----- 6
正在处理 126 ----- 7
正在处理 126 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 126
============================

正在读取第 127 个DataFrame
初始化batch数据： 127
batch数据 组装完毕 ：127
batch_tensor数据 组装完毕 ：127,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 127 ----- 1
正在处理 127 ----- 2
正在处理 127 ----- 3
正在处理 127 ----- 4
正在处理 127 ----- 5
正在处理 127 ----- 6
正在处理 127 ----- 7
正在处理 127 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 127
============================

正在读取第 128 个DataFrame
初始化batch数据： 128
batch数据 组装完毕 ：128
batch_tensor数据 组装完毕 ：128,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 128 ----- 1
正在处理 128 ----- 2
正在处理 128 ----- 3
正在处理 128 ----- 4
正在处理 128 ----- 5
正在处理 128 ----- 6
正在处理 128 ----- 7
正在处理 128 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 128
============================

正在读取第 129 个DataFrame
初始化batch数据： 129
batch数据 组装完毕 ：129
batch_tensor数据 组装完毕 ：129,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 129 ----- 1
正在处理 129 ----- 2
正在处理 129 ----- 3
正在处理 129 ----- 4
正在处理 129 ----- 5
正在处理 129 ----- 6
正在处理 129 ----- 7
正在处理 129 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 129
============================

正在读取第 130 个DataFrame
初始化batch数据： 130
batch数据 组装完毕 ：130
batch_tensor数据 组装完毕 ：130,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 130 ----- 1
正在处理 130 ----- 2
正在处理 130 ----- 3
正在处理 130 ----- 4
正在处理 130 ----- 5
正在处理 130 ----- 6
正在处理 130 ----- 7
正在处理 130 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 130
============================

正在读取第 131 个DataFrame
初始化batch数据： 131
batch数据 组装完毕 ：131
batch_tensor数据 组装完毕 ：131,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 131 ----- 1
正在处理 131 ----- 2
正在处理 131 ----- 3
正在处理 131 ----- 4
正在处理 131 ----- 5
正在处理 131 ----- 6
正在处理 131 ----- 7
正在处理 131 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 131
============================

正在读取第 132 个DataFrame
初始化batch数据： 132
batch数据 组装完毕 ：132
batch_tensor数据 组装完毕 ：132,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 132 ----- 1
正在处理 132 ----- 2
正在处理 132 ----- 3
正在处理 132 ----- 4
正在处理 132 ----- 5
正在处理 132 ----- 6
正在处理 132 ----- 7
正在处理 132 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 132
============================

正在读取第 133 个DataFrame
初始化batch数据： 133
batch数据 组装完毕 ：133
batch_tensor数据 组装完毕 ：133,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 133 ----- 1
正在处理 133 ----- 2
正在处理 133 ----- 3
正在处理 133 ----- 4
正在处理 133 ----- 5
正在处理 133 ----- 6
正在处理 133 ----- 7
正在处理 133 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 133
============================

正在读取第 134 个DataFrame
初始化batch数据： 134
batch数据 组装完毕 ：134
batch_tensor数据 组装完毕 ：134,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 134 ----- 1
正在处理 134 ----- 2
正在处理 134 ----- 3
正在处理 134 ----- 4
正在处理 134 ----- 5
正在处理 134 ----- 6
正在处理 134 ----- 7
正在处理 134 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 134
============================

正在读取第 135 个DataFrame
初始化batch数据： 135
batch数据 组装完毕 ：135
batch_tensor数据 组装完毕 ：135,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 135 ----- 1
正在处理 135 ----- 2
正在处理 135 ----- 3
正在处理 135 ----- 4
正在处理 135 ----- 5
正在处理 135 ----- 6
正在处理 135 ----- 7
正在处理 135 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 135
============================

正在读取第 136 个DataFrame
初始化batch数据： 136
batch数据 组装完毕 ：136
batch_tensor数据 组装完毕 ：136,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 136 ----- 1
正在处理 136 ----- 2
正在处理 136 ----- 3
正在处理 136 ----- 4
正在处理 136 ----- 5
正在处理 136 ----- 6
正在处理 136 ----- 7
正在处理 136 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 136
============================

正在读取第 137 个DataFrame
初始化batch数据： 137
batch数据 组装完毕 ：137
batch_tensor数据 组装完毕 ：137,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 137 ----- 1
正在处理 137 ----- 2
正在处理 137 ----- 3
正在处理 137 ----- 4
正在处理 137 ----- 5
正在处理 137 ----- 6
正在处理 137 ----- 7
正在处理 137 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 137
============================

正在读取第 138 个DataFrame
初始化batch数据： 138
batch数据 组装完毕 ：138
batch_tensor数据 组装完毕 ：138,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 138 ----- 1
正在处理 138 ----- 2
正在处理 138 ----- 3
正在处理 138 ----- 4
正在处理 138 ----- 5
正在处理 138 ----- 6
正在处理 138 ----- 7
正在处理 138 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 138
============================

正在读取第 139 个DataFrame
初始化batch数据： 139
batch数据 组装完毕 ：139
batch_tensor数据 组装完毕 ：139,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 139 ----- 1
正在处理 139 ----- 2
正在处理 139 ----- 3
正在处理 139 ----- 4
正在处理 139 ----- 5
正在处理 139 ----- 6
正在处理 139 ----- 7
正在处理 139 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 139
============================

正在读取第 140 个DataFrame
初始化batch数据： 140
batch数据 组装完毕 ：140
batch_tensor数据 组装完毕 ：140,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 140 ----- 1
正在处理 140 ----- 2
正在处理 140 ----- 3
正在处理 140 ----- 4
正在处理 140 ----- 5
正在处理 140 ----- 6
正在处理 140 ----- 7
正在处理 140 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 140
============================

正在读取第 141 个DataFrame
初始化batch数据： 141
batch数据 组装完毕 ：141
batch_tensor数据 组装完毕 ：141,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 141 ----- 1
正在处理 141 ----- 2
正在处理 141 ----- 3
正在处理 141 ----- 4
正在处理 141 ----- 5
正在处理 141 ----- 6
正在处理 141 ----- 7
正在处理 141 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 141
============================

正在读取第 142 个DataFrame
初始化batch数据： 142
batch数据 组装完毕 ：142
batch_tensor数据 组装完毕 ：142,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 142 ----- 1
正在处理 142 ----- 2
正在处理 142 ----- 3
正在处理 142 ----- 4
正在处理 142 ----- 5
正在处理 142 ----- 6
正在处理 142 ----- 7
正在处理 142 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 142
============================

正在读取第 143 个DataFrame
初始化batch数据： 143
batch数据 组装完毕 ：143
batch_tensor数据 组装完毕 ：143,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 143 ----- 1
正在处理 143 ----- 2
正在处理 143 ----- 3
正在处理 143 ----- 4
正在处理 143 ----- 5
正在处理 143 ----- 6
正在处理 143 ----- 7
正在处理 143 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 143
============================

正在读取第 144 个DataFrame
初始化batch数据： 144
batch数据 组装完毕 ：144
batch_tensor数据 组装完毕 ：144,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 144 ----- 1
正在处理 144 ----- 2
正在处理 144 ----- 3
正在处理 144 ----- 4
正在处理 144 ----- 5
正在处理 144 ----- 6
正在处理 144 ----- 7
正在处理 144 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 144
============================

正在读取第 145 个DataFrame
初始化batch数据： 145
batch数据 组装完毕 ：145
batch_tensor数据 组装完毕 ：145,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 145 ----- 1
正在处理 145 ----- 2
正在处理 145 ----- 3
正在处理 145 ----- 4
正在处理 145 ----- 5
正在处理 145 ----- 6
正在处理 145 ----- 7
正在处理 145 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 145
============================

正在读取第 146 个DataFrame
初始化batch数据： 146
batch数据 组装完毕 ：146
batch_tensor数据 组装完毕 ：146,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 146 ----- 1
正在处理 146 ----- 2
正在处理 146 ----- 3
正在处理 146 ----- 4
正在处理 146 ----- 5
正在处理 146 ----- 6
正在处理 146 ----- 7
正在处理 146 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 146
============================

正在读取第 147 个DataFrame
初始化batch数据： 147
batch数据 组装完毕 ：147
batch_tensor数据 组装完毕 ：147,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 147 ----- 1
正在处理 147 ----- 2
正在处理 147 ----- 3
正在处理 147 ----- 4
正在处理 147 ----- 5
正在处理 147 ----- 6
正在处理 147 ----- 7
正在处理 147 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 147
============================

正在读取第 148 个DataFrame
初始化batch数据： 148
batch数据 组装完毕 ：148
batch_tensor数据 组装完毕 ：148,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 148 ----- 1
正在处理 148 ----- 2
正在处理 148 ----- 3
正在处理 148 ----- 4
正在处理 148 ----- 5
正在处理 148 ----- 6
正在处理 148 ----- 7
正在处理 148 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 148
============================

正在读取第 149 个DataFrame
初始化batch数据： 149
batch数据 组装完毕 ：149
batch_tensor数据 组装完毕 ：149,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 149 ----- 1
正在处理 149 ----- 2
正在处理 149 ----- 3
正在处理 149 ----- 4
正在处理 149 ----- 5
正在处理 149 ----- 6
正在处理 149 ----- 7
正在处理 149 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 149
============================

正在读取第 150 个DataFrame
初始化batch数据： 150
batch数据 组装完毕 ：150
batch_tensor数据 组装完毕 ：150,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 150 ----- 1
正在处理 150 ----- 2
正在处理 150 ----- 3
正在处理 150 ----- 4
正在处理 150 ----- 5
正在处理 150 ----- 6
正在处理 150 ----- 7
正在处理 150 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 150
============================

正在读取第 151 个DataFrame
初始化batch数据： 151
batch数据 组装完毕 ：151
batch_tensor数据 组装完毕 ：151,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 151 ----- 1
正在处理 151 ----- 2
正在处理 151 ----- 3
正在处理 151 ----- 4
正在处理 151 ----- 5
正在处理 151 ----- 6
正在处理 151 ----- 7
正在处理 151 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 151
============================

正在读取第 152 个DataFrame
初始化batch数据： 152
batch数据 组装完毕 ：152
batch_tensor数据 组装完毕 ：152,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 152 ----- 1
正在处理 152 ----- 2
正在处理 152 ----- 3
正在处理 152 ----- 4
正在处理 152 ----- 5
正在处理 152 ----- 6
正在处理 152 ----- 7
正在处理 152 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 152
============================

正在读取第 153 个DataFrame
初始化batch数据： 153
batch数据 组装完毕 ：153
batch_tensor数据 组装完毕 ：153,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 153 ----- 1
正在处理 153 ----- 2
正在处理 153 ----- 3
正在处理 153 ----- 4
正在处理 153 ----- 5
正在处理 153 ----- 6
正在处理 153 ----- 7
正在处理 153 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 153
============================

正在读取第 154 个DataFrame
初始化batch数据： 154
batch数据 组装完毕 ：154
batch_tensor数据 组装完毕 ：154,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 154 ----- 1
正在处理 154 ----- 2
正在处理 154 ----- 3
正在处理 154 ----- 4
正在处理 154 ----- 5
正在处理 154 ----- 6
正在处理 154 ----- 7
正在处理 154 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 154
============================

正在读取第 155 个DataFrame
初始化batch数据： 155
batch数据 组装完毕 ：155
batch_tensor数据 组装完毕 ：155,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 155 ----- 1
正在处理 155 ----- 2
正在处理 155 ----- 3
正在处理 155 ----- 4
正在处理 155 ----- 5
正在处理 155 ----- 6
正在处理 155 ----- 7
正在处理 155 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 155
============================

正在读取第 156 个DataFrame
初始化batch数据： 156
batch数据 组装完毕 ：156
batch_tensor数据 组装完毕 ：156,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 156 ----- 1
正在处理 156 ----- 2
正在处理 156 ----- 3
正在处理 156 ----- 4
正在处理 156 ----- 5
正在处理 156 ----- 6
正在处理 156 ----- 7
正在处理 156 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 156
============================

正在读取第 157 个DataFrame
初始化batch数据： 157
batch数据 组装完毕 ：157
batch_tensor数据 组装完毕 ：157,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 157 ----- 1
正在处理 157 ----- 2
正在处理 157 ----- 3
正在处理 157 ----- 4
正在处理 157 ----- 5
正在处理 157 ----- 6
正在处理 157 ----- 7
正在处理 157 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 157
============================

正在读取第 158 个DataFrame
初始化batch数据： 158
batch数据 组装完毕 ：158
batch_tensor数据 组装完毕 ：158,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 158 ----- 1
正在处理 158 ----- 2
正在处理 158 ----- 3
正在处理 158 ----- 4
正在处理 158 ----- 5
正在处理 158 ----- 6
正在处理 158 ----- 7
正在处理 158 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 158
============================

正在读取第 159 个DataFrame
初始化batch数据： 159
batch数据 组装完毕 ：159
batch_tensor数据 组装完毕 ：159,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 159 ----- 1
正在处理 159 ----- 2
正在处理 159 ----- 3
正在处理 159 ----- 4
正在处理 159 ----- 5
正在处理 159 ----- 6
正在处理 159 ----- 7
正在处理 159 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 159
============================

正在读取第 160 个DataFrame
初始化batch数据： 160
batch数据 组装完毕 ：160
batch_tensor数据 组装完毕 ：160,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 160 ----- 1
正在处理 160 ----- 2
正在处理 160 ----- 3
正在处理 160 ----- 4
正在处理 160 ----- 5
正在处理 160 ----- 6
正在处理 160 ----- 7
正在处理 160 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 160
============================

正在读取第 161 个DataFrame
初始化batch数据： 161
batch数据 组装完毕 ：161
batch_tensor数据 组装完毕 ：161,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 161 ----- 1
正在处理 161 ----- 2
正在处理 161 ----- 3
正在处理 161 ----- 4
正在处理 161 ----- 5
正在处理 161 ----- 6
正在处理 161 ----- 7
正在处理 161 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 161
============================

正在读取第 162 个DataFrame
初始化batch数据： 162
batch数据 组装完毕 ：162
batch_tensor数据 组装完毕 ：162,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 162 ----- 1
正在处理 162 ----- 2
正在处理 162 ----- 3
正在处理 162 ----- 4
正在处理 162 ----- 5
正在处理 162 ----- 6
正在处理 162 ----- 7
正在处理 162 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 162
============================

正在读取第 163 个DataFrame
初始化batch数据： 163
batch数据 组装完毕 ：163
batch_tensor数据 组装完毕 ：163,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 163 ----- 1
正在处理 163 ----- 2
正在处理 163 ----- 3
正在处理 163 ----- 4
正在处理 163 ----- 5
正在处理 163 ----- 6
正在处理 163 ----- 7
正在处理 163 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 163
============================

正在读取第 164 个DataFrame
初始化batch数据： 164
batch数据 组装完毕 ：164
batch_tensor数据 组装完毕 ：164,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 164 ----- 1
正在处理 164 ----- 2
正在处理 164 ----- 3
正在处理 164 ----- 4
正在处理 164 ----- 5
正在处理 164 ----- 6
正在处理 164 ----- 7
正在处理 164 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 164
============================

正在读取第 165 个DataFrame
初始化batch数据： 165
batch数据 组装完毕 ：165
batch_tensor数据 组装完毕 ：165,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 165 ----- 1
正在处理 165 ----- 2
正在处理 165 ----- 3
正在处理 165 ----- 4
正在处理 165 ----- 5
正在处理 165 ----- 6
正在处理 165 ----- 7
正在处理 165 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 165
============================

正在读取第 166 个DataFrame
初始化batch数据： 166
batch数据 组装完毕 ：166
batch_tensor数据 组装完毕 ：166,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 166 ----- 1
正在处理 166 ----- 2
正在处理 166 ----- 3
正在处理 166 ----- 4
正在处理 166 ----- 5
正在处理 166 ----- 6
正在处理 166 ----- 7
正在处理 166 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 166
============================

正在读取第 167 个DataFrame
初始化batch数据： 167
batch数据 组装完毕 ：167
batch_tensor数据 组装完毕 ：167,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 167 ----- 1
正在处理 167 ----- 2
正在处理 167 ----- 3
正在处理 167 ----- 4
正在处理 167 ----- 5
正在处理 167 ----- 6
正在处理 167 ----- 7
正在处理 167 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 167
============================

正在读取第 168 个DataFrame
初始化batch数据： 168
batch数据 组装完毕 ：168
batch_tensor数据 组装完毕 ：168,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 168 ----- 1
正在处理 168 ----- 2
正在处理 168 ----- 3
正在处理 168 ----- 4
正在处理 168 ----- 5
正在处理 168 ----- 6
正在处理 168 ----- 7
正在处理 168 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 168
============================

正在读取第 169 个DataFrame
初始化batch数据： 169
batch数据 组装完毕 ：169
batch_tensor数据 组装完毕 ：169,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 169 ----- 1
正在处理 169 ----- 2
正在处理 169 ----- 3
正在处理 169 ----- 4
正在处理 169 ----- 5
正在处理 169 ----- 6
正在处理 169 ----- 7
正在处理 169 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 169
============================

正在读取第 170 个DataFrame
初始化batch数据： 170
batch数据 组装完毕 ：170
batch_tensor数据 组装完毕 ：170,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 170 ----- 1
正在处理 170 ----- 2
正在处理 170 ----- 3
正在处理 170 ----- 4
正在处理 170 ----- 5
正在处理 170 ----- 6
正在处理 170 ----- 7
正在处理 170 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 170
============================

正在读取第 171 个DataFrame
初始化batch数据： 171
batch数据 组装完毕 ：171
batch_tensor数据 组装完毕 ：171,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 171 ----- 1
正在处理 171 ----- 2
正在处理 171 ----- 3
正在处理 171 ----- 4
正在处理 171 ----- 5
正在处理 171 ----- 6
正在处理 171 ----- 7
正在处理 171 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 171
============================

正在读取第 172 个DataFrame
初始化batch数据： 172
batch数据 组装完毕 ：172
batch_tensor数据 组装完毕 ：172,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 172 ----- 1
正在处理 172 ----- 2
正在处理 172 ----- 3
正在处理 172 ----- 4
正在处理 172 ----- 5
正在处理 172 ----- 6
正在处理 172 ----- 7
正在处理 172 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 172
============================

正在读取第 173 个DataFrame
初始化batch数据： 173
batch数据 组装完毕 ：173
batch_tensor数据 组装完毕 ：173,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 173 ----- 1
正在处理 173 ----- 2
正在处理 173 ----- 3
正在处理 173 ----- 4
正在处理 173 ----- 5
正在处理 173 ----- 6
正在处理 173 ----- 7
正在处理 173 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 173
============================

正在读取第 174 个DataFrame
初始化batch数据： 174
batch数据 组装完毕 ：174
batch_tensor数据 组装完毕 ：174,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 174 ----- 1
正在处理 174 ----- 2
正在处理 174 ----- 3
正在处理 174 ----- 4
正在处理 174 ----- 5
正在处理 174 ----- 6
正在处理 174 ----- 7
正在处理 174 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 174
============================

正在读取第 175 个DataFrame
初始化batch数据： 175
batch数据 组装完毕 ：175
batch_tensor数据 组装完毕 ：175,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 175 ----- 1
正在处理 175 ----- 2
正在处理 175 ----- 3
正在处理 175 ----- 4
正在处理 175 ----- 5
正在处理 175 ----- 6
正在处理 175 ----- 7
正在处理 175 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 175
============================

正在读取第 176 个DataFrame
初始化batch数据： 176
batch数据 组装完毕 ：176
batch_tensor数据 组装完毕 ：176,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 176 ----- 1
正在处理 176 ----- 2
正在处理 176 ----- 3
正在处理 176 ----- 4
正在处理 176 ----- 5
正在处理 176 ----- 6
正在处理 176 ----- 7
正在处理 176 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 176
============================

正在读取第 177 个DataFrame
初始化batch数据： 177
batch数据 组装完毕 ：177
batch_tensor数据 组装完毕 ：177,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 177 ----- 1
正在处理 177 ----- 2
正在处理 177 ----- 3
正在处理 177 ----- 4
正在处理 177 ----- 5
正在处理 177 ----- 6
正在处理 177 ----- 7
正在处理 177 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 177
============================

正在读取第 178 个DataFrame
初始化batch数据： 178
batch数据 组装完毕 ：178
batch_tensor数据 组装完毕 ：178,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 178 ----- 1
正在处理 178 ----- 2
正在处理 178 ----- 3
正在处理 178 ----- 4
正在处理 178 ----- 5
正在处理 178 ----- 6
正在处理 178 ----- 7
正在处理 178 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 178
============================

正在读取第 179 个DataFrame
初始化batch数据： 179
batch数据 组装完毕 ：179
batch_tensor数据 组装完毕 ：179,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 179 ----- 1
正在处理 179 ----- 2
正在处理 179 ----- 3
正在处理 179 ----- 4
正在处理 179 ----- 5
正在处理 179 ----- 6
正在处理 179 ----- 7
正在处理 179 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 179
============================

正在读取第 180 个DataFrame
初始化batch数据： 180
batch数据 组装完毕 ：180
batch_tensor数据 组装完毕 ：180,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 180 ----- 1
正在处理 180 ----- 2
正在处理 180 ----- 3
正在处理 180 ----- 4
正在处理 180 ----- 5
正在处理 180 ----- 6
正在处理 180 ----- 7
正在处理 180 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 180
============================

正在读取第 181 个DataFrame
初始化batch数据： 181
batch数据 组装完毕 ：181
batch_tensor数据 组装完毕 ：181,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 181 ----- 1
正在处理 181 ----- 2
正在处理 181 ----- 3
正在处理 181 ----- 4
正在处理 181 ----- 5
正在处理 181 ----- 6
正在处理 181 ----- 7
正在处理 181 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 181
============================

正在读取第 182 个DataFrame
初始化batch数据： 182
batch数据 组装完毕 ：182
batch_tensor数据 组装完毕 ：182,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 182 ----- 1
正在处理 182 ----- 2
正在处理 182 ----- 3
正在处理 182 ----- 4
正在处理 182 ----- 5
正在处理 182 ----- 6
正在处理 182 ----- 7
正在处理 182 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 182
============================

正在读取第 183 个DataFrame
初始化batch数据： 183
batch数据 组装完毕 ：183
batch_tensor数据 组装完毕 ：183,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 183 ----- 1
正在处理 183 ----- 2
正在处理 183 ----- 3
正在处理 183 ----- 4
正在处理 183 ----- 5
正在处理 183 ----- 6
正在处理 183 ----- 7
正在处理 183 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 183
============================

正在读取第 184 个DataFrame
初始化batch数据： 184
batch数据 组装完毕 ：184
batch_tensor数据 组装完毕 ：184,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 184 ----- 1
正在处理 184 ----- 2
正在处理 184 ----- 3
正在处理 184 ----- 4
正在处理 184 ----- 5
正在处理 184 ----- 6
正在处理 184 ----- 7
正在处理 184 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 184
============================

正在读取第 185 个DataFrame
初始化batch数据： 185
batch数据 组装完毕 ：185
batch_tensor数据 组装完毕 ：185,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 185 ----- 1
正在处理 185 ----- 2
正在处理 185 ----- 3
正在处理 185 ----- 4
正在处理 185 ----- 5
正在处理 185 ----- 6
正在处理 185 ----- 7
正在处理 185 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 185
============================

正在读取第 186 个DataFrame
初始化batch数据： 186
batch数据 组装完毕 ：186
batch_tensor数据 组装完毕 ：186,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 186 ----- 1
正在处理 186 ----- 2
正在处理 186 ----- 3
正在处理 186 ----- 4
正在处理 186 ----- 5
正在处理 186 ----- 6
正在处理 186 ----- 7
正在处理 186 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 186
============================

正在读取第 187 个DataFrame
初始化batch数据： 187
batch数据 组装完毕 ：187
batch_tensor数据 组装完毕 ：187,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 187 ----- 1
正在处理 187 ----- 2
正在处理 187 ----- 3
正在处理 187 ----- 4
正在处理 187 ----- 5
正在处理 187 ----- 6
正在处理 187 ----- 7
正在处理 187 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 187
============================

正在读取第 188 个DataFrame
初始化batch数据： 188
batch数据 组装完毕 ：188
batch_tensor数据 组装完毕 ：188,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 188 ----- 1
正在处理 188 ----- 2
正在处理 188 ----- 3
正在处理 188 ----- 4
正在处理 188 ----- 5
正在处理 188 ----- 6
正在处理 188 ----- 7
正在处理 188 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 188
============================

正在读取第 189 个DataFrame
初始化batch数据： 189
batch数据 组装完毕 ：189
batch_tensor数据 组装完毕 ：189,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 189 ----- 1
正在处理 189 ----- 2
正在处理 189 ----- 3
正在处理 189 ----- 4
正在处理 189 ----- 5
正在处理 189 ----- 6
正在处理 189 ----- 7
正在处理 189 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 189
============================

正在读取第 190 个DataFrame
初始化batch数据： 190
batch数据 组装完毕 ：190
batch_tensor数据 组装完毕 ：190,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 190 ----- 1
正在处理 190 ----- 2
正在处理 190 ----- 3
正在处理 190 ----- 4
正在处理 190 ----- 5
正在处理 190 ----- 6
正在处理 190 ----- 7
正在处理 190 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 190
============================

正在读取第 191 个DataFrame
初始化batch数据： 191
batch数据 组装完毕 ：191
batch_tensor数据 组装完毕 ：191,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 191 ----- 1
正在处理 191 ----- 2
正在处理 191 ----- 3
正在处理 191 ----- 4
正在处理 191 ----- 5
正在处理 191 ----- 6
正在处理 191 ----- 7
正在处理 191 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 191
============================

正在读取第 192 个DataFrame
初始化batch数据： 192
batch数据 组装完毕 ：192
batch_tensor数据 组装完毕 ：192,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 192 ----- 1
正在处理 192 ----- 2
正在处理 192 ----- 3
正在处理 192 ----- 4
正在处理 192 ----- 5
正在处理 192 ----- 6
正在处理 192 ----- 7
正在处理 192 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 192
============================

正在读取第 193 个DataFrame
初始化batch数据： 193
batch数据 组装完毕 ：193
batch_tensor数据 组装完毕 ：193,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 193 ----- 1
正在处理 193 ----- 2
正在处理 193 ----- 3
正在处理 193 ----- 4
正在处理 193 ----- 5
正在处理 193 ----- 6
正在处理 193 ----- 7
正在处理 193 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 193
============================

正在读取第 194 个DataFrame
初始化batch数据： 194
batch数据 组装完毕 ：194
batch_tensor数据 组装完毕 ：194,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 194 ----- 1
正在处理 194 ----- 2
正在处理 194 ----- 3
正在处理 194 ----- 4
正在处理 194 ----- 5
正在处理 194 ----- 6
正在处理 194 ----- 7
正在处理 194 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 194
============================

正在读取第 195 个DataFrame
初始化batch数据： 195
batch数据 组装完毕 ：195
batch_tensor数据 组装完毕 ：195,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 195 ----- 1
正在处理 195 ----- 2
正在处理 195 ----- 3
正在处理 195 ----- 4
正在处理 195 ----- 5
正在处理 195 ----- 6
正在处理 195 ----- 7
正在处理 195 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 195
============================

正在读取第 196 个DataFrame
初始化batch数据： 196
batch数据 组装完毕 ：196
batch_tensor数据 组装完毕 ：196,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 196 ----- 1
正在处理 196 ----- 2
正在处理 196 ----- 3
正在处理 196 ----- 4
正在处理 196 ----- 5
正在处理 196 ----- 6
正在处理 196 ----- 7
正在处理 196 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 196
============================

正在读取第 197 个DataFrame
初始化batch数据： 197
batch数据 组装完毕 ：197
batch_tensor数据 组装完毕 ：197,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 197 ----- 1
正在处理 197 ----- 2
正在处理 197 ----- 3
正在处理 197 ----- 4
正在处理 197 ----- 5
正在处理 197 ----- 6
正在处理 197 ----- 7
正在处理 197 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 197
============================

正在读取第 198 个DataFrame
初始化batch数据： 198
batch数据 组装完毕 ：198
batch_tensor数据 组装完毕 ：198,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 198 ----- 1
正在处理 198 ----- 2
正在处理 198 ----- 3
正在处理 198 ----- 4
正在处理 198 ----- 5
正在处理 198 ----- 6
正在处理 198 ----- 7
正在处理 198 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 198
============================

正在读取第 199 个DataFrame
初始化batch数据： 199
batch数据 组装完毕 ：199
batch_tensor数据 组装完毕 ：199,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 199 ----- 1
正在处理 199 ----- 2
正在处理 199 ----- 3
正在处理 199 ----- 4
正在处理 199 ----- 5
正在处理 199 ----- 6
正在处理 199 ----- 7
正在处理 199 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 199
============================

正在读取第 200 个DataFrame
初始化batch数据： 200
batch数据 组装完毕 ：200
batch_tensor数据 组装完毕 ：200,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 200 ----- 1
正在处理 200 ----- 2
正在处理 200 ----- 3
正在处理 200 ----- 4
正在处理 200 ----- 5
正在处理 200 ----- 6
正在处理 200 ----- 7
正在处理 200 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 200
============================

正在读取第 201 个DataFrame
初始化batch数据： 201
batch数据 组装完毕 ：201
batch_tensor数据 组装完毕 ：201,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 201 ----- 1
正在处理 201 ----- 2
正在处理 201 ----- 3
正在处理 201 ----- 4
正在处理 201 ----- 5
正在处理 201 ----- 6
正在处理 201 ----- 7
正在处理 201 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 201
============================

正在读取第 202 个DataFrame
初始化batch数据： 202
batch数据 组装完毕 ：202
batch_tensor数据 组装完毕 ：202,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 202 ----- 1
正在处理 202 ----- 2
正在处理 202 ----- 3
正在处理 202 ----- 4
正在处理 202 ----- 5
正在处理 202 ----- 6
正在处理 202 ----- 7
正在处理 202 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 202
============================

正在读取第 203 个DataFrame
初始化batch数据： 203
batch数据 组装完毕 ：203
batch_tensor数据 组装完毕 ：203,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 203 ----- 1
正在处理 203 ----- 2
正在处理 203 ----- 3
正在处理 203 ----- 4
正在处理 203 ----- 5
正在处理 203 ----- 6
正在处理 203 ----- 7
正在处理 203 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 203
============================

正在读取第 204 个DataFrame
初始化batch数据： 204
batch数据 组装完毕 ：204
batch_tensor数据 组装完毕 ：204,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 204 ----- 1
正在处理 204 ----- 2
正在处理 204 ----- 3
正在处理 204 ----- 4
正在处理 204 ----- 5
正在处理 204 ----- 6
正在处理 204 ----- 7
正在处理 204 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 204
============================

正在读取第 205 个DataFrame
初始化batch数据： 205
batch数据 组装完毕 ：205
batch_tensor数据 组装完毕 ：205,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 205 ----- 1
正在处理 205 ----- 2
正在处理 205 ----- 3
正在处理 205 ----- 4
正在处理 205 ----- 5
正在处理 205 ----- 6
正在处理 205 ----- 7
正在处理 205 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 205
============================

正在读取第 206 个DataFrame
初始化batch数据： 206
batch数据 组装完毕 ：206
batch_tensor数据 组装完毕 ：206,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 206 ----- 1
正在处理 206 ----- 2
正在处理 206 ----- 3
正在处理 206 ----- 4
正在处理 206 ----- 5
正在处理 206 ----- 6
正在处理 206 ----- 7
正在处理 206 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 206
============================

正在读取第 207 个DataFrame
初始化batch数据： 207
batch数据 组装完毕 ：207
batch_tensor数据 组装完毕 ：207,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 8 块， 开始调用模型
正在处理 207 ----- 1
正在处理 207 ----- 2
正在处理 207 ----- 3
正在处理 207 ----- 4
正在处理 207 ----- 5
正在处理 207 ----- 6
正在处理 207 ----- 7
正在处理 207 ----- 8

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 207
============================

正在读取第 208 个DataFrame
初始化batch数据： 208
batch数据 组装完毕 ：208
batch_tensor数据 组装完毕 ：208,开始分块处理
分块处理完毕数据完毕，每块的长度为:512,一共有 7 块， 开始调用模型
正在处理 208 ----- 1
正在处理 208 ----- 2
正在处理 208 ----- 3
正在处理 208 ----- 4
正在处理 208 ----- 5
正在处理 208 ----- 6
正在处理 208 ----- 7

/tmp/ipykernel_474/2717872624.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["feature"] = [ tv.tolist() for tv in  text_vector]

文件写入完毕 208
============================

In [108]:
tip_df

,user_id,business_id,text,date,compliment_count,length
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0,30
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0,57
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0,38
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0,25
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0,38
...,...,...,...,...,...,...
908910,eYodOTF8pkqKPzHkcxZs-Q,3lHTewuKFt5IImbXJoFeDQ,Disappointed in one of your managers.,2021-09-11 19:18:57,0,37
908911,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,Great food and service.,2021-10-30 11:54:36,0,23
908912,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,Love their Cubans!!,2021-11-05 13:18:56,0,19
908913,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,Great pizza great price,2021-11-20 16:11:44,0,23
908914,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,Food is good value but a bit hot!,2021-12-07 22:30:00,0,33